// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `layout` slice of the he translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/layout/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/he/layout';` and reads nothing from it.
// `../he.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'קרוסלה',
  carouselLabel: 'קרוסלה',
  carouselSlide: 'שקופית',
  carouselSlidePosition: 'שקופית {index} מתוך {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'שקופיות הקרוסלה',
  carouselGoTo: 'עבור לשקופית {index}',
  scrollerLabel: 'תוכן שניתן לגלול',
  scrollPrevious: 'גלול אחורה',
  scrollNext: 'גלול קדימה',
  closeNavigation: 'סגור ניווט',
  openNavigation: 'פתח את הניווט',
  resizeNavigation: 'שנה את גודל הניווט',
  appRailCollapse: 'כווץ את הניווט',
  appRailExpand: 'הרחב את הניווט',
  appRailItemCollapse: 'כווץ {label}',
  appRailItemExpand: 'הרחב את {label}',
  resizeValuePercent: '{value} אחוזים',
  commandPaletteLabel: 'לוח פקודות',
  commandPalettePlaceholder: 'חפש פקודות…',
  commandPaletteEmpty: 'אין פקודות תואמות.',
  commandPaletteResults: 'פקודות',
  dockPanelCollapse: 'כווץ לוח',
  dockPanelExpand: 'הרחב את הלוח',
  dockPanelResize: 'שנה את גודל הלוח',
  responsivePanel: 'חלונית',
  breadcrumb: 'פירורי לחם',
  resizeDivider: 'שנה את גודל המפריד בין הלוח {a} ללוח {b}',
  widgetFullscreenPanel: 'פאנל מסך מלא',
  widgetViewGroup: 'תצוגת פאנל',
  widgetExitFullscreen: 'צא ממסך מלא',
  widgetExpandToFullscreen: 'הרחב למסך מלא',
  widgetCollapse: 'כווץ לוח',
  widgetExpand: 'הרחב את הלוח',
  skipToContent: 'דלג לתוכן',
  dashboardGridLabel: 'רשת לוח המחוונים',
  dashboardCellCollisionRejected: 'לא ניתן למקם שם {label} כי הוא חופף לתא אחר.',
  dashboardCellMoved: '{label} הועבר לעמודה {x}, שורה {y}.',
  dashboardCellResized: '{label} השתנה לרוחב {w}, גובה {h}.',
  filterBarReset: 'אפס מסננים',
  filterBarActiveFilters: 'מסננים פעילים',
  drilldownDocuments: 'מסמכים',
  drilldownRuns: 'הרצות סוכן',
  drilldownEmpty: 'לא נבחר פריט',
  drilldownUntitledNode: 'שלב ללא כותרת',
  reorderMovePending: 'שינוי הסדר בהמתנה.',
  reorderMoveCancelled: 'הסידור מחדש בוטל.',
};

registerLyraLocale('he', strings, { dir: 'rtl', name: 'עברית' });
