// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `overlays` slice of the he translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/overlays/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/he/overlays';` and reads nothing from it.
// `../he.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'דירוג',
  calloutAnnouncementWithContext: '{context} — {content}',
  closeWithContext: 'סגור: {snippet}',
  closeWithTruncatedContext: 'סגור: {snippet}…',
  toastContentIncomplete: 'התראה עם תוכן חלקי',
  toastOverflow: 'התראות שלא הוצגו: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'רווח',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'חץ למעלה',
  kbdArrowDownWord: 'חץ למטה',
  kbdArrowLeftWord: 'חץ שמאלה',
  kbdArrowRightWord: 'חץ ימינה',
  kbdPlusWord: 'פלוס',
  kbdMinusWord: 'מינוס',
  kbdCommandWord: 'פקודה',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'אופציה',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('he', strings, { dir: 'rtl', name: 'עברית' });
