// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'דירוג',
  calloutAnnouncementWithContext: '{context} — {content}',
  closeWithContext: 'סגור: {snippet}',
  closeWithTruncatedContext: 'סגור: {snippet}…',
  toastContentIncomplete: 'התראה עם תוכן חלקי',
  toastOverflow: 'התראות שלא הוצגו: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'רווח',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'חץ למעלה',
  kbdArrowDownWord: 'חץ למטה',
  kbdArrowLeftWord: 'חץ שמאלה',
  kbdArrowRightWord: 'חץ ימינה',
  kbdPlusWord: 'פלוס',
  kbdMinusWord: 'מינוס',
  kbdCommandWord: 'פקודה',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'אופציה',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('he', strings, { dir: 'rtl', name: 'עברית' });
