// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'carrousel',
  carouselLabel: 'Carrousel',
  carouselSlide: 'dia',
  carouselSlidePosition: 'Dia {index} van {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Carrousel-dia’s',
  carouselGoTo: 'Ga naar dia {index}',
  scrollerLabel: 'Scrollbare inhoud',
  scrollPrevious: 'Terug scrollen',
  scrollNext: 'Verder scrollen',
  closeNavigation: 'Navigatie sluiten',
  openNavigation: 'Navigatie openen',
  resizeNavigation: 'Navigatieformaat aanpassen',
  appRailCollapse: 'Navigatie inklappen',
  appRailExpand: 'Navigatie uitklappen',
  appRailItemCollapse: '{label} inklappen',
  appRailItemExpand: '{label} uitklappen',
  resizeValuePercent: '{value} procent',
  commandPaletteLabel: 'Opdrachtpalet',
  commandPalettePlaceholder: 'Opdrachten zoeken…',
  commandPaletteEmpty: 'Geen overeenkomende opdrachten.',
  commandPaletteResults: 'Opdrachten',
  dockPanelCollapse: 'Paneel inklappen',
  dockPanelExpand: 'Paneel uitklappen',
  dockPanelResize: 'Paneelgrootte aanpassen',
  responsivePanel: 'Paneel',
  breadcrumb: 'Broodkruimelpad',
  resizeDivider: 'Scheiding tussen paneel {a} en paneel {b} aanpassen',
  widgetFullscreenPanel: 'Paneel op volledig scherm',
  widgetViewGroup: 'Paneelweergave',
  widgetExitFullscreen: 'Volledig scherm sluiten',
  widgetExpandToFullscreen: 'Op volledig scherm weergeven',
  widgetCollapse: 'Paneel inklappen',
  widgetExpand: 'Paneel uitklappen',
  skipToContent: 'Naar inhoud gaan',
  dashboardGridLabel: 'Dashboardraster',
  dashboardCellCollisionRejected: '{label} kan daar niet worden geplaatst omdat het een andere cel overlapt.',
  dashboardCellMoved: '{label} verplaatst naar kolom {x}, rij {y}.',
  dashboardCellResized: 'Formaat van {label} aangepast naar breedte {w}, hoogte {h}.',
  filterBarReset: 'Filters wissen',
  filterBarActiveFilters: 'Actieve filters',
  drilldownDocuments: 'Documenten',
  drilldownRuns: 'Agentruns',
  drilldownEmpty: 'Geen item geselecteerd',
  drilldownUntitledNode: 'Naamloze stap',
  reorderMovePending: 'Opnieuw ordenen in behandeling.',
  reorderMoveCancelled: 'Opnieuw ordenen geannuleerd.',
  commandPaletteResultCount: {
    one: '{count} opdracht',
    other: '{count} opdrachten',
  },
};

registerLyraLocale('nl', strings);
