// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `utility` slice of the nl translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/utility/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/nl/utility';` and reads nothing from it.
// `../nl.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON naar klembord kopiëren',
  circularReference: 'Cirkelverwijzing',
  copyDiff: 'Verschil kopiëren',
  diffViewOldLabel: 'Origineel',
  diffViewNewLabel: 'Gewijzigd',
  diffViewHiddenLines: {
    one: '{count} ongewijzigde regel',
    other: '{count} ongewijzigde regels',
  },
  diffViewTooLarge: 'Het verschil is te groot om weer te geven.',
  jsonArray: 'array',
  jsonObject: 'object',
  jsonValue: 'waarde',
  jsonCopyLabel: '{label} kopiëren',
  jsonExpandLabel: '{label} uitklappen',
  jsonCollapseLabel: '{label} inklappen',
  jsonItemCount: {
    one: '{count} item',
    other: '{count} items',
  },
  jsonKeyCount: {
    one: '{count} sleutel',
    other: '{count} sleutels',
  },
  jsonViewerLimit: 'Alleen de eerste {count} JSON-knooppunten en {depth} nestingniveaus worden weergegeven en doorzocht.',
  pollPause: 'Pauzeren',
  pollResume: 'Hervatten',
  pollInactive: 'Inactief',
  pollRefreshing: 'Vernieuwen…',
  pollPaused: 'Gepauzeerd',
  pollPausedAnnounce: 'Gepauzeerd.',
  pollResumedAnnounce: 'Hervat.',
  pollRefreshingAnnounce: 'Wordt nu vernieuwd.',
  randomContentPause: 'Rotatie pauzeren',
  randomContentResume: 'Rotatie hervatten',
  exportButtonLabel: 'Exporteren',
  knownDateDay: 'Dag',
  knownDateMonth: 'Maand',
  knownDateYear: 'Jaar',
  exportFormatMenuLabel: '{label}-formaat',
  mentionSuggestions: 'Suggesties',
  mentionResultCount: {
    one: '{count} suggestie',
    other: '{count} suggesties',
  },
  mentionResultPosition: 'Suggestie {current} van {total}',
  iconLoadError: 'Het pictogram kon niet worden geladen.',
  iconTooLarge: 'Het pictogrambestand is te groot om weer te geven.',
  iconSanitizerMissing: 'Voor een veilige weergave van dit pictogram moet het optionele pakket "dompurify" zijn geïnstalleerd.',
  tourSkip: 'Overslaan',
  tourDone: 'Klaar',
  tourStepOf: 'Stap {current} van {total}',
};

registerLyraLocale('nl', strings, { dir: 'ltr', name: 'Nederlands' });
