// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON क्लिपबोर्डमा प्रतिलिपि गर्नुहोस्',
  circularReference: 'चक्रीय सन्दर्भ',
  copyDiff: 'भिन्नता प्रतिलिपि गर्नुहोस्',
  diffViewOldLabel: 'मूल',
  diffViewNewLabel: 'परिमार्जित',
  diffViewHiddenLines: {
    one: '{count} अपरिवर्तित पङ्क्ति',
    other: '{count} अपरिवर्तित पङ्क्तिहरू',
  },
  diffViewTooLarge: 'देखाउनका लागि भिन्नता धेरै ठूलो छ।',
  jsonArray: 'एरे',
  jsonObject: 'वस्तु',
  jsonValue: 'मान',
  jsonCopyLabel: '{label} प्रतिलिपि गर्नुहोस्',
  jsonExpandLabel: '{label} फैलाउनुहोस्',
  jsonCollapseLabel: '{label} खुम्च्याउनुहोस्',
  jsonItemCount: {
    one: '{count} वस्तु',
    other: '{count} वस्तुहरू',
  },
  jsonKeyCount: {
    one: '{count} कुञ्जी',
    other: '{count} कुञ्जीहरू',
  },
  jsonViewerLimit: 'पहिला {count} JSON नोड र {depth} तहसम्मको नेस्टिङ मात्र देखाइन्छ र खोजिन्छ।',
  pollPause: 'रोक्नुहोस्',
  pollResume: 'फेरि सुरु गर्नुहोस्',
  pollRefresh: 'अहिले ताजा गर्नुहोस्',
  pollInactive: 'निष्क्रिय',
  pollRefreshing: 'ताजा हुँदैछ…',
  pollPaused: 'रोकिएको',
  pollPausedAnnounce: 'रोकियो।',
  pollResumedAnnounce: 'फेरि सुरु भयो।',
  pollRefreshingAnnounce: 'अहिले ताजा हुँदैछ।',
  randomContentPause: 'घुमाइ रोक्नुहोस्',
  randomContentResume: 'घुमाइ फेरि सुरु गर्नुहोस्',
  randomContentNext: 'अर्को देखाउनुहोस्',
  exportButtonLabel: 'निर्यात गर्नुहोस्',
  knownDateDay: 'दिन',
  knownDateMonth: 'महिना',
  knownDateYear: 'वर्ष',
  exportFormatMenuLabel: '{label} ढाँचा',
  mentionSuggestions: 'सुझावहरू',
  mentionResultCount: {
    one: '{count} सुझाव',
    other: '{count} सुझावहरू',
  },
  mentionResultPosition: '{total} मध्ये सुझाव {current}',
  iconLoadError: 'आइकन लोड हुन सकेन।',
  iconTooLarge: 'देखाउनका लागि आइकन फाइल धेरै ठूलो छ।',
  iconSanitizerMissing: 'यो आइकन सुरक्षित रूपमा देखाउन वैकल्पिक "dompurify" प्याकेज स्थापना गर्नुपर्छ।',
  tourSkip: 'छोड्नुहोस्',
  tourDone: 'सम्पन्न',
  tourStepOf: '{total} मध्ये चरण {current}',
};

registerLyraLocale('ne', strings);
