import { DEFAULT_MAX_FILE_SIZE_BYTES } from '../src/lyra.js';
import type {
  BreadcrumbItemTarget,
  CardOrientation,
  FormatBytesUnit,
  FormatDisplay,
  LyraCarouselOrientation,
  LyraChartArea,
  LyraChartConfiguration,
  LyraChartDataConfiguration,
  LyraChartDatasetConfiguration,
  LyraChartPlugin,
  LyraChartValueFormatter,
  LyraChartValueFormatterContext,
  LyraComboboxAppearance,
  LyraComboboxPlacement,
  LyraComboboxTagRenderer,
  LyraEmojiPickerSize,
  LyraFileInputCapture,
  LyraLiteChartScale,
  LyraTimeRangeSize,
  LyraTokenInputSize,
  MenuItemSelectDetail,
  MenuItemStateChangeDetail,
  MenuItemVariant,
  RadioAppearance,
  RadioGroupOrientation,
  ResultCardAppearance,
  TableColumnEditable,
  TableEdgeAlign,
  TableSelectionMode,
  TableSortMode,
  TaskListAppearance,
  TreeBadgeTone,
  TreeSelection,
  WordCloudLegendItem,
  WordCloudOrientations,
  WordCloudScale,
} from '../src/lyra.js';

// Registration-free package-root reachability for every public property/configuration type found
// missing by the 2026-08-08 contract review. Keeping them in one tuple makes an accidental removal
// fail `test:types` even though the same name remains reachable from a granular or family entry.
const rootPublicTypes: [
  BreadcrumbItemTarget,
  CardOrientation,
  FormatBytesUnit,
  FormatDisplay,
  LyraCarouselOrientation,
  LyraChartArea,
  LyraChartConfiguration,
  LyraChartDataConfiguration,
  LyraChartDatasetConfiguration,
  LyraChartPlugin,
  LyraChartValueFormatter,
  LyraChartValueFormatterContext,
  LyraComboboxAppearance,
  LyraComboboxPlacement,
  LyraComboboxTagRenderer,
  LyraEmojiPickerSize,
  LyraFileInputCapture,
  LyraLiteChartScale,
  LyraTimeRangeSize,
  LyraTokenInputSize,
  MenuItemSelectDetail,
  MenuItemStateChangeDetail,
  MenuItemVariant,
  RadioAppearance,
  RadioGroupOrientation,
  ResultCardAppearance,
  TableColumnEditable,
  TableEdgeAlign,
  TableSelectionMode,
  TableSortMode,
  TaskListAppearance,
  TreeBadgeTone,
  TreeSelection,
  WordCloudLegendItem,
  WordCloudOrientations,
  WordCloudScale,
] | undefined = undefined;

void rootPublicTypes;
void DEFAULT_MAX_FILE_SIZE_BYTES;
