// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON क्लिपबोर्ड पर कॉपी करें',
  circularReference: 'चक्रीय संदर्भ',
  copyDiff: 'अंतर कॉपी करें',
  diffViewOldLabel: 'मूल',
  diffViewNewLabel: 'बदला हुआ',
  diffViewHiddenLines: {
    one: '{count} अपरिवर्तित पंक्ति',
    other: '{count} अपरिवर्तित पंक्तियाँ',
  },
  diffViewTooLarge: 'अंतर दिखाने के लिए बहुत बड़ा है।',
  jsonArray: 'ऐरे',
  jsonObject: 'ऑब्जेक्ट',
  jsonValue: 'मान',
  jsonCopyLabel: '{label} कॉपी करें',
  jsonExpandLabel: '{label} फैलाएँ',
  jsonCollapseLabel: '{label} समेटें',
  jsonItemCount: {
    one: '{count} आइटम',
    other: '{count} आइटम',
  },
  jsonKeyCount: {
    one: '{count} कुंजी',
    other: '{count} कुंजियाँ',
  },
  jsonViewerLimit: 'केवल पहले {count} JSON नोड और {depth} नेस्टिंग स्तर दिखाए और खोजे जाते हैं।',
  pollPause: 'रोकें',
  pollResume: 'फिर शुरू करें',
  pollInactive: 'निष्क्रिय',
  pollRefreshing: 'रीफ़्रेश हो रहा है…',
  pollPaused: 'रुका हुआ',
  pollPausedAnnounce: 'रोक दिया गया।',
  pollResumedAnnounce: 'फिर शुरू किया गया।',
  pollRefreshingAnnounce: 'अभी रीफ़्रेश हो रहा है।',
  randomContentPause: 'घुमाव रोकें',
  randomContentResume: 'घुमाव फिर शुरू करें',
  exportButtonLabel: 'निर्यात करें',
  knownDateDay: 'दिन',
  knownDateMonth: 'महीना',
  knownDateYear: 'वर्ष',
  exportFormatMenuLabel: '{label} फ़ॉर्मैट',
  mentionSuggestions: 'सुझाव',
  mentionResultCount: {
    one: '{count} सुझाव',
    other: '{count} सुझाव',
  },
  mentionResultPosition: '{total} में से सुझाव {current}',
  iconLoadError: 'आइकन लोड नहीं हो सका।',
  iconTooLarge: 'आइकन फ़ाइल दिखाने के लिए बहुत बड़ी है।',
  iconSanitizerMissing: 'इस आइकन को सुरक्षित रूप से दिखाने के लिए वैकल्पिक "dompurify" पैकेज इंस्टॉल करें।',
  tourSkip: 'छोड़ें',
  tourDone: 'पूरा हुआ',
  tourStepOf: '{total} में से चरण {current}',
};

registerLyraLocale('hi', strings);
