// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Baho',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Yopish: {snippet}',
  closeWithTruncatedContext: 'Yopish: {snippet}…',
  toastContentIncomplete: 'Tarkibi toʻliq boʻlmagan bildirishnoma',
  toastOverflow: '{count} ta bildirishnoma koʻrsatilmadi.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Boʻsh joy',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Oʻchirish',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'Yuqori strelka',
  kbdArrowDownWord: 'Pastki strelka',
  kbdArrowLeftWord: 'Chap strelka',
  kbdArrowRightWord: 'Oʻng strelka',
  kbdPlusWord: 'Qoʻshish',
  kbdMinusWord: 'Ayirish',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('uz', strings);
