// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSONʼni clipboardʼga nusxalash',
  circularReference: 'Siklik havola',
  copyDiff: 'Farqni nusxalash',
  diffViewOldLabel: 'Asl',
  diffViewNewLabel: 'Oʻzgartirilgan',
  diffViewHiddenLines: {
    one: '{count} oʻzgarmagan qator',
    other: '{count} oʻzgarmagan qator',
  },
  diffViewTooLarge: 'Farqni koʻrsatish uchun juda katta.',
  jsonArray: 'Massiv',
  jsonObject: 'Obyekt',
  jsonValue: 'qiymat',
  jsonCopyLabel: '{label}ni nusxalash',
  jsonExpandLabel: '{label}ni yoyish',
  jsonCollapseLabel: '{label}ni yigʻish',
  jsonItemCount: {
    one: '{count} ta element',
    other: '{count} ta element',
  },
  jsonKeyCount: {
    one: '{count} ta kalit',
    other: '{count} ta kalit',
  },
  jsonViewerLimit: 'Faqat dastlabki {count} ta JSON tuguni va {depth} ta ichma-ichlik darajasi koʻrsatiladi va qidiriladi.',
  pollPause: 'Toʻxtatib turish',
  pollResume: 'Davom ettirish',
  pollInactive: 'Faol emas',
  pollRefreshing: 'Yangilanmoqda…',
  pollPaused: 'Toʻxtatildi',
  pollPausedAnnounce: 'Toʻxtatildi.',
  pollResumedAnnounce: 'Davom ettirildi.',
  pollRefreshingAnnounce: 'Hozir yangilanmoqda.',
  randomContentPause: 'Aylanishni toʻxtatish',
  randomContentResume: 'Aylanishni davom ettirish',
  exportButtonLabel: 'Eksport qilish',
  knownDateDay: 'Kun',
  knownDateMonth: 'Oy',
  knownDateYear: 'Yil',
  exportFormatMenuLabel: '{label} formati',
  mentionSuggestions: 'Takliflar',
  mentionResultCount: {
    one: '{count} ta taklif',
    other: '{count} ta taklif',
  },
  mentionResultPosition: '{total} tadan {current}-taklif',
  iconLoadError: 'Belgini yuklab boʻlmadi.',
  iconTooLarge: 'Belgi fayli koʻrsatish uchun juda katta.',
  iconSanitizerMissing: 'Belgini xavfsiz koʻrsatish uchun ixtiyoriy "dompurify" paketini oʻrnatish kerak.',
  tourSkip: 'Oʻtkazib yuborish',
  tourDone: 'Tayyor',
  tourStepOf: '{total} tadan {current}-qadam',
};

registerLyraLocale('uz', strings);
