// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'အဆင့်သတ်မှတ်ချက်',
  calloutAnnouncementWithContext: '{context} — {content}',
  closeWithContext: 'ပိတ်ရန်: {snippet}',
  closeWithTruncatedContext: 'ပိတ်ရန်: {snippet}…',
  toastContentIncomplete: 'အကြောင်းအရာ မပြည့်စုံသော အသိပေးချက်',
  toastOverflow: 'မပြထားသော အသိပေးချက် {count} ခု။',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Space',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'ဖျက်ရန်',
  kbdHomeWord: 'အစ',
  kbdEndWord: 'အဆုံး',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'စာမျက်နှာ အပေါ်',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'စာမျက်နှာ အောက်',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'အပေါ်မြှား',
  kbdArrowDownWord: 'အောက်မြှား',
  kbdArrowLeftWord: 'ဘယ်မြှား',
  kbdArrowRightWord: 'ညာမြှား',
  kbdPlusWord: 'ပေါင်း',
  kbdMinusWord: 'နုတ်',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('my', strings);
