// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON ကို ကလစ်ဘုတ်သို့ ကူးယူရန်',
  circularReference: 'စက်ဝိုင်းပုံ ကိုးကားမှု',
  copyDiff: 'ကွာခြားချက်ကို ကူးယူရန်',
  diffViewOldLabel: 'မူရင်း',
  diffViewNewLabel: 'ပြင်ဆင်ပြီး',
  diffViewHiddenLines: {
    other: 'မပြောင်းလဲသော စာကြောင်း {count} ကြောင်း',
  },
  diffViewTooLarge: 'ကွာခြားချက်ကို ပြရန် အလွန်ကြီးမားနေသည်။',
  jsonArray: 'အခင်း',
  jsonObject: 'အရာဝတ္ထု',
  jsonValue: 'တန်ဖိုး',
  jsonCopyLabel: '{label} ကို ကူးယူရန်',
  jsonExpandLabel: '{label} ကို ချဲ့ရန်',
  jsonCollapseLabel: '{label} ကို ခေါက်သိမ်းရန်',
  jsonItemCount: {
    other: 'အရာ {count} ခု',
  },
  jsonKeyCount: {
    other: 'ကီး {count} ခု',
  },
  jsonViewerLimit: 'ပထမဆုံး JSON နိုဒ် {count} ခုနှင့် အဆင့်ဆင့်အတွင်းဝင်မှု {depth} အဆင့်အထိကိုသာ ပြသပြီး ရှာဖွေသည်။',
  pollPause: 'ခေတ္တရပ်ရန်',
  pollResume: 'ပြန်စရန်',
  pollInactive: 'မလှုပ်ရှားပါ',
  pollRefreshing: 'ပြန်လည်စတင်နေသည်…',
  pollPaused: 'ခေတ္တရပ်ထားသည်',
  pollPausedAnnounce: 'ခေတ္တရပ်ထားသည်။',
  pollResumedAnnounce: 'ပြန်စလိုက်သည်။',
  pollRefreshingAnnounce: 'ယခု ပြန်လည်စတင်နေသည်။',
  randomContentPause: 'လှည့်ပတ်မှုကို ခေတ္တရပ်ရန်',
  randomContentResume: 'လှည့်ပတ်မှုကို ပြန်စရန်',
  exportButtonLabel: 'ထုတ်ယူရန်',
  knownDateDay: 'နေ့',
  knownDateMonth: 'လ',
  knownDateYear: 'နှစ်',
  exportFormatMenuLabel: '{label} ပုံစံ',
  mentionSuggestions: 'အကြံပြုချက်များ',
  mentionResultCount: {
    other: 'အကြံပြုချက် {count} ခု',
  },
  mentionResultPosition: 'အကြံပြုချက် {total} ခုအနက် {current} ခုမြောက်',
  iconLoadError: 'အိုင်ကွန်ကို မတင်နိုင်ပါ။',
  iconTooLarge: 'အိုင်ကွန်ဖိုင်သည် ပြရန် အလွန်ကြီးမားနေသည်။',
  iconSanitizerMissing: 'ဤအိုင်ကွန်ကို ဘေးကင်းစွာပြရန် ရွေးချယ်နိုင်သော "dompurify" ပက်ကေ့ဂျ်ကို ထည့်သွင်းရန် လိုအပ်သည်။',
  tourSkip: 'ကျော်ရန်',
  tourDone: 'ပြီးပါပြီ',
  tourStepOf: 'အဆင့် {total} ခုအနက် {current} ခုမြောက်',
};

registerLyraLocale('my', strings);
