#!/usr/bin/env bash
# Packages both plugin skills into deterministic standalone archives. Before packaging the API
# reference skill, regenerates its references/ from packages/lyra-ui/llms/ (the published component
# API docs, themselves generated by `pnpm --filter @aceshooting/lyra-ui run llms`). The references
# are generated copies so the archive stays self-contained.
#
# The skill deliberately does NOT ship llms-full.txt: it is the same content concatenated into one
# ~750 KB file, and an agent reading a single component should pay for one component, not the whole
# catalog. references/components/<tag>.md is addressed directly from the tag name.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="${ROOT_DIR}/plugins/lyra-ui/skills/lyra-ui"
REFERENCES_DIR="${SKILL_DIR}/references"
LLMS_DIR="${ROOT_DIR}/packages/lyra-ui/llms"
OUTPUT_DIR="${ROOT_DIR}/skills"
OUTPUT_PATH="${OUTPUT_DIR}/lyra-ui.skill"
SKILL_MD="${SKILL_DIR}/SKILL.md"
COMPOSITION_SKILL_DIR="${ROOT_DIR}/plugins/lyra-ui/skills/compose-lyra-interfaces"
COMPOSITION_OUTPUT_PATH="${OUTPUT_DIR}/compose-lyra-interfaces.skill"

echo "Validating ${SKILL_MD} frontmatter..."
if [[ ! -f "${SKILL_MD}" ]]; then
  echo "Error: ${SKILL_MD} not found." >&2
  exit 1
fi
if ! grep -q "^name:" "${SKILL_MD}"; then
  echo "Error: ${SKILL_MD} is missing a 'name:' frontmatter field." >&2
  exit 1
fi
if ! grep -q "^description:" "${SKILL_MD}"; then
  echo "Error: ${SKILL_MD} is missing a 'description:' frontmatter field." >&2
  exit 1
fi

if [[ ! -d "${LLMS_DIR}/components" ]]; then
  echo "Error: ${LLMS_DIR}/components not found — run \`pnpm --filter @aceshooting/lyra-ui run llms\` first." >&2
  exit 1
fi

echo "Regenerating references/ from packages/lyra-ui/llms/..."
rm -rf "${REFERENCES_DIR}"
mkdir -p "${REFERENCES_DIR}"
for file in index.md shared.md tokens.md peers.md migration.md; do
  cp "${LLMS_DIR}/${file}" "${REFERENCES_DIR}/${file}"
done
cp -r "${LLMS_DIR}/components" "${REFERENCES_DIR}/components"

mkdir -p "${OUTPUT_DIR}"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

package_skill() {
  local source_dir="$1"
  local output_path="$2"
  local staging_name="$3"
  local skill_md="${source_dir}/SKILL.md"
  local staging_dir="${TMP_DIR}/${staging_name}"

  echo "Validating ${skill_md} frontmatter..."
  if [[ ! -f "${skill_md}" ]]; then
    echo "Error: ${skill_md} not found." >&2
    exit 1
  fi
  if ! grep -q "^name:" "${skill_md}"; then
    echo "Error: ${skill_md} is missing a 'name:' frontmatter field." >&2
    exit 1
  fi
  if ! grep -q "^description:" "${skill_md}"; then
    echo "Error: ${skill_md} is missing a 'description:' frontmatter field." >&2
    exit 1
  fi

  echo "Packaging ${output_path}..."
  rm -f "${output_path}"
  cp -r "${source_dir}" "${staging_dir}"
  find "${staging_dir}" -name '.DS_Store' -delete
  # Build a byte-for-byte stable ZIP: normalize timestamps, permissions, traversal order, and
  # compression settings instead of relying on platform-specific `zip` metadata.
  find "${staging_dir}" -exec touch -t 198001010000.00 {} +
  python3 - "${staging_dir}" "${output_path}" <<'PY'
import os
import sys
import zipfile

root, output = sys.argv[1:]
with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
    for current, directories, files in os.walk(root):
        directories.sort()
        files.sort()
        for name in files:
            absolute = os.path.join(current, name)
            relative = os.path.relpath(absolute, root).replace(os.sep, "/")
            info = zipfile.ZipInfo(relative, (1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            with open(absolute, "rb") as source:
                archive.writestr(info, source.read(), compress_type=zipfile.ZIP_DEFLATED, compresslevel=9)
PY

  if [[ -s "${output_path}" ]]; then
    echo "Created ${output_path} ($(du -h "${output_path}" | cut -f1))"
  else
    echo "Error: failed to create ${output_path}" >&2
    exit 1
  fi

  echo "Verifying packaged skill contents..."
  while IFS= read -r absolute_file; do
    relative_file="${absolute_file#"${source_dir}/"}"
    if ! unzip -p "${output_path}" "${relative_file}" | cmp -s - "${absolute_file}"; then
      echo "Error: ${output_path} contains stale or incorrect ${relative_file}" >&2
      exit 1
    fi
  done < <(find "${source_dir}" -type f)
  echo "Packaged skill contents are synchronized ($(unzip -l "${output_path}" | tail -1 | awk '{print $2}') files)."
}

package_skill "${SKILL_DIR}" "${OUTPUT_PATH}" "lyra-ui"
package_skill "${COMPOSITION_SKILL_DIR}" "${COMPOSITION_OUTPUT_PATH}" "compose-lyra-interfaces"
