#!/usr/bin/env bash
# Packages plugins/lyra-ui/skills/lyra-ui/ into ./skills/lyra-ui.skill, after regenerating its
# references/ from packages/lyra-ui/llms/ (the published component API docs, themselves generated by
# `pnpm --filter @aceshooting/lyra-ui run llms`). The references are generated copies so the archive
# stays self-contained.
#
# The skill deliberately does NOT ship llms-full.txt: it is the same content concatenated into one
# ~750 KB file, and an agent reading a single component should pay for one component, not the whole
# catalog. references/components/<tag>.md is addressed directly from the tag name.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="${ROOT_DIR}/plugins/lyra-ui/skills/lyra-ui"
REFERENCES_DIR="${SKILL_DIR}/references"
LLMS_DIR="${ROOT_DIR}/packages/lyra-ui/llms"
OUTPUT_DIR="${ROOT_DIR}/skills"
OUTPUT_PATH="${OUTPUT_DIR}/lyra-ui.skill"
SKILL_MD="${SKILL_DIR}/SKILL.md"

echo "Validating ${SKILL_MD} frontmatter..."
if [[ ! -f "${SKILL_MD}" ]]; then
  echo "Error: ${SKILL_MD} not found." >&2
  exit 1
fi
if ! grep -q "^name:" "${SKILL_MD}"; then
  echo "Error: ${SKILL_MD} is missing a 'name:' frontmatter field." >&2
  exit 1
fi
if ! grep -q "^description:" "${SKILL_MD}"; then
  echo "Error: ${SKILL_MD} is missing a 'description:' frontmatter field." >&2
  exit 1
fi

if [[ ! -d "${LLMS_DIR}/components" ]]; then
  echo "Error: ${LLMS_DIR}/components not found — run \`pnpm --filter @aceshooting/lyra-ui run llms\` first." >&2
  exit 1
fi

echo "Regenerating references/ from packages/lyra-ui/llms/..."
rm -rf "${REFERENCES_DIR}"
mkdir -p "${REFERENCES_DIR}"
for file in index.md shared.md tokens.md peers.md migration.md; do
  cp "${LLMS_DIR}/${file}" "${REFERENCES_DIR}/${file}"
done
cp -r "${LLMS_DIR}/components" "${REFERENCES_DIR}/components"

echo "Packaging ${OUTPUT_PATH}..."
mkdir -p "${OUTPUT_DIR}"
rm -f "${OUTPUT_PATH}"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT
cp -r "${SKILL_DIR}" "${TMP_DIR}/lyra-ui"
find "${TMP_DIR}" -name '.DS_Store' -delete
# Build a byte-for-byte stable ZIP: normalize timestamps, permissions, traversal order, and
# compression settings instead of relying on platform-specific `zip` metadata.
find "${TMP_DIR}/lyra-ui" -exec touch -t 198001010000.00 {} +
python3 - "${TMP_DIR}/lyra-ui" "${OUTPUT_PATH}" <<'PY'
import os
import sys
import zipfile

root, output = sys.argv[1:]
with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
    for current, directories, files in os.walk(root):
        directories.sort()
        files.sort()
        for name in files:
            absolute = os.path.join(current, name)
            relative = os.path.relpath(absolute, root).replace(os.sep, "/")
            info = zipfile.ZipInfo(relative, (1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            with open(absolute, "rb") as source:
                archive.writestr(info, source.read(), compress_type=zipfile.ZIP_DEFLATED, compresslevel=9)
PY

if [[ -s "${OUTPUT_PATH}" ]]; then
  echo "Created ${OUTPUT_PATH} ($(du -h "${OUTPUT_PATH}" | cut -f1))"
else
  echo "Error: failed to create ${OUTPUT_PATH}" >&2
  exit 1
fi

echo "Verifying packaged skill contents..."
while IFS= read -r absolute_file; do
  relative_file="${absolute_file#"${SKILL_DIR}/"}"
  if ! unzip -p "${OUTPUT_PATH}" "${relative_file}" | cmp -s - "${absolute_file}"; then
    echo "Error: ${OUTPUT_PATH} contains stale or incorrect ${relative_file}" >&2
    exit 1
  fi
done < <(find "${SKILL_DIR}" -type f)
echo "Packaged skill contents are synchronized ($(unzip -l "${OUTPUT_PATH}" | tail -1 | awk '{print $2}') files)."
