packages:
  - 'packages/*'
overrides:
  '@xmldom/xmldom': ^0.8.13
minimumReleaseAgeExclude:
  - '@aceshooting/lyra-flags@0.1.0'
allowBuilds:
  esbuild: true
  rs-module-lexer: true
  core-js: true
  es5-ext: true
