// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'carousel',
  carouselLabel: 'Carousel',
  carouselSlide: 'slide',
  carouselSlidePosition: 'Slide {index} out of {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Di carousel slides',
  carouselGoTo: 'Go reach slide {index}',
  scrollerLabel: 'Content wey you fit scroll',
  scrollPrevious: 'Scroll go back',
  scrollNext: 'Scroll go front',
  closeNavigation: 'Close di navigation',
  openNavigation: 'Open di navigation',
  resizeNavigation: 'Change navigation size',
  appRailCollapse: 'Collapse di navigation',
  appRailExpand: 'Expand di navigation',
  appRailItemCollapse: 'Collapse di {label}',
  appRailItemExpand: 'Expand di {label}',
  resizeValuePercent: '{value} percent',
  commandPaletteLabel: 'List of commands wey you fit run',
  commandPalettePlaceholder: 'Find command wey you wan use…',
  commandPaletteEmpty: 'No command match.',
  commandPaletteResults: 'Commands',
  dockPanelCollapse: 'Collapse di panel',
  dockPanelExpand: 'Expand di panel',
  dockPanelResize: 'Change di panel size',
  responsivePanel: 'Panel',
  breadcrumb: 'Path wey show where you dey',
  resizeDivider: 'Change di divider size between panel {a} and panel {b}',
  widgetFullscreenPanel: 'Panel wey full screen',
  widgetViewGroup: 'How panel dey look',
  widgetExitFullscreen: 'Comot fullscreen',
  widgetExpandToFullscreen: 'Expand reach fullscreen',
  widgetCollapse: 'Collapse di panel',
  widgetExpand: 'Expand di panel',
  skipToContent: 'Skip go content',
  dashboardGridLabel: 'Dashboard grid',
  dashboardCellCollisionRejected: 'You no fit put {label} there because e dey cover another cell.',
  dashboardCellMoved: 'Dem move {label} go column {x}, row {y}.',
  dashboardCellResized: 'Dem change {label} size to width {w}, height {h}.',
  filterBarReset: 'Reset di filters',
  filterBarActiveFilters: 'Filters wey dey on',
  drilldownDocuments: 'Documents',
  drilldownRuns: 'Agent runs',
  drilldownEmpty: 'You never select any item',
  drilldownUntitledNode: 'Step wey no get title',
  reorderMovePending: 'Reorder dey wait.',
  reorderMoveCancelled: 'Dem cancel di reorder.',
  commandPaletteResultCount: {
    one: '{count} command dey',
    other: '{count} command dem dey',
  },
};

registerLyraLocale('pcm', strings);
