// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'Copy JSON go clipboard',
  circularReference: 'Reference wey dey go round',
  copyDiff: 'Copy di diff',
  diffViewOldLabel: 'Wetin dey before',
  diffViewNewLabel: 'Wetin don change',
  diffViewHiddenLines: {
    one: '{count} line wey no change',
    other: '{count} lines wey no change',
  },
  diffViewTooLarge: 'Diff too big to show.',
  jsonArray: 'array',
  jsonObject: 'object',
  jsonValue: 'value',
  jsonCopyLabel: 'Copy am: {label}',
  jsonExpandLabel: 'Expand am: {label}',
  jsonCollapseLabel: 'Collapse am: {label}',
  jsonItemCount: {
    one: '{count} item',
    other: '{count} item dem',
  },
  jsonKeyCount: {
    one: '{count} key',
    other: '{count} key dem',
  },
  jsonViewerLimit: 'Na only di first {count} JSON nodes and {depth} nesting levels dem show and search.',
  pollPause: 'Pause am',
  pollResume: 'Continue am',
  pollRefresh: 'Make am refresh now',
  pollInactive: 'E no dey active',
  pollRefreshing: 'E dey refresh…',
  pollPaused: 'E don pause',
  pollPausedAnnounce: 'E don pause.',
  pollResumedAnnounce: 'E don continue.',
  pollRefreshingAnnounce: 'E dey refresh now.',
  randomContentPause: 'Pause di rotation',
  randomContentResume: 'Continue rotation',
  randomContentNext: 'Show anoda one',
  exportButtonLabel: 'Export am',
  knownDateDay: 'Day',
  knownDateMonth: 'Month',
  knownDateYear: 'Year',
  exportFormatMenuLabel: 'Format for {label}',
  mentionSuggestions: 'Things e suggest',
  mentionResultCount: {
    one: '{count} suggestion',
    other: '{count} suggestion dem',
  },
  mentionResultPosition: 'Suggestion {current} out of {total}',
  iconLoadError: 'Di icon no load.',
  iconTooLarge: 'Di icon file too big to show.',
  iconSanitizerMissing: 'Dis icon need make you install di optional "dompurify" package so e go render safely.',
  tourSkip: 'Skip am',
  tourDone: 'We don finish',
  tourStepOf: 'Step {current} out of {total}',
  mentionMoreResults: {
    one: '{count} more suggestion dey',
    other: '{count} more suggestion dem dey',
  },
};

registerLyraLocale('pcm', strings);
