// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `charts` slice of the it translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/charts/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/it/charts';` and reads nothing from it.
// `../it.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  chartCategory: 'Categoria',
  chartTotal: 'Totale',
  chartAxisTotal: 'Totale {axis}',
  chartPrimaryAxis: 'Asse primario',
  chartSecondaryAxis: 'Asse secondario',
  chartPointLabel: 'Punto {n}',
  chartPointCoordinates: 'x {x}, y {y}',
  chartBubblePointCoordinates: 'x {x}, y {y}, raggio {radius}',
  chartLabeledPoint: '{label}: {coordinates}',
  chartTrendIncreasing: 'in aumento',
  chartTrendDecreasing: 'in diminuzione',
  chartTrendFlat: 'stabile',
  chartSummary: '{label}: {count} valori, intervallo da {min} a {max}, tendenza {trend}',
  chartSeriesNoData: '{label}: nessun dato',
  chartSummaryWithData: 'Grafico {type}. {summaries}.',
  chartSummaryEmpty: 'Grafico {type} senza dati.',
  chartSummarySeparator: '. ',
  chartData: 'Dati del grafico',
  chartDataSampled: 'La tabella dati generata mostra un campione di fino a 1.000 record. Fornisci una tabella dati personalizzata per accedere a tutti i dati del grafico.',
  chartZoomUnavailable: 'Lo zoom non è disponibile, ma il grafico principale resta disponibile.',
  chartDataLabelsUnavailable: 'Le etichette dati non sono disponibili, ma il grafico principale resta disponibile.',
  chartStackTotalsUnavailable: 'I totali delle pile non sono disponibili, ma il grafico principale resta disponibile.',
  chartAnnotationsUnavailable: 'Le annotazioni del grafico non sono disponibili, ma il grafico principale resta disponibile.',
  chartTypeLine: 'Linee',
  chartTypeBar: 'Barre',
  chartTypeScatter: 'Dispersione',
  chartTypePie: 'Torta',
  chartTypeDoughnut: 'Ciambella',
  chartTypeRadar: 'Radar',
  chartTypePolarArea: 'Area polare',
  chartTypeBubble: 'Bolle',
  boxPlotSeriesSummary: '{label}: {count} distribuzioni, intervallo mediano da {min} a {max}, tendenza mediana {trend}',
  boxPlotSummaryWithData: 'Box plot. {summaries}.',
  boxPlotSummaryEmpty: 'Box plot senza dati.',
  boxPlotData: 'Dati del box plot',
  chartSeriesLabel: 'Serie',
  boxPlotMin: 'Min',
  boxPlotQ1: 'Q1',
  boxPlotMedian: 'Mediana',
  boxPlotQ3: 'Q3',
  boxPlotMax: 'Max',
  boxPlot: 'Box plot',
  histogramFrequency: 'Frequenza',
  liteChartMarkSummary: '{series}, {label}: {value} ({index} di {total})',
  liteChartBarLabel: '{series}, {label}: {value}',
  chartValuePercentageLabel: '{label}: {value} ({percentage})',
  liteChartCustomMarkSummary: '{content} ({index} di {total})',
  chartMissingLibrary: 'Questo componente richiede il pacchetto opzionale "chart.js" installato per visualizzare i grafici.',
  boxPlotMissingLibrary: 'Questo componente richiede il pacchetto opzionale per i box plot installato per visualizzarli.',
};

registerLyraLocale('it', strings);
