// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'carosello',
  carouselLabel: 'Carosello',
  carouselSlide: 'diapositiva',
  carouselSlidePosition: 'Diapositiva {index} di {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Diapositive del carosello',
  carouselGoTo: 'Vai alla diapositiva {index}',
  scrollerLabel: 'Contenuto scorrevole',
  scrollPrevious: 'Scorri indietro',
  scrollNext: 'Scorri avanti',
  closeNavigation: 'Chiudi la navigazione',
  openNavigation: 'Apri la navigazione',
  resizeNavigation: 'Ridimensiona la navigazione',
  appRailCollapse: 'Comprimi la navigazione',
  appRailExpand: 'Espandi la navigazione',
  appRailItemCollapse: 'Comprimi {label}',
  appRailItemExpand: 'Espandi {label}',
  resizeValuePercent: '{value} percento',
  commandPaletteLabel: 'Tavolozza dei comandi',
  commandPalettePlaceholder: 'Cerca comandi…',
  commandPaletteEmpty: 'Nessun comando corrispondente.',
  commandPaletteResults: 'Comandi',
  dockPanelCollapse: 'Comprimi il pannello',
  dockPanelExpand: 'Espandi il pannello',
  dockPanelResize: 'Ridimensiona il pannello',
  responsivePanel: 'Pannello',
  breadcrumb: 'Percorso di navigazione',
  resizeDivider: 'Ridimensiona il divisore tra il pannello {a} e il pannello {b}',
  widgetFullscreenPanel: 'Pannello a schermo intero',
  widgetViewGroup: 'Vista del pannello',
  widgetExitFullscreen: 'Esci dallo schermo intero',
  widgetExpandToFullscreen: 'Espandi a schermo intero',
  widgetCollapse: 'Comprimi il pannello',
  widgetExpand: 'Espandi il pannello',
  skipToContent: 'Vai al contenuto',
  dashboardGridLabel: 'Griglia della dashboard',
  dashboardCellCollisionRejected: '{label} non può essere posizionato qui perché si sovrappone a un’altra cella.',
  dashboardCellMoved: '{label} spostato nella colonna {x}, riga {y}.',
  dashboardCellResized: '{label} ridimensionato a larghezza {w}, altezza {h}.',
  filterBarReset: 'Ripristina i filtri',
  filterBarActiveFilters: 'Filtri attivi',
  drilldownDocuments: 'Documenti',
  drilldownRuns: 'Esecuzioni agente',
  drilldownEmpty: 'Nessun elemento selezionato',
  drilldownUntitledNode: 'Passaggio senza titolo',
  reorderMovePending: 'Riordinamento in corso.',
  reorderMoveCancelled: 'Riordinamento annullato.',
  commandPaletteResultCount: {
    one: 'comando {count}',
    many: '{count} comandi',
    other: '{count} comandi',
  },
};

registerLyraLocale('it', strings);
