// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Valutazione',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Chiudi: {snippet}',
  closeWithTruncatedContext: 'Chiudi: {snippet}…',
  toastContentIncomplete: 'Notifica con contenuto incompleto',
  toastOverflow: 'Notifiche non mostrate: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Esc',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Spazio',
  kbdDeleteVisual: 'Canc',
  kbdDeleteWord: 'Canc',
  kbdHomeWord: 'Home',
  kbdEndWord: 'Fine',
  kbdPageUpVisual: 'Pag ↑',
  kbdPageUpWord: 'Pagina su',
  kbdPageDownVisual: 'Pag ↓',
  kbdPageDownWord: 'Pagina giù',
  kbdEnterWord: 'Invio',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'Freccia su',
  kbdArrowDownWord: 'Freccia giù',
  kbdArrowLeftWord: 'Freccia sinistra',
  kbdArrowRightWord: 'Freccia destra',
  kbdPlusWord: 'Più',
  kbdMinusWord: 'Meno',
  kbdCommandWord: 'Cmd',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Ctrl',
  kbdOptionWord: 'Opzione',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Maiusc',
};

registerLyraLocale('it', strings);
