// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `utility` slice of the it translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/utility/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/it/utility';` and reads nothing from it.
// `../it.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'Copia JSON negli appunti',
  circularReference: 'Riferimento circolare',
  copyDiff: 'Copia diff',
  diffViewOldLabel: 'Originale',
  diffViewNewLabel: 'Modificato',
  diffViewHiddenLines: {
    one: '{count} riga invariata',
    many: '{count} righe invariate',
    other: '{count} righe invariate',
  },
  diffViewTooLarge: 'Il diff è troppo grande per essere mostrato.',
  jsonArray: 'array',
  jsonObject: 'oggetto',
  jsonValue: 'valore',
  jsonCopyLabel: 'Copia {label}',
  jsonExpandLabel: 'Espandi {label}',
  jsonCollapseLabel: 'Comprimi {label}',
  jsonItemCount: {
    one: '{count} elemento',
    many: '{count} elementi',
    other: '{count} elementi',
  },
  jsonKeyCount: {
    one: '{count} chiave',
    many: '{count} chiavi',
    other: '{count} chiavi',
  },
  jsonViewerLimit: 'Vengono mostrati e ricercati solo i primi {count} nodi JSON e {depth} livelli di annidamento.',
  pollPause: 'Sospendi',
  pollResume: 'Riprendi',
  pollInactive: 'Inattivo',
  pollRefreshing: 'Aggiornamento…',
  pollPaused: 'In pausa',
  pollPausedAnnounce: 'In pausa.',
  pollResumedAnnounce: 'Ripreso.',
  pollRefreshingAnnounce: 'Aggiornamento in corso.',
  randomContentPause: 'Sospendi rotazione',
  randomContentResume: 'Riprendi rotazione',
  exportButtonLabel: 'Esporta',
  knownDateDay: 'Giorno',
  knownDateMonth: 'Mese',
  knownDateYear: 'Anno',
  exportFormatMenuLabel: 'Formato {label}',
  mentionSuggestions: 'Suggerimenti',
  mentionResultCount: {
    one: '{count} suggerimento',
    many: '{count} suggerimenti',
    other: '{count} suggerimenti',
  },
  mentionResultPosition: 'Suggerimento {current} di {total}',
  iconLoadError: 'Impossibile caricare l’icona.',
  iconTooLarge: 'Il file dell’icona è troppo grande per essere mostrato.',
  iconSanitizerMissing: 'Questa icona richiede il pacchetto opzionale "dompurify" installato per essere visualizzata in sicurezza.',
  tourSkip: 'Salta',
  tourDone: 'Fine',
  tourStepOf: 'Passaggio {current} di {total}',
};

registerLyraLocale('it', strings);
