// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `layout` slice of the pl translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/layout/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/pl/layout';` and reads nothing from it.
// `../pl.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'karuzela',
  carouselLabel: 'Karuzela',
  carouselSlide: 'slajd',
  carouselSlidePosition: 'Slajd {index} z {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Slajdy karuzeli',
  carouselGoTo: 'Przejdź do slajdu {index}',
  scrollerLabel: 'Przewijana treść',
  scrollPrevious: 'Przewiń wstecz',
  scrollNext: 'Przewiń dalej',
  closeNavigation: 'Zamknij nawigację',
  openNavigation: 'Otwórz nawigację',
  resizeNavigation: 'Zmień rozmiar nawigacji',
  appRailCollapse: 'Zwiń nawigację',
  appRailExpand: 'Rozwiń nawigację',
  appRailItemCollapse: 'Zwiń {label}',
  appRailItemExpand: 'Rozwiń {label}',
  resizeValuePercent: '{value} procent',
  commandPaletteLabel: 'Paleta poleceń',
  commandPalettePlaceholder: 'Szukaj poleceń…',
  commandPaletteEmpty: 'Brak pasujących poleceń.',
  commandPaletteResults: 'Polecenia',
  dockPanelCollapse: 'Zwiń panel',
  dockPanelExpand: 'Rozwiń panel',
  dockPanelResize: 'Zmień rozmiar panelu',
  responsivePanel: 'Panel',
  breadcrumb: 'Okruszki nawigacyjne',
  resizeDivider: 'Zmień rozmiar separatora między panelami {a} i {b}',
  widgetFullscreenPanel: 'Panel pełnoekranowy',
  widgetViewGroup: 'Widok panelu',
  widgetExitFullscreen: 'Zamknij pełny ekran',
  widgetExpandToFullscreen: 'Rozwiń do pełnego ekranu',
  widgetCollapse: 'Zwiń panel',
  widgetExpand: 'Rozwiń panel',
  skipToContent: 'Przejdź do treści',
  dashboardGridLabel: 'Siatka pulpitu',
  dashboardCellCollisionRejected: 'Nie można umieścić elementu {label} w tym miejscu, ponieważ nachodzi na inną komórkę.',
  dashboardCellMoved: 'Przeniesiono {label} do kolumny {x}, wiersza {y}.',
  dashboardCellResized: 'Zmieniono rozmiar {label}: szerokość {w}, wysokość {h}.',
  filterBarReset: 'Wyczyść filtry',
  filterBarActiveFilters: 'Aktywne filtry',
  drilldownDocuments: 'Dokumenty',
  drilldownRuns: 'Uruchomienia agenta',
  drilldownEmpty: 'Nie wybrano elementu',
  drilldownUntitledNode: 'Krok bez tytułu',
  reorderMovePending: 'Oczekiwanie na zmianę kolejności.',
  reorderMoveCancelled: 'Anulowano zmianę kolejności.',
};

registerLyraLocale('pl', strings);
