// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Ocena',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Zamknij: {snippet}',
  closeWithTruncatedContext: 'Zamknij: {snippet}…',
  toastContentIncomplete: 'Powiadomienie z niepełną treścią',
  toastOverflow: 'Nie wyświetlono powiadomień: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Spacja',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Usuń',
  kbdHomeWord: 'Początek',
  kbdEndWord: 'Koniec',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'Strzałka w górę',
  kbdArrowDownWord: 'Strzałka w dół',
  kbdArrowLeftWord: 'Strzałka w lewo',
  kbdArrowRightWord: 'Strzałka w prawo',
  kbdPlusWord: 'Plus',
  kbdMinusWord: 'Minus',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('pl', strings);
