// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import '../de/charts.js';
import { registerLyraLocaleDelta } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  chartMissingLibrary: 'Für diese Komponente muss das optionale Paket «chart.js» installiert sein, um Diagramme darzustellen.',
};

registerLyraLocaleDelta('de-CH', 'de', strings, { dir: 'ltr' });
