// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import '../de/retrieval.js';
import { registerLyraLocaleDelta } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  graphMissingLibrary: 'Für diese Komponente muss das optionale Paket «d3» installiert sein, um den Graphen darzustellen.',
  memoryPanelAddWithContext: '«{label}» zum Langzeitgedächtnis hinzufügen',
};

registerLyraLocaleDelta('de-CH', 'de', strings, { dir: 'ltr' });
