// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import '../de/utility.js';
import { registerLyraLocaleDelta } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  diffViewTooLarge: 'Der Diff ist zu gross für die Anzeige.',
  iconTooLarge: 'Die Symboldatei ist zu gross für die Anzeige.',
  iconSanitizerMissing: 'Für dieses Symbol muss das optionale Paket «dompurify» installiert sein, damit sicher gerendert werden kann.',
};

registerLyraLocaleDelta('de-CH', 'de', strings, { dir: 'ltr' });
