// Side-effect imports register every component…
import './components/sparkline/sparkline.js';
import './components/toast/toast.js';
import './components/toast/toast-item.js';
import './components/combobox/combobox.js';
import './components/combobox/option.js';
import './components/date-picker/date-picker.js';
import './components/date-picker/date-input.js';
import './components/flag/flag.js';
import './components/empty/empty.js';
import './components/skeleton/skeleton.js';
import './components/stat/stat.js';
import './components/table/table.js';
import './components/gauge/gauge.js';
import './components/export-button/export-button.js';
import './components/split/split.js';
import './components/time-range/time-range.js';
import './components/playback/playback.js';
import './components/heatmap/heatmap.js';
import './components/graph/graph.js';
import './components/tree/tree.js';
import './components/tree/tree-node.js';
import './components/chart/chart.js';
import './components/chart/bar-chart.js';
import './components/chart/line-chart.js';
import './components/chart/pie-chart.js';
import './components/chart/doughnut-chart.js';
import './components/chart/scatter-chart.js';
import './components/chart/bubble-chart.js';
import './components/chart/radar-chart.js';
import './components/chart/polar-area-chart.js';
import './components/chart/box-plot.js';
import './components/chart/histogram.js';
import './components/map/map.js';
import './components/file-input/file-input.js';
import './components/widget/widget.js';

// …and the barrel re-exports classes, helpers, and types.
export { LyraSparkline } from './components/sparkline/sparkline.js';
export { LyraToast } from './components/toast/toast.js';
export type { ToastPlacement, ToastCreateOptions } from './components/toast/toast.js';
export { LyraToastItem } from './components/toast/toast-item.js';
export type { ToastVariant, ToastSize } from './components/toast/toast-item.js';
export { toast } from './components/toast/toaster.js';
export type { ToastOptions, ToastHandle } from './components/toast/toaster.js';
export { LyraCombobox } from './components/combobox/combobox.js';
export type { OptionFilter } from './components/combobox/combobox.js';
export { LyraOption } from './components/combobox/option.js';
export { LyraDatePicker } from './components/date-picker/date-picker.js';
export type { DateRange } from './components/date-picker/date-picker.js';
export { LyraDateInput } from './components/date-picker/date-input.js';
export { LyraFlag } from './components/flag/flag.js';
export { LANGUAGE_TO_COUNTRY, languageToCountry } from './components/flag/language-map.js';
export { LyraEmpty } from './components/empty/empty.js';
export { LyraSkeleton } from './components/skeleton/skeleton.js';
export type { SkeletonVariant, SkeletonEffect } from './components/skeleton/skeleton.js';
export { LyraStat } from './components/stat/stat.js';
export type { StatVariant } from './components/stat/stat.js';
export { LyraTable } from './components/table/table.js';
export type { TableColumn } from './components/table/table.js';
export { LyraGauge } from './components/gauge/gauge.js';
export type { GaugeType } from './components/gauge/gauge.js';
export { LyraExportButton } from './components/export-button/export-button.js';
export type { ExportFormat } from './components/export-button/export-button.js';
export { escapeCsvField, buildCsv, downloadBlob } from './components/export-button/csv.js';
export type { CsvColumn } from './components/export-button/csv.js';
export { LyraSplit } from './components/split/split.js';
export { LyraTimeRange } from './components/time-range/time-range.js';
export { LyraPlayback } from './components/playback/playback.js';
export { LyraHeatmap } from './components/heatmap/heatmap.js';
export { linearAlpha, sqrtStep } from './components/heatmap/heatmap-scale.js';
export { LyraGraph } from './components/graph/graph.js';
export type { GraphNode, GraphLink } from './components/graph/graph.js';
export { LyraTree } from './components/tree/tree.js';
export type { TreeItem } from './components/tree/tree.js';
export { LyraTreeNode } from './components/tree/tree-node.js';
export { LyraChart } from './components/chart/chart.js';
export type { Series, LyraChartType } from './components/chart/chart.js';
export { LyraBarChart } from './components/chart/bar-chart.js';
export { LyraLineChart } from './components/chart/line-chart.js';
export { LyraPieChart } from './components/chart/pie-chart.js';
export { LyraDoughnutChart } from './components/chart/doughnut-chart.js';
export { LyraScatterChart } from './components/chart/scatter-chart.js';
export { LyraBubbleChart } from './components/chart/bubble-chart.js';
export { LyraRadarChart } from './components/chart/radar-chart.js';
export { LyraPolarAreaChart } from './components/chart/polar-area-chart.js';
export { LyraBoxPlot } from './components/chart/box-plot.js';
export type { BoxPlotSeries, BoxPlotPoint } from './components/chart/box-plot.js';
export { LyraHistogram } from './components/chart/histogram.js';
export { binValues } from './components/chart/histogram-bin.js';
export type { HistogramBucket } from './components/chart/histogram-bin.js';
export { LyraMap } from './components/map/map.js';
export type { LegendEntry, ChoroplethLayer } from './components/map/map.js';
export { LyraFileInput } from './components/file-input/file-input.js';
export { LyraWidget } from './components/widget/widget.js';
export type { MapMarker } from './components/map/map.js';
export type { ComboboxSource, ComboboxSourceRow } from './components/combobox/combobox.js';
export type { CalendarDay } from './components/heatmap/calendar-grid.js';

export { LyraElement } from './internal/lyra-element.js';
export { FormAssociated } from './internal/form-associated.js';
export { LYRA_PREFIX, tag, defineElement } from './internal/prefix.js';
