// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'Nakili JSON kwenye ubao wa kunakili',
  circularReference: 'Rejeleo la duara',
  copyDiff: 'Nakili tofauti',
  diffViewOldLabel: 'Asili',
  diffViewNewLabel: 'Iliyorekebishwa',
  diffViewHiddenLines: {
    one: 'mstari {count} ambao haujabadilika',
    other: 'mistari {count} ambayo haijabadilika',
  },
  diffViewTooLarge: 'Tofauti ni kubwa mno kuonyeshwa.',
  jsonArray: 'safu',
  jsonObject: 'kitu',
  jsonValue: 'thamani',
  jsonCopyLabel: 'Nakili {label}',
  jsonExpandLabel: 'Panua {label}',
  jsonCollapseLabel: 'Kunja {label}',
  jsonItemCount: {
    one: 'kipengee {count}',
    other: 'vipengee {count}',
  },
  jsonKeyCount: {
    one: 'ufunguo {count}',
    other: 'funguo {count}',
  },
  jsonViewerLimit: 'Ni nodi {count} za kwanza za JSON na viwango {depth} vya ndani pekee vinavyoonyeshwa na kutafutwa.',
  pollPause: 'Sitisha',
  pollResume: 'Endelea',
  pollInactive: 'Haifanyi kazi',
  pollRefreshing: 'Inasasisha…',
  pollPaused: 'Imesitishwa',
  pollPausedAnnounce: 'Imesitishwa.',
  pollResumedAnnounce: 'Imeendelea.',
  pollRefreshingAnnounce: 'Inasasisha sasa.',
  randomContentPause: 'Sitisha mzunguko',
  randomContentResume: 'Endelea na mzunguko',
  exportButtonLabel: 'Hamisha',
  knownDateDay: 'Siku',
  knownDateMonth: 'Mwezi',
  knownDateYear: 'Mwaka',
  exportFormatMenuLabel: 'Muundo wa {label}',
  mentionSuggestions: 'Mapendekezo',
  mentionResultCount: {
    one: 'pendekezo {count}',
    other: 'mapendekezo {count}',
  },
  mentionResultPosition: 'Pendekezo {current} kati ya {total}',
  iconLoadError: 'Imeshindwa kupakia ikoni.',
  iconTooLarge: 'Faili la ikoni ni kubwa mno kuonyeshwa.',
  iconSanitizerMissing: 'Ikoni hii inahitaji kifurushi cha hiari cha "dompurify" kisakinishwe ili kuonyeshwa kwa usalama.',
  tourSkip: 'Ruka',
  tourDone: 'Imekamilika',
  tourStepOf: 'Hatua {current} kati ya {total}',
};

registerLyraLocale('sw', strings);
