// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `overlays` slice of the nn translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/overlays/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/nn/overlays';` and reads nothing from it.
// `../nn.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Vurdering',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Lukk: {snippet}',
  closeWithTruncatedContext: 'Lukk: {snippet}…',
  toastContentIncomplete: 'Varsel med ufullstendig innhald',
  toastOverflow: 'Varsel som ikkje er viste: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tabulator',
  kbdSpaceWord: 'Mellomrom',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Rettetast',
  kbdArrowUpWord: 'Pil opp',
  kbdArrowDownWord: 'Pil ned',
  kbdArrowLeftWord: 'Pil venstre',
  kbdArrowRightWord: 'Pil høgre',
  kbdPlusWord: 'Pluss',
  kbdMinusWord: 'Minus',
  kbdCommandWord: 'Kommando',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Kontroll',
  kbdOptionWord: 'Tilval',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('nn', strings);
