// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'रेटिंग',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'बंद करीं: {snippet}',
  closeWithTruncatedContext: 'बंद करीं: {snippet}…',
  toastContentIncomplete: 'अधूरा मजमून वाला सूचना',
  toastOverflow: 'ना देखावल गइल सूचना: {count}।',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'एस्केप',
  kbdTabWord: 'टैब',
  kbdSpaceWord: 'स्पेस',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'डिलीट',
  kbdHomeWord: 'होम',
  kbdEndWord: 'एंड',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'पेज अप',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'पेज डाउन',
  kbdEnterWord: 'एंटर',
  kbdBackspaceWord: 'बैकस्पेस',
  kbdArrowUpWord: 'ऊपर एरो',
  kbdArrowDownWord: 'नीचे एरो',
  kbdArrowLeftWord: 'बायाँ एरो',
  kbdArrowRightWord: 'दायाँ एरो',
  kbdPlusWord: 'प्लस',
  kbdMinusWord: 'माइनस',
  kbdCommandWord: 'कमांड',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'कंट्रोल',
  kbdOptionWord: 'ऑप्शन',
  kbdAltWord: 'ऑल्ट',
  kbdShiftWord: 'शिफ्ट',
};

registerLyraLocale('bho', strings);
