// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON କ୍ଲିପ୍‌ବୋର୍ଡକୁ ନକଲ କରନ୍ତୁ',
  circularReference: 'ଚକ୍ରାକାର ସନ୍ଦର୍ଭ',
  copyDiff: 'ପାର୍ଥକ୍ୟ ନକଲ କରନ୍ତୁ',
  diffViewOldLabel: 'ମୂଳ',
  diffViewNewLabel: 'ପରିବର୍ତ୍ତିତ',
  diffViewHiddenLines: {
    one: '{count}ଟି ଅପରିବର୍ତ୍ତିତ ଧାଡ଼ି',
    other: '{count}ଟି ଅପରିବର୍ତ୍ତିତ ଧାଡ଼ି',
  },
  diffViewTooLarge: 'ପାର୍ଥକ୍ୟ ଦେଖାଇବା ପାଇଁ ବହୁତ ବଡ଼।',
  jsonArray: 'ଆରେ',
  jsonObject: 'ଅବଜେକ୍ଟ',
  jsonValue: 'ମୂଲ୍ୟ',
  jsonCopyLabel: '{label} ନକଲ କରନ୍ତୁ',
  jsonExpandLabel: '{label} ପ୍ରସାରଣ କରନ୍ତୁ',
  jsonCollapseLabel: '{label} ସଙ୍କୁଚିତ କରନ୍ତୁ',
  jsonItemCount: {
    one: '{count}ଟି ବସ୍ତୁ',
    other: '{count}ଟି ବସ୍ତୁ',
  },
  jsonKeyCount: {
    one: '{count}ଟି କୀ',
    other: '{count}ଟି କୀ',
  },
  jsonViewerLimit: 'କେବଳ ପ୍ରଥମ {count}ଟି JSON ନୋଡ୍ ଏବଂ {depth}ଟି ନେଷ୍ଟିଂ ସ୍ତର ଦେଖାଯାଏ ଓ ଖୋଜାଯାଏ।',
  pollPause: 'ବିରତି ଦିଅନ୍ତୁ',
  pollResume: 'ପୁନଃଆରମ୍ଭ କରନ୍ତୁ',
  pollRefresh: 'ଏବେ ସତେଜ କରନ୍ତୁ',
  pollInactive: 'ନିଷ୍କ୍ରିୟ',
  pollRefreshing: 'ସତେଜ ହେଉଛି…',
  pollPaused: 'ବିରତ ଅଛି',
  pollPausedAnnounce: 'ବିରତ ଅଛି।',
  pollResumedAnnounce: 'ପୁନଃଆରମ୍ଭ ହେଲା।',
  pollRefreshingAnnounce: 'ଏବେ ସତେଜ ହେଉଛି।',
  randomContentPause: 'ଘୂର୍ଣ୍ଣନ ବନ୍ଦ କରନ୍ତୁ',
  randomContentResume: 'ଘୂର୍ଣ୍ଣନ ପୁନଃଆରମ୍ଭ କରନ୍ତୁ',
  randomContentNext: 'ଅନ୍ୟଟି ଦେଖାନ୍ତୁ',
  exportButtonLabel: 'ରପ୍ତାନି କରନ୍ତୁ',
  knownDateDay: 'ଦିନ',
  knownDateMonth: 'ମାସ',
  knownDateYear: 'ବର୍ଷ',
  exportFormatMenuLabel: '{label} ଫର୍ମାଟ୍',
  mentionSuggestions: 'ପରାମର୍ଶ',
  mentionResultCount: {
    one: '{count}ଟି ପରାମର୍ଶ',
    other: '{count}ଟି ପରାମର୍ଶ',
  },
  mentionResultPosition: '{total} ମଧ୍ୟରୁ ପରାମର୍ଶ {current}',
  iconLoadError: 'ଆଇକନ୍ ଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ।',
  iconTooLarge: 'ଆଇକନ୍ ଫାଇଲ୍ ଦେଖାଇବା ପାଇଁ ବହୁତ ବଡ଼।',
  iconSanitizerMissing: 'ଏହି ଆଇକନ୍‌କୁ ସୁରକ୍ଷିତ ଭାବରେ ଦେଖାଇବା ପାଇଁ ବୈକଳ୍ପିକ "dompurify" ପ୍ୟାକେଜ୍ ଇନ୍‌ଷ୍ଟଲ୍ କରିବା ଆବଶ୍ୟକ।',
  tourSkip: 'ଛାଡ଼ନ୍ତୁ',
  tourDone: 'ସମାପ୍ତ',
  tourStepOf: '{total} ମଧ୍ୟରୁ ପଦକ୍ଷେପ {current}',
};

registerLyraLocale('or', strings);
