// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `forms` slice of the ja translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/forms/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/ja/forms';` and reads nothing from it.
// `../ja.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  openCalendar: 'カレンダーを開く',
  comboboxLoadError: '選択肢を読み込めませんでした。',
  comboboxSelectedOverflow: '他 {n} 件',
  checkboxRequired: '続行するにはこのチェックボックスをオンにしてください。',
  checkboxGroupRequired: '1 つ以上選択してください。',
  tokenInputRequired: '1 つ以上の値を入力してください。',
  tokenInputEditWithContext: '{label} を編集',
  iconButtonLabel: 'ボタン',
  codeEditorLabel: 'コードエディター',
  switchRequired: 'これをオンにしてください。',
  textareaLabel: 'テキスト',
  comboboxOverflow: '他 {n} 件 — 検索条件を絞り込んでください',
  comboboxRequired: '選択肢を選んでください。',
  comboboxCreate: '{value}を作成',
  comboboxLabel: 'コンボボックス',
  previousMonth: '前の月',
  nextMonth: '次の月',
  chooseDate: '日付を選択',
  dateInputPastDisabled: '過去の日付は指定できません。',
  dateInputFutureDisabled: '未来の日付は指定できません。',
  timeInputLabel: '時刻',
  timeInputHour: '時',
  timeInputMinute: '分',
  timeInputSecond: '秒',
  timeInputDayPeriod: '午前／午後',
  timeInputEmptySegment: '未入力',
  timeInputOpen: '時刻選択を開く',
  timeInputPopup: '時刻を選択',
  timeInputNow: '現在',
  timeInputInvalid: '完全な時刻を入力してください。',
  timeInputMinMessage: '{min} 以降の時刻を指定してください。',
  timeInputMaxMessage: '{max} 以前の時刻を指定してください。',
  timeInputRangeMessage: '日付をまたぐ {min} から {max} の間の時刻を指定してください。',
  timeInputStepMessage: '指定された間隔に合う時刻を入力してください。',
  inputLabel: 'テキスト',
  showPassword: 'パスワードを表示',
  hidePassword: 'パスワードを非表示',
  radioRequired: '選択肢を選んでください。',
  sliderLabel: 'スライダー',
  colorPicker: 'カラーピッカー',
  selectValueMissing: '選択肢を選んでください。',
  rangeStart: '範囲の開始',
  rangeEnd: '範囲の終了',
  phoneInputLabel: '電話',
  phoneInputIncomplete: 'この電話番号は不完全です。',
  otpInputIncomplete: '{total} 文字すべてを入力してください。',
  otpInputLabel: '確認コード',
  numberInputIncrease: '増やす',
  numberInputDecrease: '減らす',
  textareaCharacterCount: {
    other: '{count} 文字',
  },
  textareaCharactersRemaining: {
    other: '残り {count} 文字',
  },
  colorPickerSaturationBrightness: '彩度と明度',
  colorPickerSaturationBrightnessValue: '彩度 {saturation}%、明度 {brightness}%',
  colorPickerHue: '色相',
  colorPickerHueValue: '{hue} 度',
  colorPickerOpacity: '不透明度',
  colorPickerOpacityValue: '不透明度 {opacity}%',
  colorPickerValueField: 'カラー値',
  colorPickerToggleFormat: 'カラー形式を切り替え',
  colorPickerEyeDropper: '画面から色を選択',
  colorPickerSwatches: 'カラーサンプル',
  colorPickerSwatch: '{color} を選択',
  colorPickerCurrentValue: '現在の色：{color}',
  selectSelectedOverflow: '他 {n} 件',
  emojiPickerSearchLabel: '絵文字を検索',
  emojiPickerGridLabel: '絵文字',
  emojiPickerEmpty: '絵文字が見つかりません',
  emojiPickerLoadError: '絵文字を読み込めませんでした。',
  emojiPickerGroupSmileysEmotion: 'スマイリーと感情',
  emojiPickerGroupPeopleBody: '人と体',
  emojiPickerGroupComponent: 'コンポーネント',
  emojiPickerGroupAnimalsNature: '動物と自然',
  emojiPickerGroupFoodDrink: '食べ物と飲み物',
  emojiPickerGroupTravelPlaces: '旅行と場所',
  emojiPickerGroupActivities: 'アクティビティ',
  emojiPickerGroupObjects: 'もの',
  emojiPickerGroupSymbols: '記号',
  emojiPickerGroupFlags: '旗',
  emojiPickerGroupUnknown: 'グループ {group}',
  rubricSubmit: '送信',
  rubricSubmitAndNext: '送信して次へ',
  rubricSkip: 'スキップ',
  localePickerLabel: '言語',
  localePickerRequired: '言語を選択してください。',
};

registerLyraLocale('ja', strings);
