// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'カルーセル',
  carouselLabel: 'カルーセル',
  carouselSlide: 'スライド',
  carouselSlidePosition: '{total} 枚中 {index} 枚目のスライド',
  carouselSlideAnnouncement: '{position}：{content}',
  carouselSlideAnnouncementSeparator: '。',
  carouselIndicators: 'カルーセルのスライド',
  carouselGoTo: 'スライド {index} へ移動',
  scrollerLabel: 'スクロール可能なコンテンツ',
  scrollPrevious: '前へスクロール',
  scrollNext: '次へスクロール',
  closeNavigation: 'ナビゲーションを閉じる',
  openNavigation: 'ナビゲーションを開く',
  resizeNavigation: 'ナビゲーションのサイズを変更',
  appRailCollapse: 'ナビゲーションを折りたたむ',
  appRailExpand: 'ナビゲーションを展開',
  appRailItemCollapse: '{label} を折りたたむ',
  appRailItemExpand: '{label} を展開',
  resizeValuePercent: '{value} パーセント',
  commandPaletteLabel: 'コマンドパレット',
  commandPalettePlaceholder: 'コマンドを検索…',
  commandPaletteEmpty: '一致するコマンドがありません。',
  commandPaletteResults: 'コマンド',
  dockPanelCollapse: 'パネルを折りたたむ',
  dockPanelExpand: 'パネルを展開',
  dockPanelResize: 'パネルのサイズを変更',
  responsivePanel: 'パネル',
  breadcrumb: 'パンくずリスト',
  resizeDivider: 'パネル {a} とパネル {b} の間の仕切りをサイズ変更',
  widgetFullscreenPanel: '全画面パネル',
  widgetViewGroup: 'パネルの表示',
  widgetExitFullscreen: '全画面表示を終了',
  widgetExpandToFullscreen: '全画面表示にする',
  widgetCollapse: 'パネルを折りたたむ',
  widgetExpand: 'パネルを展開',
  skipToContent: '本文へスキップ',
  dashboardGridLabel: 'ダッシュボードグリッド',
  dashboardCellCollisionRejected: '{label} は他のセルと重なるため、そこには配置できません。',
  dashboardCellMoved: '{label} を {x} 列 {y} 行へ移動しました。',
  dashboardCellResized: '{label} のサイズを幅 {w}、高さ {h} に変更しました。',
  filterBarReset: 'フィルターをリセット',
  filterBarActiveFilters: '適用中のフィルター',
  drilldownDocuments: 'ドキュメント',
  drilldownRuns: 'エージェントの実行',
  drilldownEmpty: '項目が選択されていません',
  drilldownUntitledNode: '無題のステップ',
  reorderMovePending: '並べ替えを保留しています。',
  reorderMoveCancelled: '並べ替えをキャンセルしました。',
  commandPaletteResultCount: {
    other: '{count} コマンド',
  },
};

registerLyraLocale('ja', strings);
