// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `utility` slice of the ja translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/utility/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/ja/utility';` and reads nothing from it.
// `../ja.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON をクリップボードにコピー',
  circularReference: '循環参照',
  copyDiff: '差分をコピー',
  diffViewOldLabel: '変更前',
  diffViewNewLabel: '変更後',
  diffViewHiddenLines: {
    other: '変更のない {count} 行',
  },
  diffViewTooLarge: '差分が大きすぎて表示できません。',
  jsonArray: '配列',
  jsonObject: 'オブジェクト',
  jsonValue: '値',
  jsonCopyLabel: '{label} をコピー',
  jsonExpandLabel: '{label} を展開',
  jsonCollapseLabel: '{label} を折りたたむ',
  jsonItemCount: {
    other: '{count} 件',
  },
  jsonKeyCount: {
    other: 'キー {count} 個',
  },
  jsonViewerLimit: '表示と検索の対象は先頭 {count} 個の JSON ノードとネスト {depth} 段までです。',
  pollPause: '一時停止',
  pollResume: '再開',
  pollInactive: '停止中',
  pollRefreshing: '更新中…',
  pollPaused: '一時停止中',
  pollPausedAnnounce: '一時停止しました。',
  pollResumedAnnounce: '再開しました。',
  pollRefreshingAnnounce: '更新しています。',
  randomContentPause: '切り替えを一時停止',
  randomContentResume: '切り替えを再開',
  exportButtonLabel: 'エクスポート',
  knownDateDay: '日',
  knownDateMonth: '月',
  knownDateYear: '年',
  exportFormatMenuLabel: '{label} の形式',
  mentionSuggestions: '候補',
  mentionResultCount: {
    other: '{count} 件の候補',
  },
  mentionResultPosition: '{total} 件中 {current} 件目の候補',
  iconLoadError: 'アイコンを読み込めませんでした。',
  iconTooLarge: 'アイコンファイルが大きすぎて表示できません。',
  iconSanitizerMissing: 'このアイコンを安全に表示するには、オプションの "dompurify" パッケージをインストールしてください。',
  tourSkip: 'スキップ',
  tourDone: '完了',
  tourStepOf: '{total} ステップ中 {current} ステップ目',
};

registerLyraLocale('ja', strings);
