// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON क्लिपबोर्डवर कॉपी करा',
  circularReference: 'चक्रीय संदर्भ',
  copyDiff: 'फरक कॉपी करा',
  diffViewOldLabel: 'मूळ',
  diffViewNewLabel: 'बदललेले',
  diffViewHiddenLines: {
    one: '{count} अपरिवर्तित ओळ',
    other: '{count} अपरिवर्तित ओळी',
  },
  diffViewTooLarge: 'फरक दाखवण्यासाठी खूप मोठा आहे.',
  jsonArray: 'अ‍ॅरे',
  jsonObject: 'ऑब्जेक्ट',
  jsonValue: 'मूल्य',
  jsonCopyLabel: '{label} कॉपी करा',
  jsonExpandLabel: '{label} विस्तृत करा',
  jsonCollapseLabel: '{label} आकुंचित करा',
  jsonItemCount: {
    one: '{count} घटक',
    other: '{count} घटक',
  },
  jsonKeyCount: {
    one: '{count} की',
    other: '{count} की',
  },
  jsonViewerLimit: 'फक्त पहिले {count} JSON नोड आणि {depth} नेस्टिंग स्तर दाखवले व शोधले जातात.',
  pollPause: 'थांबवा',
  pollResume: 'पुन्हा सुरू करा',
  pollRefresh: 'आता रिफ्रेश करा',
  pollInactive: 'निष्क्रिय',
  pollRefreshing: 'रिफ्रेश होत आहे…',
  pollPaused: 'थांबवले आहे',
  pollPausedAnnounce: 'थांबवले आहे.',
  pollResumedAnnounce: 'पुन्हा सुरू केले.',
  pollRefreshingAnnounce: 'आता रिफ्रेश होत आहे.',
  randomContentPause: 'फिरवणे थांबवा',
  randomContentResume: 'फिरवणे पुन्हा सुरू करा',
  randomContentNext: 'दुसरे दाखवा',
  exportButtonLabel: 'निर्यात करा',
  knownDateDay: 'दिवस',
  knownDateMonth: 'महिना',
  knownDateYear: 'वर्ष',
  exportFormatMenuLabel: '{label} स्वरूप',
  mentionSuggestions: 'सूचना',
  mentionResultCount: {
    one: '{count} सूचना',
    other: '{count} सूचना',
  },
  mentionResultPosition: 'एकूण {total} पैकी {current} वी सूचना',
  iconLoadError: 'चिन्ह लोड करता आले नाही.',
  iconTooLarge: 'चिन्हाची फाइल दाखवण्यासाठी खूप मोठी आहे.',
  iconSanitizerMissing: 'हे चिन्ह सुरक्षितपणे दाखवण्यासाठी पर्यायी "dompurify" पॅकेज स्थापित करणे आवश्यक आहे.',
  tourSkip: 'वगळा',
  tourDone: 'पूर्ण झाले',
  tourStepOf: 'एकूण {total} पैकी {current} वी पायरी',
  mentionMoreResults: {
    one: '{count} अधिक सूचना',
    other: '{count} अधिक सूचना',
  },
};

registerLyraLocale('mr', strings);
