// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'ਰੇਟਿੰਗ',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'ਬੰਦ ਕਰੋ: {snippet}',
  closeWithTruncatedContext: 'ਬੰਦ ਕਰੋ: {snippet}…',
  toastContentIncomplete: 'ਅਧੂਰੀ ਸਮੱਗਰੀ ਵਾਲੀ ਸੂਚਨਾ',
  toastOverflow: 'ਨਾ ਦਿਖਾਈਆਂ ਸੂਚਨਾਵਾਂ: {count}।',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape ਕੁੰਜੀ',
  kbdTabWord: 'Tab ਕੁੰਜੀ',
  kbdSpaceWord: 'Space ਕੁੰਜੀ',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete ਕੁੰਜੀ',
  kbdHomeWord: 'Home ਕੁੰਜੀ',
  kbdEndWord: 'End ਕੁੰਜੀ',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up ਕੁੰਜੀ',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down ਕੁੰਜੀ',
  kbdEnterWord: 'Enter ਕੁੰਜੀ',
  kbdBackspaceWord: 'ਬੈਕਸਪੇਸ ਕੁੰਜੀ',
  kbdArrowUpWord: 'ਉੱਪਰ ਤੀਰ ਕੁੰਜੀ',
  kbdArrowDownWord: 'ਹੇਠਾਂ ਤੀਰ ਕੁੰਜੀ',
  kbdArrowLeftWord: 'ਖੱਬਾ ਤੀਰ ਕੁੰਜੀ',
  kbdArrowRightWord: 'ਸੱਜਾ ਤੀਰ ਕੁੰਜੀ',
  kbdPlusWord: 'ਪਲੱਸ ਕੁੰਜੀ',
  kbdMinusWord: 'ਮਾਈਨਸ ਕੁੰਜੀ',
  kbdCommandWord: 'Command ਕੁੰਜੀ',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control ਕੁੰਜੀ',
  kbdOptionWord: 'Option ਕੁੰਜੀ',
  kbdAltWord: 'Alt ਕੁੰਜੀ',
  kbdShiftWord: 'Shift ਕੁੰਜੀ',
};

registerLyraLocale('pa', strings);
