// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'băng chuyền',
  carouselLabel: 'Băng chuyền',
  carouselSlide: 'trang chiếu',
  carouselSlidePosition: 'Trang chiếu {index} trên {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Các trang chiếu',
  carouselGoTo: 'Đi đến trang chiếu {index}',
  scrollerLabel: 'Nội dung có thể cuộn',
  scrollPrevious: 'Cuộn về trước',
  scrollNext: 'Cuộn về sau',
  closeNavigation: 'Đóng điều hướng',
  openNavigation: 'Mở điều hướng',
  resizeNavigation: 'Đổi kích thước điều hướng',
  appRailCollapse: 'Thu gọn điều hướng',
  appRailExpand: 'Mở rộng điều hướng',
  appRailItemCollapse: 'Thu gọn {label}',
  appRailItemExpand: 'Mở rộng {label}',
  resizeValuePercent: '{value} phần trăm',
  commandPaletteLabel: 'Bảng lệnh',
  commandPalettePlaceholder: 'Tìm lệnh…',
  commandPaletteEmpty: 'Không có lệnh phù hợp.',
  commandPaletteResults: 'Lệnh',
  dockPanelCollapse: 'Thu gọn bảng',
  dockPanelExpand: 'Mở rộng bảng',
  dockPanelResize: 'Đổi kích thước bảng',
  responsivePanel: 'Bảng',
  breadcrumb: 'Điều hướng đường dẫn',
  resizeDivider: 'Đổi kích thước vạch ngăn giữa bảng {a} và bảng {b}',
  widgetFullscreenPanel: 'Bảng toàn màn hình',
  widgetViewGroup: 'Chế độ xem bảng',
  widgetExitFullscreen: 'Thoát chế độ toàn màn hình',
  widgetExpandToFullscreen: 'Mở rộng toàn màn hình',
  widgetCollapse: 'Thu gọn bảng',
  widgetExpand: 'Mở rộng bảng',
  skipToContent: 'Chuyển đến nội dung',
  dashboardGridLabel: 'Lưới bảng điều khiển',
  dashboardCellCollisionRejected: 'Không thể đặt {label} ở đó vì vị trí bị chồng lên một ô khác.',
  dashboardCellMoved: 'Đã chuyển {label} đến cột {x}, hàng {y}.',
  dashboardCellResized: 'Đã đổi kích thước {label} thành rộng {w}, cao {h}.',
  filterBarReset: 'Đặt lại bộ lọc',
  filterBarActiveFilters: 'Bộ lọc đang dùng',
  drilldownDocuments: 'Tài liệu',
  drilldownRuns: 'Lượt chạy của tác tử',
  drilldownEmpty: 'Chưa chọn mục nào',
  drilldownUntitledNode: 'Bước chưa có tên',
  reorderMovePending: 'Đang chờ sắp xếp lại.',
  reorderMoveCancelled: 'Đã hủy sắp xếp lại.',
  commandPaletteResultCount: {
    other: '{count} lệnh',
  },
};

registerLyraLocale('vi', strings);
