// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `layout` slice of the zh-TW translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/layout/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/zh-TW/layout';` and reads nothing from it.
// `../zh-TW.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: '輪播',
  carouselLabel: '輪播',
  carouselSlide: '幻燈片',
  carouselSlidePosition: '第{index}張幻燈片，共{total}張',
  carouselSlideAnnouncement: '{position}：{content}',
  carouselSlideAnnouncementSeparator: '。',
  carouselIndicators: '輪播幻燈片',
  carouselGoTo: '轉到第{index}張幻燈片',
  scrollerLabel: '可滾動內容',
  scrollPrevious: '向前滾動',
  scrollNext: '向後滾動',
  closeNavigation: '關閉導航',
  openNavigation: '開啟導航',
  resizeNavigation: '調整導航寬度',
  appRailCollapse: '收起導航',
  appRailExpand: '展開導航',
  appRailItemCollapse: '收起{label}',
  appRailItemExpand: '展開{label}',
  resizeValuePercent: '百分之{value}',
  commandPaletteLabel: '命令面板',
  commandPalettePlaceholder: '搜尋命令…',
  commandPaletteEmpty: '沒有匹配的命令。',
  commandPaletteResults: '命令',
  dockPanelCollapse: '收起面板',
  dockPanelExpand: '展開面板',
  dockPanelResize: '調整面板大小',
  responsivePanel: '面板',
  breadcrumb: '麵包屑導航',
  resizeDivider: '調整面板{a}與面板{b}之間的分隔條',
  widgetFullscreenPanel: '全屏面板',
  widgetViewGroup: '面板檢視',
  widgetExitFullscreen: '退出全屏',
  widgetExpandToFullscreen: '展開為全屏',
  widgetCollapse: '收起面板',
  widgetExpand: '展開面板',
  skipToContent: '跳到主要內容',
  dashboardGridLabel: '儀表板網格',
  dashboardCellCollisionRejected: '{label}無法放置在此處，因為它與另一個單元格重疊。',
  dashboardCellMoved: '{label}已移動到第{x}列、第{y}行。',
  dashboardCellResized: '{label}的大小已調整為寬{w}、高{h}。',
  filterBarReset: '重置篩選條件',
  filterBarActiveFilters: '生效的篩選條件',
  drilldownDocuments: '文件',
  drilldownRuns: '智慧體執行',
  drilldownEmpty: '未選擇任何項',
  drilldownUntitledNode: '未命名步驟',
  reorderMovePending: '重新排序待處理。',
  reorderMoveCancelled: '重新排序已取消。',
};

registerLyraLocale('zh-TW', strings);
