// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: '評分',
  calloutAnnouncementWithContext: '{context}：{content}',
  closeWithContext: '關閉：{snippet}',
  closeWithTruncatedContext: '關閉：{snippet}…',
  toastContentIncomplete: '內容不完整的通知',
  toastOverflow: '未顯示的通知：{count}條。',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Esc',
  kbdTabWord: 'Tab',
  kbdSpaceWord: '空格',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: '刪除',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: '向上翻頁',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: '向下翻頁',
  kbdEnterWord: '回車',
  kbdBackspaceWord: '退格',
  kbdArrowUpWord: '向上箭頭',
  kbdArrowDownWord: '向下箭頭',
  kbdArrowLeftWord: '向左箭頭',
  kbdArrowRightWord: '向右箭頭',
  kbdPlusWord: '加號',
  kbdMinusWord: '減號',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('zh-TW', strings);
