// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `utility` slice of the zh-TW translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/utility/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/zh-TW/utility';` and reads nothing from it.
// `../zh-TW.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: '將 JSON 複製到剪貼簿',
  circularReference: '迴圈引用',
  copyDiff: '複製差異',
  diffViewOldLabel: '原始',
  diffViewNewLabel: '修改後',
  diffViewHiddenLines: {
    other: '{count}行未更改',
  },
  diffViewTooLarge: '差異過大，無法顯示。',
  jsonArray: '陣列',
  jsonObject: '物件',
  jsonValue: '值',
  jsonCopyLabel: '複製{label}',
  jsonExpandLabel: '展開{label}',
  jsonCollapseLabel: '收起{label}',
  jsonItemCount: {
    other: '{count}項',
  },
  jsonKeyCount: {
    other: '{count}個鍵',
  },
  jsonViewerLimit: '僅顯示和搜尋前{count}個 JSON 節點及{depth}層巢狀。',
  pollPause: '暫停',
  pollResume: '繼續',
  pollInactive: '未啟用',
  pollRefreshing: '重新整理中…',
  pollPaused: '已暫停',
  pollPausedAnnounce: '已暫停。',
  pollResumedAnnounce: '已繼續。',
  pollRefreshingAnnounce: '正在重新整理。',
  randomContentPause: '暫停輪換',
  randomContentResume: '繼續輪換',
  exportButtonLabel: '匯出',
  knownDateDay: '日',
  knownDateMonth: '月',
  knownDateYear: '年',
  exportFormatMenuLabel: '{label}格式',
  mentionSuggestions: '建議',
  mentionResultCount: {
    other: '{count}項建議',
  },
  mentionResultPosition: '第{current}項建議，共{total}項',
  iconLoadError: '圖示載入失敗。',
  iconTooLarge: '圖示檔案過大，無法顯示。',
  iconSanitizerMissing: '此圖示需要安裝可選的 "dompurify" 套件才能安全渲染。',
  tourSkip: '跳過',
  tourDone: '完成',
  tourStepOf: '第{current}步，共{total}步',
};

registerLyraLocale('zh-TW', strings);
