export * from './drilldown-panel.class.js';
import { LyraDrilldownPanel } from './drilldown-panel.class.js';
import { defineElement } from '../../internal/prefix.js';
import '../breadcrumb/breadcrumb.js';
import '../breadcrumb/breadcrumb-item.js';
import '../tabs/tabs.js';
import '../document-preview/document-preview.js';
import '../entity-card/entity-card.js';
import '../source-card/source-card.js';
import '../empty/empty.js';
defineElement('drilldown-panel', LyraDrilldownPanel);
