// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'ภาพสไลด์',
  carouselLabel: 'ภาพสไลด์',
  carouselSlide: 'สไลด์',
  carouselSlidePosition: 'สไลด์ {index} จาก {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'สไลด์ในภาพสไลด์',
  carouselGoTo: 'ไปยังสไลด์ {index}',
  scrollerLabel: 'เนื้อหาที่เลื่อนได้',
  scrollPrevious: 'เลื่อนย้อนกลับ',
  scrollNext: 'เลื่อนถัดไป',
  closeNavigation: 'ปิดการนำทาง',
  openNavigation: 'เปิดการนำทาง',
  resizeNavigation: 'ปรับขนาดการนำทาง',
  appRailCollapse: 'ยุบการนำทาง',
  appRailExpand: 'ขยายการนำทาง',
  appRailPin: 'ปักหมุดการนำทาง',
  appRailUnpin: 'เลิกปักหมุดการนำทาง',
  appRailItemCollapse: 'ยุบ {label}',
  appRailItemExpand: 'ขยาย {label}',
  resizeValuePercent: '{value} เปอร์เซ็นต์',
  commandPaletteLabel: 'แผงคำสั่ง',
  commandPalettePlaceholder: 'ค้นหาคำสั่ง…',
  commandPaletteEmpty: 'ไม่พบคำสั่งที่ตรงกัน',
  commandPaletteResults: 'คำสั่ง',
  dockPanelCollapse: 'ยุบแผง',
  dockPanelExpand: 'ขยายแผง',
  dockPanelResize: 'ปรับขนาดแผง',
  responsivePanel: 'แผง',
  breadcrumb: 'เส้นทางนำทาง',
  resizeDivider: 'ปรับขนาดตัวแบ่งระหว่างแผง {a} และแผง {b}',
  widgetFullscreenPanel: 'แผงเต็มหน้าจอ',
  widgetViewGroup: 'มุมมองแผง',
  widgetExitFullscreen: 'ออกจากโหมดเต็มหน้าจอ',
  widgetExpandToFullscreen: 'ขยายเป็นเต็มหน้าจอ',
  widgetCollapse: 'ยุบแผง',
  widgetExpand: 'ขยายแผง',
  skipToContent: 'ข้ามไปยังเนื้อหา',
  dashboardGridLabel: 'ตารางแดชบอร์ด',
  dashboardCellCollisionRejected: 'วาง {label} ตรงนั้นไม่ได้ เพราะทับกับช่องอื่น',
  dashboardCellMoved: 'ย้าย {label} ไปยังคอลัมน์ {x} แถว {y} แล้ว',
  dashboardCellResized: 'ปรับขนาด {label} เป็นกว้าง {w} สูง {h} แล้ว',
  filterBarReset: 'รีเซ็ตตัวกรอง',
  filterBarActiveFilters: 'ตัวกรองที่ใช้งาน',
  drilldownDocuments: 'เอกสาร',
  drilldownRuns: 'การทำงานของเอเจนต์',
  drilldownEmpty: 'ไม่ได้เลือกรายการ',
  drilldownUntitledNode: 'ขั้นตอนไม่มีชื่อ',
  reorderMovePending: 'กำลังรอจัดลำดับใหม่',
  reorderMoveCancelled: 'ยกเลิกการจัดลำดับใหม่แล้ว',
  commandPaletteResultCount: {
    other: 'คำสั่ง {count}',
  },
};

registerLyraLocale('th', strings);
