// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Arvio',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Sulje: {snippet}',
  closeWithTruncatedContext: 'Sulje: {snippet}…',
  toastContentIncomplete: 'Ilmoitus, jonka sisältö on puutteellinen',
  toastOverflow: 'Näyttämättömiä ilmoituksia: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Sarkain',
  kbdSpaceWord: 'Välilyönti',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Askelpalautin',
  kbdArrowUpWord: 'Nuoli ylös',
  kbdArrowDownWord: 'Nuoli alas',
  kbdArrowLeftWord: 'Nuoli vasemmalle',
  kbdArrowRightWord: 'Nuoli oikealle',
  kbdPlusWord: 'Plus',
  kbdMinusWord: 'Miinus',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('fi', strings);
