// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `layout` slice of the nb translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/layout/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/nb/layout';` and reads nothing from it.
// `../nb.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'karusell',
  carouselLabel: 'Karusell',
  carouselSlide: 'lysbilde',
  carouselSlidePosition: 'Lysbilde {index} av {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Karusell-lysbilder',
  carouselGoTo: 'Gå til lysbilde {index}',
  scrollerLabel: 'Rullbart innhold',
  scrollPrevious: 'Rull bakover',
  scrollNext: 'Rull fremover',
  closeNavigation: 'Lukk navigasjon',
  openNavigation: 'Åpne navigasjon',
  resizeNavigation: 'Endre størrelse på navigasjon',
  appRailCollapse: 'Skjul navigasjon',
  appRailExpand: 'Utvid navigasjon',
  appRailItemCollapse: 'Skjul {label}',
  appRailItemExpand: 'Utvid {label}',
  resizeValuePercent: '{value} prosent',
  commandPaletteLabel: 'Kommandopalett',
  commandPalettePlaceholder: 'Søk etter kommandoer …',
  commandPaletteEmpty: 'Ingen samsvarende kommandoer.',
  commandPaletteResults: 'Kommandoer',
  dockPanelCollapse: 'Skjul panel',
  dockPanelExpand: 'Utvid panel',
  dockPanelResize: 'Endre størrelse på panel',
  responsivePanel: 'Panel',
  breadcrumb: 'Brødsmulesti',
  resizeDivider: 'Endre størrelse på skillelinjen mellom panel {a} og panel {b}',
  widgetFullscreenPanel: 'Fullskjermpanel',
  widgetViewGroup: 'Panelvisning',
  widgetExitFullscreen: 'Avslutt fullskjerm',
  widgetExpandToFullscreen: 'Utvid til fullskjerm',
  widgetCollapse: 'Skjul panel',
  widgetExpand: 'Utvid panel',
  skipToContent: 'Hopp til innhold',
  dashboardGridLabel: 'Rutenett for instrumentbord',
  dashboardCellCollisionRejected: '{label} kan ikke plasseres der fordi den overlapper en annen celle.',
  dashboardCellMoved: '{label} ble flyttet til kolonne {x}, rad {y}.',
  dashboardCellResized: '{label} ble endret til bredde {w}, høyde {h}.',
  filterBarReset: 'Tilbakestill filtre',
  filterBarActiveFilters: 'Aktive filtre',
  drilldownDocuments: 'Dokumenter',
  drilldownRuns: 'Agentkjøringer',
  drilldownEmpty: 'Ingen element valgt',
  drilldownUntitledNode: 'Trinn uten tittel',
  reorderMovePending: 'Omorganisering venter.',
  reorderMoveCancelled: 'Omorganisering avbrutt.',
};

registerLyraLocale('nb', strings);
