// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `layout` slice of the tr translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/layout/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/tr/layout';` and reads nothing from it.
// `../tr.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'karusel',
  carouselLabel: 'Karusel',
  carouselSlide: 'slayt',
  carouselSlidePosition: '{total} slayttan {index}. slayt',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Karusel slaytları',
  carouselGoTo: '{index}. slayta git',
  scrollerLabel: 'Kaydırılabilir içerik',
  scrollPrevious: 'Geri kaydır',
  scrollNext: 'İleri kaydır',
  closeNavigation: 'Gezinmeyi kapat',
  openNavigation: 'Gezinmeyi aç',
  resizeNavigation: 'Gezinme alanını yeniden boyutlandır',
  appRailCollapse: 'Gezinme menüsünü daralt',
  appRailExpand: 'Gezinme menüsünü genişlet',
  appRailItemCollapse: '{label} öğesini daralt',
  appRailItemExpand: '{label} öğesini genişlet',
  resizeValuePercent: 'yüzde {value}',
  commandPaletteLabel: 'Komut paleti',
  commandPalettePlaceholder: 'Komutlarda ara…',
  commandPaletteEmpty: 'Eşleşen komut yok.',
  commandPaletteResults: 'Komutlar',
  dockPanelCollapse: 'Paneli daralt',
  dockPanelExpand: 'Paneli genişlet',
  dockPanelResize: 'Paneli yeniden boyutlandır',
  responsivePanel: 'Panel',
  breadcrumb: 'İçerik yolu',
  resizeDivider: '{a} ve {b} panelleri arasındaki ayırıcıyı yeniden boyutlandır',
  widgetFullscreenPanel: 'Tam ekran paneli',
  widgetViewGroup: 'Panel görünümü',
  widgetExitFullscreen: 'Tam ekrandan çık',
  widgetExpandToFullscreen: 'Tam ekrana genişlet',
  widgetCollapse: 'Paneli daralt',
  widgetExpand: 'Paneli genişlet',
  skipToContent: 'İçeriğe atla',
  dashboardGridLabel: 'Kontrol paneli ızgarası',
  dashboardCellCollisionRejected: '{label}, başka bir hücreyle çakıştığı için buraya yerleştirilemez.',
  dashboardCellMoved: '{label}, {x}. sütuna ve {y}. satıra taşındı.',
  dashboardCellResized: '{label}, {w} genişliğe ve {h} yüksekliğe yeniden boyutlandırıldı.',
  filterBarReset: 'Filtreleri sıfırla',
  filterBarActiveFilters: 'Etkin filtreler',
  drilldownDocuments: 'Belgeler',
  drilldownRuns: 'Aracı çalıştırmaları',
  drilldownEmpty: 'Hiçbir öğe seçilmedi',
  drilldownUntitledNode: 'Adsız adım',
  reorderMovePending: 'Yeniden sıralama bekleniyor.',
  reorderMoveCancelled: 'Yeniden sıralama iptal edildi.',
};

registerLyraLocale('tr', strings);
