// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `overlays` slice of the tr translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/overlays/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/tr/overlays';` and reads nothing from it.
// `../tr.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Puan',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Kapat: {snippet}',
  closeWithTruncatedContext: 'Kapat: {snippet}…',
  toastContentIncomplete: 'İçeriği eksik bildirim',
  toastOverflow: 'Gösterilmeyen bildirim sayısı: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Boşluk',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Sil',
  kbdHomeWord: 'Başlangıç',
  kbdEndWord: 'Son',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Sayfa Yukarı',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Sayfa Aşağı',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Geri sil',
  kbdArrowUpWord: 'Yukarı ok',
  kbdArrowDownWord: 'Aşağı ok',
  kbdArrowLeftWord: 'Sol ok',
  kbdArrowRightWord: 'Sağ ok',
  kbdPlusWord: 'Artı',
  kbdMinusWord: 'Eksi',
  kbdCommandWord: 'Komut',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Denetim',
  kbdOptionWord: 'Seçenek',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('tr', strings);
