// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'Salin JSON menyang clipboard',
  circularReference: 'Referensi muter',
  copyDiff: 'Salin bedane',
  diffViewOldLabel: 'Asli',
  diffViewNewLabel: 'Diowahi',
  diffViewHiddenLines: {
    other: '{count} saran',
  },
  diffViewTooLarge: 'Bedane kegedhen kanggo ditampilake.',
  jsonArray: 'larik',
  jsonObject: 'objek',
  jsonValue: 'nilai',
  jsonCopyLabel: 'Salin {label}',
  jsonExpandLabel: 'Bukak {label}',
  jsonCollapseLabel: 'Ciutake {label}',
  jsonItemCount: {
    other: '{count} barang',
  },
  jsonKeyCount: {
    other: '{count} kunci',
  },
  jsonViewerLimit: 'Mung simpul JSON {count} kapisan lan tingkat tumpukan {depth} sing ditampilake lan ditelusuri.',
  pollPause: 'Ngaso',
  pollResume: 'Terusake',
  pollRefresh: 'Muat maneh saiki',
  pollInactive: 'Ora aktif',
  pollRefreshing: 'Lagi dimuat maneh…',
  pollPaused: 'Diendhegake',
  pollPausedAnnounce: 'Diendhegake.',
  pollResumedAnnounce: 'Wis diterusake.',
  pollRefreshingAnnounce: 'Saiki lagi dimuat maneh.',
  randomContentPause: 'Ngaso rotasi',
  randomContentResume: 'Terusake rotasi',
  randomContentNext: 'Tampilake liyane',
  exportButtonLabel: 'Ekspor',
  knownDateDay: 'Dina',
  knownDateMonth: 'Sasi',
  knownDateYear: 'Taun',
  exportFormatMenuLabel: 'Format {label}',
  mentionSuggestions: 'Saran',
  mentionResultCount: {
    other: '{count} saran',
  },
  mentionResultPosition: 'Saran {current} saka {total}',
  iconLoadError: 'Ikon ora bisa dimuat.',
  iconTooLarge: 'Berkas ikon kegedhen kanggo ditampilake.',
  iconSanitizerMissing: 'Ikon iki mbutuhake paket opsional "dompurify" supaya aman ditampilake.',
  tourSkip: 'Lumpati',
  tourDone: 'Rampung',
  tourStepOf: 'Langkah {current} saka {total}',
};

registerLyraLocale('jv', strings);
