// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'گردونه',
  carouselLabel: 'گردونه',
  carouselSlide: 'اسلاید',
  carouselSlidePosition: 'اسلاید {index} از {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'اسلایدهای گردونه',
  carouselGoTo: 'رفتن به اسلاید {index}',
  scrollerLabel: 'محتوای پیمایش‌پذیر',
  scrollPrevious: 'پیمایش به عقب',
  scrollNext: 'پیمایش به جلو',
  closeNavigation: 'بستن راهبری',
  openNavigation: 'بازکردن راهبری',
  resizeNavigation: 'تغییر اندازهٔ راهبری',
  appRailCollapse: 'جمع‌کردن راهبری',
  appRailExpand: 'بازکردن راهبری',
  appRailItemCollapse: 'جمع‌کردن {label}',
  appRailItemExpand: 'بازکردن {label}',
  resizeValuePercent: '{value} درصد',
  commandPaletteLabel: 'صفحه‌کلید فرمان',
  commandPalettePlaceholder: 'فرمان‌ها را جست‌وجو کنید…',
  commandPaletteEmpty: 'فرمان همسان پیدا نشد.',
  commandPaletteResults: 'فرمان‌ها',
  dockPanelCollapse: 'جمع‌کردن پنل',
  dockPanelExpand: 'بازکردن پنل',
  dockPanelResize: 'تغییر اندازهٔ پنل',
  responsivePanel: 'پنل',
  breadcrumb: 'مسیر صفحه',
  resizeDivider: 'تغییر اندازهٔ جداکنندهٔ پنل {a} و پنل {b}',
  widgetFullscreenPanel: 'پنل تمام‌صفحه',
  widgetViewGroup: 'نمای پنل',
  widgetExitFullscreen: 'خروج از تمام‌صفحه',
  widgetExpandToFullscreen: 'بازکردن در تمام‌صفحه',
  widgetCollapse: 'جمع‌کردن پنل',
  widgetExpand: 'بازکردن پنل',
  skipToContent: 'رفتن به محتوا',
  dashboardGridLabel: 'شبکهٔ داشبورد',
  dashboardCellCollisionRejected: '{label} در آنجا جا داده نمی‌شود، چون با خانهٔ دیگری هم‌پوشانی دارد.',
  dashboardCellMoved: '{label} به ستون {x}، ردیف {y} انتقال یافت.',
  dashboardCellResized: 'اندازهٔ {label} به عرض {w} و ارتفاع {h} تغییر کرد.',
  filterBarReset: 'بازنشانی پالایه‌ها',
  filterBarActiveFilters: 'پالایه‌های فعال',
  drilldownDocuments: 'سندها',
  drilldownRuns: 'اجراهای ایجنت',
  drilldownEmpty: 'هیچ موردی انتخاب نشده است',
  drilldownUntitledNode: 'مرحلهٔ بدون عنوان',
  reorderMovePending: 'ترتیب‌دهی دوباره در انتظار است.',
  reorderMoveCancelled: 'ترتیب‌دهی دوباره لغو شد.',
  commandPaletteResultCount: {
    one: 'دستور {count}',
    other: '{count} دستورات',
  },
};

registerLyraLocale('fa-AF', strings, { dir: 'rtl', name: 'دری' });
