// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `layout` slice of the ru translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/layout/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/ru/layout';` and reads nothing from it.
// `../ru.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'карусель',
  carouselLabel: 'Карусель',
  carouselSlide: 'слайд',
  carouselSlidePosition: 'Слайд {index} из {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Слайды карусели',
  carouselGoTo: 'Перейти к слайду {index}',
  scrollerLabel: 'Прокручиваемое содержимое',
  scrollPrevious: 'Прокрутить назад',
  scrollNext: 'Прокрутить вперёд',
  closeNavigation: 'Закрыть навигацию',
  openNavigation: 'Открыть навигацию',
  resizeNavigation: 'Изменить размер навигации',
  appRailCollapse: 'Свернуть навигацию',
  appRailExpand: 'Развернуть навигацию',
  resizeValuePercent: '{value} процентов',
  commandPaletteLabel: 'Палитра команд',
  commandPalettePlaceholder: 'Поиск команд…',
  commandPaletteEmpty: 'Подходящих команд нет.',
  commandPaletteResults: 'Команды',
  dockPanelCollapse: 'Свернуть панель',
  dockPanelExpand: 'Развернуть панель',
  dockPanelResize: 'Изменить размер панели',
  responsivePanel: 'Панель',
  breadcrumb: 'Навигационная цепочка',
  resizeDivider: 'Изменить размер: разделитель между панелями {a} и {b}',
  widgetFullscreenPanel: 'Полноэкранная панель',
  widgetViewGroup: 'Режим панели',
  widgetExitFullscreen: 'Выйти из полноэкранного режима',
  widgetExpandToFullscreen: 'Развернуть на весь экран',
  widgetCollapse: 'Свернуть панель',
  widgetExpand: 'Развернуть панель',
  skipToContent: 'Перейти к содержимому',
  dashboardGridLabel: 'Сетка панели мониторинга',
  dashboardCellCollisionRejected: '{label} нельзя разместить здесь: перекрытие с другой ячейкой.',
  dashboardCellMoved: '{label} перемещён в столбец {x}, строку {y}.',
  dashboardCellResized: 'Размер {label} изменён: ширина {w}, высота {h}.',
  filterBarReset: 'Сбросить фильтры',
  filterBarActiveFilters: 'Активные фильтры',
  drilldownDocuments: 'Документы',
  drilldownRuns: 'Запуски агентов',
  drilldownEmpty: 'Элемент не выбран',
  drilldownUntitledNode: 'Шаг без названия',
  reorderMovePending: 'Переупорядочивание ожидает завершения.',
  reorderMoveCancelled: 'Переупорядочивание отменено.',
};

registerLyraLocale('ru', strings);
