// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Оценка',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Закрыть: {snippet}',
  closeWithTruncatedContext: 'Закрыть: {snippet}…',
  toastContentIncomplete: 'Уведомление с неполным содержимым',
  toastOverflow: 'Непоказанные уведомления: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Пробел',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Ввод',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'Стрелка вверх',
  kbdArrowDownWord: 'Стрелка вниз',
  kbdArrowLeftWord: 'Стрелка влево',
  kbdArrowRightWord: 'Стрелка вправо',
  kbdPlusWord: 'Плюс',
  kbdMinusWord: 'Минус',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('ru', strings);
