// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Peunteun',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Tutup: {snippet}',
  closeWithTruncatedContext: 'Tutup: {snippet}…',
  toastContentIncomplete: 'Bewara eusina teu lengkep',
  toastOverflow: 'Bewara teu dipintonkeun: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Spasi',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Hapus',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'Panah luhur',
  kbdArrowDownWord: 'Panah handap',
  kbdArrowLeftWord: 'Panah kénca',
  kbdArrowRightWord: 'Panah katuhu',
  kbdPlusWord: 'Tambah',
  kbdMinusWord: 'Kurang',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('su', strings);
