// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `layout` slice of the es translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/layout/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/es/layout';` and reads nothing from it.
// `../es.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'carrusel',
  carouselLabel: 'Carrusel',
  carouselSlide: 'diapositiva',
  carouselSlidePosition: 'Diapositiva {index} de {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Diapositivas del carrusel',
  carouselGoTo: 'Ir a la diapositiva {index}',
  scrollerLabel: 'Contenido desplazable',
  scrollPrevious: 'Desplazar hacia atrás',
  scrollNext: 'Desplazar hacia delante',
  closeNavigation: 'Cerrar la navegación',
  openNavigation: 'Abrir la navegación',
  resizeNavigation: 'Redimensionar la navegación',
  appRailCollapse: 'Contraer la navegación',
  appRailExpand: 'Expandir la navegación',
  resizeValuePercent: '{value} por ciento',
  commandPaletteLabel: 'Paleta de comandos',
  commandPalettePlaceholder: 'Buscar comandos…',
  commandPaletteEmpty: 'No hay comandos que coincidan.',
  commandPaletteResults: 'Comandos',
  dockPanelCollapse: 'Contraer el panel',
  dockPanelExpand: 'Expandir el panel',
  dockPanelResize: 'Redimensionar el panel',
  responsivePanel: 'Panel',
  breadcrumb: 'Ruta de navegación',
  resizeDivider: 'Redimensionar el divisor entre el panel {a} y el panel {b}',
  widgetFullscreenPanel: 'Panel en pantalla completa',
  widgetViewGroup: 'Vista del panel',
  widgetExitFullscreen: 'Salir de la pantalla completa',
  widgetExpandToFullscreen: 'Expandir a pantalla completa',
  widgetCollapse: 'Contraer el panel',
  widgetExpand: 'Expandir el panel',
  skipToContent: 'Ir al contenido',
  dashboardGridLabel: 'Cuadrícula del panel',
  dashboardCellCollisionRejected: '{label} no se puede colocar ahí porque se solapa con otra celda.',
  dashboardCellMoved: '{label} se ha movido a la columna {x}, fila {y}.',
  dashboardCellResized: '{label} se ha redimensionado a {w} de ancho y {h} de alto.',
  filterBarReset: 'Restablecer los filtros',
  filterBarActiveFilters: 'Filtros activos',
  drilldownDocuments: 'Documentos',
  drilldownRuns: 'Ejecuciones del agente',
  drilldownEmpty: 'No hay ningún elemento seleccionado',
  drilldownUntitledNode: 'Paso sin título',
  reorderMovePending: 'Reordenación pendiente.',
  reorderMoveCancelled: 'Reordenación cancelada.',
};

registerLyraLocale('es', strings);
