// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `overlays` slice of the de translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/overlays/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/de/overlays';` and reads nothing from it.
// `../de.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Bewertung',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Schließen: {snippet}',
  closeWithTruncatedContext: 'Schließen: {snippet}…',
  toastContentIncomplete: 'Benachrichtigung mit unvollständigem Inhalt',
  toastOverflow: 'Nicht angezeigte Benachrichtigungen: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tabulator',
  kbdSpaceWord: 'Leertaste',
  kbdDeleteVisual: 'Entf',
  kbdDeleteWord: 'Entfernen',
  kbdHomeWord: 'Pos 1',
  kbdEndWord: 'Ende',
  kbdPageUpVisual: 'Bild ↑',
  kbdPageUpWord: 'Bild auf',
  kbdPageDownVisual: 'Bild ↓',
  kbdPageDownWord: 'Bild ab',
  kbdEnterWord: 'Eingabe',
  kbdBackspaceWord: 'Rücktaste',
  kbdArrowUpWord: 'Pfeil nach oben',
  kbdArrowDownWord: 'Pfeil nach unten',
  kbdArrowLeftWord: 'Pfeil nach links',
  kbdArrowRightWord: 'Pfeil nach rechts',
  kbdPlusWord: 'Plus',
  kbdMinusWord: 'Minus',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Strg',
  kbdControlWord: 'Steuerung',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Umschalt',
};

registerLyraLocale('de', strings);
