// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Bewertung',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Schließen: {snippet}',
  closeWithTruncatedContext: 'Schließen: {snippet}…',
  toastContentIncomplete: 'Benachrichtigung mit unvollständigem Inhalt',
  toastOverflow: 'Nicht angezeigte Benachrichtigungen: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tabulator',
  kbdSpaceWord: 'Leertaste',
  kbdDeleteVisual: 'Entf',
  kbdDeleteWord: 'Entfernen',
  kbdHomeWord: 'Pos 1',
  kbdEndWord: 'Ende',
  kbdPageUpVisual: 'Bild ↑',
  kbdPageUpWord: 'Bild auf',
  kbdPageDownVisual: 'Bild ↓',
  kbdPageDownWord: 'Bild ab',
  kbdEnterWord: 'Eingabe',
  kbdBackspaceWord: 'Rücktaste',
  kbdArrowUpWord: 'Pfeil nach oben',
  kbdArrowDownWord: 'Pfeil nach unten',
  kbdArrowLeftWord: 'Pfeil nach links',
  kbdArrowRightWord: 'Pfeil nach rechts',
  kbdPlusWord: 'Plus',
  kbdMinusWord: 'Minus',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Strg',
  kbdControlWord: 'Steuerung',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Umschalt',
};

registerLyraLocale('de', strings);
