// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Ìṣàyẹ̀wò',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Pá: {snippet}',
  closeWithTruncatedContext: 'Pá: {snippet}…',
  toastContentIncomplete: 'Ìfitónilétí tó ní àkóónú tí kò pé',
  toastOverflow: 'Àwọn ìfitónilétí tí a kò fi hàn: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Ààyè',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Pa rẹ́',
  kbdHomeWord: 'Ilé',
  kbdEndWord: 'Òpin',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Ojúewé sókè',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Ojúewé sọ̀kalẹ̀',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Bọ́tìnì ìpadàsẹ́yìn',
  kbdArrowUpWord: 'Ọfà sókè',
  kbdArrowDownWord: 'Ọfà sọ̀kalẹ̀',
  kbdArrowLeftWord: 'Ọfà sí òsì',
  kbdArrowRightWord: 'Ọfà sí ọ̀tún',
  kbdPlusWord: 'Àfikún',
  kbdMinusWord: 'Ìdínkù',
  kbdCommandWord: 'Àṣẹ',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Ìṣàkóso',
  kbdOptionWord: 'Àṣàyàn',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Yípadà',
};

registerLyraLocale('yo', strings);
