// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `charts` slice of the id translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/charts/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/id/charts';` and reads nothing from it.
// `../id.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  chartCategory: 'Kategori',
  chartTotal: 'Total',
  chartAxisTotal: 'Total {axis}',
  chartPrimaryAxis: 'Sumbu utama',
  chartSecondaryAxis: 'Sumbu sekunder',
  chartPointLabel: 'Titik {n}',
  chartPointCoordinates: 'x {x}, y {y}',
  chartBubblePointCoordinates: 'x {x}, y {y}, jari-jari {radius}',
  chartLabeledPoint: '{label}: {coordinates}',
  chartTrendIncreasing: 'meningkat',
  chartTrendDecreasing: 'menurun',
  chartTrendFlat: 'stabil',
  chartSummary: '{label}: {count} nilai, rentang {min} hingga {max}, tren {trend}',
  chartSeriesNoData: '{label}: tidak ada data',
  chartSummaryWithData: 'Bagan {type}. {summaries}.',
  chartSummaryEmpty: 'Bagan {type} tanpa data.',
  chartSummarySeparator: '. ',
  chartData: 'Data bagan',
  chartDataSampled: 'Tabel data yang dibuat menampilkan sampel hingga 1.000 catatan. Berikan tabel data khusus untuk mengakses semua data bagan.',
  chartZoomUnavailable: 'Pembesaran tidak tersedia, tetapi bagan utama tetap dapat digunakan.',
  chartDataLabelsUnavailable: 'Label data tidak tersedia, tetapi bagan utama tetap dapat digunakan.',
  chartStackTotalsUnavailable: 'Total tumpukan tidak tersedia, tetapi bagan utama tetap dapat digunakan.',
  chartAnnotationsUnavailable: 'Anotasi bagan tidak tersedia, tetapi bagan utama tetap dapat digunakan.',
  chartTypeLine: 'Garis',
  chartTypeBar: 'Batang',
  chartTypeScatter: 'Sebar',
  chartTypePie: 'Lingkaran',
  chartTypeDoughnut: 'Donat',
  chartTypeRadar: 'Radar',
  chartTypePolarArea: 'Area polar',
  chartTypeBubble: 'Gelembung',
  boxPlotSeriesSummary: '{label}: {count} distribusi, rentang median {min} hingga {max}, tren median {trend}',
  boxPlotSummaryWithData: 'Diagram kotak. {summaries}.',
  boxPlotSummaryEmpty: 'Diagram kotak tanpa data.',
  boxPlotData: 'Data diagram kotak',
  chartSeriesLabel: 'Seri',
  boxPlotMin: 'Minimum',
  boxPlotQ1: 'Kuartil 1',
  boxPlotMedian: 'Median',
  boxPlotQ3: 'Kuartil 3',
  boxPlotMax: 'Maksimum',
  boxPlot: 'Diagram kotak',
  histogramFrequency: 'Frekuensi',
  liteChartMarkSummary: '{series}, {label}: {value} ({index} dari {total})',
  liteChartBarLabel: '{series}, {label}: {value}',
  chartValuePercentageLabel: '{label}: {value} ({percentage})',
  liteChartCustomMarkSummary: '{content} ({index} dari {total})',
  chartMissingLibrary: 'Komponen ini memerlukan paket opsional "chart.js" agar bagan dapat ditampilkan.',
  boxPlotMissingLibrary: 'Komponen ini memerlukan paket bagan diagram kotak opsional agar diagram kotak dapat ditampilkan.',
};

registerLyraLocale('id', strings);
