// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `forms` slice of the id translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/forms/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/id/forms';` and reads nothing from it.
// `../id.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  openCalendar: 'Buka kalender',
  comboboxLoadError: 'Tidak dapat memuat opsi.',
  comboboxSelectedOverflow: '+{n} lainnya',
  checkboxRequired: 'Centang kotak ini jika Anda ingin melanjutkan.',
  checkboxGroupRequired: 'Pilih setidaknya satu opsi.',
  tokenInputRequired: 'Masukkan setidaknya satu nilai.',
  tokenInputEditWithContext: 'Ubah {label}',
  iconButtonLabel: 'Tombol',
  codeEditorLabel: 'Editor kode',
  switchRequired: 'Aktifkan ini.',
  textareaLabel: 'Teks',
  comboboxOverflow: '+{n} lainnya — perinci pencarian Anda',
  comboboxRequired: 'Pilih sebuah opsi.',
  comboboxCreate: 'Buat {value}',
  comboboxLabel: 'Kotak kombo',
  previousMonth: 'Bulan sebelumnya',
  nextMonth: 'Bulan berikutnya',
  chooseDate: 'Pilih tanggal',
  dateInputPastDisabled: 'Tanggal tidak boleh berada di masa lalu.',
  dateInputFutureDisabled: 'Tanggal tidak boleh berada di masa depan.',
  timeInputLabel: 'Waktu',
  timeInputHour: 'Jam',
  timeInputMinute: 'Menit',
  timeInputSecond: 'Detik',
  timeInputDayPeriod: 'Periode hari',
  timeInputEmptySegment: 'Kosong',
  timeInputOpen: 'Buka pemilih waktu',
  timeInputPopup: 'Pilih waktu',
  timeInputNow: 'Sekarang',
  timeInputInvalid: 'Masukkan waktu yang lengkap.',
  timeInputMinMessage: 'Waktu harus pada atau setelah {min}.',
  timeInputMaxMessage: 'Waktu harus pada atau sebelum {max}.',
  timeInputRangeMessage: 'Waktu harus berada di antara {min} dan {max}, termasuk melewati tengah malam.',
  timeInputStepMessage: 'Masukkan waktu yang sesuai dengan interval yang diwajibkan.',
  inputLabel: 'Teks',
  showPassword: 'Tampilkan kata sandi',
  hidePassword: 'Sembunyikan kata sandi',
  radioRequired: 'Pilih sebuah opsi.',
  sliderLabel: 'Penggeser',
  colorPicker: 'Pemilih warna',
  selectValueMissing: 'Pilih sebuah opsi.',
  rangeStart: 'Awal rentang',
  rangeEnd: 'Akhir rentang',
  matchMismatch: 'Nilai tidak cocok.',
  phoneInputLabel: 'Telepon',
  phoneInputIncomplete: 'Nomor telepon ini belum lengkap.',
  otpInputIncomplete: 'Masukkan semua {total} karakter.',
  otpInputLabel: 'Kode verifikasi',
  numberInputIncrease: 'Tambah',
  numberInputDecrease: 'Kurangi',
  textareaCharacterCount: {
    other: '{count} karakter',
  },
  textareaCharactersRemaining: {
    other: 'Sisa {count} karakter',
  },
  colorPickerSaturationBrightness: 'Saturasi dan kecerahan',
  colorPickerSaturationBrightnessValue: 'Saturasi {saturation}%, kecerahan {brightness}%',
  colorPickerHue: 'Corak warna',
  colorPickerHueValue: '{hue} derajat',
  colorPickerOpacity: 'Opasitas',
  colorPickerOpacityValue: 'Opasitas {opacity}%',
  colorPickerValueField: 'Nilai warna',
  colorPickerToggleFormat: 'Ubah format warna',
  colorPickerEyeDropper: 'Pilih warna dari layar',
  colorPickerSwatches: 'Sampel warna',
  colorPickerSwatch: 'Pilih {color}',
  colorPickerCurrentValue: 'Warna saat ini: {color}',
  selectSelectedOverflow: '+{n} lainnya',
  emojiPickerSearchLabel: 'Cari emoji',
  emojiPickerGridLabel: 'Emoji',
  emojiPickerEmpty: 'Emoji tidak ditemukan',
  emojiPickerLoadError: 'Tidak dapat memuat emoji.',
  emojiPickerGroupSmileysEmotion: 'Wajah dan emosi',
  emojiPickerGroupPeopleBody: 'Orang dan tubuh',
  emojiPickerGroupComponent: 'Komponen',
  emojiPickerGroupAnimalsNature: 'Hewan dan alam',
  emojiPickerGroupFoodDrink: 'Makanan dan minuman',
  emojiPickerGroupTravelPlaces: 'Perjalanan dan tempat',
  emojiPickerGroupActivities: 'Aktivitas',
  emojiPickerGroupObjects: 'Objek',
  emojiPickerGroupSymbols: 'Simbol',
  emojiPickerGroupFlags: 'Bendera',
  emojiPickerGroupUnknown: 'Grup {group}',
  rubricSubmit: 'Kirim',
  rubricSubmitAndNext: 'Kirim dan lanjutkan',
  rubricSkip: 'Lewati',
  localePickerLabel: 'Bahasa',
  localePickerRequired: 'Pilih bahasa.',
};

registerLyraLocale('id', strings, { dir: 'ltr', name: 'Bahasa Indonesia' });
