// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `layout` slice of the id translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/layout/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/id/layout';` and reads nothing from it.
// `../id.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'karusel',
  carouselLabel: 'Karusel',
  carouselSlide: 'slide',
  carouselSlidePosition: 'Slide {index} dari {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Slide karusel',
  carouselGoTo: 'Buka slide {index}',
  scrollerLabel: 'Konten yang dapat digulir',
  scrollPrevious: 'Gulir mundur',
  scrollNext: 'Gulir maju',
  closeNavigation: 'Tutup navigasi',
  openNavigation: 'Buka navigasi',
  resizeNavigation: 'Ubah ukuran navigasi',
  appRailCollapse: 'Ciutkan navigasi',
  appRailExpand: 'Perluas navigasi',
  appRailItemCollapse: 'Ciutkan {label}',
  appRailItemExpand: 'Perluas {label}',
  resizeValuePercent: '{value} persen',
  commandPaletteLabel: 'Palet perintah',
  commandPalettePlaceholder: 'Cari perintah…',
  commandPaletteEmpty: 'Tidak ada perintah yang cocok.',
  commandPaletteResults: 'Perintah',
  dockPanelCollapse: 'Ciutkan panel',
  dockPanelExpand: 'Perluas panel',
  dockPanelResize: 'Ubah ukuran panel',
  responsivePanel: 'Panel',
  breadcrumb: 'Jejak navigasi',
  resizeDivider: 'Ubah ukuran pembagi antara panel {a} dan panel {b}',
  widgetFullscreenPanel: 'Panel layar penuh',
  widgetViewGroup: 'Tampilan panel',
  widgetExitFullscreen: 'Keluar dari layar penuh',
  widgetExpandToFullscreen: 'Perluas ke layar penuh',
  widgetCollapse: 'Ciutkan panel',
  widgetExpand: 'Perluas panel',
  skipToContent: 'Lompat ke konten',
  dashboardGridLabel: 'Kisi dasbor',
  dashboardCellCollisionRejected: '{label} tidak dapat ditempatkan di sana karena bertumpang tindih dengan sel lain.',
  dashboardCellMoved: '{label} dipindahkan ke kolom {x}, baris {y}.',
  dashboardCellResized: 'Ukuran {label} diubah menjadi lebar {w}, tinggi {h}.',
  filterBarReset: 'Atur ulang filter',
  filterBarActiveFilters: 'Filter aktif',
  drilldownDocuments: 'Dokumen',
  drilldownRuns: 'Proses agen',
  drilldownEmpty: 'Tidak ada item yang dipilih',
  drilldownUntitledNode: 'Langkah tanpa judul',
  reorderMovePending: 'Pengurutan ulang tertunda.',
  reorderMoveCancelled: 'Pengurutan ulang dibatalkan.',
};

registerLyraLocale('id', strings);
