// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Penilaian',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Tutup: {snippet}',
  closeWithTruncatedContext: 'Tutup: {snippet}…',
  toastContentIncomplete: 'Notifikasi dengan konten yang belum lengkap',
  toastOverflow: 'Notifikasi yang tidak ditampilkan: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Spasi',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Hapus',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'Panah atas',
  kbdArrowDownWord: 'Panah bawah',
  kbdArrowLeftWord: 'Panah kiri',
  kbdArrowRightWord: 'Panah kanan',
  kbdPlusWord: 'Plus',
  kbdMinusWord: 'Minus',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('id', strings);
