// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'Salin JSON ke papan klip',
  circularReference: 'Referensi melingkar',
  copyDiff: 'Salin perbedaan',
  diffViewOldLabel: 'Asli',
  diffViewNewLabel: 'Diubah',
  diffViewHiddenLines: {
    other: '{count} baris yang tidak berubah',
  },
  diffViewTooLarge: 'Perbedaan terlalu besar untuk ditampilkan.',
  jsonArray: 'larik',
  jsonObject: 'objek',
  jsonValue: 'nilai',
  jsonCopyLabel: 'Salin {label}',
  jsonExpandLabel: 'Perluas {label}',
  jsonCollapseLabel: 'Ciutkan {label}',
  jsonItemCount: {
    other: '{count} item',
  },
  jsonKeyCount: {
    other: '{count} kunci',
  },
  jsonViewerLimit: 'Hanya {count} simpul JSON pertama dan {depth} tingkat penyarangan yang ditampilkan dan dicari.',
  pollPause: 'Jeda',
  pollResume: 'Lanjutkan',
  pollInactive: 'Tidak aktif',
  pollRefreshing: 'Memuat ulang…',
  pollPaused: 'Dijeda',
  pollPausedAnnounce: 'Dijeda.',
  pollResumedAnnounce: 'Dilanjutkan.',
  pollRefreshingAnnounce: 'Sedang memuat ulang.',
  randomContentPause: 'Jeda rotasi',
  randomContentResume: 'Lanjutkan rotasi',
  exportButtonLabel: 'Ekspor',
  knownDateDay: 'Hari',
  knownDateMonth: 'Bulan',
  knownDateYear: 'Tahun',
  exportFormatMenuLabel: 'Format {label}',
  mentionSuggestions: 'Saran',
  mentionResultCount: {
    other: '{count} saran',
  },
  mentionResultPosition: 'Saran {current} dari {total}',
  iconLoadError: 'Ikon gagal dimuat.',
  iconTooLarge: 'File ikon terlalu besar untuk ditampilkan.',
  iconSanitizerMissing: 'Ikon ini memerlukan paket opsional "dompurify" agar dapat ditampilkan dengan aman.',
  tourSkip: 'Lewati',
  tourDone: 'Selesai',
  tourStepOf: 'Langkah {current} dari {total}',
};

registerLyraLocale('id', strings);
