// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./am/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './am/agent-tools.js';
import './am/charts.js';
import './am/conversation.js';
import './am/data.js';
import './am/forms.js';
import './am/layout.js';
import './am/media.js';
import './am/overlays.js';
import './am/retrieval.js';
import './am/utility.js';
import './am/viewers.js';
import './am/shared.js';
