// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./da/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './da/agent-tools.js';
import './da/charts.js';
import './da/conversation.js';
import './da/data.js';
import './da/forms.js';
import './da/layout.js';
import './da/media.js';
import './da/overlays.js';
import './da/retrieval.js';
import './da/utility.js';
import './da/viewers.js';
import './da/shared.js';
