// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// de translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/de/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./de/`, never this file.
import './de/agent-tools.js';
import './de/charts.js';
import './de/conversation.js';
import './de/data.js';
import './de/forms.js';
import './de/layout.js';
import './de/media.js';
import './de/overlays.js';
import './de/retrieval.js';
import './de/utility.js';
import './de/viewers.js';
import './de/shared.js';
