// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// es translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/es/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./es/`, never this file.
import './es/agent-tools.js';
import './es/charts.js';
import './es/conversation.js';
import './es/data.js';
import './es/forms.js';
import './es/layout.js';
import './es/media.js';
import './es/overlays.js';
import './es/retrieval.js';
import './es/utility.js';
import './es/viewers.js';
import './es/shared.js';
