// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// fi translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/fi/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./fi/`, never this file.
import './fi/agent-tools.js';
import './fi/charts.js';
import './fi/conversation.js';
import './fi/data.js';
import './fi/forms.js';
import './fi/layout.js';
import './fi/media.js';
import './fi/overlays.js';
import './fi/retrieval.js';
import './fi/utility.js';
import './fi/viewers.js';
import './fi/shared.js';
