// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./fr/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './fr/agent-tools.js';
import './fr/charts.js';
import './fr/conversation.js';
import './fr/data.js';
import './fr/forms.js';
import './fr/layout.js';
import './fr/media.js';
import './fr/overlays.js';
import './fr/retrieval.js';
import './fr/utility.js';
import './fr/viewers.js';
import './fr/shared.js';
