// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./gu/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './gu/agent-tools.js';
import './gu/charts.js';
import './gu/conversation.js';
import './gu/data.js';
import './gu/forms.js';
import './gu/layout.js';
import './gu/media.js';
import './gu/overlays.js';
import './gu/retrieval.js';
import './gu/utility.js';
import './gu/viewers.js';
import './gu/shared.js';
