// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./ha/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './ha/agent-tools.js';
import './ha/charts.js';
import './ha/conversation.js';
import './ha/data.js';
import './ha/forms.js';
import './ha/layout.js';
import './ha/media.js';
import './ha/overlays.js';
import './ha/retrieval.js';
import './ha/utility.js';
import './ha/viewers.js';
import './ha/shared.js';
