// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// hi translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/hi/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./hi/`, never this file.
import './hi/agent-tools.js';
import './hi/charts.js';
import './hi/conversation.js';
import './hi/data.js';
import './hi/forms.js';
import './hi/layout.js';
import './hi/media.js';
import './hi/overlays.js';
import './hi/retrieval.js';
import './hi/utility.js';
import './hi/viewers.js';
import './hi/shared.js';
