// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./hr/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './hr/agent-tools.js';
import './hr/charts.js';
import './hr/conversation.js';
import './hr/data.js';
import './hr/forms.js';
import './hr/layout.js';
import './hr/media.js';
import './hr/overlays.js';
import './hr/retrieval.js';
import './hr/utility.js';
import './hr/viewers.js';
import './hr/shared.js';
