// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./it/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './it/agent-tools.js';
import './it/charts.js';
import './it/conversation.js';
import './it/data.js';
import './it/forms.js';
import './it/layout.js';
import './it/media.js';
import './it/overlays.js';
import './it/retrieval.js';
import './it/utility.js';
import './it/viewers.js';
import './it/shared.js';
