// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// ja translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/ja/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./ja/`, never this file.
import './ja/agent-tools.js';
import './ja/charts.js';
import './ja/conversation.js';
import './ja/data.js';
import './ja/forms.js';
import './ja/layout.js';
import './ja/media.js';
import './ja/overlays.js';
import './ja/retrieval.js';
import './ja/utility.js';
import './ja/viewers.js';
import './ja/shared.js';
