// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./ln/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './ln/agent-tools.js';
import './ln/charts.js';
import './ln/conversation.js';
import './ln/data.js';
import './ln/forms.js';
import './ln/layout.js';
import './ln/media.js';
import './ln/overlays.js';
import './ln/retrieval.js';
import './ln/utility.js';
import './ln/viewers.js';
import './ln/shared.js';
