// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./ms/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './ms/agent-tools.js';
import './ms/charts.js';
import './ms/conversation.js';
import './ms/data.js';
import './ms/forms.js';
import './ms/layout.js';
import './ms/media.js';
import './ms/overlays.js';
import './ms/retrieval.js';
import './ms/utility.js';
import './ms/viewers.js';
import './ms/shared.js';
