// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./nb/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './nb/agent-tools.js';
import './nb/charts.js';
import './nb/conversation.js';
import './nb/data.js';
import './nb/forms.js';
import './nb/layout.js';
import './nb/media.js';
import './nb/overlays.js';
import './nb/retrieval.js';
import './nb/utility.js';
import './nb/viewers.js';
import './nb/shared.js';
