// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./nn/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './nn/agent-tools.js';
import './nn/charts.js';
import './nn/conversation.js';
import './nn/data.js';
import './nn/forms.js';
import './nn/layout.js';
import './nn/media.js';
import './nn/overlays.js';
import './nn/retrieval.js';
import './nn/utility.js';
import './nn/viewers.js';
import './nn/shared.js';
