// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// nn translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/nn/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./nn/`, never this file.
import './nn/agent-tools.js';
import './nn/charts.js';
import './nn/conversation.js';
import './nn/data.js';
import './nn/forms.js';
import './nn/layout.js';
import './nn/media.js';
import './nn/overlays.js';
import './nn/retrieval.js';
import './nn/utility.js';
import './nn/viewers.js';
import './nn/shared.js';
