// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./om/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './om/agent-tools.js';
import './om/charts.js';
import './om/conversation.js';
import './om/data.js';
import './om/forms.js';
import './om/layout.js';
import './om/media.js';
import './om/overlays.js';
import './om/retrieval.js';
import './om/utility.js';
import './om/viewers.js';
import './om/shared.js';
