// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./pa/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './pa/agent-tools.js';
import './pa/charts.js';
import './pa/conversation.js';
import './pa/data.js';
import './pa/forms.js';
import './pa/layout.js';
import './pa/media.js';
import './pa/overlays.js';
import './pa/retrieval.js';
import './pa/utility.js';
import './pa/viewers.js';
import './pa/shared.js';
