// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./pcm/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './pcm/agent-tools.js';
import './pcm/charts.js';
import './pcm/conversation.js';
import './pcm/data.js';
import './pcm/forms.js';
import './pcm/layout.js';
import './pcm/media.js';
import './pcm/overlays.js';
import './pcm/retrieval.js';
import './pcm/utility.js';
import './pcm/viewers.js';
import './pcm/shared.js';
