// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// pl translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/pl/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./pl/`, never this file.
import './pl/agent-tools.js';
import './pl/charts.js';
import './pl/conversation.js';
import './pl/data.js';
import './pl/forms.js';
import './pl/layout.js';
import './pl/media.js';
import './pl/overlays.js';
import './pl/retrieval.js';
import './pl/utility.js';
import './pl/viewers.js';
import './pl/shared.js';
