// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./pnb/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './pnb/agent-tools.js';
import './pnb/charts.js';
import './pnb/conversation.js';
import './pnb/data.js';
import './pnb/forms.js';
import './pnb/layout.js';
import './pnb/media.js';
import './pnb/overlays.js';
import './pnb/retrieval.js';
import './pnb/utility.js';
import './pnb/viewers.js';
import './pnb/shared.js';
