// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./ps/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './ps/agent-tools.js';
import './ps/charts.js';
import './ps/conversation.js';
import './ps/data.js';
import './ps/forms.js';
import './ps/layout.js';
import './ps/media.js';
import './ps/overlays.js';
import './ps/retrieval.js';
import './ps/utility.js';
import './ps/viewers.js';
import './ps/shared.js';
