// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./pt-BR/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './pt-BR/agent-tools.js';
import './pt-BR/charts.js';
import './pt-BR/conversation.js';
import './pt-BR/data.js';
import './pt-BR/forms.js';
import './pt-BR/layout.js';
import './pt-BR/media.js';
import './pt-BR/overlays.js';
import './pt-BR/retrieval.js';
import './pt-BR/utility.js';
import './pt-BR/viewers.js';
import './pt-BR/shared.js';
