// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./pt-PT/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './pt-PT/agent-tools.js';
import './pt-PT/charts.js';
import './pt-PT/conversation.js';
import './pt-PT/data.js';
import './pt-PT/forms.js';
import './pt-PT/layout.js';
import './pt-PT/media.js';
import './pt-PT/overlays.js';
import './pt-PT/retrieval.js';
import './pt-PT/utility.js';
import './pt-PT/viewers.js';
import './pt-PT/shared.js';
