// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// pt-PT translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/pt-PT/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./pt-PT/`, never this file.
import './pt-PT/agent-tools.js';
import './pt-PT/charts.js';
import './pt-PT/conversation.js';
import './pt-PT/data.js';
import './pt-PT/forms.js';
import './pt-PT/layout.js';
import './pt-PT/media.js';
import './pt-PT/overlays.js';
import './pt-PT/retrieval.js';
import './pt-PT/utility.js';
import './pt-PT/viewers.js';
import './pt-PT/shared.js';
