// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./sl/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './sl/agent-tools.js';
import './sl/charts.js';
import './sl/conversation.js';
import './sl/data.js';
import './sl/forms.js';
import './sl/layout.js';
import './sl/media.js';
import './sl/overlays.js';
import './sl/retrieval.js';
import './sl/utility.js';
import './sl/viewers.js';
import './sl/shared.js';
