// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./su/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './su/agent-tools.js';
import './su/charts.js';
import './su/conversation.js';
import './su/data.js';
import './su/forms.js';
import './su/layout.js';
import './su/media.js';
import './su/overlays.js';
import './su/retrieval.js';
import './su/utility.js';
import './su/viewers.js';
import './su/shared.js';
