// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./sv/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './sv/agent-tools.js';
import './sv/charts.js';
import './sv/conversation.js';
import './sv/data.js';
import './sv/forms.js';
import './sv/layout.js';
import './sv/media.js';
import './sv/overlays.js';
import './sv/retrieval.js';
import './sv/utility.js';
import './sv/viewers.js';
import './sv/shared.js';
