// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./ta/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './ta/agent-tools.js';
import './ta/charts.js';
import './ta/conversation.js';
import './ta/data.js';
import './ta/forms.js';
import './ta/layout.js';
import './ta/media.js';
import './ta/overlays.js';
import './ta/retrieval.js';
import './ta/utility.js';
import './ta/viewers.js';
import './ta/shared.js';
