// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./te/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './te/agent-tools.js';
import './te/charts.js';
import './te/conversation.js';
import './te/data.js';
import './te/forms.js';
import './te/layout.js';
import './te/media.js';
import './te/overlays.js';
import './te/retrieval.js';
import './te/utility.js';
import './te/viewers.js';
import './te/shared.js';
