// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./th/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './th/agent-tools.js';
import './th/charts.js';
import './th/conversation.js';
import './th/data.js';
import './th/forms.js';
import './th/layout.js';
import './th/media.js';
import './th/overlays.js';
import './th/retrieval.js';
import './th/utility.js';
import './th/viewers.js';
import './th/shared.js';
