// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./tl/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './tl/agent-tools.js';
import './tl/charts.js';
import './tl/conversation.js';
import './tl/data.js';
import './tl/forms.js';
import './tl/layout.js';
import './tl/media.js';
import './tl/overlays.js';
import './tl/retrieval.js';
import './tl/utility.js';
import './tl/viewers.js';
import './tl/shared.js';
