// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./tr/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './tr/agent-tools.js';
import './tr/charts.js';
import './tr/conversation.js';
import './tr/data.js';
import './tr/forms.js';
import './tr/layout.js';
import './tr/media.js';
import './tr/overlays.js';
import './tr/retrieval.js';
import './tr/utility.js';
import './tr/viewers.js';
import './tr/shared.js';
