// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// tr translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/tr/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./tr/`, never this file.
import './tr/agent-tools.js';
import './tr/charts.js';
import './tr/conversation.js';
import './tr/data.js';
import './tr/forms.js';
import './tr/layout.js';
import './tr/media.js';
import './tr/overlays.js';
import './tr/retrieval.js';
import './tr/utility.js';
import './tr/viewers.js';
import './tr/shared.js';
