// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// uk translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/uk/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./uk/`, never this file.
import './uk/agent-tools.js';
import './uk/charts.js';
import './uk/conversation.js';
import './uk/data.js';
import './uk/forms.js';
import './uk/layout.js';
import './uk/media.js';
import './uk/overlays.js';
import './uk/retrieval.js';
import './uk/utility.js';
import './uk/viewers.js';
import './uk/shared.js';
