// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./uk/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './uk/agent-tools.js';
import './uk/charts.js';
import './uk/conversation.js';
import './uk/data.js';
import './uk/forms.js';
import './uk/layout.js';
import './uk/media.js';
import './uk/overlays.js';
import './uk/retrieval.js';
import './uk/utility.js';
import './uk/viewers.js';
import './uk/shared.js';
