// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./vi/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './vi/agent-tools.js';
import './vi/charts.js';
import './vi/conversation.js';
import './vi/data.js';
import './vi/forms.js';
import './vi/layout.js';
import './vi/media.js';
import './vi/overlays.js';
import './vi/retrieval.js';
import './vi/utility.js';
import './vi/viewers.js';
import './vi/shared.js';
