// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand; to
// translate, edit the slice file under ./yo/, never this file. Back-compat aggregate:
// importing it registers every family slice (import one directly for a smaller bundle).
// Regenerate: node scripts/generate-translation-slices.mjs --write.
import './yo/agent-tools.js';
import './yo/charts.js';
import './yo/conversation.js';
import './yo/data.js';
import './yo/forms.js';
import './yo/layout.js';
import './yo/media.js';
import './yo/overlays.js';
import './yo/retrieval.js';
import './yo/utility.js';
import './yo/viewers.js';
import './yo/shared.js';
