// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// zh-CN translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/zh-CN/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./zh-CN/`, never this file.
import './zh-CN/agent-tools.js';
import './zh-CN/charts.js';
import './zh-CN/conversation.js';
import './zh-CN/data.js';
import './zh-CN/forms.js';
import './zh-CN/layout.js';
import './zh-CN/media.js';
import './zh-CN/overlays.js';
import './zh-CN/retrieval.js';
import './zh-CN/utility.js';
import './zh-CN/viewers.js';
import './zh-CN/shared.js';
