// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// zh-TW translation catalog for @aceshooting/lyra-ui.
//
// Back-compat aggregate: importing this file registers every family slice below, preserving the
// pre-16.0.0 "one import gets everything" behaviour and merge semantics (a later
// registerLyraLocale() call, or a per-instance `.strings` override, still wins). An application
// that only uses a handful of components can import the family slice(s) it actually needs instead
// -- e.g. `@aceshooting/lyra-ui/translations/zh-TW/data` -- for a smaller bundle. Every catalog
// key belongs to exactly one slice: its owning family, or `shared` when more than one family
// reaches it. To translate, edit the slice file under `./zh-TW/`, never this file.
import './zh-TW/agent-tools.js';
import './zh-TW/charts.js';
import './zh-TW/conversation.js';
import './zh-TW/data.js';
import './zh-TW/forms.js';
import './zh-TW/layout.js';
import './zh-TW/media.js';
import './zh-TW/overlays.js';
import './zh-TW/retrieval.js';
import './zh-TW/utility.js';
import './zh-TW/viewers.js';
import './zh-TW/shared.js';
