// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `overlays` slice of the sv translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/overlays/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/sv/overlays';` and reads nothing from it.
// `../sv.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Betyg',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Stäng: {snippet}',
  closeWithTruncatedContext: 'Stäng: {snippet}…',
  toastContentIncomplete: 'Avisering med ofullständigt innehåll',
  toastOverflow: 'Aviseringar som inte visas: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tabb',
  kbdSpaceWord: 'Blanksteg',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Retur',
  kbdBackspaceWord: 'Backsteg',
  kbdArrowUpWord: 'Uppåtpil',
  kbdArrowDownWord: 'Nedåtpil',
  kbdArrowLeftWord: 'Vänsterpil',
  kbdArrowRightWord: 'Högerpil',
  kbdPlusWord: 'Plus',
  kbdMinusWord: 'Minus',
  kbdCommandWord: 'Kommando',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Alternativ',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Skift',
};

registerLyraLocale('sv', strings);
