// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `layout` slice of the ar translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/layout/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/ar/layout';` and reads nothing from it.
// `../ar.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'شريط دوّار',
  carouselLabel: 'شريط دوّار',
  carouselSlide: 'شريحة',
  carouselSlidePosition: 'الشريحة {index} من {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'شرائح الشريط الدوّار',
  carouselGoTo: 'الانتقال إلى الشريحة {index}',
  scrollerLabel: 'محتوى قابل للتمرير',
  scrollPrevious: 'التمرير للخلف',
  scrollNext: 'التمرير للأمام',
  closeNavigation: 'إغلاق التنقل',
  openNavigation: 'فتح التنقل',
  resizeNavigation: 'تغيير حجم التنقل',
  appRailCollapse: 'طي التنقل',
  appRailExpand: 'توسيع التنقل',
  appRailItemCollapse: 'طي {label}',
  appRailItemExpand: 'توسيع {label}',
  resizeValuePercent: '{value} بالمئة',
  commandPaletteLabel: 'لوحة الأوامر',
  commandPalettePlaceholder: 'ابحث في الأوامر…',
  commandPaletteEmpty: 'لا توجد أوامر مطابقة.',
  commandPaletteResults: 'الأوامر',
  dockPanelCollapse: 'طي اللوحة',
  dockPanelExpand: 'توسيع اللوحة',
  dockPanelResize: 'تغيير حجم اللوحة',
  responsivePanel: 'لوحة',
  breadcrumb: 'مسار التنقل',
  resizeDivider: 'تغيير حجم الفاصل بين اللوحة {a} واللوحة {b}',
  widgetFullscreenPanel: 'لوحة ملء الشاشة',
  widgetViewGroup: 'عرض اللوحة',
  widgetExitFullscreen: 'إنهاء ملء الشاشة',
  widgetExpandToFullscreen: 'توسيع إلى ملء الشاشة',
  widgetCollapse: 'طي اللوحة',
  widgetExpand: 'توسيع اللوحة',
  skipToContent: 'تخطي إلى المحتوى',
  dashboardGridLabel: 'شبكة لوحة المعلومات',
  dashboardCellCollisionRejected: 'لا يمكن وضع {label} هناك لأنه يتداخل مع خلية أخرى.',
  dashboardCellMoved: 'تم نقل {label} إلى العمود {x}، الصف {y}.',
  dashboardCellResized: 'تم تغيير حجم {label} إلى عرض {w} وارتفاع {h}.',
  filterBarReset: 'إعادة تعيين عوامل التصفية',
  filterBarActiveFilters: 'عوامل التصفية النشطة',
  drilldownDocuments: 'المستندات',
  drilldownRuns: 'عمليات تشغيل الوكيل',
  drilldownEmpty: 'لم يتم تحديد أي عنصر',
  drilldownUntitledNode: 'خطوة بلا عنوان',
  reorderMovePending: 'إعادة الترتيب معلّقة.',
  reorderMoveCancelled: 'تم إلغاء إعادة الترتيب.',
};

registerLyraLocale('ar', strings, { dir: 'rtl', name: 'العربية' });
