// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'تقييم',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'إغلاق: {snippet}',
  closeWithTruncatedContext: 'إغلاق: {snippet}…',
  toastContentIncomplete: 'إشعار بمحتوى غير مكتمل',
  toastOverflow: 'الإشعارات التي لم تُعرض: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'مسافة',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'حذف',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'صفحة لأعلى',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'صفحة لأسفل',
  kbdEnterWord: 'إدخال',
  kbdBackspaceWord: 'مسافة للخلف',
  kbdArrowUpWord: 'السهم لأعلى',
  kbdArrowDownWord: 'السهم لأسفل',
  kbdArrowLeftWord: 'السهم لليسار',
  kbdArrowRightWord: 'السهم لليمين',
  kbdPlusWord: 'علامة الجمع',
  kbdMinusWord: 'علامة الطرح',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('ar', strings, { dir: 'rtl', name: 'العربية' });
