// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Note',
  calloutAnnouncementWithContext: '{context} : {content}',
  closeWithContext: 'Fermer : {snippet}',
  closeWithTruncatedContext: 'Fermer : {snippet}…',
  toastContentIncomplete: 'Notification au contenu incomplet',
  toastOverflow: 'Notifications non affichées : {count}.',
  kbdEscapeVisual: 'Échap',
  kbdEscapeWord: 'Échappement',
  kbdTabWord: 'Tabulation',
  kbdSpaceWord: 'Espace',
  kbdDeleteVisual: 'Suppr',
  kbdDeleteWord: 'Suppression',
  kbdHomeWord: 'Début',
  kbdEndWord: 'Fin',
  kbdPageUpVisual: 'Pg. préc',
  kbdPageUpWord: 'Page précédente',
  kbdPageDownVisual: 'Pg. suiv',
  kbdPageDownWord: 'Page suivante',
  kbdEnterWord: 'Entrée',
  kbdBackspaceWord: 'Retour arrière',
  kbdArrowUpWord: 'Flèche haut',
  kbdArrowDownWord: 'Flèche bas',
  kbdArrowLeftWord: 'Flèche gauche',
  kbdArrowRightWord: 'Flèche droite',
  kbdPlusWord: 'Plus',
  kbdMinusWord: 'Moins',
  kbdCommandWord: 'Commande',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Contrôle',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Maj',
};

registerLyraLocale('fr', strings);
