// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `utility` slice of the fr translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/utility/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/fr/utility';` and reads nothing from it.
// `../fr.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'Copier le JSON dans le presse-papiers',
  circularReference: 'Référence circulaire',
  copyDiff: 'Copier le diff',
  diffViewOldLabel: 'Original',
  diffViewNewLabel: 'Modifié',
  diffViewHiddenLines: {
    one: '{count} ligne inchangée',
    many: '{count} lignes inchangées',
    other: '{count} lignes inchangées',
  },
  diffViewTooLarge: 'Le diff est trop volumineux pour être affiché.',
  jsonArray: 'tableau',
  jsonObject: 'objet',
  jsonValue: 'valeur',
  jsonCopyLabel: 'Copier {label}',
  jsonExpandLabel: 'Développer {label}',
  jsonCollapseLabel: 'Réduire {label}',
  jsonItemCount: {
    one: '{count} élément',
    many: '{count} éléments',
    other: '{count} éléments',
  },
  jsonKeyCount: {
    one: '{count} clé',
    many: '{count} clés',
    other: '{count} clés',
  },
  jsonViewerLimit: 'Seuls les {count} premiers nœuds JSON et {depth} niveaux d’imbrication sont affichés et parcourus.',
  pollPause: 'Mettre en pause',
  pollResume: 'Reprendre',
  pollInactive: 'Inactif',
  pollRefreshing: 'Actualisation…',
  pollPaused: 'En pause',
  pollPausedAnnounce: 'Mis en pause.',
  pollResumedAnnounce: 'Reprise.',
  pollRefreshingAnnounce: 'Actualisation en cours.',
  randomContentPause: 'Mettre la rotation en pause',
  randomContentResume: 'Reprendre la rotation',
  exportButtonLabel: 'Exporter',
  knownDateDay: 'Jour',
  knownDateMonth: 'Mois',
  knownDateYear: 'Année',
  exportFormatMenuLabel: 'Format {label}',
  mentionSuggestions: 'Suggestions',
  mentionResultCount: {
    one: '{count} suggestion',
    many: '{count} suggestions',
    other: '{count} suggestions',
  },
  mentionResultPosition: 'Suggestion {current} sur {total}',
  iconLoadError: 'Le chargement de l’icône a échoué.',
  iconTooLarge: 'Le fichier de l’icône est trop volumineux pour être affiché.',
  iconSanitizerMissing: 'Cette icône nécessite le paquet optionnel "dompurify" pour un affichage sécurisé.',
  tourSkip: 'Ignorer',
  tourDone: 'Terminer',
  tourStepOf: 'Étape {current} sur {total}',
};

registerLyraLocale('fr', strings);
