// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'রেটিং',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'বন্ধ করুন: {snippet}',
  closeWithTruncatedContext: 'বন্ধ করুন: {snippet}…',
  toastContentIncomplete: 'অসম্পূর্ণ বিষয়বস্তুর বিজ্ঞপ্তি',
  toastOverflow: '{count}টি বিজ্ঞপ্তি দেখানো হয়নি।',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'এসকেপ',
  kbdTabWord: 'ট্যাব',
  kbdSpaceWord: 'স্পেস',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'ডিলিট',
  kbdHomeWord: 'হোম',
  kbdEndWord: 'এন্ড',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'পেজ আপ',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'পেজ ডাউন',
  kbdEnterWord: 'এন্টার',
  kbdBackspaceWord: 'ব্যাকস্পেস',
  kbdArrowUpWord: 'ওপরের তীর',
  kbdArrowDownWord: 'নিচের তীর',
  kbdArrowLeftWord: 'বাঁয়ের তীর',
  kbdArrowRightWord: 'ডানের তীর',
  kbdPlusWord: 'প্লাস',
  kbdMinusWord: 'মাইনাস',
  kbdCommandWord: 'কমান্ড',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'কন্ট্রোল',
  kbdOptionWord: 'অপশন',
  kbdAltWord: 'অল্ট',
  kbdShiftWord: 'শিফট',
};

registerLyraLocale('bn', strings);
