// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `charts` slice of the fa translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/charts/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/fa/charts';` and reads nothing from it.
// `../fa.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  chartCategory: 'دسته‌بندی',
  chartTotal: 'مجموع',
  chartAxisTotal: 'مجموع {axis}',
  chartPrimaryAxis: 'محور اصلی',
  chartSecondaryAxis: 'محور ثانویه',
  chartPointLabel: 'نقطه {n}',
  chartPointCoordinates: 'مختصات x: {x}، مختصات y: {y}',
  chartBubblePointCoordinates: 'مختصات x: {x}، مختصات y: {y}، شعاع: {radius}',
  chartLabeledPoint: '{label} — {coordinates}',
  chartTrendIncreasing: 'افزایشی',
  chartTrendDecreasing: 'کاهشی',
  chartTrendFlat: 'ثابت',
  chartSummary: '{label}: {count} مقدار، بازهٔ {min} تا {max}، روند {trend}',
  chartSeriesNoData: '{label}: داده‌ای وجود ندارد',
  chartSummaryWithData: 'نمودار {type}. {summaries}.',
  chartSummaryEmpty: 'نمودار {type} بدون داده.',
  chartSummarySeparator: '. ',
  chartData: 'داده‌های نمودار',
  chartDataSampled: 'جدول دادهٔ تولیدشده نمونه‌ای شامل حداکثر ۱٬۰۰۰ رکورد را نشان می‌دهد. برای دسترسی به همهٔ داده‌های نمودار، یک جدول دادهٔ سفارشی فراهم کنید.',
  chartZoomUnavailable: 'بزرگ‌نمایی در دسترس نیست، اما نمودار اصلی همچنان در دسترس است.',
  chartDataLabelsUnavailable: 'برچسب‌های داده در دسترس نیستند، اما نمودار اصلی همچنان در دسترس است.',
  chartStackTotalsUnavailable: 'جمع‌های پشته‌ای در دسترس نیستند، اما نمودار اصلی همچنان در دسترس است.',
  chartAnnotationsUnavailable: 'حاشیه‌نویسی‌های نمودار در دسترس نیستند، اما نمودار اصلی همچنان در دسترس است.',
  chartTypeLine: 'خطی',
  chartTypeBar: 'میله‌ای',
  chartTypeScatter: 'پراکندگی',
  chartTypePie: 'دایره‌ای',
  chartTypeDoughnut: 'حلقه‌ای',
  chartTypeRadar: 'رادار',
  chartTypePolarArea: 'ناحیهٔ قطبی',
  chartTypeBubble: 'حباب',
  boxPlotSeriesSummary: '{label}: {count} توزیع، بازهٔ میانه از {min} تا {max}، روند میانهٔ {trend}',
  boxPlotSummaryWithData: 'نمودار جعبه‌ای. {summaries}.',
  boxPlotSummaryEmpty: 'نمودار جعبه‌ای بدون داده.',
  boxPlotData: 'داده‌های نمودار جعبه‌ای',
  chartSeriesLabel: 'سری',
  boxPlotMin: 'حداقل',
  boxPlotQ1: 'Q1',
  boxPlotMedian: 'میانه',
  boxPlotQ3: 'Q3',
  boxPlotMax: 'حداکثر',
  boxPlot: 'نمودار جعبه‌ای',
  histogramFrequency: 'فراوانی',
  liteChartMarkSummary: '{series}، {label}: {value} ({index} از {total})',
  liteChartBarLabel: '{series}، {label}: {value}',
  liteChartCustomMarkSummary: '{content} ({index} از {total})',
  chartMissingLibrary: 'برای نمایش نمودارها، باید بستهٔ اختیاری «chart.js» را نصب کنید.',
  boxPlotMissingLibrary: 'برای نمایش نمودارهای جعبه‌ای، باید بستهٔ اختیاری نمودار جعبه‌ای را نصب کنید.',
};

registerLyraLocale('fa', strings, { dir: 'rtl', name: 'فارسی' });
