// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `utility` slice of the fa translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/utility/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/fa/utility';` and reads nothing from it.
// `../fa.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'کپی JSON در کلیپ‌بورد',
  circularReference: 'ارجاع دوری',
  copyDiff: 'کپی تفاوت',
  diffViewOldLabel: 'اصلی',
  diffViewNewLabel: 'اصلاح‌شده',
  diffViewHiddenLines: {
    one: '{count} خط بدون تغییر',
    other: '{count} خط بدون تغییر',
  },
  diffViewTooLarge: 'تفاوت برای نمایش خیلی بزرگ است.',
  jsonArray: 'آرایه',
  jsonObject: 'شیء',
  jsonValue: 'مقدار',
  jsonCopyLabel: 'کپی {label}',
  jsonExpandLabel: 'گسترش {label}',
  jsonCollapseLabel: 'جمع کردن {label}',
  jsonItemCount: {
    one: '{count} مورد',
    other: '{count} مورد',
  },
  jsonKeyCount: {
    one: '{count} کلید',
    other: '{count} کلید',
  },
  jsonViewerLimit: 'فقط {count} گرهٔ نخست JSON و {depth} سطح تودرتو نمایش داده و جست‌وجو می‌شوند.',
  pollPause: 'مکث',
  pollResume: 'ادامه',
  pollInactive: 'غیرفعال',
  pollRefreshing: 'در حال تازه‌سازی…',
  pollPaused: 'در حالت مکث',
  pollPausedAnnounce: 'مکث شد.',
  pollResumedAnnounce: 'ادامه یافت.',
  pollRefreshingAnnounce: 'اکنون در حال تازه‌سازی است.',
  randomContentPause: 'مکث چرخش',
  randomContentResume: 'ادامهٔ چرخش',
  exportButtonLabel: 'برون‌بری',
  knownDateDay: 'روز',
  knownDateMonth: 'ماه',
  knownDateYear: 'سال',
  exportFormatMenuLabel: 'فرمت {label}',
  mentionSuggestions: 'پیشنهادات',
  mentionResultCount: {
    one: '{count} پیشنهاد',
    other: '{count} پیشنهاد',
  },
  mentionResultPosition: 'پیشنهاد {current} از {total}',
  iconLoadError: 'نماد بارگیری نشد.',
  iconTooLarge: 'فایل نماد برای نمایش خیلی بزرگ است.',
  iconSanitizerMissing: 'برای نمایش ایمن این نماد، باید بستهٔ اختیاری «dompurify» نصب باشد.',
  tourSkip: 'رد کردن',
  tourDone: 'انجام شد',
  tourStepOf: 'مرحله {current} از {total}',
};

registerLyraLocale('fa', strings, { dir: 'rtl', name: 'فارسی' });
