// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `charts` slice of the zh-CN translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/charts/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/zh-CN/charts';` and reads nothing from it.
// `../zh-CN.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  chartCategory: '类别',
  chartTotal: '合计',
  chartAxisTotal: '{axis}合计',
  chartPrimaryAxis: '主坐标轴',
  chartSecondaryAxis: '次坐标轴',
  chartPointLabel: '第{n}个数据点',
  chartPointCoordinates: 'x：{x}，y：{y}',
  chartBubblePointCoordinates: 'x：{x}，y：{y}，半径：{radius}',
  chartLabeledPoint: '{label}：{coordinates}',
  chartTrendIncreasing: '上升',
  chartTrendDecreasing: '下降',
  chartTrendFlat: '持平',
  chartSummary: '{label}：{count}个值，范围从{min}到{max}，趋势{trend}',
  chartSeriesNoData: '{label}：无数据',
  chartSummaryWithData: '{type}图。{summaries}。',
  chartSummaryEmpty: '{type}图，无数据。',
  chartSummarySeparator: '。',
  chartData: '图表数据',
  chartDataSampled: '生成的数据表显示最多 1,000 条记录的样本。请提供自定义数据表以访问全部图表数据。',
  chartZoomUnavailable: '缩放不可用，但核心图表仍可用。',
  chartDataLabelsUnavailable: '数据标签不可用，但核心图表仍可用。',
  chartStackTotalsUnavailable: '堆叠总计不可用，但核心图表仍可用。',
  chartAnnotationsUnavailable: '图表注释不可用，但核心图表仍可用。',
  chartTypeLine: '折线',
  chartTypeBar: '柱状',
  chartTypeScatter: '散点',
  chartTypePie: '饼',
  chartTypeDoughnut: '环形',
  chartTypeRadar: '雷达',
  chartTypePolarArea: '极坐标区域',
  chartTypeBubble: '气泡',
  boxPlotSeriesSummary: '{label}：{count}个分布，中位数范围从{min}到{max}，中位数趋势{trend}',
  boxPlotSummaryWithData: '箱线图。{summaries}。',
  boxPlotSummaryEmpty: '箱线图，无数据。',
  boxPlotData: '箱线图数据',
  chartSeriesLabel: '系列',
  boxPlotMin: '最小值',
  boxPlotQ1: 'Q1',
  boxPlotMedian: '中位数',
  boxPlotQ3: 'Q3',
  boxPlotMax: '最大值',
  boxPlot: '箱线图',
  histogramFrequency: '频数',
  liteChartMarkSummary: '{series}，{label}：{value}（第{index}项，共{total}项）',
  liteChartBarLabel: '{series}，{label}：{value}',
  chartValuePercentageLabel: '{label}：{value}（{percentage}）',
  liteChartCustomMarkSummary: '{content}（第{index}项，共{total}项）',
  chartMissingLibrary: '此组件需要安装可选的 "chart.js" 包才能渲染图表。',
  boxPlotMissingLibrary: '此组件需要安装可选的箱线图扩展包才能渲染箱线图。',
};

registerLyraLocale('zh-CN', strings);
