// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `overlays` slice of the zh-CN translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/overlays/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/zh-CN/overlays';` and reads nothing from it.
// `../zh-CN.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: '评分',
  calloutAnnouncementWithContext: '{context}：{content}',
  closeWithContext: '关闭：{snippet}',
  closeWithTruncatedContext: '关闭：{snippet}…',
  toastContentIncomplete: '内容不完整的通知',
  toastOverflow: '未显示的通知：{count}条。',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Esc',
  kbdTabWord: 'Tab',
  kbdSpaceWord: '空格',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: '删除',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: '向上翻页',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: '向下翻页',
  kbdEnterWord: '回车',
  kbdBackspaceWord: '退格',
  kbdArrowUpWord: '向上箭头',
  kbdArrowDownWord: '向下箭头',
  kbdArrowLeftWord: '向左箭头',
  kbdArrowRightWord: '向右箭头',
  kbdPlusWord: '加号',
  kbdMinusWord: '减号',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('zh-CN', strings);
