// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `utility` slice of the zh-CN translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/utility/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/zh-CN/utility';` and reads nothing from it.
// `../zh-CN.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: '将 JSON 复制到剪贴板',
  circularReference: '循环引用',
  copyDiff: '复制差异',
  diffViewOldLabel: '原始',
  diffViewNewLabel: '修改后',
  diffViewHiddenLines: {
    other: '{count}行未更改',
  },
  diffViewTooLarge: '差异过大，无法显示。',
  jsonArray: '数组',
  jsonObject: '对象',
  jsonValue: '值',
  jsonCopyLabel: '复制{label}',
  jsonExpandLabel: '展开{label}',
  jsonCollapseLabel: '收起{label}',
  jsonItemCount: {
    other: '{count}项',
  },
  jsonKeyCount: {
    other: '{count}个键',
  },
  jsonViewerLimit: '仅显示和搜索前{count}个 JSON 节点及{depth}层嵌套。',
  pollPause: '暂停',
  pollResume: '继续',
  pollInactive: '未启用',
  pollRefreshing: '刷新中…',
  pollPaused: '已暂停',
  pollPausedAnnounce: '已暂停。',
  pollResumedAnnounce: '已继续。',
  pollRefreshingAnnounce: '正在刷新。',
  randomContentPause: '暂停轮换',
  randomContentResume: '继续轮换',
  exportButtonLabel: '导出',
  knownDateDay: '日',
  knownDateMonth: '月',
  knownDateYear: '年',
  exportFormatMenuLabel: '{label}格式',
  mentionSuggestions: '建议',
  mentionResultCount: {
    other: '{count}项建议',
  },
  mentionResultPosition: '第{current}项建议，共{total}项',
  iconLoadError: '图标加载失败。',
  iconTooLarge: '图标文件过大，无法显示。',
  iconSanitizerMissing: '此图标需要安装可选的 "dompurify" 包才能安全渲染。',
  tourSkip: '跳过',
  tourDone: '完成',
  tourStepOf: '第{current}步，共{total}步',
};

registerLyraLocale('zh-CN', strings);
