// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `charts` slice of the uk translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/charts/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/uk/charts';` and reads nothing from it.
// `../uk.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  chartCategory: 'Категорія',
  chartTotal: 'Усього',
  chartAxisTotal: '{axis} — усього',
  chartPrimaryAxis: 'Основна вісь',
  chartSecondaryAxis: 'Додаткова вісь',
  chartPointLabel: 'Точка {n}',
  chartPointCoordinates: 'x {x}, y {y}',
  chartBubblePointCoordinates: 'x {x}, y {y}, радіус {radius}',
  chartLabeledPoint: '{label}: {coordinates}',
  chartTrendIncreasing: 'зростання',
  chartTrendDecreasing: 'спадання',
  chartTrendFlat: 'без змін',
  chartSummary: '{label}: значень — {count}, діапазон від {min} до {max}, тенденція — {trend}',
  chartSeriesNoData: '{label}: немає даних',
  chartSummaryWithData: 'Діаграма типу {type}. {summaries}.',
  chartSummaryEmpty: 'Діаграма типу {type} без даних.',
  chartSummarySeparator: '. ',
  chartData: 'Дані діаграми',
  chartDataSampled: 'Згенерована таблиця даних містить вибірку з не більш як 1 000 записів. Щоб переглянути всі дані діаграми, надайте власну таблицю даних.',
  chartZoomUnavailable: 'Масштабування недоступне, але основна діаграма працює.',
  chartDataLabelsUnavailable: 'Підписи даних недоступні, але основна діаграма працює.',
  chartStackTotalsUnavailable: 'Підсумки стовпців недоступні, але основна діаграма працює.',
  chartAnnotationsUnavailable: 'Анотації діаграми недоступні, але основна діаграма працює.',
  chartTypeLine: 'Лінійна',
  chartTypeBar: 'Стовпчаста',
  chartTypeScatter: 'Точкова',
  chartTypePie: 'Кругова',
  chartTypeDoughnut: 'Кільцева',
  chartTypeRadar: 'Радарна',
  chartTypePolarArea: 'Полярна',
  chartTypeBubble: 'Бульбашкова',
  boxPlotSeriesSummary: '{label}: розподілів — {count}, діапазон медіан від {min} до {max}, тенденція медіани — {trend}',
  boxPlotSummaryWithData: 'Діаграма розмаху. {summaries}.',
  boxPlotSummaryEmpty: 'Діаграма розмаху без даних.',
  boxPlotData: 'Дані діаграми розмаху',
  chartSeriesLabel: 'Ряд',
  boxPlotMin: 'Мін.',
  boxPlotQ1: 'Q1',
  boxPlotMedian: 'Медіана',
  boxPlotQ3: 'Q3',
  boxPlotMax: 'Макс.',
  boxPlot: 'Діаграма розмаху',
  histogramFrequency: 'Частота',
  liteChartMarkSummary: '{series}, {label}: {value} ({index} із {total})',
  liteChartBarLabel: '{series}, {label}: {value}',
  chartValuePercentageLabel: '{label}: {value} ({percentage})',
  liteChartCustomMarkSummary: '{content} ({index} із {total})',
  chartMissingLibrary: 'Щоб відображати діаграми, потрібно встановити необов’язковий пакет "chart.js".',
  boxPlotMissingLibrary: 'Щоб відображати діаграми розмаху, потрібно встановити необов’язковий пакет для побудови діаграм розмаху.',
};

registerLyraLocale('uk', strings, { dir: 'ltr', name: 'Українська' });
