// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `layout` slice of the uk translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/layout/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/uk/layout';` and reads nothing from it.
// `../uk.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'карусель',
  carouselLabel: 'Карусель',
  carouselSlide: 'слайд',
  carouselSlidePosition: 'Слайд {index} із {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Слайди каруселі',
  carouselGoTo: 'Перейти до слайда {index}',
  scrollerLabel: 'Вміст із прокручуванням',
  scrollPrevious: 'Прокрутити назад',
  scrollNext: 'Прокрутити вперед',
  closeNavigation: 'Закрити навігацію',
  openNavigation: 'Відкрити навігацію',
  resizeNavigation: 'Змінити розмір навігації',
  appRailCollapse: 'Згорнути навігацію',
  appRailExpand: 'Розгорнути навігацію',
  appRailItemCollapse: 'Згорнути {label}',
  appRailItemExpand: 'Розгорнути {label}',
  resizeValuePercent: '{value} відсотків',
  commandPaletteLabel: 'Палітра команд',
  commandPalettePlaceholder: 'Пошук команд…',
  commandPaletteEmpty: 'Відповідних команд не знайдено.',
  commandPaletteResults: 'Команди',
  dockPanelCollapse: 'Згорнути панель',
  dockPanelExpand: 'Розгорнути панель',
  dockPanelResize: 'Змінити розмір панелі',
  responsivePanel: 'Панель',
  breadcrumb: 'Навігаційний ланцюжок',
  resizeDivider: 'Змінити розмір роздільника між панелями {a} і {b}',
  widgetFullscreenPanel: 'Повноекранна панель',
  widgetViewGroup: 'Вигляд панелі',
  widgetExitFullscreen: 'Вийти з повноекранного режиму',
  widgetExpandToFullscreen: 'Розгорнути на весь екран',
  widgetCollapse: 'Згорнути панель',
  widgetExpand: 'Розгорнути панель',
  skipToContent: 'Перейти до вмісту',
  dashboardGridLabel: 'Сітка панелі керування',
  dashboardCellCollisionRejected: 'Не вдалося розмістити {label}: ця комірка перекриває іншу.',
  dashboardCellMoved: '{label} переміщено до стовпця {x}, рядка {y}.',
  dashboardCellResized: 'Розмір {label} змінено: ширина {w}, висота {h}.',
  filterBarReset: 'Скинути фільтри',
  filterBarActiveFilters: 'Активні фільтри',
  drilldownDocuments: 'Документи',
  drilldownRuns: 'Запуски агента',
  drilldownEmpty: 'Елемент не вибрано',
  drilldownUntitledNode: 'Крок без назви',
  reorderMovePending: 'Очікується зміна порядку.',
  reorderMoveCancelled: 'Зміну порядку скасовано.',
};

registerLyraLocale('uk', strings, { dir: 'ltr', name: 'Українська' });
