// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'రేటింగ్',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'మూసివేయండి: {snippet}',
  closeWithTruncatedContext: 'మూసివేయండి: {snippet}…',
  toastContentIncomplete: 'అసంపూర్ణ విషయంతో నోటిఫికేషన్',
  toastOverflow: 'చూపించని నోటిఫికేషన్‌లు: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Space',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'పై బాణం',
  kbdArrowDownWord: 'కింది బాణం',
  kbdArrowLeftWord: 'ఎడమ బాణం',
  kbdArrowRightWord: 'కుడి బాణం',
  kbdPlusWord: 'ప్లస్',
  kbdMinusWord: 'మైనస్',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('te', strings);
