// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSONను క్లిప్‌బోర్డ్‌కు కాపీ చేయండి',
  circularReference: 'చక్రీయ సూచన',
  copyDiff: 'మార్పుల తేడాను కాపీ చేయండి',
  diffViewOldLabel: 'మునుపటిది',
  diffViewNewLabel: 'మార్చినది',
  diffViewHiddenLines: {
    one: '{count} మార్పులేని పంక్తి',
    other: '{count} మార్పులేని పంక్తులు',
  },
  diffViewTooLarge: 'తేడాను చూపించడానికి అది చాలా పెద్దది.',
  jsonArray: 'అర్రే',
  jsonObject: 'ఆబ్జెక్ట్',
  jsonValue: 'విలువ',
  jsonCopyLabel: '{label}ను కాపీ చేయండి',
  jsonExpandLabel: '{label}ను విస్తరించండి',
  jsonCollapseLabel: '{label}ను ముడుచండి',
  jsonItemCount: {
    one: '{count} అంశం',
    other: '{count} అంశాలు',
  },
  jsonKeyCount: {
    one: '{count} కీ',
    other: '{count} కీలు',
  },
  jsonViewerLimit: 'మొదటి {count} JSON నోడ్‌లు, గరిష్ఠంగా {depth} అంచెల లోతు మాత్రమే చూపించి వెతుకుతారు.',
  pollPause: 'తాత్కాలికంగా ఆపండి',
  pollResume: 'మళ్లీ ప్రారంభించండి',
  pollInactive: 'నిష్క్రియంగా ఉంది',
  pollRefreshing: 'తాజా చేస్తోంది…',
  pollPaused: 'ఆపివేశారు',
  pollPausedAnnounce: 'ఆపివేశారు.',
  pollResumedAnnounce: 'మళ్లీ ప్రారంభించారు.',
  pollRefreshingAnnounce: 'ఇప్పుడు తాజా చేస్తోంది.',
  randomContentPause: 'భ్రమణాన్ని ఆపండి',
  randomContentResume: 'భ్రమణాన్ని మళ్లీ ప్రారంభించండి',
  exportButtonLabel: 'ఎగుమతి చేయండి',
  knownDateDay: 'రోజు',
  knownDateMonth: 'నెల',
  knownDateYear: 'సంవత్సరం',
  exportFormatMenuLabel: '{label} ఫార్మాట్',
  mentionSuggestions: 'సూచనలు',
  mentionResultCount: {
    one: '{count} సూచన',
    other: '{count} సూచనలు',
  },
  mentionResultPosition: '{total}లో {current}వ సూచన',
  iconLoadError: 'చిహ్నాన్ని లోడ్ చేయలేకపోయాం.',
  iconTooLarge: 'చిహ్నం ఫైల్ చూపించడానికి చాలా పెద్దది.',
  iconSanitizerMissing: 'ఈ చిహ్నాన్ని సురక్షితంగా చూపించడానికి ఐచ్ఛిక "dompurify" ప్యాకేజీని ఇన్‌స్టాల్ చేయాలి.',
  tourSkip: 'దాటవేయండి',
  tourDone: 'పూర్తయింది',
  tourStepOf: '{total}లో {current}వ దశ',
};

registerLyraLocale('te', strings);
