// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Penilaian',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Tutup: {snippet}',
  closeWithTruncatedContext: 'Tutup: {snippet}…',
  toastContentIncomplete: 'Pemberitahuan dengan kandungan tidak lengkap',
  toastOverflow: '{count} pemberitahuan tidak dipaparkan.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Ruang',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Padam',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'Anak panah atas',
  kbdArrowDownWord: 'Anak panah bawah',
  kbdArrowLeftWord: 'Anak panah kiri',
  kbdArrowRightWord: 'Anak panah kanan',
  kbdPlusWord: 'Tambah',
  kbdMinusWord: 'Tolak',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('ms', strings);
