// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'કૅરોઉઝલ',
  carouselLabel: 'કૅરોઉઝલ',
  carouselSlide: 'સ્લાઇડ',
  carouselSlidePosition: '{total}માંથી સ્લાઇડ {index}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'કૅરોઉઝલની સ્લાઇડ્સ',
  carouselGoTo: 'સ્લાઇડ {index} પર જાઓ',
  scrollerLabel: 'સ્ક્રોલ કરી શકાય તેવી સામગ્રી',
  scrollPrevious: 'પાછળ સ્ક્રોલ કરો',
  scrollNext: 'આગળ સ્ક્રોલ કરો',
  closeNavigation: 'નેવિગેશન બંધ કરો',
  openNavigation: 'નેવિગેશન ખોલો',
  resizeNavigation: 'નેવિગેશનનું કદ બદલો',
  appRailCollapse: 'નેવિગેશન સંકુચિત કરો',
  appRailExpand: 'નેવિગેશન વિસ્તૃત કરો',
  appRailItemCollapse: '{label} સંકુચિત કરો',
  appRailItemExpand: '{label} વિસ્તૃત કરો',
  resizeValuePercent: '{value} ટકા',
  commandPaletteLabel: 'આદેશ પૅલેટ',
  commandPalettePlaceholder: 'આદેશો શોધો…',
  commandPaletteEmpty: 'મેળ ખાતો કોઈ આદેશ નથી.',
  commandPaletteResults: 'આદેશો',
  dockPanelCollapse: 'પૅનલ સંકુચિત કરો',
  dockPanelExpand: 'પૅનલ વિસ્તૃત કરો',
  dockPanelResize: 'પૅનલનું કદ બદલો',
  responsivePanel: 'પૅનલ',
  breadcrumb: 'બ્રેડક્રમ્બ',
  resizeDivider: 'પૅનલ {a} અને પૅનલ {b} વચ્ચેના વિભાજકનું કદ બદલો',
  widgetFullscreenPanel: 'પૂર્ણસ્ક્રીન પૅનલ',
  widgetViewGroup: 'પૅનલ દૃશ્ય',
  widgetExitFullscreen: 'પૂર્ણસ્ક્રીનમાંથી બહાર નીકળો',
  widgetExpandToFullscreen: 'પૂર્ણસ્ક્રીન સુધી વિસ્તૃત કરો',
  widgetCollapse: 'પૅનલ સંકુચિત કરો',
  widgetExpand: 'પૅનલ વિસ્તૃત કરો',
  skipToContent: 'સામગ્રી પર જાઓ',
  dashboardGridLabel: 'ડૅશબોર્ડ ગ્રીડ',
  dashboardCellCollisionRejected: '{label} ત્યાં મૂકી શકાતું નથી, કારણ કે તે બીજા સેલ પર ચઢી જાય છે.',
  dashboardCellMoved: '{label} કૉલમ {x}, પંક્તિ {y} પર ખસેડ્યું.',
  dashboardCellResized: '{label}ની પહોળાઈ {w} અને ઊંચાઈ {h} કરવામાં આવી.',
  filterBarReset: 'ફિલ્ટર ફરીથી સેટ કરો',
  filterBarActiveFilters: 'સક્રિય ફિલ્ટર',
  drilldownDocuments: 'દસ્તાવેજો',
  drilldownRuns: 'એજન્ટ રન',
  drilldownEmpty: 'કોઈ વસ્તુ પસંદ નથી',
  drilldownUntitledNode: 'શીર્ષક વિનાનું પગલું',
  reorderMovePending: 'ફરી ગોઠવવાનું બાકી છે.',
  reorderMoveCancelled: 'ફરી ગોઠવવાનું રદ થયું.',
  commandPaletteResultCount: {
    one: '{count} આદેશ',
    other: '{count} આદેશો',
  },
};

registerLyraLocale('gu', strings);
