// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'ngagharị onyonyo',
  carouselLabel: 'Ngagharị onyonyo',
  carouselSlide: 'onyonyo',
  carouselSlidePosition: 'Onyonyo {index} n’ime {total}',
  carouselSlideAnnouncement: 'Nọmba {position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Ihe ngosi ngagharị onyonyo',
  carouselGoTo: 'Gaa na onyonyo {index}',
  scrollerLabel: 'Ọdịnaya a pụrụ ịpịgharị',
  scrollPrevious: 'Pịgharịa azụ',
  scrollNext: 'Pịgharịa n’ihu',
  closeNavigation: 'Mechie nnyagharị',
  openNavigation: 'Mepee nnyagharị',
  resizeNavigation: 'Gbanwee nha nnyagharị',
  appRailCollapse: 'Kpọkọọ nnyagharị',
  appRailExpand: 'Mụbaa nnyagharị',
  appRailPin: 'Kpọchie nnyagharị n’ebe ọ nọ',
  appRailUnpin: 'Tọpụ nnyagharị n’ebe ọ nọ',
  appRailItemCollapse: 'Kpọkọọ {label}',
  appRailItemExpand: 'Mụbaa {label}',
  resizeValuePercent: '{value} pasent',
  commandPaletteLabel: 'Ndepụta iwu',
  commandPalettePlaceholder: 'Chọọ iwu…',
  commandPaletteEmpty: 'Enweghị iwu dabara.',
  commandPaletteResults: 'Iwu',
  dockPanelCollapse: 'Kpọkọọ panel',
  dockPanelExpand: 'Mụbaa panel',
  dockPanelResize: 'Gbanwee nha panel',
  responsivePanel: 'Ogwe',
  breadcrumb: 'Akara ụzọ',
  resizeDivider: 'Gbanwee nha nkewa panel {a} na panel {b}',
  widgetFullscreenPanel: 'Panel ihuenyo zuru ezu',
  widgetViewGroup: 'Nlele panel',
  widgetExitFullscreen: 'Pụọ na ihuenyo zuru ezu',
  widgetExpandToFullscreen: 'Mụbaa ka ọ bụrụ ihuenyo zuru ezu',
  widgetCollapse: 'Kpọkọọ panel',
  widgetExpand: 'Mụbaa panel',
  skipToContent: 'Mafee gaa n’ọdịnaya',
  dashboardGridLabel: 'Grid dashboard',
  dashboardCellCollisionRejected: 'Enweghị ike idowe {label} ebe ahụ n’ihi na ọ gafere sel ọzọ.',
  dashboardCellMoved: 'Ebugala {label} na kọlụm {x}, ahịrị {y}.',
  dashboardCellResized: 'Agbanweela nha {label} ka obosara ya bụrụ {w}, ịdị elu ya bụrụ {h}.',
  filterBarReset: 'Tọgharịa nzacha',
  filterBarActiveFilters: 'Nzacha na-arụ ọrụ',
  drilldownDocuments: 'Akwụkwọ',
  drilldownRuns: 'Ọrụ onye nnọchiteanya',
  drilldownEmpty: 'Ahọpụtaghị ihe',
  drilldownUntitledNode: 'Nzọụkwụ enweghị aha',
  reorderMovePending: 'A na-eche ịhazigharị usoro.',
  reorderMoveCancelled: 'Akagbuola ịhazigharị usoro.',
  commandPaletteResultCount: {
    other: '{count} nyere iwu',
  },
};

registerLyraLocale('ig', strings);
