// AUTO-GENERATED FILE. Do not edit by hand.
// Run `pnpm --filter @aceshooting/lyra-flags run generate` (scripts/generate-index.mjs) to
// regenerate after adding/removing/renaming a file in flags/.

/**
 * Lazy map of ISO 3166-1 alpha-2 (or territory) code -> *compact* (icon-scale WebP raster)
 * flag URL loader — a subset of FLAG_LOADERS, one entry per code that has a
 * flags/compact/<code>.webp. `flagUrl(code, { variant: 'compact' })` checks this map first,
 * falling back to FLAG_LOADERS (the standard vector) for a code with no compact variant. See
 * scripts/build-compact.mjs for how flags/compact/ is populated. Note the entries point at a
 * .webp asset, not a .svg — the compact tier is a raster (see build-compact.mjs for why).
 * @type {Record<string, () => Promise<string>>}
 */
export const FLAG_LOADERS_COMPACT = {
  ad: () => import('./compact/loaders/ad.js').then((m) => m.default),
  af: () => import('./compact/loaders/af.js').then((m) => m.default),
  ar: () => import('./compact/loaders/ar.js').then((m) => m.default),
  as: () => import('./compact/loaders/as.js').then((m) => m.default),
  bl: () => import('./compact/loaders/bl.js').then((m) => m.default),
  bm: () => import('./compact/loaders/bm.js').then((m) => m.default),
  bn: () => import('./compact/loaders/bn.js').then((m) => m.default),
  br: () => import('./compact/loaders/br.js').then((m) => m.default),
  bt: () => import('./compact/loaders/bt.js').then((m) => m.default),
  bz: () => import('./compact/loaders/bz.js').then((m) => m.default),
  cy: () => import('./compact/loaders/cy.js').then((m) => m.default),
  dm: () => import('./compact/loaders/dm.js').then((m) => m.default),
  do: () => import('./compact/loaders/do.js').then((m) => m.default),
  ec: () => import('./compact/loaders/ec.js').then((m) => m.default),
  eg: () => import('./compact/loaders/eg.js').then((m) => m.default),
  es: () => import('./compact/loaders/es.js').then((m) => m.default),
  fj: () => import('./compact/loaders/fj.js').then((m) => m.default),
  fk: () => import('./compact/loaders/fk.js').then((m) => m.default),
  gi: () => import('./compact/loaders/gi.js').then((m) => m.default),
  gq: () => import('./compact/loaders/gq.js').then((m) => m.default),
  gs: () => import('./compact/loaders/gs.js').then((m) => m.default),
  gt: () => import('./compact/loaders/gt.js').then((m) => m.default),
  gu: () => import('./compact/loaders/gu.js').then((m) => m.default),
  hr: () => import('./compact/loaders/hr.js').then((m) => m.default),
  ht: () => import('./compact/loaders/ht.js').then((m) => m.default),
  im: () => import('./compact/loaders/im.js').then((m) => m.default),
  io: () => import('./compact/loaders/io.js').then((m) => m.default),
  ir: () => import('./compact/loaders/ir.js').then((m) => m.default),
  je: () => import('./compact/loaders/je.js').then((m) => m.default),
  kh: () => import('./compact/loaders/kh.js').then((m) => m.default),
  ki: () => import('./compact/loaders/ki.js').then((m) => m.default),
  ky: () => import('./compact/loaders/ky.js').then((m) => m.default),
  kz: () => import('./compact/loaders/kz.js').then((m) => m.default),
  li: () => import('./compact/loaders/li.js').then((m) => m.default),
  lk: () => import('./compact/loaders/lk.js').then((m) => m.default),
  md: () => import('./compact/loaders/md.js').then((m) => m.default),
  me: () => import('./compact/loaders/me.js').then((m) => m.default),
  mp: () => import('./compact/loaders/mp.js').then((m) => m.default),
  ms: () => import('./compact/loaders/ms.js').then((m) => m.default),
  mt: () => import('./compact/loaders/mt.js').then((m) => m.default),
  mx: () => import('./compact/loaders/mx.js').then((m) => m.default),
  nf: () => import('./compact/loaders/nf.js').then((m) => m.default),
  ni: () => import('./compact/loaders/ni.js').then((m) => m.default),
  om: () => import('./compact/loaders/om.js').then((m) => m.default),
  pf: () => import('./compact/loaders/pf.js').then((m) => m.default),
  pm: () => import('./compact/loaders/pm.js').then((m) => m.default),
  pn: () => import('./compact/loaders/pn.js').then((m) => m.default),
  pt: () => import('./compact/loaders/pt.js').then((m) => m.default),
  py: () => import('./compact/loaders/py.js').then((m) => m.default),
  rs: () => import('./compact/loaders/rs.js').then((m) => m.default),
  sa: () => import('./compact/loaders/sa.js').then((m) => m.default),
  sh: () => import('./compact/loaders/sh.js').then((m) => m.default),
  sm: () => import('./compact/loaders/sm.js').then((m) => m.default),
  sv: () => import('./compact/loaders/sv.js').then((m) => m.default),
  sx: () => import('./compact/loaders/sx.js').then((m) => m.default),
  sz: () => import('./compact/loaders/sz.js').then((m) => m.default),
  tc: () => import('./compact/loaders/tc.js').then((m) => m.default),
  tm: () => import('./compact/loaders/tm.js').then((m) => m.default),
  ug: () => import('./compact/loaders/ug.js').then((m) => m.default),
  uy: () => import('./compact/loaders/uy.js').then((m) => m.default),
  va: () => import('./compact/loaders/va.js').then((m) => m.default),
  vg: () => import('./compact/loaders/vg.js').then((m) => m.default),
  vi: () => import('./compact/loaders/vi.js').then((m) => m.default),
  yt: () => import('./compact/loaders/yt.js').then((m) => m.default),
  zm: () => import('./compact/loaders/zm.js').then((m) => m.default),
};
