// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `layout` slice of the pt-BR translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/layout/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/pt-BR/layout';` and reads nothing from it.
// `../pt-BR.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'carrossel',
  carouselLabel: 'Carrossel',
  carouselSlide: 'slide',
  carouselSlidePosition: 'Slide {index} de {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Slides do carrossel',
  carouselGoTo: 'Ir para o slide {index}',
  scrollerLabel: 'Conteúdo rolável',
  scrollPrevious: 'Rolar para trás',
  scrollNext: 'Rolar para frente',
  closeNavigation: 'Fechar a navegação',
  openNavigation: 'Abrir a navegação',
  resizeNavigation: 'Redimensionar a navegação',
  appRailCollapse: 'Recolher a navegação',
  appRailExpand: 'Expandir a navegação',
  appRailItemCollapse: 'Recolher {label}',
  appRailItemExpand: 'Expandir {label}',
  resizeValuePercent: '{value} por cento',
  commandPaletteLabel: 'Paleta de comandos',
  commandPalettePlaceholder: 'Pesquisar comandos…',
  commandPaletteEmpty: 'Nenhum comando correspondente.',
  commandPaletteResults: 'Comandos',
  dockPanelCollapse: 'Recolher o painel',
  dockPanelExpand: 'Expandir o painel',
  dockPanelResize: 'Redimensionar o painel',
  responsivePanel: 'Painel',
  breadcrumb: 'Trilha de navegação',
  resizeDivider: 'Redimensionar o divisor entre o painel {a} e o painel {b}',
  widgetFullscreenPanel: 'Painel em tela cheia',
  widgetViewGroup: 'Modo de exibição do painel',
  widgetExitFullscreen: 'Sair da tela cheia',
  widgetExpandToFullscreen: 'Expandir para tela cheia',
  widgetCollapse: 'Recolher o painel',
  widgetExpand: 'Expandir o painel',
  skipToContent: 'Pular para o conteúdo',
  dashboardGridLabel: 'Grade do painel',
  dashboardCellCollisionRejected: 'Não é possível posicionar {label} aí porque sobrepõe outra célula.',
  dashboardCellMoved: '{label} movido para a coluna {x}, linha {y}.',
  dashboardCellResized: '{label} redimensionado para {w} de largura e {h} de altura.',
  filterBarReset: 'Redefinir os filtros',
  filterBarActiveFilters: 'Filtros ativos',
  drilldownDocuments: 'Documentos',
  drilldownRuns: 'Execuções do agente',
  drilldownEmpty: 'Nenhum item selecionado',
  drilldownUntitledNode: 'Etapa sem título',
  reorderMovePending: 'Reordenação pendente.',
  reorderMoveCancelled: 'Reordenação cancelada.',
};

registerLyraLocale('pt-BR', strings);
