// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Avaliação',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Fechar: {snippet}',
  closeWithTruncatedContext: 'Fechar: {snippet}…',
  toastContentIncomplete: 'Notificação com conteúdo incompleto',
  toastOverflow: 'Notificações não exibidas: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Espaço',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'Seta para cima',
  kbdArrowDownWord: 'Seta para baixo',
  kbdArrowLeftWord: 'Seta para a esquerda',
  kbdArrowRightWord: 'Seta para a direita',
  kbdPlusWord: 'Mais',
  kbdMinusWord: 'Menos',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('pt-BR', strings);
