// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Бағалау',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Жабу: {snippet}',
  closeWithTruncatedContext: 'Жабу: {snippet}…',
  toastContentIncomplete: 'Мазмұны толық емес хабарландыру',
  toastOverflow: 'Көрсетілмеген хабарландырулар: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Бос орын',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'Жоғары көрсеткі',
  kbdArrowDownWord: 'Төмен көрсеткі',
  kbdArrowLeftWord: 'Сол көрсеткі',
  kbdArrowRightWord: 'Оң көрсеткі',
  kbdPlusWord: 'Плюс',
  kbdMinusWord: 'Минус',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('kk', strings);
