// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON-ды алмасу буферіне көшіру',
  circularReference: 'Циклдік сілтеме',
  copyDiff: 'Айырмашылықты көшіру',
  diffViewOldLabel: 'Бастапқы',
  diffViewNewLabel: 'Өзгертілген',
  diffViewHiddenLines: {
    one: '{count} өзгермеген жол',
    other: '{count} өзгермеген жол',
  },
  diffViewTooLarge: 'Айырмашылық көрсету үшін тым үлкен.',
  jsonArray: 'массив',
  jsonObject: 'нысан',
  jsonValue: 'мән',
  jsonCopyLabel: 'Көшіру: {label}',
  jsonExpandLabel: 'Жаю: {label}',
  jsonCollapseLabel: 'Жию: {label}',
  jsonItemCount: {
    one: '{count} элемент',
    other: '{count} элемент',
  },
  jsonKeyCount: {
    one: '{count} кілт',
    other: '{count} кілт',
  },
  jsonViewerLimit: 'Тек алғашқы {count} JSON түйіні және {depth} кірістіру деңгейі көрсетіледі және ізделеді.',
  pollPause: 'Кідірту',
  pollResume: 'Жалғастыру',
  pollRefresh: 'Қазір жаңартыңыз',
  pollInactive: 'Белсенді емес',
  pollRefreshing: 'Жаңартылуда…',
  pollPaused: 'Кідіртілді',
  pollPausedAnnounce: 'Кідіртілді.',
  pollResumedAnnounce: 'Жалғастырылды.',
  pollRefreshingAnnounce: 'Қазір жаңартылуда.',
  randomContentPause: 'Ауысуды кідірту',
  randomContentResume: 'Ауысуды жалғастыру',
  randomContentNext: 'Басқасын көрсету',
  exportButtonLabel: 'Экспорттау',
  knownDateDay: 'Күн',
  knownDateMonth: 'Ай',
  knownDateYear: 'Жыл',
  exportFormatMenuLabel: 'Пішім: {label}',
  mentionSuggestions: 'Ұсыныстар',
  mentionResultCount: {
    one: '{count} ұсыныс',
    other: '{count} ұсыныс',
  },
  mentionResultPosition: 'Ұсыныс {current}, барлығы {total}',
  iconLoadError: 'Белгішені жүктеу мүмкін болмады.',
  iconTooLarge: 'Белгіше файлы көрсету үшін тым үлкен.',
  iconSanitizerMissing: 'Бұл белгішені қауіпсіз көрсету үшін қосымша «dompurify» бумасын орнату қажет.',
  tourSkip: 'Өткізіп жіберу',
  tourDone: 'Дайын',
  tourStepOf: 'Қадам {current}, барлығы {total}',
  mentionMoreResults: {
    one: 'тағы {count} ұсыныс',
    other: 'тағы {count} ұсыныс',
  },
};

registerLyraLocale('kk', strings);
