// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `charts` slice of the ro translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/charts/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/ro/charts';` and reads nothing from it.
// `../ro.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  chartCategory: 'Categorie',
  chartTotal: 'Total',
  chartAxisTotal: 'Total {axis}',
  chartPrimaryAxis: 'Axa principală',
  chartSecondaryAxis: 'Axa secundară',
  chartPointLabel: 'Punctul {n}',
  chartPointCoordinates: 'x {x}, y {y}',
  chartBubblePointCoordinates: 'x {x}, y {y}, rază {radius}',
  chartLabeledPoint: '{label}: {coordinates}',
  chartTrendIncreasing: 'crescătoare',
  chartTrendDecreasing: 'descrescătoare',
  chartTrendFlat: 'constantă',
  chartSummary: '{label}: {count} valori, interval de la {min} la {max}, tendință {trend}',
  chartSeriesNoData: '{label}: fără date',
  chartSummaryWithData: 'Grafic de tip {type}. {summaries}.',
  chartSummaryEmpty: 'Grafic de tip {type} fără date.',
  chartSummarySeparator: '. ',
  chartData: 'Datele graficului',
  chartDataSampled: 'Tabelul de date generat afișează un eșantion de până la 1.000 de înregistrări. Furnizează un tabel de date personalizat pentru a accesa toate datele graficului.',
  chartZoomUnavailable: 'Zoom-ul nu este disponibil, dar graficul de bază rămâne disponibil.',
  chartDataLabelsUnavailable: 'Etichetele de date nu sunt disponibile, dar graficul de bază rămâne disponibil.',
  chartStackTotalsUnavailable: 'Totalurile stivuite nu sunt disponibile, dar graficul de bază rămâne disponibil.',
  chartAnnotationsUnavailable: 'Adnotările graficului nu sunt disponibile, dar graficul de bază rămâne disponibil.',
  chartTypeLine: 'Linie',
  chartTypeBar: 'Bare',
  chartTypeScatter: 'Dispersie',
  chartTypePie: 'Circular',
  chartTypeDoughnut: 'Inelar',
  chartTypeRadar: 'Radar',
  chartTypePolarArea: 'Arie polară',
  chartTypeBubble: 'Bule',
  boxPlotSeriesSummary: '{label}: {count} distribuții, interval median de la {min} la {max}, tendință mediană {trend}',
  boxPlotSummaryWithData: 'Box plot. {summaries}.',
  boxPlotSummaryEmpty: 'Box plot fără date.',
  boxPlotData: 'Datele box plot-ului',
  chartSeriesLabel: 'Serie',
  boxPlotMin: 'Min',
  boxPlotQ1: 'Q1',
  boxPlotMedian: 'Mediană',
  boxPlotQ3: 'Q3',
  boxPlotMax: 'Max',
  boxPlot: 'Box plot',
  histogramFrequency: 'Frecvență',
  liteChartMarkSummary: '{series}, {label}: {value} ({index} din {total})',
  liteChartBarLabel: '{series}, {label}: {value}',
  chartValuePercentageLabel: '{label}: {value} ({percentage})',
  liteChartCustomMarkSummary: '{content} ({index} din {total})',
  chartMissingLibrary: 'Această componentă necesită pachetul opțional „chart.js” instalat pentru a afișa grafice.',
  boxPlotMissingLibrary: 'Această componentă necesită pachetul opțional pentru diagrame box plot instalat pentru a le afișa.',
};

registerLyraLocale('ro', strings);
