// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'carusel',
  carouselLabel: 'Carusel',
  carouselSlide: 'diapozitiv',
  carouselSlidePosition: 'Diapozitivul {index} din {total}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'Diapozitivele caruselului',
  carouselGoTo: 'Salt la diapozitivul {index}',
  scrollerLabel: 'Conținut derulabil',
  scrollPrevious: 'Derulează înapoi',
  scrollNext: 'Derulează înainte',
  closeNavigation: 'Închide navigarea',
  openNavigation: 'Deschide navigarea',
  resizeNavigation: 'Redimensionează navigarea',
  appRailCollapse: 'Restrânge navigarea',
  appRailExpand: 'Extinde navigarea',
  appRailItemCollapse: 'Restrânge {label}',
  appRailItemExpand: 'Extinde {label}',
  resizeValuePercent: '{value} la sută',
  commandPaletteLabel: 'Paletă de comenzi',
  commandPalettePlaceholder: 'Caută comenzi…',
  commandPaletteEmpty: 'Nicio comandă corespunzătoare.',
  commandPaletteResults: 'Comenzi',
  dockPanelCollapse: 'Restrânge panoul',
  dockPanelExpand: 'Extinde panoul',
  dockPanelResize: 'Redimensionează panoul',
  responsivePanel: 'Panou',
  breadcrumb: 'Fir Ariadna',
  resizeDivider: 'Separator de redimensionare între panoul {a} și panoul {b}',
  widgetFullscreenPanel: 'Panou pe tot ecranul',
  widgetViewGroup: 'Vizualizare panou',
  widgetExitFullscreen: 'Ieșire din ecran complet',
  widgetExpandToFullscreen: 'Extinde pe tot ecranul',
  widgetCollapse: 'Restrânge panoul',
  widgetExpand: 'Extinde panoul',
  skipToContent: 'Salt la conținut',
  dashboardGridLabel: 'Grila tabloului de bord',
  dashboardCellCollisionRejected: '{label} nu poate fi plasat aici pentru că se suprapune cu altă celulă.',
  dashboardCellMoved: '{label} a fost deplasat la coloana {x}, rândul {y}.',
  dashboardCellResized: '{label} a fost redimensionat la lățimea {w}, înălțimea {h}.',
  filterBarReset: 'Resetează filtrele',
  filterBarActiveFilters: 'Filtre active',
  drilldownDocuments: 'Documente',
  drilldownRuns: 'Execuții de agent',
  drilldownEmpty: 'Niciun element selectat',
  drilldownUntitledNode: 'Pas fără titlu',
  reorderMovePending: 'Reordonare în așteptare.',
  reorderMoveCancelled: 'Reordonare anulată.',
  commandPaletteResultCount: {
    one: '{count} comandă',
    few: '{count} comenzi',
    other: '{count} de comenzi',
  },
};

registerLyraLocale('ro', strings);
