// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'Copiază JSON în clipboard',
  circularReference: 'Referință circulară',
  copyDiff: 'Copiază diff-ul',
  diffViewOldLabel: 'Original',
  diffViewNewLabel: 'Modificat',
  diffViewHiddenLines: {
    one: '{count} linie neschimbată',
    few: '{count} linii neschimbate',
    other: '{count} de linii neschimbate',
  },
  diffViewTooLarge: 'Diff-ul este prea mare pentru a fi afișat.',
  jsonArray: 'tablou',
  jsonObject: 'obiect',
  jsonValue: 'valoare',
  jsonCopyLabel: 'Copiază {label}',
  jsonExpandLabel: 'Extinde {label}',
  jsonCollapseLabel: 'Restrânge {label}',
  jsonItemCount: {
    one: '{count} element',
    few: '{count} elemente',
    other: '{count} de elemente',
  },
  jsonKeyCount: {
    one: '{count} cheie',
    few: '{count} chei',
    other: '{count} de chei',
  },
  jsonViewerLimit: 'Sunt afișate și căutate doar primele {count} noduri JSON și {depth} niveluri de imbricare.',
  pollPause: 'Pune pe pauză',
  pollResume: 'Reia',
  pollRefresh: 'Actualizează acum',
  pollInactive: 'Inactiv',
  pollRefreshing: 'Se actualizează…',
  pollPaused: 'Suspendat',
  pollPausedAnnounce: 'Suspendat.',
  pollResumedAnnounce: 'Reluat.',
  pollRefreshingAnnounce: 'Se actualizează acum.',
  randomContentPause: 'Întrerupe rotația',
  randomContentResume: 'Continuă rotația',
  randomContentNext: 'Afișează altul',
  exportButtonLabel: 'Exportă',
  knownDateDay: 'Zi',
  knownDateMonth: 'Lună',
  knownDateYear: 'An',
  exportFormatMenuLabel: 'Format {label}',
  mentionSuggestions: 'Sugestii',
  mentionResultCount: {
    one: '{count} sugestie',
    few: '{count} sugestii',
    other: '{count} de sugestii',
  },
  mentionResultPosition: 'Sugestia {current} din {total}',
  iconLoadError: 'Încărcarea pictogramei a eșuat.',
  iconTooLarge: 'Fișierul pictogramei este prea mare pentru a fi afișat.',
  iconSanitizerMissing: 'Această pictogramă necesită pachetul opțional „dompurify” instalat pentru a fi afișată în siguranță.',
  tourSkip: 'Omite',
  tourDone: 'Terminat',
  tourStepOf: 'Pasul {current} din {total}',
};

registerLyraLocale('ro', strings);
