// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `utility` slice of the ro translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/utility/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/ro/utility';` and reads nothing from it.
// `../ro.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'Copiază JSON în clipboard',
  circularReference: 'Referință circulară',
  copyDiff: 'Copiază diff-ul',
  diffViewOldLabel: 'Original',
  diffViewNewLabel: 'Modificat',
  diffViewHiddenLines: {
    one: '{count} linie neschimbată',
    few: '{count} linii neschimbate',
    other: '{count} de linii neschimbate',
  },
  diffViewTooLarge: 'Diff-ul este prea mare pentru a fi afișat.',
  jsonArray: 'tablou',
  jsonObject: 'obiect',
  jsonValue: 'valoare',
  jsonCopyLabel: 'Copiază {label}',
  jsonExpandLabel: 'Extinde {label}',
  jsonCollapseLabel: 'Restrânge {label}',
  jsonItemCount: {
    one: '{count} element',
    few: '{count} elemente',
    other: '{count} de elemente',
  },
  jsonKeyCount: {
    one: '{count} cheie',
    few: '{count} chei',
    other: '{count} de chei',
  },
  jsonViewerLimit: 'Sunt afișate și căutate doar primele {count} noduri JSON și {depth} niveluri de imbricare.',
  pollPause: 'Pune pe pauză',
  pollResume: 'Reia',
  pollInactive: 'Inactiv',
  pollRefreshing: 'Se actualizează…',
  pollPaused: 'Suspendat',
  pollPausedAnnounce: 'Suspendat.',
  pollResumedAnnounce: 'Reluat.',
  pollRefreshingAnnounce: 'Se actualizează acum.',
  randomContentPause: 'Întrerupe rotația',
  randomContentResume: 'Continuă rotația',
  exportButtonLabel: 'Exportă',
  knownDateDay: 'Zi',
  knownDateMonth: 'Lună',
  knownDateYear: 'An',
  exportFormatMenuLabel: 'Format {label}',
  mentionSuggestions: 'Sugestii',
  mentionResultCount: {
    one: '{count} sugestie',
    few: '{count} sugestii',
    other: '{count} de sugestii',
  },
  mentionResultPosition: 'Sugestia {current} din {total}',
  iconLoadError: 'Încărcarea pictogramei a eșuat.',
  iconTooLarge: 'Fișierul pictogramei este prea mare pentru a fi afișat.',
  iconSanitizerMissing: 'Această pictogramă necesită pachetul opțional „dompurify” instalat pentru a fi afișată în siguranță.',
  tourSkip: 'Omite',
  tourDone: 'Terminat',
  tourStepOf: 'Pasul {current} din {total}',
};

registerLyraLocale('ro', strings);
