// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON کلیپ‌بورډ ته کاپي کول',
  circularReference: 'دوراني حواله',
  copyDiff: 'توپیر کاپي کول',
  diffViewOldLabel: 'اصلي',
  diffViewNewLabel: 'بدل شوی',
  diffViewHiddenLines: {
    one: '{count} نه‌بدل شوې کرښه',
    other: '{count} نه‌بدلې شوې کرښې',
  },
  diffViewTooLarge: 'توپیر د ښودلو لپاره ډېر لوی دی.',
  jsonArray: 'لړۍ',
  jsonObject: 'څیز',
  jsonValue: 'ارزښت',
  jsonCopyLabel: '{label} کاپي کول',
  jsonExpandLabel: '{label} غځول',
  jsonCollapseLabel: '{label} راټولول',
  jsonItemCount: {
    one: '{count} توکی',
    other: '{count} توکي',
  },
  jsonKeyCount: {
    one: '{count} کیلي',
    other: '{count} کیلي',
  },
  jsonViewerLimit: 'یوازې لومړي {count} JSON غوټې او د ځالې {depth} کچې ښودل کېږي او لټول کېږي.',
  pollPause: 'ځنډول',
  pollResume: 'بیا پیلول',
  pollRefresh: 'اوس تازه کړئ',
  pollInactive: 'غیرفعال',
  pollRefreshing: 'تازه کېږي…',
  pollPaused: 'ځنډول شوی',
  pollPausedAnnounce: 'ځنډول شو.',
  pollResumedAnnounce: 'بیا پیل شو.',
  pollRefreshingAnnounce: 'اوس تازه کېږي.',
  randomContentPause: 'تاوول ځنډول',
  randomContentResume: 'تاوول بیا پیلول',
  randomContentNext: 'بل وښايه',
  exportButtonLabel: 'صادرول',
  knownDateDay: 'ورځ',
  knownDateMonth: 'میاشت',
  knownDateYear: 'کال',
  exportFormatMenuLabel: 'د {label} بڼه',
  mentionSuggestions: 'وړاندیزونه',
  mentionResultCount: {
    one: '{count} وړاندیز',
    other: '{count} وړاندیزونه',
  },
  mentionResultPosition: 'له {total} څخه وړاندیز {current}',
  iconLoadError: 'نښه (آیکن) نه شوه راوړل کېدای.',
  iconTooLarge: 'د نښې دوتنه د ښودلو لپاره ډېره لویه ده.',
  iconSanitizerMissing: 'د دې نښې د خوندي ښودلو لپاره د "dompurify" اختیاري بسته باید نصب شي.',
  tourSkip: 'پرېښودل',
  tourDone: 'بشپړ',
  tourStepOf: 'له {total} څخه پړاو {current}',
  mentionMoreResults: {
    one: '{count} نور وړاندیز',
    other: '{count} نور وړاندیزونه',
  },
};

registerLyraLocale('ps', strings, { dir: 'rtl', name: 'پښتو' });
