// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'Sadarkaa',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'Cufi: {snippet}',
  closeWithTruncatedContext: 'Cufi: {snippet}…',
  toastContentIncomplete: 'Beeksisa qabiyyee guutuu hin qabne',
  toastOverflow: 'Beeksisawwan hin agarsiifamne: {count}.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape',
  kbdTabWord: 'Tab',
  kbdSpaceWord: 'Space',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete',
  kbdHomeWord: 'Home',
  kbdEndWord: 'End',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down',
  kbdEnterWord: 'Enter',
  kbdBackspaceWord: 'Backspace',
  kbdArrowUpWord: 'Xiyya ol',
  kbdArrowDownWord: 'Xiyya gadi',
  kbdArrowLeftWord: 'Xiyya bitaa',
  kbdArrowRightWord: 'Xiyya mirgaa',
  kbdPlusWord: 'Dabalata',
  kbdMinusWord: 'Hir\'ina',
  kbdCommandWord: 'Command',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control',
  kbdOptionWord: 'Option',
  kbdAltWord: 'Alt',
  kbdShiftWord: 'Shift',
};

registerLyraLocale('om', strings);
