// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON gara galmee waraqaatti garagalchi',
  circularReference: 'Wabii marsaa',
  copyDiff: 'Garaagarummaa garagalchi',
  diffViewOldLabel: 'Kan duraa',
  diffViewNewLabel: 'Kan fooyya\'e',
  diffViewHiddenLines: {
    one: '{count} sarara hin jijjiiramne',
    other: '{count} sarara hin jijjiiramne',
  },
  diffViewTooLarge: 'Garaagarummaan agarsiisuuf baay\'ee guddaa dha.',
  jsonArray: 'tarree',
  jsonObject: 'wantaa',
  jsonValue: 'gatii',
  jsonCopyLabel: '{label} garagalchi',
  jsonExpandLabel: '{label} bal\'isi',
  jsonCollapseLabel: '{label} qabi',
  jsonItemCount: {
    one: 'qaama {count}',
    other: 'qaamota {count}',
  },
  jsonKeyCount: {
    one: 'furtuu {count}',
    other: 'furtuu {count}',
  },
  jsonViewerLimit: 'Qoodni JSON jalqabaa {count} fi sadarkaawwan wal keessa galuu {depth} qofa agarsiifamu, barbaadamus.',
  pollPause: 'Dhaabi',
  pollResume: 'Itti fufi',
  pollRefresh: 'Amma haaromsi',
  pollInactive: 'Hojii irra hin jiru',
  pollRefreshing: 'Amma haaromsamaa jira…',
  pollPaused: 'Dhaabbateera',
  pollPausedAnnounce: 'Dhaabbateera.',
  pollResumedAnnounce: 'Itti fufeera.',
  pollRefreshingAnnounce: 'Amma haaromsamaa jira.',
  randomContentPause: 'Naanna\'uu dhaabi',
  randomContentResume: 'Naanna\'uu itti fufi',
  randomContentNext: 'Kan biraa agarsiisi',
  exportButtonLabel: 'Ala baasi',
  knownDateDay: 'Guyyaa',
  knownDateMonth: 'Ji\'a',
  knownDateYear: 'Waggaa',
  exportFormatMenuLabel: 'Bifa {label}',
  mentionSuggestions: 'Yaada dhiyaate',
  mentionResultCount: {
    one: 'yaada {count}',
    other: 'yaada {count}',
  },
  mentionResultPosition: 'Yaada {current} keessaa {total}',
  iconLoadError: 'Mallattoon fe\'amuu hin dandeenye.',
  iconTooLarge: 'Faayilli mallattoo agarsiisuuf baay\'ee guddaa dha.',
  iconSanitizerMissing: 'Mallattoon kun nageenyaan agarsiifamuuf paakeejii filannoo "dompurify" fe\'amee qabaachuu qaba.',
  tourSkip: 'Darbii',
  tourDone: 'Xumurame',
  tourStepOf: 'Tarkaanfii {current} keessaa {total}',
  mentionMoreResults: {
    one: '{count} yaada dabalataa',
    other: '{count} yaada dabalataa',
  },
};

registerLyraLocale('om', strings);
