/** English fallbacks for the experimental document editor. Applications may override these
 * through the element's inherited `strings` property. */
export const DOCX_EDITOR_STRINGS = Object.freeze({
  docxEditorLabel: 'Document editor',
  docxEditorNew: 'New',
  docxEditorOpen: 'Open',
  docxEditorSave: 'Save',
  docxEditorBold: 'Bold',
  docxEditorItalic: 'Italic',
  docxEditorUnderline: 'Underline',
  docxEditorUndo: 'Undo',
  docxEditorRedo: 'Redo',
  docxEditorUntitled: 'Untitled document',
  docxEditorIdle: 'Open a document or create a new one.',
  docxEditorOpening: 'Opening document…',
  docxEditorReady: 'Document ready',
  docxEditorUnsaved: 'Unsaved changes',
  docxEditorSaving: 'Saving document…',
  docxEditorError: 'The document could not be opened or saved. Try again or choose another DOCX file.',
  docxEditorDisconnected: 'The editor was disconnected. Open the document again to continue.',
  docxEditorShortcut: 'Press Alt+F10 to reach the toolbar.',
  docxEditorDiscardQuestion: 'Discard unsaved changes?',
  docxEditorDiscard: 'Discard changes',
  docxEditorKeep: 'Keep editing',
  docxEditorFormatting: 'Document formatting',
  docxEditorParagraphStyle: 'Paragraph style',
  docxEditorAlignment: 'Alignment',
  docxEditorAlignLeft: 'Align left',
  docxEditorAlignCenter: 'Center',
  docxEditorAlignRight: 'Align right',
  docxEditorAlignJustify: 'Justify',
  docxEditorLists: 'Lists',
  docxEditorBullets: 'Bulleted list',
  docxEditorNumbering: 'Numbered list',
  docxEditorFontFamily: 'Font family',
  docxEditorFontSize: 'Font size in points',
  docxEditorTextColor: 'Choose text color',
  docxEditorColorUnknown: 'Current color unavailable',
  docxEditorAutomaticColor: 'Automatic color',
  docxEditorLink: 'Link',
  docxEditorLinkUrl: 'Link URL',
  docxEditorLinkHint: 'Use an https:// URL, a mailto: link, or a #bookmark.',
  docxEditorLinkText: 'Link text (optional)',
  docxEditorApplyLink: 'Apply link',
  docxEditorRemoveLink: 'Remove link',
  docxEditorCancel: 'Cancel',
  docxEditorFind: 'Find and replace',
  docxEditorFindQuery: 'Find text',
  docxEditorFindSubmit: 'Find',
  docxEditorMatchCase: 'Match case',
  docxEditorWholeWord: 'Whole words',
  docxEditorFindCount: 'Matches: {count}',
  docxEditorFindTruncated: 'Results limited to the first 100 matches.',
  docxEditorPrevious: 'Previous match',
  docxEditorNext: 'Next match',
  docxEditorReplacement: 'Replace with',
  docxEditorReplace: 'Replace this match',
  docxEditorReplaced: 'Match replaced',
  docxEditorEditUnavailable: 'This edit is unavailable for the current selection or document.',
});
