/** English fallbacks for the experimental document editor. Applications may override these
 * through the element's inherited `strings` property. */
export const DOCX_EDITOR_STRINGS = Object.freeze({
  docxEditorLabel: 'Document editor',
  docxEditorNew: 'New',
  docxEditorOpen: 'Open',
  docxEditorSave: 'Save',
  docxEditorBold: 'Bold',
  docxEditorItalic: 'Italic',
  docxEditorUnderline: 'Underline',
  docxEditorUndo: 'Undo',
  docxEditorRedo: 'Redo',
  docxEditorUntitled: 'Untitled document',
  docxEditorIdle: 'Open a document or create a new one.',
  docxEditorOpening: 'Opening document…',
  docxEditorReady: 'Document ready',
  docxEditorUnsaved: 'Unsaved changes',
  docxEditorSaving: 'Saving document…',
  docxEditorError: 'The document could not be opened or saved. Try again or choose another DOCX file.',
  docxEditorDisconnected: 'The editor was disconnected. Open the document again to continue.',
  docxEditorShortcut: 'Press Alt+F10 to reach the toolbar.',
  docxEditorDiscardQuestion: 'Discard unsaved changes?',
  docxEditorDiscard: 'Discard changes',
  docxEditorKeep: 'Keep editing',
  docxEditorFormatting: 'Document formatting',
  docxEditorParagraphStyle: 'Paragraph style',
  docxEditorAlignment: 'Alignment',
  docxEditorAlignLeft: 'Align left',
  docxEditorAlignCenter: 'Center',
  docxEditorAlignRight: 'Align right',
  docxEditorAlignJustify: 'Justify',
  docxEditorLists: 'Lists',
  docxEditorBullets: 'Bulleted list',
  docxEditorNumbering: 'Numbered list',
  docxEditorFontFamily: 'Font family',
  docxEditorFontSize: 'Font size in points',
  docxEditorTextColor: 'Choose text color',
  docxEditorColorUnknown: 'Current color unavailable',
  docxEditorAutomaticColor: 'Automatic color',
  docxEditorLink: 'Link',
  docxEditorLinkUrl: 'Link URL',
  docxEditorLinkHint: 'Use an https:// URL, a mailto: link, or a #bookmark.',
  docxEditorLinkText: 'Link text (optional)',
  docxEditorApplyLink: 'Apply link',
  docxEditorRemoveLink: 'Remove link',
  docxEditorCancel: 'Cancel',
  docxEditorTable: 'Table',
  docxEditorInsertTable: 'Insert table',
  docxEditorTableRows: 'Rows',
  docxEditorTableColumns: 'Columns',
  docxEditorTableSizeHint: 'Enter a whole number from 1 to 20 for each dimension.',
  docxEditorTableStale: 'The document or selection changed. Close this dialog and choose where to insert the table again.',
  docxEditorTableDimensions: '{rows} rows, {columns} columns.',
  docxEditorTableCell: 'Row {row}, column {column}.',
  docxEditorTableRowAbove: 'Insert row above',
  docxEditorTableRowBelow: 'Insert row below',
  docxEditorTableColumnLeft: 'Insert column left',
  docxEditorTableColumnRight: 'Insert column right',
  docxEditorTableDeleteRow: 'Delete row',
  docxEditorTableDeleteColumn: 'Delete column',
  docxEditorTableDelete: 'Delete table',
  docxEditorImage: 'Image',
  docxEditorPreviousImage: 'Previous image',
  docxEditorNextImage: 'Next image',
  docxEditorNoImage: 'No image is available for these tools.',
  docxEditorResizeImage: 'Resize image',
  docxEditorDescribeImage: 'Image description',
  docxEditorDeleteImage: 'Delete image',
  docxEditorImageWidth: 'Width in points',
  docxEditorImageHeight: 'Height in points',
  docxEditorImageRatio: 'Preserve aspect ratio',
  docxEditorImageSizeHint: 'Enter a dimension from 1 to 1440 points. Aspect ratio uses the original image dimensions.',
  docxEditorImageTitle: 'Title',
  docxEditorImageDescription: 'Description',
  docxEditorImageDescriptionHint: 'Use up to 256 characters for the title and 2048 for the description. Empty fields clear the existing text.',
  docxEditorImageStale: 'The document or image selection changed. Close this dialog and select the image again.',
  docxEditorImageDimensions: '{width} × {height} points.',
  docxEditorImageApply: 'Apply',
  docxEditorFind: 'Find and replace',
  docxEditorFindQuery: 'Find text',
  docxEditorFindSubmit: 'Find',
  docxEditorMatchCase: 'Match case',
  docxEditorWholeWord: 'Whole words',
  docxEditorFindCount: 'Matches: {count}',
  docxEditorFindTruncated: 'Results limited to the first 100 matches.',
  docxEditorPrevious: 'Previous match',
  docxEditorNext: 'Next match',
  docxEditorReplacement: 'Replace with',
  docxEditorReplace: 'Replace this match',
  docxEditorReplaced: 'Match replaced',
  docxEditorEditUnavailable: 'This edit is unavailable for the current selection or document.',
});
