// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON ወደ ቅንጥብ ሰሌዳ ቅዳ',
  circularReference: 'ዑደታዊ ማጣቀሻ',
  copyDiff: 'ልዩነቱን ቅዳ',
  diffViewOldLabel: 'ዋናው',
  diffViewNewLabel: 'ተቀይሯል',
  diffViewHiddenLines: {
    one: '{count} ያልተቀየረ መስመር',
    other: '{count} ያልተቀየሩ መስመሮች',
  },
  diffViewTooLarge: 'ልዩነቱ ለማሳየት በጣም ትልቅ ነው።',
  jsonArray: 'ድርድር',
  jsonObject: 'ነገር',
  jsonValue: 'ዋጋ',
  jsonCopyLabel: '{label} ቅዳ',
  jsonExpandLabel: '{label} አስፋ',
  jsonCollapseLabel: '{label} አጠቃልል',
  jsonItemCount: {
    one: '{count} ንጥል',
    other: '{count} ንጥሎች',
  },
  jsonKeyCount: {
    one: '{count} ቁልፍ',
    other: '{count} ቁልፎች',
  },
  jsonViewerLimit: 'የመጀመሪያዎቹ {count} JSON ኖዶች እና {depth} የመደራረብ ደረጃዎች ብቻ ይታያሉ እና ይፈለጋሉ።',
  pollPause: 'አቁም',
  pollResume: 'ቀጥል',
  pollRefresh: 'አሁን አድስ',
  pollInactive: 'ንቁ ያልሆነ',
  pollRefreshing: 'በማደስ ላይ…',
  pollPaused: 'ቆሟል',
  pollPausedAnnounce: 'ቆሟል።',
  pollResumedAnnounce: 'ቀጥሏል።',
  pollRefreshingAnnounce: 'አሁን እየታደሰ ነው።',
  randomContentPause: 'ማዞሩን አቁም',
  randomContentResume: 'ማዞሩን ቀጥል',
  exportButtonLabel: 'ላክ',
  knownDateDay: 'ቀን',
  knownDateMonth: 'ወር',
  knownDateYear: 'ዓመት',
  exportFormatMenuLabel: 'የ{label} ቅርጸት',
  mentionSuggestions: 'ጥቆማዎች',
  mentionResultCount: {
    one: '{count} ጥቆማ',
    other: '{count} ጥቆማዎች',
  },
  mentionResultPosition: 'ከ{total} ጥቆማዎች {current}ኛ',
  iconLoadError: 'አዶውን መጫን አልተሳካም።',
  iconTooLarge: 'የአዶው ፋይል ለማሳየት በጣም ትልቅ ነው።',
  iconSanitizerMissing: 'ይህን አዶ በደህና ለማሳየት አማራጭ የ"dompurify" ጥቅል መጫን ያስፈልጋል።',
  tourSkip: 'ዝለል',
  tourDone: 'ተጠናቋል',
  tourStepOf: 'ከ{total} ደረጃዎች {current}ኛ',
};

registerLyraLocale('am', strings);
