// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `utility` slice of the cs translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/utility/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/cs/utility';` and reads nothing from it.
// `../cs.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'Kopírovat JSON do schránky',
  circularReference: 'Cyklický odkaz',
  copyDiff: 'Kopírovat rozdíly',
  diffViewOldLabel: 'Původní',
  diffViewNewLabel: 'Upravené',
  diffViewHiddenLines: {
    few: '{count} nezměněné řádky',
    many: '{count} nezměněného řádku',
    one: '{count} nezměněný řádek',
    other: '{count} nezměněných řádků',
  },
  diffViewTooLarge: 'Rozdíly jsou příliš velké na zobrazení.',
  jsonArray: 'pole',
  jsonObject: 'objekt',
  jsonValue: 'hodnota',
  jsonCopyLabel: 'Kopírovat {label}',
  jsonExpandLabel: 'Rozbalit {label}',
  jsonCollapseLabel: 'Sbalit {label}',
  jsonItemCount: {
    few: '{count} položky',
    many: '{count} položky',
    one: '{count} položka',
    other: '{count} položek',
  },
  jsonKeyCount: {
    few: '{count} klíče',
    many: '{count} klíče',
    one: '{count} klíč',
    other: '{count} klíčů',
  },
  jsonViewerLimit: 'Zobrazuje se a prohledává pouze prvních {count} uzlů JSON a {depth} úrovní vnoření.',
  pollPause: 'Pozastavit',
  pollResume: 'Pokračovat',
  pollInactive: 'Neaktivní',
  pollRefreshing: 'Obnovování…',
  pollPaused: 'Pozastaveno',
  pollPausedAnnounce: 'Pozastaveno.',
  pollResumedAnnounce: 'Znovu spuštěno.',
  pollRefreshingAnnounce: 'Probíhá obnovení.',
  randomContentPause: 'Pozastavit střídání',
  randomContentResume: 'Obnovit střídání',
  exportButtonLabel: 'Exportovat',
  knownDateDay: 'Den',
  knownDateMonth: 'Měsíc',
  knownDateYear: 'Rok',
  exportFormatMenuLabel: 'Formát {label}',
  mentionSuggestions: 'Návrhy',
  mentionResultCount: {
    few: '{count} návrhy',
    many: '{count} návrhu',
    one: '{count} návrh',
    other: '{count} návrhů',
  },
  mentionResultPosition: 'Návrh {current} z {total}',
  iconLoadError: 'Ikonu se nepodařilo načíst.',
  iconTooLarge: 'Soubor ikony je příliš velký na zobrazení.',
  iconSanitizerMissing: 'Tato ikona vyžaduje pro bezpečné vykreslení nainstalovaný volitelný balíček „dompurify“.',
  tourSkip: 'Přeskočit',
  tourDone: 'Hotovo',
  tourStepOf: 'Krok {current} z {total}',
};

registerLyraLocale('cs', strings);
