#!/usr/bin/env node
// Builds every generated agent-facing reference artifact from the authored sources in `llms/`.
//
// Authored (edit these):
//   llms/00-preamble.md       intro paragraphs of llms-full.txt
//   llms/shared.md            foundation + cross-cutting notes (apply to the whole library)
//   llms/<family>.md          one file per src/components/<family>/ directory
//
// Generated (never edit; `pnpm run llms` rewrites them, CI diffs them):
//   llms-full.txt             concatenation, the single-file reference published since v1
//   llms/index.md             tag -> family/import/one-line-purpose routing table
//   llms/components/<tag>.md  one self-contained file per custom element (surgical agent reads)
//   llms/tokens.md            direct --lr-theme-* mappings plus derived/fixed --lr-* tokens
//   llms/peers.md             component -> optional peer dependency map
//   llms/migration.md         wa-*/sl-* classification and codemod table
//
// A component section is assigned to a family by the src/components/<family>/ directory its tag is
// declared in, so the docs can never drift from the source tree's own grouping.
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  NORMALIZATION_SECTIONS,
  validateLocalMigrations,
  validateMappingNormalizations,
} from './component-inventory.mjs';
import { expandManifestInheritance } from './manifest-compact.mjs';

const packageDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const llmsDir = path.join(packageDir, 'llms');
const read = (...p) => readFileSync(path.join(packageDir, ...p), 'utf8');

/** Human-readable family titles, in the order they appear in llms-full.txt. */
export const FAMILIES = [
  ['forms', 'Form controls & inputs'],
  ['data', 'Data display, dashboards & flow canvas'],
  ['layout', 'Layout, navigation & structure'],
  ['overlays', 'Overlays, status & feedback'],
  ['utility', 'Utilities, formatting & observers'],
  ['media', 'Media, files & maps'],
  ['charts', 'Charts'],
  ['viewers', 'Document & file viewers'],
  ['conversation', 'Conversation & chat UI'],
  ['agent-tools', 'Agent tooling, tool calls & evaluation'],
  ['retrieval', 'Retrieval, knowledge graph & grounding'],
];

const GENERATED = (source) =>
  `<!-- GENERATED by scripts/build-llms.mjs from ${source} — do not edit this file. -->`;

/** Framework packages referenced only by the opt-in generated declaration entry points. */
export const TYPE_ONLY_DECLARATION_PEERS = Object.freeze({
  react: '@aceshooting/lyra-ui/custom-elements-jsx',
  svelte: '@aceshooting/lyra-ui/svelte',
  vue: '@aceshooting/lyra-ui/vue',
});

// ---------------------------------------------------------------------------------------------
// Manifest facts: tag -> family, declaring module, and the registration entry point to import.
// ---------------------------------------------------------------------------------------------

/**
 * One-line purpose from a class's JSDoc: drop the leading "`<lr-x>` — " restatement, unwrap the
 * source's hard line breaks, and keep the first sentence (or the first clause, when the JSDoc opens
 * with a long enumeration).
 */
function summarize(description) {
  const flat = description.split('\n\n')[0].replace(/\s+/g, ' ').trim();
  const body = flat.replace(/^`?<?lr-[a-z0-9-]+>?`?\s*[—-]\s*/i, '');
  const sentence = body.match(/^(.+?\.)(?:\s|$)/)?.[1] ?? body;
  return sentence.length > 140 ? `${sentence.slice(0, 137).trimEnd()}...` : sentence;
}

export function readTagFacts(manifest) {
  const expandedManifest = expandManifestInheritance(manifest);
  const tags = new Map();
  for (const mod of expandedManifest.modules ?? []) {
    const m = mod.path.match(/^src\/components\/([^/]+)\/([^/]+)\//);
    if (!m) continue;
    for (const decl of mod.declarations ?? []) {
      if (!decl.customElement || !decl.tagName) continue;
      // `foo.class.ts` declares the class; `foo.ts` next to it is the side-effect entry that
      // registers the tag — that is what a consumer imports.
      const entry = mod.path.replace(/\.class\.ts$/, '.ts').replace(/^src\//, '').replace(/\.ts$/, '.js');
      tags.set(decl.tagName, {
        tag: decl.tagName,
        family: m[1],
        className: decl.name,
        importPath: `@aceshooting/lyra-ui/${entry}`,
        modulePath: mod.path,
        purpose: summarize(decl.description ?? decl.summary ?? ''),
        status: decl.status,
        since: decl.since,
        maturity: decl.maturity,
        deprecations: decl.deprecations ?? [],
        cssParts: decl.cssParts ?? [],
        cssProperties: decl.cssProperties ?? [],
      });
    }
  }
  return tags;
}

// ---------------------------------------------------------------------------------------------
// Section parsing: a `## ` heading opens a section; `###` subheadings stay inside it.
// ---------------------------------------------------------------------------------------------

export function splitSections(text) {
  const lines = text.split('\n');
  const sections = [];
  let fenced = false;
  let current = null;
  for (const line of lines) {
    if (/^```/.test(line)) fenced = !fenced;
    if (!fenced && /^## /.test(line)) {
      current = { title: line.slice(3).trim(), lines: [line], tags: [] };
      sections.push(current);
      continue;
    }
    if (!current) continue;
    current.lines.push(line);
    if (!fenced && /^#{3,} /.test(line)) current.tags.push(...(line.match(/lr-[a-z0-9-]+/g) ?? []));
  }
  for (const s of sections) {
    s.tags = [...new Set([...(s.title.match(/lr-[a-z0-9-]+/g) ?? []), ...s.tags])];
    s.text = s.lines.join('\n').replace(/\n+$/, '');
  }
  return sections;
}

/** First sentence of a section's prose — used as the one-line purpose in the index. */
function firstSentence(section) {
  const body = section.text.split('\n').slice(1).join('\n');
  const prose = body
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .find((p) => p && !p.startsWith('#') && !p.startsWith('```') && !p.startsWith('|'));
  if (!prose) return '';
  const flat = prose.replace(/\n/g, ' ').replace(/\s+/g, ' ');
  const cut = flat.match(/^(.+?\.)(?:\s|$)/);
  return (cut ? cut[1] : flat).trim();
}

// ---------------------------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------------------------

export function buildTokens() {
  const input = JSON.parse(read('scripts', 'fixtures', 'token-docs.generated.json'));
  if (
    input.schemaVersion !== 1 ||
    input.authority !== 'tokens/canonical-tokens.json' ||
    !Array.isArray(input.tokens)
  ) {
    throw new Error(
      'Cannot build token reference: token-docs.generated.json must be a schema-version 1 canonical-token projection.',
    );
  }
  const shared = input.tokens.filter((token) => token.scope === 'shared');
  if (
    shared.some(
      (token) =>
        typeof token.name !== 'string' ||
        !token.name.startsWith('--lr-') ||
        typeof token.values?.light !== 'string',
    )
  ) {
    throw new Error('Cannot build token reference: every shared token needs a name and light value.');
  }
  const rows = shared.filter((token) => typeof token.themeInput === 'string');
  const plain = shared.filter((token) => token.themeInput === undefined);
  const fallback = (token) => {
    const prefix = `var(${token.themeInput}, `;
    if (!token.values.light.startsWith(prefix) || !token.values.light.endsWith(')')) {
      throw new Error(`${token.name}: light value must read its declared themeInput with a fallback.`);
    }
    return token.values.light.slice(prefix.length, -1);
  };
  const modeOverrides = (token) =>
    ['dark', 'forcedColors', 'reducedMotion']
      .filter((mode) => token.values[mode] !== undefined)
      .map((mode) => `${mode}: \`${token.values[mode]}\``)
      .join('<br>') || '—';
  const body = [
    GENERATED('scripts/fixtures/token-docs.generated.json'),
    '',
    '# Design tokens',
    '',
    'Every `lr-*` component resolves its styling through this two-layer token system, inherited from',
    '`LyraElement`:',
    '',
    '1. **`--lr-theme-*` — the application input layer.** Set these (on `:root`, or any ancestor of a',
    '   subtree) to retheme. This is the only supported theming mechanism; never hardcode a color,',
    '   spacing, or font value that fights it.',
    '2. **`--lr-*` — the internal layer.** Direct theme-backed tokens read a `--lr-theme-*` input',
    '   with a built-in fallback. Other tokens are aliases, computed or environment-backed values,',
    '   or fixed contract constants. Every component renders correctly with no theme configured.',
    '',
    'For a ready-made light/dark base, import `@aceshooting/lyra-ui/theme.css` once and put',
    '`class="lr-light"`/`class="lr-dark"` (or `data-lr-theme="light"`/`"dark"`) on an ancestor.',
    'Per-component `--lr-<component>-*` custom properties (listed in each component\'s own section)',
    'override a single element without touching the shared layer.',
    '',
    `## Direct theme-backed tokens (${rows.length})`,
    '',
    '| Internal token | `--lr-theme-*` input | Light/default fallback | Mode overrides |',
    '|---|---|---|---|',
    ...rows.map(
      (token) =>
        `| \`${token.name}\` | \`${token.themeInput}\` | \`${fallback(token)}\` | ${modeOverrides(token)} |`,
    ),
  ];
  if (plain.length) {
    body.push(
      '',
      `## Derived and fixed tokens (${plain.length})`,
      '',
      'These do not directly read a `--lr-theme-*` input. Aliases and computed values still follow',
      'the tokens or environment values they reference; fixed contract constants are intentionally',
      'not theme inputs.',
      '',
      '| Token | Light/default value | Mode overrides |',
      '|---|---|---|',
      ...plain.map(
        (token) => `| \`${token.name}\` | \`${token.values.light}\` | ${modeOverrides(token)} |`,
      ),
    );
  }
  return body.join('\n') + '\n';
}

function buildPeers(tagFacts) {
  const pkg = JSON.parse(read('package.json'));
  const peers = Object.keys(pkg.peerDependencies ?? {}).sort();
  const componentPeers = peers.filter((peer) => !(peer in TYPE_ONLY_DECLARATION_PEERS));
  const meta = pkg.peerDependenciesMeta ?? {};
  const srcRoot = path.join(packageDir, 'src', 'components');

  // Peers are attributed per tag by walking that tag's own module graph (its registration entry
  // plus every relative import it reaches), not per directory — components that share a directory
  // do not necessarily share a peer. Bare specifiers other than the peer itself end the walk.
  const peersForTag = (facts) => {
    const found = new Set();
    const seen = new Set();
    const queue = [path.join(packageDir, facts.modulePath.replace(/\.class\.ts$/, '.ts'))];
    while (queue.length) {
      const file = queue.pop();
      const resolved = [file, file.replace(/\.js$/, '.ts')].find((c) => existsSync(c) && c.endsWith('.ts'));
      if (!resolved || seen.has(resolved)) continue;
      seen.add(resolved);
      const text = readFileSync(resolved, 'utf8');
      for (const peer of componentPeers) {
        if (new RegExp(`from '${peer}(?:/|')|import\\('${peer}(?:/|')`).test(text)) found.add(peer);
      }
      for (const m of text.matchAll(/(?:from|import\()\s*'(\.[^']+)'/g)) {
        queue.push(path.resolve(path.dirname(resolved), m[1]));
      }
    }
    return [...found];
  };

  const byPeer = new Map(peers.map((p) => [p, []]));
  for (const facts of tagFacts.values()) {
    for (const peer of peersForTag(facts)) byPeer.get(peer).push(facts.tag);
  }
  // Peers reached only from a non-component module (e.g. a shared loader) still get a row.
  const walkAll = new Set();
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (/\.ts$/.test(entry.name) && !/\.(test|stories)\.ts$/.test(entry.name)) {
        const text = readFileSync(full, 'utf8');
        for (const peer of componentPeers) if (text.includes(`'${peer}`)) walkAll.add(peer);
      }
    }
  };
  walk(srcRoot);

  const rows = peers.map((peer) => ({
    peer,
    range: pkg.peerDependencies[peer],
    optional: meta[peer]?.optional !== false,
    tags: [...new Set(byPeer.get(peer))].sort(),
    seenAnywhere: walkAll.has(peer),
    declarationEntry: TYPE_ONLY_DECLARATION_PEERS[peer],
  }));

  const typeOnlyCount = peers.length - componentPeers.length;

  return [
    GENERATED('package.json + src/components/'),
    '',
    '# Optional peer dependencies',
    '',
    `All ${peers.length} peers are **optional**: nothing here is needed to install or use the library,`,
    'but they have two deliberately different roles.',
    '',
    `**Framework declaration peers (${typeOnlyCount}).** React, Svelte, and Vue are compile-time peers`,
    'only when a project imports their matching opt-in declaration entry. Those entry points emit empty',
    'JavaScript, no component imports these frameworks, and Lyra ships no runtime wrapper.',
    '',
    `**Component-loaded peers (${componentPeers.length}).** No component imports one eagerly. Install a`,
    'peer only when you use a component that needs it.',
    '',
    '**How they load.** A component that needs a peer resolves it through a dynamic `import()` on first',
    'use, rendering an `<lr-skeleton>` placeholder with `aria-busy="true"` on the host while it settles.',
    'If the peer is genuinely absent, the component falls back to an empty/degraded render and logs one',
    '`console.warn` (deduped module-wide, not per instance) — it never throws and never blocks paint.',
    '`<lr-phone-input>` is the exception: it takes an explicit consumer-built adapter',
    '(`loadLibphonenumberAdapter()`) instead of importing `libphonenumber-js` itself.',
    '',
    '**SheetJS (`xlsx`).** The supported `>=0.20.3 <0.21.0` releases are distributed by SheetJS',
    'from its CDN, not the public npm registry (whose newest release is 0.18.5). Install the peer',
    'with `pnpm add https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz` (or the equivalent npm',
    'command), matching the range below. The npm-published 0.18.5 release has unresolved advisories;',
    'do not run `npm audit fix --force` to address them when it proposes downgrading lyra-ui. That',
    'changes the component library version without installing a supported SheetJS release.',
    '',
    '| Peer | Range | Needed by |',
    '|---|---|---|',
    ...rows.map(
      (r) =>
        `| \`${r.peer}\` | \`${r.range}\` | ${
          r.tags.length
            ? r.tags.map((t) => `\`${t}\``).join(', ')
            : r.declarationEntry
              ? `type-only \`${r.declarationEntry}\` entry (no runtime import)`
            : r.seenAnywhere
              ? '_(loaded by a shared internal module)_'
              : '_(not referenced by any component)_'
        } |`,
    ),
    '',
  ].join('\n');
}

export function buildMigration() {
  const inventory = JSON.parse(read('scripts', 'fixtures', 'component-inventory.json'));
  const classifications = [
    'exact',
    'rewritten',
    'warning-required',
    'conceptual-only',
    'unsupported',
  ];
  const ruleSections = [
    'attributes',
    'properties',
    'events',
    'slots',
    'parts',
    'cssProperties',
    'methods',
    'defaults',
  ];
  if (
    inventory.schemaVersion !== 1 ||
    !Array.isArray(inventory.components) ||
    !Array.isArray(inventory.mappings) ||
    !Array.isArray(inventory.localMigrations)
  ) {
    throw new Error('Cannot build migration reference: component-inventory.json must use schema version 1.');
  }
  const localMigrationFindings = validateLocalMigrations(inventory);
  if (localMigrationFindings.length > 0) {
    throw new Error(`Cannot build migration reference: ${localMigrationFindings.join('; ')}`);
  }

  const components = new Map(inventory.components.map((component) => [component.tag, component]));
  const componentTags = new Set(components.keys());
  const upstreams = new Map(
    Object.values(inventory.upstreams ?? {}).flatMap((upstream) =>
      (upstream.components ?? []).map((component) => [component.tag, component]),
    ),
  );
  const seen = new Set();
  for (const mapping of inventory.mappings) {
    if (
      !mapping ||
      typeof mapping.upstreamTag !== 'string' ||
      !mapping.upstreamTag ||
      seen.has(mapping.upstreamTag) ||
      !['webawesome', 'shoelace'].includes(mapping.upstream) ||
      !classifications.includes(mapping.classification) ||
      !mapping.rewrites ||
      Object.keys(mapping.rewrites).some((section) => !ruleSections.includes(section)) ||
      ruleSections.some((section) => !Array.isArray(mapping.rewrites[section]))
    ) {
      throw new Error(`Cannot build migration reference: invalid mapping ${mapping?.upstreamTag ?? '<unknown>'}.`);
    }
    if (
      mapping.normalizations !== undefined &&
      (!mapping.normalizations ||
        Object.keys(mapping.normalizations).some((section) => !NORMALIZATION_SECTIONS.includes(section)) ||
        NORMALIZATION_SECTIONS.some((section) => !Array.isArray(mapping.normalizations[section])))
    ) {
      throw new Error(`Cannot build migration reference: invalid normalizations for ${mapping.upstreamTag}.`);
    }
    const normalizationFindings = validateMappingNormalizations(mapping, {
      upstream: upstreams.get(mapping.upstreamTag)?.surface,
      target: components.get(mapping.targetTag)?.surface,
    });
    if (normalizationFindings.length > 0) {
      throw new Error(`Cannot build migration reference: ${normalizationFindings.join('; ')}`);
    }
    seen.add(mapping.upstreamTag);
  }

  const count = (classification, upstream = null) =>
    inventory.mappings.filter(
      (mapping) => mapping.classification === classification && (!upstream || mapping.upstream === upstream),
    ).length;
  const automatic = (upstream = null) => count('exact', upstream) + count('rewritten', upstream);
  const manual = (upstream = null) => inventory.mappings.filter(
    (mapping) =>
      (!upstream || mapping.upstream === upstream) &&
      !['exact', 'rewritten'].includes(mapping.classification),
  ).length;
  const escapeCell = (value) => String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
  const summarizeRules = (mapping) => {
    const rules = [];
    for (const section of ruleSections) {
      for (const rule of mapping.rewrites[section]) {
        if (section === 'defaults') {
          rules.push(
            rule.action === 'insert-if-absent'
              ? `insert ${rule.member}=${String(rule.value)}`
              : `${rule.member}: ${String(rule.from)} → ${String(rule.to)}`,
          );
        } else {
          rules.push(`${section}: ${rule.from} → ${rule.to}`);
        }
      }
    }
    return rules.join('; ');
  };
  const summarizeNormalizations = (mapping) => {
    const defaults = (mapping.normalizations?.defaultEquivalences ?? []).map(
      (rule) => `${rule.member} defaults ${String(rule.upstream)} ≡ ${String(rule.target)}`,
    );
    const inferred = (mapping.normalizations?.inferredAttributeSuppressions ?? []).map(
      (rule) => `${rule.attribute} is analyzer-inferred for property-only ${rule.property}`,
    );
    const entries = [...defaults, ...inferred];
    return entries.length > 0 ? ` Equivalent surface representation: ${entries.join('; ')}; no source rewrite.` : '';
  };
  const disposition = (mapping) => {
    if (mapping.classification === 'exact') {
      return `Automatic: tag and supported side-effect registration import.${summarizeNormalizations(mapping)}`;
    }
    if (mapping.classification === 'rewritten') {
      return `Automatic: tag/import plus ${summarizeRules(mapping)}.${summarizeNormalizations(mapping)}`;
    }
    return `Manual: ${mapping.rationale || 'inspect the target contract before porting.'}`;
  };
  const section = (title, upstream, note) => {
    const rows = inventory.mappings
      .filter((mapping) => mapping.upstream === upstream)
      .sort((left, right) => left.upstreamTag.localeCompare(right.upstreamTag));
    return [
      `## ${title} (${rows.length})`,
      '',
      note,
      '',
      '| From | Lyra target or candidate | Classification | Disposition |',
      '|---|---|---|---|',
      ...rows.map((mapping) => {
        const target = mapping.targetTag
          ? componentTags.has(mapping.targetTag)
            ? `\`<${mapping.targetTag}>\``
            : `not shipped (\`<${mapping.targetTag}>\` candidate)`
          : '—';
        return `| \`<${mapping.upstreamTag}>\` | ${target} | \`${mapping.classification}\` | ${escapeCell(disposition(mapping))} |`;
      }),
      '',
    ];
  };
  const localProfileRows = inventory.localMigrations
    .slice()
    .sort((left, right) => left.origin.localeCompare(right.origin) || left.tag.localeCompare(right.tag))
    .map((profile) => {
      const defaults = profile.defaults
        .map((rule) =>
          rule.value === true
            ? `presence \`${rule.member}\``
            : `\`${rule.member}="${String(rule.value)}"\``,
        )
        .join(', ');
      return `| \`${profile.origin}\` | \`<${profile.tag}>\` | ${defaults} |`;
    });

  return [
    GENERATED('scripts/fixtures/component-inventory.json'),
    '',
    '# Migrating to `lr-*`',
    '',
    'Migration decisions come from the pinned, schema-validated component inventory. A matching name',
    'does not by itself prove API compatibility. The codemod changes only `exact` and `rewritten`',
    'mappings; `warning-required`, `conceptual-only`, `unsupported`, and unknown tags stay unchanged',
    'and receive location-aware warnings.',
    '',
    'The version-matched CLI ships with the package and runs without a repository checkout.',
    'Replace `<version>` with the installed Lyra major/minor/patch you are targeting:',
    '',
    '```bash',
    'npx --package @aceshooting/lyra-ui@<version> lyra-ui-migrate --check --report=lyra-migration.json src',
    '```',
    '',
    '`--check` never writes source files and exits nonzero while rewrites or warnings remain, which',
    'makes it suitable for CI after an applied migration.',
    '',
    'The supported upstream identities are `@awesome.me/webawesome` and `@awesome.me/webawesome-pro`',
    'for Web Awesome, plus `@shoelace-style/shoelace`. The tool scans HTML, standalone CSS,',
    'JavaScript, TypeScript, JSX, Vue, Svelte, MDX, and Markdown. It rewrites inventory-declared',
    'tags, members, defaults, and supported side-effect registration imports.',
    'Imports with bindings remain manual because exported names cannot be inferred safely. An',
    'aliased component value that uses a rewritten member blocks that mapping across the scanned',
    'target set, preventing a registration import from changing while an old member remains. A root',
    'Web Awesome or Shoelace registration import changes only when that package identity and tier',
    'prove the registration closure and no manual component use exists anywhere in the scanned target',
    'set. Root-included targets use `@aceshooting/lyra-ui/all.js`; root-excluded targets receive granular registration imports.',
    'An automatic-looking tag with no matching side-effect registration in the scanned target set',
    'stays unchanged with `REGISTRATION_CLOSURE_REQUIRED`; include the registration-owning entry file',
    'in the scan instead of accepting an inert `lr-*` result.',
    'Targets with optional runtime peers also emit an `OPTIONAL_PEER_REQUIRED` report entry naming',
    'each package that must be installed.',
    'Re-running the tool is idempotent; comments, prose, partial strings, and unrelated packages are',
    'left alone.',
    '',
    'The JSON migration report records every rewrite and warning with its file, line, column,',
    'origin, tag/member, action, target, and warning code. Run without `--check` only after inspecting',
    'that report and the target component reference in `llms/components/<tag>.md`.',
    '',
    '`dir` and `lang` are platform-global HTML passthrough attributes, not component-member drift.',
    'Web Awesome\'s `did-ssr` is its runtime hydration marker, not an authored member to recreate or',
    'rename on a Lyra component. The inventory records these exclusions explicitly.',
    '',
    '## Migrating Lyra 7 defaults',
    '',
    'The local defaults profile is opt-in and separate from Web Awesome/Shoelace migration. It never',
    'renames an `lr-*` tag or import; it only inserts an absent attribute that preserves a changed',
    'Lyra 7 default. Boolean `true` is emitted as canonical attribute presence, including the positive',
    'inverse `without-arrow` spelling.',
    '',
    '```bash',
    'npx --package @aceshooting/lyra-ui@<version> lyra-ui-migrate --origin=lyra-v7 --check --report=lyra-v7-migration.json src',
    '```',
    '',
    'Opaque framework spreads and DOM aliases block that component profile across the scanned target',
    'set with a warning. Expand or classify them before applying, then rerun to verify byte idempotence.',
    '',
    '| Origin | Component | Inserted only when absent |',
    '|---|---|---|',
    ...localProfileRows,
    '',
    '## Classification summary',
    '',
    '| Ecosystem | Exact | Rewritten | Warning required | Conceptual only | Unsupported | Automatic | Manual |',
    '|---|---:|---:|---:|---:|---:|---:|---:|',
    ...[
      ['Web Awesome', 'webawesome'],
      ['Shoelace', 'shoelace'],
    ].map(
      ([label, upstream]) =>
        `| ${label} | ${count('exact', upstream)} | ${count('rewritten', upstream)} | ${count('warning-required', upstream)} | ${count('conceptual-only', upstream)} | ${count('unsupported', upstream)} | ${automatic(upstream)} | ${manual(upstream)} |`,
    ),
    `| **Total** | **${count('exact')}** | **${count('rewritten')}** | **${count('warning-required')}** | **${count('conceptual-only')}** | **${count('unsupported')}** | **${automatic()}** | **${manual()}** |`,
    '',
    ...section(
      'Web Awesome',
      'webawesome',
      'The pinned Web Awesome manifest is authoritative for this inventory; only rows marked automatic are codemod inputs.',
    ),
    ...section(
      'Shoelace',
      'shoelace',
      'Shoelace relationships are classified independently; a same-suffix tag is never treated as proof of compatibility.',
    ),
  ].join('\n');
}

function buildIndex(sectionsByFamily, tagFacts) {
  const out = [
    GENERATED('custom-elements.json + llms/<family>.md'),
    '',
    '# Component index',
    '',
    `${tagFacts.size} custom elements, grouped by the source family they live in.`,
    '',
    '**Reading one component.** Its reference file path is derived from the tag — no search needed:',
    '`llms/components/<tag>.md` (e.g. `llms/components/lr-table.md`). Each is self-contained: import',
    'path, optional peers, properties, events, slots, CSS parts, themeable custom properties, a usage',
    'snippet, and known gotchas — a few hundred tokens instead of the whole catalog.',
    '',
    '**Importing.** Registration paths are stable aliases derived from the tag:',
    "`import '@aceshooting/lyra-ui/components/lr-table.js';` registers `<lr-table>` and remains",
    'valid if its internal family folder moves. Class-only `.class.js` entries intentionally keep',
    'their owning family path and do not register the tag.',
    '',
    '**Everything else.** Library-wide behavior (base class, events, form association, `locale`/',
    '`strings`, TypeScript, frameworks, SSR): `llms/shared.md`. Design tokens: `llms/tokens.md`.',
    'Optional peers: `llms/peers.md`. Safe `wa-*`/`sl-*` migration: `llms/migration.md`.',
    '',
  ];
  for (const [family, title] of FAMILIES) {
    const sections = sectionsByFamily.get(family) ?? [];
    const tags = sections.flatMap((s) => s.tags);
    out.push(`## ${title} — \`components/${family}/\` (${tags.length})`, '');
    for (const section of sections) {
      const fallback = firstSentence(section);
      for (const tag of section.tags) {
        const facts = tagFacts.get(tag);
        if (!facts) continue;
        const shortPath = `${tag}.js`;
        out.push(
          `- \`${tag}\` · ${shortPath} · \`${facts.status}\` since \`${facts.since}\` — ` +
            `${facts.purpose || fallback}`,
        );
      }
    }
    out.push('');
  }
  return out.join('\n');
}

function buildComponentFile(tag, section, tagFacts, peersByTag) {
  const facts = tagFacts.get(tag);
  const shares = section.tags.filter((t) => t !== tag && tagFacts.has(t));
  const peers = peersByTag.get(tag) ?? [];
  const cssPartNames = facts.cssParts?.map((p) => p.name) ?? [];
  const cssPropNames = facts.cssProperties?.map((p) => p.name) ?? [];
  const deprecationLines = facts.deprecations.map((entry) => {
    const subject = entry.kind === 'component'
      ? `\`${tag}\``
      : `\`${entry.name}\`${entry.attribute ? ` / \`${entry.attribute}\`` : ''}`;
    const replacement = entry.replacement?.usage ?? entry.replacement?.name;
    return `- **Deprecated ${entry.kind}** ${subject} since \`${entry.since}\`; use ` +
      `${entry.replacement?.kind ?? 'API'} \`${replacement}\`; removal not before ` +
      `\`${entry.removalNotBefore}\` — ${entry.rationale}`;
  });
  return [
    GENERATED(`llms/${facts.family}.md`),
    '',
    `# \`${tag}\``,
    '',
    `- **Import** \`import '@aceshooting/lyra-ui/components/${tag}.js';\` ` +
      '(stable tag alias; registers the tag)',
    `- **Class** \`${facts.className}\`, also available unregistered from` +
      ` \`${facts.importPath.replace(/\.js$/, '.class.js')}\``,
    `- **Family** \`components/${facts.family}/\` — see \`llms/index.md\` for its siblings`,
    `- **Status** \`${facts.status}\` since \`${facts.since}\` — see the maturity and deprecation` +
      ' policy in `llms/shared.md`',
    ...(deprecationLines.length ? deprecationLines : ['- **Deprecations** none']),
    peers.length
      ? `- **Optional peers** ${peers.map((p) => `\`${p}\``).join(', ') } — see \`llms/peers.md\``
      : '- **Optional peers** none',
    cssPartNames.length || cssPropNames.length
      ? `- **Themeable via** ${cssPartNames.length} part${cssPartNames.length === 1 ? '' : 's'}, ${cssPropNames.length} custom propert${cssPropNames.length === 1 ? 'y' : 'ies'} — see this component's own \`@csspart\`/\`@cssprop\` list below`
      : '- **Themeable via** nothing component-specific — inherits only the shared surface',
    shares.length
      ? `- **Documented with** ${shares.map((t) => `\`${t}\``).join(', ')} (same section below)`
      : null,
    '- **Library-wide behavior** (events, form association, `locale`/`strings`, tokens, TS types):' +
      ' `llms/shared.md`',
    '',
    '---',
    '',
    section.text,
    '',
  ]
    .filter((l) => l !== null)
    .join('\n');
}

// ---------------------------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------------------------

export function build({ write = true } = {}) {
  const manifest = JSON.parse(read('custom-elements.json'));
  const tagFacts = readTagFacts(manifest);

  const preamble = read('llms', '00-preamble.md').trimEnd();
  const shared = read('llms', 'shared.md').trimEnd();

  const sectionsByFamily = new Map();
  const sectionByTag = new Map();
  const problems = [];
  for (const [tag, facts] of tagFacts) {
    if (!['stable', 'experimental'].includes(facts.status) ||
        !/^(?:\d+\.\d+\.\d+|unreleased)$/.test(facts.since ?? '')) {
      problems.push(`\`${tag}\` has no valid CEM status/since metadata.`);
    }
  }
  for (const [family] of FAMILIES) {
    const file = path.join(llmsDir, `${family}.md`);
    if (!existsSync(file)) {
      problems.push(`llms/${family}.md is missing.`);
      continue;
    }
    const sections = splitSections(readFileSync(file, 'utf8'));
    sectionsByFamily.set(family, sections);
    for (const section of sections) {
      for (const tag of section.tags) {
        const facts = tagFacts.get(tag);
        if (!facts) {
          problems.push(`llms/${family}.md documents \`${tag}\`, which no longer exists in custom-elements.json.`);
          continue;
        }
        if (facts.family !== family) {
          problems.push(
            `\`${tag}\` is documented in llms/${family}.md but declared in src/components/${facts.family}/ — move the section to llms/${facts.family}.md.`,
          );
        }
        if (sectionByTag.has(tag)) {
          problems.push(`\`${tag}\` is documented twice: "${sectionByTag.get(tag).title}" and "${section.title}".`);
          continue;
        }
        sectionByTag.set(tag, section);
      }
    }
  }
  for (const tag of tagFacts.keys()) {
    if (!sectionByTag.has(tag)) problems.push(`\`${tag}\` has no section in any llms/<family>.md.`);
  }
  if (problems.length) {
    throw new Error(`Cannot build llms artifacts:\n  - ${problems.join('\n  - ')}`);
  }

  // Peer map, reused by the per-component headers.
  const peersText = buildPeers(tagFacts);
  const peersByTag = new Map();
  for (const line of peersText.split('\n')) {
    const m = line.match(/^\| `([^`]+)` \| `[^`]*` \| (.*) \|$/);
    if (!m) continue;
    for (const tag of m[2].match(/lr-[a-z0-9-]+/g) ?? []) {
      (peersByTag.get(tag) ?? peersByTag.set(tag, []).get(tag)).push(m[1]);
    }
  }

  // llms-full.txt — the single-file reference, unchanged in role since v1.
  const contents = [
    '## Contents',
    '',
    'This file is the concatenation of the per-family sources in `llms/`. When only one component is',
    'in question, read `llms/components/<tag>.md` instead — it is the same text plus its import path,',
    'and costs a few hundred tokens instead of the whole catalog. `llms/index.md` maps every tag to its',
    'family and entry point.',
    '',
    '- **Foundation** — base class, form association, events, i18n, theming, TypeScript, frameworks,' +
      ' SSR, packaging (`llms/shared.md`)',
    ...FAMILIES.map(([family, title]) => {
      const tags = (sectionsByFamily.get(family) ?? []).flatMap((s) => s.tags).length;
      return `- **${title}** — ${tags} tags in \`components/${family}/\``;
    }),
    '- **Reference tables** — design tokens (`llms/tokens.md`), optional peers (`llms/peers.md`),' +
      ' `wa-*`/`sl-*` migration (`llms/migration.md`)',
  ].join('\n');

  const fullParts = [preamble, '', contents, '', '---', '', '# Foundation', '', shared, ''];
  for (const [family, title] of FAMILIES) {
    fullParts.push(`# ${title} (\`components/${family}/\`)`, '');
    for (const section of sectionsByFamily.get(family)) fullParts.push(section.text, '');
  }
  const full = fullParts.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';

  // llms.txt — the short index. Its catalog is generated from the same family sources, so its
  // taxonomy can never drift from llms-full.txt's (it used to carry its own hand-kept grouping).
  const shortIndex = [readFileSync(path.join(llmsDir, '00-llms-txt-intro.md'), 'utf8').trimEnd(), ''];
  for (const [family, title] of FAMILIES) {
    const tags = (sectionsByFamily.get(family) ?? []).flatMap((s) => s.tags);
    shortIndex.push(
      `- **${title}** (\`components/${family}/\`, ${tags.length}) — ${tags.map((t) => `\`${t}\``).join(', ')}`,
      '',
    );
  }

  const artifacts = new Map([
    [path.join(packageDir, 'llms-full.txt'), full],
    [path.join(packageDir, 'llms.txt'), `${shortIndex.join('\n').trimEnd()}\n`],
    [path.join(llmsDir, 'index.md'), buildIndex(sectionsByFamily, tagFacts)],
    [path.join(llmsDir, 'tokens.md'), buildTokens()],
    [path.join(llmsDir, 'peers.md'), peersText],
    [path.join(llmsDir, 'migration.md'), buildMigration()],
  ]);
  for (const [tag, section] of sectionByTag) {
    artifacts.set(
      path.join(llmsDir, 'components', `${tag}.md`),
      buildComponentFile(tag, section, tagFacts, peersByTag),
    );
  }

  if (write) {
    rmSync(path.join(llmsDir, 'components'), { recursive: true, force: true });
    mkdirSync(path.join(llmsDir, 'components'), { recursive: true });
    for (const [file, text] of artifacts) writeFileSync(file, text);
  }
  return artifacts;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const artifacts = build();
  console.log(
    `Built llms-full.txt + ${artifacts.size - 1} files under llms/ (${[...artifacts.values()].reduce((a, t) => a + t.length, 0)} bytes).`,
  );
}
