#!/usr/bin/env node

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import {
  build,
  buildMigration,
  readTagFacts,
  TYPE_ONLY_DECLARATION_PEERS,
} from './build-llms.mjs';
import { createManifestInheritanceFixture } from './fixtures/manifest-inheritance.mjs';
import { compactManifest } from './manifest-compact.mjs';

const inventory = JSON.parse(
  readFileSync(new URL('./fixtures/component-inventory.json', import.meta.url), 'utf8'),
);
const migration = buildMigration();

const conversationReference = readFileSync(new URL('../llms/conversation.md', import.meta.url), 'utf8');
const dataReference = readFileSync(new URL('../llms/data.md', import.meta.url), 'utf8');
const markdownSharedSource = readFileSync(
  new URL('../src/components/conversation/markdown/markdown-shared.ts', import.meta.url),
  'utf8',
);
const headingItemBody = markdownSharedSource.match(
  /export interface MarkdownHeadingItem\s*{(?<body>[^}]*)}/,
)?.groups?.body;
assert.ok(headingItemBody, 'MarkdownHeadingItem must remain a declared public interface');
const headingItemKeys = [...headingItemBody.matchAll(/^\s*(?<key>[A-Za-z_$][\w$]*)\??:/gm)].map(
  ({ groups }) => groups.key,
);
const conversationLines = conversationReference.split('\n');
const headingTreeContractIndex = conversationLines.findIndex((line) =>
  line.startsWith('- `getHeadingTree()'),
);
assert.notEqual(
  headingTreeContractIndex,
  -1,
  'the authored Markdown reference must document getHeadingTree()',
);
const headingTreeContract = conversationLines
  .slice(headingTreeContractIndex, headingTreeContractIndex + 3)
  .join(' ');
assert.ok(
  headingTreeContract.includes('MarkdownHeadingItem[]') &&
    headingTreeContract.includes(`\`{ ${headingItemKeys.join(', ')} }[]\``),
  'getHeadingTree() prose must name its exported return type and exact object keys',
);

const flowCanvasSection = dataReference
  .split('## `lr-flow-canvas`')[1]
  ?.split('\n## `lr-')[0];
assert.ok(flowCanvasSection, 'the authored data reference must contain lr-flow-canvas');
const flowCanvasExample = flowCanvasSection.match(/```html\n(?<html>[\s\S]*?)\n```/)?.groups?.html;
assert.ok(flowCanvasExample, 'lr-flow-canvas must retain a canonical HTML example');
const flowCanvasElement = flowCanvasExample.match(/<lr-flow-canvas\b[\s\S]*?<\/lr-flow-canvas>/)?.[0];
assert.ok(flowCanvasElement, 'the canonical example must contain a complete lr-flow-canvas');
assert.match(
  flowCanvasElement,
  /<lr-flow-controls\b[^>]*slot="bottom-start"[^>]*><\/lr-flow-controls>/,
  'the canonical flow controls must be assigned inside the canvas bottom-start slot',
);
assert.match(
  flowCanvasElement,
  /<lr-flow-minimap\b[^>]*slot="bottom-end"[^>]*><\/lr-flow-minimap>/,
  'the canonical minimap must be assigned inside the canvas bottom-end slot',
);

const compactFacts = readTagFacts(compactManifest(createManifestInheritanceFixture()));
assert.deepEqual(
  compactFacts.get('lr-fixture-child').cssParts.map(({ name }) => name),
  ['base', 'control'],
  'generated component docs must count inherited CSS parts from the compact manifest',
);
assert.deepEqual(
  compactFacts.get('lr-fixture-child').cssProperties.map(({ name }) => name),
  ['--lr-fixture-base-color', '--lr-fixture-child-color'],
  'generated component docs must count inherited CSS properties from the compact manifest',
);

assert.match(
  migration,
  /^<!-- GENERATED by scripts\/build-llms\.mjs from scripts\/fixtures\/component-inventory\.json/m,
);
assert.match(migration, /The codemod changes only `exact` and `rewritten`/);
assert.match(migration, /The JSON migration report records every rewrite and warning/);
assert.match(migration, /npx --package @aceshooting\/lyra-ui@<version> lyra-ui-migrate --check/);
assert.doesNotMatch(migration, /pnpm migrate-wa/, 'consumer migration docs must use the published CLI');
assert.match(migration, /`@aceshooting\/lyra-ui\/all\.js`/);
assert.match(migration, /root-excluded targets receive granular registration imports/);
assert.match(migration, /`OPTIONAL_PEER_REQUIRED`/);
assert.match(migration, /`REGISTRATION_CLOSURE_REQUIRED`/);
assert.match(migration, /`@awesome\.me\/webawesome` and `@awesome\.me\/webawesome-pro`/);
assert.match(migration, /standalone CSS/);
assert.match(migration, /Shoelace relationships are classified independently/);
assert.doesNotMatch(migration, /review ledger|reviewed independently|reviewed and recorded/);
assert.match(migration, /## Migrating Lyra 7 defaults/);
assert.match(migration, /lyra-ui-migrate --origin=lyra-v7 --check/);
assert.match(
  migration,
  /\| `lyra-v7` \| `<lr-popup>` \| `strategy="fixed"`, `placement="bottom-start"`, `distance="4"`, presence `flip`, presence `shift` \|/,
);
assert.match(
  migration,
  /\| `lyra-v7` \| `<lr-popover>` \| `placement="bottom-start"`, `distance="4"`, presence `without-arrow` \|/,
);
assert.match(migration, /It never\nrenames an `lr-\*` tag or import/);
const classifications = ['exact', 'rewritten', 'warning-required', 'conceptual-only', 'unsupported'];
for (const [label, upstream] of [
  ['Web Awesome', 'webawesome'],
  ['Shoelace', 'shoelace'],
]) {
  const mappings = inventory.mappings.filter((mapping) => mapping.upstream === upstream);
  const counts = Object.fromEntries(
    classifications.map((classification) => [
      classification,
      mappings.filter((mapping) => mapping.classification === classification).length,
    ]),
  );
  assert.ok(
    migration.includes(
      `| ${label} | ${counts.exact} | ${counts.rewritten} | ${counts['warning-required']} | ` +
        `${counts['conceptual-only']} | ${counts.unsupported} | ${counts.exact + counts.rewritten} | ` +
        `${counts['warning-required'] + counts['conceptual-only'] + counts.unsupported} |`,
    ),
  );
}
assert.match(
  migration,
  /\| `<sl-resize-observer>` \| `<lr-resize-observer>` \| `rewritten` \| Automatic: tag\/import plus events: sl-resize → lr-resize\. \|/,
);
assert.match(
  migration,
  /\| `<wa-data-grid>` \| `<lr-data-grid>` \| `rewritten` \| Automatic: tag\/import plus events: wa-cell-click → lr-cell-click;/,
);
assert.match(migration, /\| `<wa-include>` \| `<lr-include>` \| `warning-required` \| Manual:/);
assert.doesNotMatch(migration, /mechanical tag\/import rename|Documented 1:1 mirrors/);

const documentedSources = migration
  .split('\n')
  .map((line) => line.match(/^\| `<((?:wa|sl)-[a-z0-9-]+)>` \|/)?.[1])
  .filter(Boolean)
  .sort();
assert.deepEqual(
  documentedSources,
  inventory.mappings.map((mapping) => mapping.upstreamTag).sort(),
  'migration.md must document every inventory mapping exactly once',
);

assert.deepEqual(TYPE_ONLY_DECLARATION_PEERS, {
  react: '@aceshooting/lyra-ui/custom-elements-jsx',
  svelte: '@aceshooting/lyra-ui/svelte',
  vue: '@aceshooting/lyra-ui/vue',
});

const artifacts = build({ write: false });
const tokens = [...artifacts].find(([file]) => file.endsWith('/llms/tokens.md'))?.[1];
const peers = [...artifacts].find(([file]) => file.endsWith('/llms/peers.md'))?.[1];
const index = [...artifacts].find(([file]) => file.endsWith('/llms/index.md'))?.[1];
const table = [...artifacts].find(([file]) => file.endsWith('/llms/components/lr-table.md'))?.[1];
const streamingText = [...artifacts].find(([file]) => file.endsWith('/llms/components/lr-streaming-text.md'))?.[1];
assert.ok(tokens, 'build({ write: false }) must produce llms/tokens.md');
assert.ok(peers, 'build({ write: false }) must produce llms/peers.md');
assert.ok(index, 'build({ write: false }) must produce llms/index.md');
assert.ok(table, 'build({ write: false }) must produce per-tag component docs');
assert.ok(streamingText, 'build({ write: false }) must produce lr-streaming-text docs');

assert.match(index, /components\/lr-table\.js/);
assert.doesNotMatch(index, /path is NOT `components\/<tag>\/`/);
assert.match(table, /import '@aceshooting\/lyra-ui\/components\/lr-table\.js';/);
assert.match(table, /components\/data\/table\/table\.class\.js/);
assert.match(
  streamingText,
  /- \*\*Optional peers\*\* `dompurify`, `katex`, `marked`, `shiki` — see `llms\/peers\.md`/,
  'transitive peers must follow the double-quoted side-effect lr-streaming-text → lr-markdown registration edge',
);

assert.match(
  tokens,
  /^<!-- GENERATED by scripts\/build-llms\.mjs from scripts\/fixtures\/token-docs\.generated\.json/m,
);
assert.match(tokens, /## Direct theme-backed tokens \(262\)/);
assert.match(tokens, /## Derived and fixed tokens \(75\)/);
assert.match(tokens, /Aliases and computed values still follow/);
assert.match(tokens, /fixed contract constants are intentionally\nnot theme inputs/);
assert.doesNotMatch(tokens, /Each reads one `--lr-theme-\*` input/);
assert.match(tokens, /\| `--lr-color-brand` \| `var\(--lr-color-brand-fill-loud\)` \| forcedColors: `LinkText` \|/);
assert.match(tokens, /\| `--lr-mask-opaque` \| `#000` \| — \|/);
assert.match(
  tokens,
  /\| `--lr-color-surface` \| `--lr-theme-color-surface-default` \| `#fff` \| dark: `var\(--lr-theme-color-surface-default, #1a1a1a\)`<br>forcedColors: `Canvas` \|/,
);

assert.match(peers, /All 29 peers are \*\*optional\*\*/);
assert.match(peers, /\*\*Framework declaration peers \(3\)\.\*\*/);
assert.match(peers, /\*\*Component-loaded peers \(26\)\.\*\*/);

for (const [peer, entry] of Object.entries(TYPE_ONLY_DECLARATION_PEERS)) {
  const row = peers
    .split('\n')
    .find((line) => line.startsWith(`| \`${peer}\` |`));
  assert.ok(row, `${peer} must have an optional-peer row`);
  assert.ok(row.includes(`type-only \`${entry}\` entry`));
  assert.doesNotMatch(row, /not referenced by any component/);
}

assert.match(
  peers,
  /Those entry points emit empty\nJavaScript, no component imports these frameworks, and Lyra ships no runtime wrapper\./,
);

console.log('LLM peer classification tests passed.');
