#!/usr/bin/env node
// Builds every generated agent-facing reference artifact from the authored sources in `llms/`.
//
// Authored (edit these):
//   llms/00-preamble.md       intro paragraphs of llms-full.txt
//   llms/shared.md            foundation + cross-cutting notes (apply to the whole library)
//   llms/<family>.md          one file per src/components/<family>/ directory
//
// Generated (never edit; `pnpm run llms` rewrites them, CI diffs them):
//   llms-full.txt             concatenation, the single-file reference published since v1
//   llms/index.md             tag -> family/import/one-line-purpose routing table
//   llms/components/<tag>.md  one self-contained file per custom element (surgical agent reads)
//   llms/tokens.md            every --lr-* token and the --lr-theme-* input it reads
//   llms/peers.md             component -> optional peer dependency map
//   llms/migration.md         wa-*/sl-* -> lr-* rename table
//
// A component section is assigned to a family by the src/components/<family>/ directory its tag is
// declared in, so the docs can never drift from the source tree's own grouping.
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildMirrorMap } from './migrate-wa.mjs';

const packageDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const llmsDir = path.join(packageDir, 'llms');
const read = (...p) => readFileSync(path.join(packageDir, ...p), 'utf8');

/** Human-readable family titles, in the order they appear in llms-full.txt. */
export const FAMILIES = [
  ['forms', 'Form controls & inputs'],
  ['data', 'Data display, dashboards & flow canvas'],
  ['layout', 'Layout, navigation & structure'],
  ['overlays', 'Overlays, status & feedback'],
  ['utility', 'Utilities, formatting & observers'],
  ['media', 'Media, files & maps'],
  ['charts', 'Charts'],
  ['viewers', 'Document & file viewers'],
  ['conversation', 'Conversation & chat UI'],
  ['agent-tools', 'Agent tooling, tool calls & evaluation'],
  ['retrieval', 'Retrieval, knowledge graph & grounding'],
];

const GENERATED = (source) =>
  `<!-- GENERATED by scripts/build-llms.mjs from ${source} — do not edit this file. -->`;

// ---------------------------------------------------------------------------------------------
// Manifest facts: tag -> family, declaring module, and the registration entry point to import.
// ---------------------------------------------------------------------------------------------

/**
 * One-line purpose from a class's JSDoc: drop the leading "`<lr-x>` — " restatement, unwrap the
 * source's hard line breaks, and keep the first sentence (or the first clause, when the JSDoc opens
 * with a long enumeration).
 */
function summarize(description) {
  const flat = description.split('\n\n')[0].replace(/\s+/g, ' ').trim();
  const body = flat.replace(/^`?<?lr-[a-z0-9-]+>?`?\s*[—-]\s*/i, '');
  const sentence = body.match(/^(.+?\.)(?:\s|$)/)?.[1] ?? body;
  return sentence.length > 140 ? `${sentence.slice(0, 137).trimEnd()}...` : sentence;
}

export function readTagFacts(manifest) {
  const tags = new Map();
  for (const mod of manifest.modules ?? []) {
    const m = mod.path.match(/^src\/components\/([^/]+)\/([^/]+)\//);
    if (!m) continue;
    for (const decl of mod.declarations ?? []) {
      if (!decl.customElement || !decl.tagName) continue;
      // `foo.class.ts` declares the class; `foo.ts` next to it is the side-effect entry that
      // registers the tag — that is what a consumer imports.
      const entry = mod.path.replace(/\.class\.ts$/, '.ts').replace(/^src\//, '').replace(/\.ts$/, '.js');
      tags.set(decl.tagName, {
        tag: decl.tagName,
        family: m[1],
        className: decl.name,
        importPath: `@aceshooting/lyra-ui/${entry}`,
        modulePath: mod.path,
        purpose: summarize(decl.description ?? decl.summary ?? ''),
        cssParts: decl.cssParts ?? [],
        cssProperties: decl.cssProperties ?? [],
      });
    }
  }
  return tags;
}

// ---------------------------------------------------------------------------------------------
// Section parsing: a `## ` heading opens a section; `###` subheadings stay inside it.
// ---------------------------------------------------------------------------------------------

export function splitSections(text) {
  const lines = text.split('\n');
  const sections = [];
  let fenced = false;
  let current = null;
  for (const line of lines) {
    if (/^```/.test(line)) fenced = !fenced;
    if (!fenced && /^## /.test(line)) {
      current = { title: line.slice(3).trim(), lines: [line], tags: [] };
      sections.push(current);
      continue;
    }
    if (!current) continue;
    current.lines.push(line);
    if (!fenced && /^#{3,} /.test(line)) current.tags.push(...(line.match(/lr-[a-z0-9-]+/g) ?? []));
  }
  for (const s of sections) {
    s.tags = [...new Set([...(s.title.match(/lr-[a-z0-9-]+/g) ?? []), ...s.tags])];
    s.text = s.lines.join('\n').replace(/\n+$/, '');
  }
  return sections;
}

/** First sentence of a section's prose — used as the one-line purpose in the index. */
function firstSentence(section) {
  const body = section.text.split('\n').slice(1).join('\n');
  const prose = body
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .find((p) => p && !p.startsWith('#') && !p.startsWith('```') && !p.startsWith('|'));
  if (!prose) return '';
  const flat = prose.replace(/\n/g, ' ').replace(/\s+/g, ' ');
  const cut = flat.match(/^(.+?\.)(?:\s|$)/);
  return (cut ? cut[1] : flat).trim();
}

// ---------------------------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------------------------

function buildTokens() {
  const src = read('src', 'internal', 'tokens.styles.ts');
  const rows = [];
  for (const line of src.split('\n')) {
    const m = line.match(/^\s*(--lr-[a-z0-9-]+):\s*var\((--lr-theme-[a-z0-9-]+),\s*(.+?)\);\s*$/);
    if (m) rows.push({ token: m[1], input: m[2], fallback: m[3].trim() });
  }
  const plain = [];
  for (const line of src.split('\n')) {
    const m = line.match(/^\s*(--lr-[a-z0-9-]+):\s*(?!var\(--lr-theme)([^;]+);\s*$/);
    if (m) plain.push({ token: m[1], value: m[2].trim() });
  }
  const body = [
    GENERATED('src/internal/tokens.styles.ts'),
    '',
    '# Design tokens',
    '',
    'Every `lr-*` component resolves its styling through this two-layer token system, inherited from',
    '`LyraElement`:',
    '',
    '1. **`--lr-theme-*` — the application input layer.** Set these (on `:root`, or any ancestor of a',
    '   subtree) to retheme. This is the only supported theming mechanism; never hardcode a color,',
    '   spacing, or font value that fights it.',
    '2. **`--lr-*` — the internal layer.** Each reads one `--lr-theme-*` input with a hardcoded',
    '   fallback, so every component renders correctly with no theme configured at all.',
    '',
    'For a ready-made light/dark base, import `@aceshooting/lyra-ui/theme.css` once and put',
    '`class="lr-light"`/`class="lr-dark"` (or `data-lr-theme="light"`/`"dark"`) on an ancestor.',
    'Per-component `--lr-<component>-*` custom properties (listed in each component\'s own section)',
    'override a single element without touching the shared layer.',
    '',
    `## Themeable inputs (${rows.length})`,
    '',
    '| Internal token | `--lr-theme-*` input | Fallback |',
    '|---|---|---|',
    ...rows.map((r) => `| \`${r.token}\` | \`${r.input}\` | \`${r.fallback}\` |`),
  ];
  if (plain.length) {
    body.push(
      '',
      `## Derived tokens (${plain.length})`,
      '',
      'Computed from the layer above; not directly themeable.',
      '',
      '| Token | Value |',
      '|---|---|',
      ...plain.map((r) => `| \`${r.token}\` | \`${r.value}\` |`),
    );
  }
  return body.join('\n') + '\n';
}

function buildPeers(tagFacts) {
  const pkg = JSON.parse(read('package.json'));
  const peers = Object.keys(pkg.peerDependencies ?? {}).sort();
  const meta = pkg.peerDependenciesMeta ?? {};
  const srcRoot = path.join(packageDir, 'src', 'components');

  // Peers are attributed per tag by walking that tag's own module graph (its registration entry
  // plus every relative import it reaches), not per directory — components that share a directory
  // do not necessarily share a peer. Bare specifiers other than the peer itself end the walk.
  const peersForTag = (facts) => {
    const found = new Set();
    const seen = new Set();
    const queue = [path.join(packageDir, facts.modulePath.replace(/\.class\.ts$/, '.ts'))];
    while (queue.length) {
      const file = queue.pop();
      const resolved = [file, file.replace(/\.js$/, '.ts')].find((c) => existsSync(c) && c.endsWith('.ts'));
      if (!resolved || seen.has(resolved)) continue;
      seen.add(resolved);
      const text = readFileSync(resolved, 'utf8');
      for (const peer of peers) {
        if (new RegExp(`from '${peer}(?:/|')|import\\('${peer}(?:/|')`).test(text)) found.add(peer);
      }
      for (const m of text.matchAll(/(?:from|import\()\s*'(\.[^']+)'/g)) {
        queue.push(path.resolve(path.dirname(resolved), m[1]));
      }
    }
    return [...found];
  };

  const byPeer = new Map(peers.map((p) => [p, []]));
  for (const facts of tagFacts.values()) {
    for (const peer of peersForTag(facts)) byPeer.get(peer).push(facts.tag);
  }
  // Peers reached only from a non-component module (e.g. a shared loader) still get a row.
  const walkAll = new Set();
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (/\.ts$/.test(entry.name) && !/\.(test|stories)\.ts$/.test(entry.name)) {
        const text = readFileSync(full, 'utf8');
        for (const peer of peers) if (text.includes(`'${peer}`)) walkAll.add(peer);
      }
    }
  };
  walk(srcRoot);

  const rows = peers.map((peer) => ({
    peer,
    range: pkg.peerDependencies[peer],
    optional: meta[peer]?.optional !== false,
    tags: [...new Set(byPeer.get(peer))].sort(),
    seenAnywhere: walkAll.has(peer),
  }));

  return [
    GENERATED('package.json + src/components/'),
    '',
    '# Optional peer dependencies',
    '',
    `All ${peers.length} peers are **optional**: nothing here is needed to install or use the library,`,
    'and no component imports one eagerly. Install a peer only when you use a component that needs it.',
    '',
    '**How they load.** A component that needs a peer resolves it through a dynamic `import()` on first',
    'use, rendering an `<lr-skeleton>` placeholder with `aria-busy="true"` on the host while it settles.',
    'If the peer is genuinely absent, the component falls back to an empty/degraded render and logs one',
    '`console.warn` (deduped module-wide, not per instance) — it never throws and never blocks paint.',
    '`<lr-phone-input>` is the exception: it takes an explicit consumer-built adapter',
    '(`loadLibphonenumberAdapter()`) instead of importing `libphonenumber-js` itself.',
    '',
    '| Peer | Range | Needed by |',
    '|---|---|---|',
    ...rows.map(
      (r) =>
        `| \`${r.peer}\` | \`${r.range}\` | ${
          r.tags.length
            ? r.tags.map((t) => `\`${t}\``).join(', ')
            : r.seenAnywhere
              ? '_(loaded by a shared internal module)_'
              : '_(not referenced by any component)_'
        } |`,
    ),
    '',
  ].join('\n');
}

function buildMigration() {
  const { map } = buildMirrorMap(read('README.md'));
  const wa = [...map.entries()].filter(([from]) => from.startsWith('wa-')).sort();
  const sl = [...map.entries()].filter(([from]) => from.startsWith('sl-')).sort();
  const section = (title, rows, note) => [
    `## ${title} (${rows.length})`,
    '',
    note,
    '',
    '| From | To |',
    '|---|---|',
    ...rows.map(([from, to]) => `| \`<${from}>\` | \`<${to}>\` |`),
    '',
  ];
  return [
    GENERATED('README.md migration/catalog tables'),
    '',
    '# Migrating to `lr-*`',
    '',
    'Lyra has no runtime, theme, or token dependency on Web Awesome or Shoelace. Where a component',
    'mirrors one, it keeps the documented public vocabulary — attributes, slots, events, CSS parts and',
    'custom properties — under the `lr-` prefix, so the migration is a mechanical tag/import rename.',
    'Intentional differences are always called out in the component\'s own section',
    '(`llms/components/<tag>.md`); check it before assuming a 1:1 attribute match. Known example:',
    'Lyra\'s combobox uses `with-clear` where Web Awesome uses `clearable`.',
    '',
    'Also rewrite the import specifiers: `@awesome.me/webawesome` and `@shoelace-style/shoelace`',
    '-> `@aceshooting/lyra-ui` (per-component entry points are listed in `llms/index.md`).',
    '',
    'A tag absent from these tables has no documented counterpart — port it by hand, or check',
    '`llms/index.md` for a Lyra component that covers the same job under a different name.',
    '',
    ...section(
      'Web Awesome',
      wa,
      'Documented 1:1 mirrors. `wa-*` names not listed here are Web Awesome components Lyra does not mirror.',
    ),
    ...section(
      'Shoelace',
      sl,
      'Best-effort mapping: Web Awesome, not Lyra, is Shoelace\'s direct successor, so these agree less often.',
    ),
  ].join('\n');
}

function buildIndex(sectionsByFamily, tagFacts) {
  const out = [
    GENERATED('custom-elements.json + llms/<family>.md'),
    '',
    '# Component index',
    '',
    `${tagFacts.size} custom elements, grouped by the source family they live in.`,
    '',
    '**Reading one component.** Its reference file path is derived from the tag — no search needed:',
    '`llms/components/<tag>.md` (e.g. `llms/components/lr-table.md`). Each is self-contained: import',
    'path, optional peers, properties, events, slots, CSS parts, themeable custom properties, a usage',
    'snippet, and known gotchas — a few hundred tokens instead of the whole catalog.',
    '',
    '**Importing.** Every entry below shows the path to append to `@aceshooting/lyra-ui/components/`:',
    "`import '@aceshooting/lyra-ui/components/data/table/table.js';` registers `<lr-table>`. The path",
    'is NOT `components/<tag>/` — it always carries the family segment. Swap `.js` for `.class.js` to',
    'get the class without registering the tag.',
    '',
    '**Everything else.** Library-wide behavior (base class, events, form association, `locale`/',
    '`strings`, TypeScript, frameworks, SSR): `llms/shared.md`. Design tokens: `llms/tokens.md`.',
    'Optional peers: `llms/peers.md`. `wa-*`/`sl-*` renames: `llms/migration.md`.',
    '',
  ];
  for (const [family, title] of FAMILIES) {
    const sections = sectionsByFamily.get(family) ?? [];
    const tags = sections.flatMap((s) => s.tags);
    out.push(`## ${title} — \`components/${family}/\` (${tags.length})`, '');
    for (const section of sections) {
      const fallback = firstSentence(section);
      for (const tag of section.tags) {
        const facts = tagFacts.get(tag);
        if (!facts) continue;
        const shortPath = facts.importPath.replace('@aceshooting/lyra-ui/components/', '');
        out.push(`- \`${tag}\` · ${shortPath} — ${facts.purpose || fallback}`);
      }
    }
    out.push('');
  }
  return out.join('\n');
}

function buildComponentFile(tag, section, tagFacts, peersByTag) {
  const facts = tagFacts.get(tag);
  const shares = section.tags.filter((t) => t !== tag && tagFacts.has(t));
  const peers = peersByTag.get(tag) ?? [];
  const cssPartNames = facts.cssParts?.map((p) => p.name) ?? [];
  const cssPropNames = facts.cssProperties?.map((p) => p.name) ?? [];
  return [
    GENERATED(`llms/${facts.family}.md`),
    '',
    `# \`${tag}\``,
    '',
    `- **Import** \`import '${facts.importPath}';\` (registers the tag; side-effect import)`,
    `- **Class** \`${facts.className}\`, also available unregistered from` +
      ` \`${facts.importPath.replace(/\.js$/, '.class.js')}\``,
    `- **Family** \`components/${facts.family}/\` — see \`llms/index.md\` for its siblings`,
    peers.length
      ? `- **Optional peers** ${peers.map((p) => `\`${p}\``).join(', ') } — see \`llms/peers.md\``
      : '- **Optional peers** none',
    cssPartNames.length || cssPropNames.length
      ? `- **Themeable via** ${cssPartNames.length} part${cssPartNames.length === 1 ? '' : 's'}, ${cssPropNames.length} custom propert${cssPropNames.length === 1 ? 'y' : 'ies'} — see this component's own \`@csspart\`/\`@cssprop\` list below`
      : '- **Themeable via** nothing component-specific — inherits only the shared surface',
    shares.length
      ? `- **Documented with** ${shares.map((t) => `\`${t}\``).join(', ')} (same section below)`
      : null,
    '- **Library-wide behavior** (events, form association, `locale`/`strings`, tokens, TS types):' +
      ' `llms/shared.md`',
    '',
    '---',
    '',
    section.text,
    '',
  ]
    .filter((l) => l !== null)
    .join('\n');
}

// ---------------------------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------------------------

export function build({ write = true } = {}) {
  const manifest = JSON.parse(read('custom-elements.json'));
  const tagFacts = readTagFacts(manifest);

  const preamble = read('llms', '00-preamble.md').trimEnd();
  const shared = read('llms', 'shared.md').trimEnd();

  const sectionsByFamily = new Map();
  const sectionByTag = new Map();
  const problems = [];
  for (const [family] of FAMILIES) {
    const file = path.join(llmsDir, `${family}.md`);
    if (!existsSync(file)) {
      problems.push(`llms/${family}.md is missing.`);
      continue;
    }
    const sections = splitSections(readFileSync(file, 'utf8'));
    sectionsByFamily.set(family, sections);
    for (const section of sections) {
      for (const tag of section.tags) {
        const facts = tagFacts.get(tag);
        if (!facts) {
          problems.push(`llms/${family}.md documents \`${tag}\`, which no longer exists in custom-elements.json.`);
          continue;
        }
        if (facts.family !== family) {
          problems.push(
            `\`${tag}\` is documented in llms/${family}.md but declared in src/components/${facts.family}/ — move the section to llms/${facts.family}.md.`,
          );
        }
        if (sectionByTag.has(tag)) {
          problems.push(`\`${tag}\` is documented twice: "${sectionByTag.get(tag).title}" and "${section.title}".`);
          continue;
        }
        sectionByTag.set(tag, section);
      }
    }
  }
  for (const tag of tagFacts.keys()) {
    if (!sectionByTag.has(tag)) problems.push(`\`${tag}\` has no section in any llms/<family>.md.`);
  }
  if (problems.length) {
    throw new Error(`Cannot build llms artifacts:\n  - ${problems.join('\n  - ')}`);
  }

  // Peer map, reused by the per-component headers.
  const peersText = buildPeers(tagFacts);
  const peersByTag = new Map();
  for (const line of peersText.split('\n')) {
    const m = line.match(/^\| `([^`]+)` \| `[^`]*` \| (.*) \|$/);
    if (!m) continue;
    for (const tag of m[2].match(/lr-[a-z0-9-]+/g) ?? []) {
      (peersByTag.get(tag) ?? peersByTag.set(tag, []).get(tag)).push(m[1]);
    }
  }

  // llms-full.txt — the single-file reference, unchanged in role since v1.
  const contents = [
    '## Contents',
    '',
    'This file is the concatenation of the per-family sources in `llms/`. When only one component is',
    'in question, read `llms/components/<tag>.md` instead — it is the same text plus its import path,',
    'and costs a few hundred tokens instead of the whole catalog. `llms/index.md` maps every tag to its',
    'family and entry point.',
    '',
    '- **Foundation** — base class, form association, events, i18n, theming, TypeScript, frameworks,' +
      ' SSR, packaging (`llms/shared.md`)',
    ...FAMILIES.map(([family, title]) => {
      const tags = (sectionsByFamily.get(family) ?? []).flatMap((s) => s.tags).length;
      return `- **${title}** — ${tags} tags in \`components/${family}/\``;
    }),
    '- **Reference tables** — design tokens (`llms/tokens.md`), optional peers (`llms/peers.md`),' +
      ' `wa-*`/`sl-*` migration (`llms/migration.md`)',
  ].join('\n');

  const fullParts = [preamble, '', contents, '', '---', '', '# Foundation', '', shared, ''];
  for (const [family, title] of FAMILIES) {
    fullParts.push(`# ${title} (\`components/${family}/\`)`, '');
    for (const section of sectionsByFamily.get(family)) fullParts.push(section.text, '');
  }
  const full = fullParts.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';

  // llms.txt — the short index. Its catalog is generated from the same family sources, so its
  // taxonomy can never drift from llms-full.txt's (it used to carry its own hand-kept grouping).
  const shortIndex = [readFileSync(path.join(llmsDir, '00-llms-txt-intro.md'), 'utf8').trimEnd(), ''];
  for (const [family, title] of FAMILIES) {
    const tags = (sectionsByFamily.get(family) ?? []).flatMap((s) => s.tags);
    shortIndex.push(
      `- **${title}** (\`components/${family}/\`, ${tags.length}) — ${tags.map((t) => `\`${t}\``).join(', ')}`,
      '',
    );
  }

  const artifacts = new Map([
    [path.join(packageDir, 'llms-full.txt'), full],
    [path.join(packageDir, 'llms.txt'), `${shortIndex.join('\n').trimEnd()}\n`],
    [path.join(llmsDir, 'index.md'), buildIndex(sectionsByFamily, tagFacts)],
    [path.join(llmsDir, 'tokens.md'), buildTokens()],
    [path.join(llmsDir, 'peers.md'), peersText],
    [path.join(llmsDir, 'migration.md'), buildMigration()],
  ]);
  for (const [tag, section] of sectionByTag) {
    artifacts.set(
      path.join(llmsDir, 'components', `${tag}.md`),
      buildComponentFile(tag, section, tagFacts, peersByTag),
    );
  }

  if (write) {
    rmSync(path.join(llmsDir, 'components'), { recursive: true, force: true });
    mkdirSync(path.join(llmsDir, 'components'), { recursive: true });
    for (const [file, text] of artifacts) writeFileSync(file, text);
  }
  return artifacts;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const artifacts = build();
  console.log(
    `Built llms-full.txt + ${artifacts.size - 1} files under llms/ (${[...artifacts.values()].reduce((a, t) => a + t.length, 0)} bytes).`,
  );
}
