#!/usr/bin/env node
// Builds every generated agent-facing reference artifact from the authored sources in `llms/`.
// Authored (edit these):
//   llms/00-preamble.md       intro paragraphs of llms-full.txt
//   llms/shared/*.md          focused foundation + cross-cutting topic guides
//   llms/<family>.md          one file per src/components/<family>/ directory
// Generated (never edit; `pnpm run llms` rewrites them, CI diffs them):
//   llms/shared.md            legacy combined guide assembled from llms/shared/*.md
//   llms-full.txt             concatenation, the single-file reference published since v1
//   llms/index.md             tag -> family/import/one-line-purpose routing table
//   llms/components/<tag>.md  one file per custom element (surgical agent reads); a tag sharing a
//                             section with siblings gets its own facts plus a pointer to the
//                             section's primary tag file instead of a duplicated body
//   llms/tokens.md            direct --lr-theme-* mappings plus derived/fixed --lr-* tokens
//   llms/peers.md             component -> optional peer dependency map
//   llms/migration.md         wa-*/sl-* classification and codemod table
// A component section is assigned to a family by the src/components/<family>/ directory its tag is
// declared in, so the docs can never drift from the source tree's own grouping.
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  NORMALIZATION_SECTIONS,
  validateLocalMigrations,
  validateMappingNormalizations,
  validateMethodEdgeParity,
} from './component-inventory.mjs';
import {
  optionalPeersForComponent,
  runtimeModuleSpecifiers,
} from './generate-component-inventory.mjs';
import { formatDeprecationSubject } from './component-metadata.mjs';
import { expandManifestInheritance } from './manifest-compact.mjs';
import { isMainModule } from './is-main-module.mjs';
import { projectRenameLedger } from './lyra-rename-ledger.mjs';
import { readCurrentCompatibilityContextSync } from './check-published-compatibility.mjs';
import { readComponentMetadataSources, assembleComponentMetadata } from './component-metadata-source.mjs';
import { SHARED_COMPAT_ORDER, SHARED_TOPICS } from './shared-topics.mjs';

export { SHARED_TOPICS } from './shared-topics.mjs';

const packageDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const llmsDir = path.join(packageDir, 'llms');
const read = (...p) => readFileSync(path.join(packageDir, ...p), 'utf8');

/** Human-readable family titles, in the order they appear in llms-full.txt. */
export const FAMILIES = [
  ['forms', 'Form controls & inputs'],
  ['data', 'Data display, dashboards & flow canvas'],
  ['layout', 'Layout, navigation & structure'],
  ['overlays', 'Overlays, status & feedback'],
  ['utility', 'Utilities, formatting & observers'],
  ['media', 'Media, files & maps'],
  ['charts', 'Charts'],
  ['viewers', 'Document & file viewers'],
  ['conversation', 'Conversation & chat UI'],
  ['agent-tools', 'Agent tooling, tool calls & evaluation'],
  ['retrieval', 'Retrieval, knowledge graph & grounding'],
];

const GENERATED = (source) =>
  `<!-- GENERATED by scripts/build-llms.mjs from ${source} — do not edit this file. -->`;

/** Framework packages referenced only by the opt-in generated declaration entry points. */
export const TYPE_ONLY_DECLARATION_PEERS = Object.freeze({
  react: '@aceshooting/lyra-ui/custom-elements-jsx',
  svelte: '@aceshooting/lyra-ui/svelte',
  vue: '@aceshooting/lyra-ui/vue',
});

/**
 * Consumer-supplied child registrations needed by the compound markup documented for an owner.
 * These are deliberately usage metadata, not component-dependency edges: importing a group stays
 * granular, while a consumer copying its authored compound example gets every tag it uses.
 */
export const COMPOUND_USAGE_REGISTRATIONS = Object.freeze({
  'lr-checkbox-group': Object.freeze(['lr-checkbox']),
  'lr-radio-group': Object.freeze(['lr-radio', 'lr-radio-button']),
  'lr-tab-group': Object.freeze(['lr-tab', 'lr-tab-panel']),
});

// ---------------------------------------------------------------------------------------------
// Manifest facts: tag -> family, declaring module, and the registration entry point to import.
// ---------------------------------------------------------------------------------------------

/**
 * One-line purpose from a class's JSDoc: drop the leading "`<lr-x>` — " restatement, unwrap the
 * source's hard line breaks, and keep the first sentence (or the first clause, when the JSDoc opens
 * with a long enumeration).
 */
function summarize(description) {
  const flat = description.split('\n\n')[0].replace(/\s+/g, ' ').trim();
  const body = flat.replace(/^`?<?lr-[a-z0-9-]+>?`?\s*[—-]\s*/i, '');
  const sentence = body.match(/^(.+?\.)(?:\s|$)/)?.[1] ?? body;
  return sentence.length > 140 ? `${sentence.slice(0, 137).trimEnd()}...` : sentence;
}

export function readTagFacts(manifest) {
  const expandedManifest = expandManifestInheritance(manifest);
  const tags = new Map();
  for (const mod of expandedManifest.modules ?? []) {
    const m = mod.path.match(/^src\/components\/([^/]+)\/([^/]+)\//);
    if (!m) continue;
    for (const decl of mod.declarations ?? []) {
      if (!decl.customElement || !decl.tagName) continue;
      // `foo.class.ts` declares the class; `foo.ts` next to it is the side-effect entry that
      // registers the tag — that is what a consumer imports.
      const entry = mod.path.replace(/\.class\.ts$/, '.ts').replace(/^src\//, '').replace(/\.ts$/, '.js');
      tags.set(decl.tagName, {
        tag: decl.tagName,
        family: m[1],
        className: decl.name,
        importPath: `@aceshooting/lyra-ui/${entry}`,
        modulePath: mod.path,
        purpose: summarize(decl.description ?? decl.summary ?? ''),
        status: decl.status,
        since: decl.since,
        maturity: decl.maturity,
        deprecations: decl.deprecations ?? [],
        cssParts: decl.cssParts ?? [],
        cssProperties: decl.cssProperties ?? [],
      });
    }
  }
  return tags;
}

// ---------------------------------------------------------------------------------------------
// Section parsing: a `## ` heading opens a section; `###` subheadings stay inside it.
// ---------------------------------------------------------------------------------------------

export function splitSections(text) {
  const lines = text.split('\n');
  const sections = [];
  let fenced = false;
  let current = null;
  for (const line of lines) {
    if (/^```/.test(line)) fenced = !fenced;
    if (!fenced && /^## /.test(line)) {
      current = { title: line.slice(3).trim(), lines: [line], tags: [] };
      sections.push(current);
      continue;
    }
    if (!current) continue;
    current.lines.push(line);
    if (!fenced && /^#{3,} /.test(line)) current.tags.push(...(line.match(/lr-[a-z0-9-]+/g) ?? []));
  }
  for (const s of sections) {
    s.tags = [...new Set([...(s.title.match(/lr-[a-z0-9-]+/g) ?? []), ...s.tags])];
    s.text = s.lines.join('\n').replace(/\n+$/, '');
  }
  return sections;
}

// A positional "see the X note above/below" (or "<lr-other-tag>'s own ... above/below") reference
// only resolves while reading the whole authored `llms/<family>.md`. `buildComponentFile()` copies
// nothing but a single section's own `text` into `llms/components/<tag>.md` -- never the family
// preamble, and never a *different* section -- so a reference that reads fine in the family file
// can still dangle once split. Three shapes are checked, all deliberately narrow (a missed unusual
// phrasing is still fine prose; a false positive blocks every future `pnpm run llms`):
//   1. "<lr-other>'s own note/section/... above/below" naming a tag outside this section's own
//      `tags` -- that tag's content is never in this file, regardless of story order.
//   2. "<word(s)> note/section above/below" whose most distinctive word does not recur anywhere
//      else in this section's own text -- so there is nothing here for the reference to resolve to.
//   3. "this file's `<lr-other>` ... section" naming a tag outside this section's own `tags` --
//      unlike shapes 1-2, this phrasing carries no "above"/"below" at all (that is exactly how one
//      slipped past shapes 1-2 once already: reworded from "see the lr-graph section above" to
//      "this file's `lr-graph` section", which drops the literal word "above" while leaving the
//      same dangling cross-section reference intact). "This file" is true of the authored
//      `llms/<family>.md` but false of the generated per-tag file the reader actually lands on.
const POSITIONAL_TAG_REFERENCE_RE =
  /<(lr-[a-z0-9-]+)>`?'s own (?:notes?|sections?|explanations?|write-?ups?|documentation|docs|discussions?|treatments?)\b[^.]{0,40}?\b(above|below)\b/gi;
const POSITIONAL_NOTE_REFERENCE_RE = /\b([\w-]+(?:[ \t]+[\w-]+)?)[ \t]+(notes?|sections?)[ \t]+(above|below)\b/gi;
const POSITIONAL_SAME_FILE_SECTION_RE = /\bthis file'?s\s+`?(lr-[a-z0-9-]+)`?'?s?\s+section\b/gi;
const POSITIONAL_REFERENCE_STOPWORDS = new Set([
  'the', 'a', 'an', 'of', 'for', 'its', 'own', 'this', 'that', 'note', 'notes', 'section',
  'sections', 'see', 'and', 'or', 'with', 'from', 'to', 'in', 'on', 'at', 'is', 'are', 'per',
  'under', 'over',
]);

function positionalReferenceCandidateWords(phrase) {
  return phrase
    .split(/[^a-z0-9]+/i)
    .filter((word) => word.length >= 3 && !POSITIONAL_REFERENCE_STOPWORDS.has(word.toLowerCase()));
}

/** @returns {string[]} human-readable problems, empty when every positional reference resolves. */
export function findDanglingPositionalReferences(section) {
  const problems = [];
  const { text } = section;
  const ownTags = new Set(section.tags);

  for (const match of text.matchAll(POSITIONAL_TAG_REFERENCE_RE)) {
    const [snippet, referencedTag, direction] = match;
    if (ownTags.has(referencedTag)) continue;
    problems.push(
      `${section.title}: "${snippet.replace(/\s+/g, ' ')}" points ${direction} at \`${referencedTag}\`'s ` +
        `own section, which is a different section and will not be present in this component's ` +
        `generated llms/components/*.md file. Inline the referenced text or link to the published ` +
        `llms/components/${referencedTag}.md instead of a positional "${direction}".`,
    );
  }

  for (const match of text.matchAll(POSITIONAL_NOTE_REFERENCE_RE)) {
    const [snippet, phraseRaw, , direction] = match;
    const words = positionalReferenceCandidateWords(phraseRaw);
    if (words.length === 0) continue;
    const resolved = words.some((word) => {
      const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const occurrences = text.match(new RegExp(`\\b${escaped}\\b`, 'gi')) ?? [];
      return occurrences.length >= 2;
    });
    if (!resolved) {
      problems.push(
        `${section.title}: "${snippet.replace(/\s+/g, ' ')}" refers ${direction} to a note/section ` +
          `whose key word(s) [${words.join(', ')}] appear nowhere else in this section -- inline the ` +
          `referenced text instead of a positional "${direction}".`,
      );
    }
  }

  for (const match of text.matchAll(POSITIONAL_SAME_FILE_SECTION_RE)) {
    const [snippet, referencedTag] = match;
    if (ownTags.has(referencedTag)) continue;
    problems.push(
      `${section.title}: "${snippet.replace(/\s+/g, ' ')}" points at \`${referencedTag}\`'s own ` +
        `section via "this file's ... section", which is a different section and will not be ` +
        `present in this component's generated llms/components/*.md file. Inline the referenced ` +
        `text or link to the published llms/components/${referencedTag}.md instead.`,
    );
  }
  return problems;
}

/** First sentence of a section's prose — used as the one-line purpose in the index. */
function firstSentence(section) {
  const body = section.text.split('\n').slice(1).join('\n');
  const prose = body
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .find((p) => p && !p.startsWith('#') && !p.startsWith('```') && !p.startsWith('|'));
  if (!prose) return '';
  const flat = prose.replace(/\n/g, ' ').replace(/\s+/g, ' ');
  const cut = flat.match(/^(.+?\.)(?:\s|$)/);
  return (cut ? cut[1] : flat).trim();
}

export function validateCompoundUsageRegistrations(
  registrations,
  tagFacts,
  sectionByTag,
) {
  const problems = [];
  for (const [owner, relatedTags] of Object.entries(registrations)) {
    if (!tagFacts.has(owner)) {
      problems.push(`compound usage owner \`${owner}\` is not a public custom element`);
      continue;
    }
    if (!Array.isArray(relatedTags) || relatedTags.length === 0) {
      problems.push(`compound usage owner \`${owner}\` needs at least one related tag`);
      continue;
    }
    const section = sectionByTag.get(owner);
    const seen = new Set();
    for (const relatedTag of relatedTags) {
      if (typeof relatedTag !== 'string' || !/^lr-[a-z0-9-]+$/.test(relatedTag)) {
        problems.push(`compound usage owner \`${owner}\` has an invalid related tag`);
        continue;
      }
      if (relatedTag === owner) {
        problems.push(`compound usage owner \`${owner}\` cannot list itself as a related tag`);
      }
      if (seen.has(relatedTag)) {
        problems.push(`compound usage owner \`${owner}\` lists \`${relatedTag}\` more than once`);
      }
      seen.add(relatedTag);
      if (!tagFacts.has(relatedTag)) {
        problems.push(`compound usage owner \`${owner}\` refers to unknown tag \`${relatedTag}\``);
      }
      if (section && !new RegExp(`<${relatedTag}(?:\\s|/?>)`, 'u').test(section.text)) {
        problems.push(
          `compound usage owner \`${owner}\` does not use \`${relatedTag}\` in its authored section`,
        );
      }
    }
  }
  return problems;
}

// ---------------------------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------------------------

export function buildTokens() {
  const input = JSON.parse(read('scripts', 'fixtures', 'token-docs.generated.json'));
  if (
    input.schemaVersion !== 1 ||
    input.authority !== 'tokens/canonical-tokens.json' ||
    !Array.isArray(input.tokens)
  ) {
    throw new Error(
      'Cannot build token reference: token-docs.generated.json must be a schema-version 1 canonical-token projection.',
    );
  }
  const shared = input.tokens.filter((token) => token.scope === 'shared');
  if (
    shared.some(
      (token) =>
        typeof token.name !== 'string' ||
        !token.name.startsWith('--lr-') ||
        typeof token.values?.light !== 'string',
    )
  ) {
    throw new Error('Cannot build token reference: every shared token needs a name and light value.');
  }
  const rows = shared.filter((token) => typeof token.themeInput === 'string');
  const plain = shared.filter((token) => token.themeInput === undefined);
  // The themeInput read does not have to be the OUTERMOST var(): a token may wrap it in a
  // narrower-scope input first, which is how --lr-icon-button-size reads
  // --lr-icon-button-size-scope ahead of --lr-theme-icon-button-size. What the contract actually
  // requires is that the declared themeInput is read SOMEWHERE in the chain and has a fallback, so
  // find it and take its balanced argument rather than string-stripping a fixed prefix.
  const fallback = (token) => {
    const marker = `var(${token.themeInput}, `;
    const start = token.values.light.indexOf(marker);
    if (start === -1) {
      throw new Error(`${token.name}: light value must read its declared themeInput with a fallback.`);
    }
    let depth = 1;
    let i = start + marker.length;
    for (; i < token.values.light.length && depth > 0; i += 1) {
      const ch = token.values.light[i];
      if (ch === '(') depth += 1;
      else if (ch === ')') depth -= 1;
    }
    if (depth !== 0) {
      throw new Error(`${token.name}: light value has an unbalanced themeInput fallback.`);
    }
    return token.values.light.slice(start + marker.length, i - 1);
  };
  const modeOverrides = (token) =>
    ['dark', 'forcedColors', 'reducedMotion']
      .filter((mode) => token.values[mode] !== undefined)
      .map((mode) => `${mode}: \`${token.values[mode]}\``)
      .join('<br>') || '—';
  const body = [
    GENERATED('scripts/fixtures/token-docs.generated.json'),
    '',
    '# Design tokens',
    '',
    'Every `lr-*` component resolves its styling through this two-layer token system, inherited from',
    '`LyraElement`:',
    '',
    '1. **`--lr-theme-*` — the application input layer.** Set these (on `:root`, or any ancestor of a',
    '   subtree) to retheme. This is the only supported theming mechanism; never hardcode a color,',
    '   spacing, or font value that fights it.',
    '2. **`--lr-*` — the internal layer.** Direct theme-backed tokens read a `--lr-theme-*` input',
    '   with a built-in fallback. Other tokens are aliases, computed or environment-backed values,',
    '   or fixed contract constants. Every component renders correctly with no theme configured.',
    '',
    'For a ready-made light/dark base, import `@aceshooting/lyra-ui/theme.css` once and put',
    '`class="lr-light"`/`class="lr-dark"` (or `data-lr-theme="light"`/`"dark"`) on an ancestor.',
    'For the shadcn/ui look, also import `@aceshooting/lyra-ui/looks/shadcn.css` and select',
    '`data-lr-look="shadcn"` on the root or a scoped ancestor; look and mode remain independent.',
    'See [Styles and tokens](./shared/styles-and-tokens.md) for runtime and stylesheet options.',
    'Per-component `--lr-<component>-*` custom properties (listed in each component\'s own section)',
    'override a single element without touching the shared layer.',
    '',
    '**Consumer-scope exception: the focus ring.** `--lr-focus-ring` and its three parts',
    '(`-width`/`-color`/`-offset`) are the one layer-2 group `theme.css` also declares at document',
    'scope, on `:root` and on both mode selectors. They exist to serve a CONSUMER-authored idiom —',
    'the Web Awesome `outline: var(--wa-focus-ring)` that migrating projects already have — and that',
    'rule is written against the consumer\'s own element, where a `:host`-only token resolves to',
    'nothing. An empty `var()` makes the whole `outline` declaration invalid at computed-value time,',
    'and because `outline` does not inherit, the ring did not degrade: it DISAPPEARED, silently, with',
    'no console warning. So `outline: var(--lr-focus-ring); outline-offset:',
    'var(--lr-focus-ring-offset);` now works wherever you write it, provided `theme.css` is imported.',
    'Every component still re-derives all four on its own `:host`, so component rendering is',
    'unchanged.',
    '',
    '> **Why layer 1 is not merely *preferred* but *required*: an ancestor `--lr-*` override does',
    '> not survive a nested component boundary.** Every component re-derives the whole `--lr-*` layer',
    '> from `--lr-theme-*` on its **own** `:host` (that is what `LyraElement`\'s shared token',
    '> stylesheet does). So setting, say, `--lr-color-warning-quiet` on an application element does',
    '> apply to that element and to plain nested markup — it looks right in review and in a shallow',
    '> `getComputedStyle` probe — but it is **reset at the first `lr-*` element inside another',
    '> `lr-*` element\'s shadow root** (a badge inside a table cell, say), which re-derives it back to',
    '> the library fallback. The override degrades silently, the deeper it is consumed, with no',
    '> warning. Always set the `--lr-theme-*` input instead: that layer is read through `var()` at',
    '> every level, so it inherits across every boundary. Per-component `--lr-<component>-*`',
    '> properties are the other safe lever, because no component re-declares another component\'s',
    '> namespace — with six named exceptions declared by the shared base layer itself; see below.',
    '',
    '**The `--lr-*` names that look per-component but are not.** `--lr-focus-ring-width`,',
    '`--lr-focus-ring-color`, `--lr-focus-ring-offset` (the consumer-scope exception above),',
    '`--lr-icon-button-size`, `--lr-otp-input-segment-size`, and `--lr-popover-viewport-clamp` are',
    'the only tokens the shared base `:host` block in `internal/tokens.styles.ts` declares under a',
    'component-looking name — each reads its own `--lr-theme-*` input there. Because that block is',
    'mixed into every `lr-*` component, all six behave like the internal layer above, not like an',
    'ordinary per-component property: a rule that sets one of them directly on an ancestor is reset',
    'at the first intervening `lr-*` component and never reaches a nested target — even though',
    'setting it directly on the target element itself still works, which is what makes the failure',
    'look arbitrary rather than systematic. Reach through a subtree with `--lr-theme-focus-ring-*`,',
    '`--lr-theme-otp-input-segment-size`, or `--lr-theme-popover-viewport-clamp` instead.',
    '`--lr-icon-button-size` additionally has a dedicated subtree-scoped input,',
    '`--lr-icon-button-size-scope`, which an ancestor rule can set without reaching for the',
    'application-wide `--lr-theme-icon-button-size`. The subtree input wins where both are set,',
    'because the shipped `design-tokens.css` declares the theme tier on `:root` and a var() chain',
    'only falls through for a property that is unset everywhere. Every other `--lr-<component>-*`',
    'token — including',
    'the rest of `lr-icon-button`\'s own (`-radius`, `-background`, `-color`, `-border`, and their',
    '`-hover`/`-active` variants) — is not re-declared anywhere in the shared layer and inherits',
    'normally from an ancestor.',
    '',
    `## Direct theme-backed tokens (${rows.length})`,
    '',
    '| Internal token | `--lr-theme-*` input | Light/default fallback | Mode overrides |',
    '|---|---|---|---|',
    ...rows.map(
      (token) =>
        `| \`${token.name}\` | \`${token.themeInput}\` | \`${fallback(token)}\` | ${modeOverrides(token)} |`,
    ),
  ];
  if (plain.length) {
    body.push(
      '',
      `## Derived and fixed tokens (${plain.length})`,
      '',
      'These do not directly read a `--lr-theme-*` input. Aliases and computed values still follow',
      'the tokens or environment values they reference; fixed contract constants are intentionally',
      'not theme inputs.',
      '',
      '| Token | Light/default value | Mode overrides |',
      '|---|---|---|',
      ...plain.map(
        (token) => `| \`${token.name}\` | \`${token.values.light}\` | ${modeOverrides(token)} |`,
      ),
    );
  }
  return body.join('\n') + '\n';
}

function publishablePeerRange(peer, range) {
  if (typeof range !== 'string' || range.length === 0) {
    throw new TypeError(`${peer}: peer dependency needs a non-empty string range`);
  }
  if (!range.startsWith('workspace:')) return range;
  const publishable = range.slice('workspace:'.length);
  if (!publishable || publishable === '*' || publishable === '^' || publishable === '~') {
    throw new Error(
      `${peer}: cannot derive published peer guidance from unresolved workspace range ${range}`,
    );
  }
  return publishable;
}

export function buildPeers(tagFacts) {
  const pkg = JSON.parse(read('package.json'));
  const peers = Object.keys(pkg.peerDependencies ?? {}).sort();
  const componentPeers = peers.filter((peer) => !(peer in TYPE_ONLY_DECLARATION_PEERS));
  const meta = pkg.peerDependenciesMeta ?? {};
  const srcRoot = path.join(packageDir, 'src', 'components');

  // Use the inventory's parser-backed module traversal so docs and autoloader prerequisites are
  // generated from one runtime-edge definition. Comments, examples, strings, and type-only imports
  // cannot become peer requirements, and capability-gated composed children follow the same rule.
  const peersForTag = (facts) =>
    optionalPeersForComponent(
      { registrationModule: facts.modulePath.replace(/\.class\.ts$/, '.ts') },
      pkg,
    ).filter((peer) => componentPeers.includes(peer));

  const byPeer = new Map(peers.map((p) => [p, []]));
  for (const facts of tagFacts.values()) {
    for (const peer of peersForTag(facts)) byPeer.get(peer).push(facts.tag);
  }
  // Peers reached only from a non-component module (e.g. a shared loader) still get a row.
  const walkAll = new Set();
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (/\.ts$/.test(entry.name) && !/\.(test|stories)\.ts$/.test(entry.name)) {
        const text = readFileSync(full, 'utf8');
        for (const specifier of runtimeModuleSpecifiers(text, full)) {
          for (const peer of componentPeers) {
            if (specifier === peer || specifier.startsWith(`${peer}/`)) walkAll.add(peer);
          }
        }
      }
    }
  };
  walk(srcRoot);

  const rows = peers.map((peer) => ({
    peer,
    range: publishablePeerRange(peer, pkg.peerDependencies[peer]),
    optional: meta[peer]?.optional !== false,
    tags: [...new Set(byPeer.get(peer))].sort(),
    seenAnywhere: walkAll.has(peer),
    declarationEntry: TYPE_ONLY_DECLARATION_PEERS[peer],
  }));

  const typeOnlyCount = peers.length - componentPeers.length;

  return [
    GENERATED('package.json + src/components/'),
    '',
    '# Optional peer dependencies',
    '',
    `All ${peers.length} peers are **optional**: nothing here is needed to install or use the library,`,
    'but they have two deliberately different roles.',
    '',
    `**Framework declaration peers (${typeOnlyCount}).** React, Svelte, and Vue are compile-time peers`,
    'only when a project imports their matching opt-in declaration entry. Those entry points emit empty',
    'JavaScript, no component imports these frameworks, and Lyra ships no runtime wrapper.',
    '',
    `**Component-loaded peers (${componentPeers.length}).** No component imports one eagerly. Install a`,
    'peer only when you use a component that needs it.',
    '',
    '**How they load.** Most component-loaded peers resolve through a dynamic `import()` on first use.',
    'Loading and failure behavior is component-specific: placeholders, `aria-busy`, visible localized',
    'fallbacks, events, and console diagnostics vary. Consult the owning component section for its exact',
    'loading and failure contract. `<lr-phone-input>` is the exception: it takes an explicit',
    'consumer-built adapter',
    '(`loadLibphonenumberAdapter()`) instead of importing `libphonenumber-js` itself.',
    '',
    '**SheetJS (`xlsx`).** The supported `>=0.20.3 <0.21.0` releases are distributed by SheetJS',
    'from its CDN, not the public npm registry (whose newest release is 0.18.5). Install the peer',
    'with `pnpm add https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz` (or the equivalent npm',
    'command), matching the range below. The npm-published 0.18.5 release has unresolved advisories;',
    'do not run `npm audit fix --force` to address them when it proposes downgrading lyra-ui. That',
    'changes the component library version without installing a supported SheetJS release.',
    '',
    '**PDF.js (`pdfjs-dist`).** Installing the peer is not sufficient on its own: PDF.js renders in a',
    'web worker, and it has no way to locate that worker inside a bundled app. If nothing configures',
    'it, every document load rejects with `No "GlobalWorkerOptions.workerSrc" specified.` Point',
    '`<lr-pdf-viewer>` at the worker chunk your own bundler emitted, either per element with',
    '`worker-src` (`<lr-pdf-viewer worker-src="/assets/pdf.worker.mjs">`) or once at startup by',
    "importing `pdfjs-dist` yourself and setting `GlobalWorkerOptions.workerSrc`. An already-configured",
    'global always wins, and because that global is process-wide the first viewer to load settles it',
    'for the page.',
    '',
    '| Peer | Range | Needed by |',
    '|---|---|---|',
    ...rows.map(
      (r) =>
        `| \`${r.peer}\` | \`${r.range}\` | ${
          r.tags.length
            ? r.tags.map((t) => `\`${t}\``).join(', ')
            : r.declarationEntry
              ? `type-only \`${r.declarationEntry}\` entry (no runtime import)`
            : r.seenAnywhere
              ? '_(loaded by a shared internal module)_'
              : '_(not referenced by any component)_'
        } |`,
    ),
    '',
  ].join('\n');
}

/**
 * README's `| Component | Mirrors | Notes |` (Web Awesome) and `| Shoelace | Lyra | Migration note |`
 * (Shoelace) mirror tables each carry a free-text note per row -- e.g. the typed `<lr-chart>`
 * subclasses' "type locked" caveat -- keyed off the upstream tag(s) that row documents. Table
 * detection mirrors buildMirrorMap (scripts/migrate-wa.mjs), but that helper keeps only the tag
 * columns for codemod purposes and discards this third column; this parses it back out so a real
 * per-row caveat can be forwarded into the generated migration disposition instead of silently
 * dropped for every mapping.
 */
function parseReadmeMirrorNotes(readmeText) {
  const notes = new Map();
  let mode = null;
  for (const rawLine of readmeText.split('\n')) {
    const line = rawLine.trim();
    if (/^\|\s*Component\s*\|\s*Mirrors\s*\|\s*Notes\s*\|$/.test(line)) {
      mode = 'wa';
      continue;
    }
    if (/^\|\s*Shoelace\s*\|\s*Lyra\s*\|\s*Migration note\s*\|$/.test(line)) {
      mode = 'sl';
      continue;
    }
    if (!line.startsWith('|')) {
      mode = null;
      continue;
    }
    if (!mode) continue;
    const cells = line.split('|').slice(1, -1).map((cell) => cell.trim());
    if (cells.length < 3 || !cells[2]) continue;
    const tagCell = mode === 'sl' ? cells[0] : cells[1];
    const tags =
      mode === 'sl'
        ? [...tagCell.matchAll(/<sl-([a-z0-9-]+)>/g)].map((match) => `sl-${match[1]}`)
        : [...tagCell.matchAll(/`((?:wa|sl)-[a-z0-9-]+)`/g)].map((match) => match[1]);
    for (const tag of tags) {
      if (!notes.has(tag)) notes.set(tag, cells[2]);
    }
  }
  return notes;
}

/**
 * Consumer reference for the Lyra-to-Lyra rename profiles, generated from the same ledger the CLI
 * embeds, so a documented rename can never differ from the one the codemod performs. Ledger
 * completeness is gated by check-migration-coverage.mjs, not here, so docs still build while a
 * deprecation waits for its entry.
 */
export function buildLyraRenameReference(renameLedger, inventory, { exportDeprecations = [], compatibilityContext = null } = {}) {
  const projection = projectRenameLedger(renameLedger, inventory, { exportDeprecations, compatibilityContext });
  const cell = (value) => String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
  const lines = [];
  for (const profile of projection.profiles) {
    const from = `Lyra ${profile.fromMajor}`;
    const to = `Lyra ${profile.toMajor}`;
    const hasRetired = [...profile.reviews, ...profile.moduleReviews].some(entry => entry.removedIn) || Object.values(compatibilityContext?.records ?? {}).some(entry => entry.state === 'retired' && Number(entry.policy.removalNotBefore.split('.')[0]) === profile.aliasRemovalMajor);
    lines.push(
      `## Migrating from ${from} to ${to} (\`--origin=${profile.origin}\`)`,
      '',
      `${from} minor releases and ${to} rename some Lyra-only attributes, properties, events, CSS parts,`,
      hasRetired ? 'custom properties and slots. Published names retired in this installed release remain migration inputs.' : 'custom properties and slots. Each previous name keeps working as a deprecated alias until',
      `${hasRetired ? 'Removed aliases no longer work at runtime.' : `Lyra ${profile.aliasRemovalMajor} removes it.`} Names mirrored from Web Awesome or Shoelace, and their defaults, never`,
      hasRetired ? 'change. Run the CLI of the installed package after upgrading; historical profiles remain available. It' : `change. Run the CLI of the installed package after upgrading, within ${from} or to ${to}. It`,
      'applies only the entries the installed release ships, so running it again after a later upgrade',
      'picks up the rest:',
      '',
      '```bash',
      `npx lyra-ui-migrate --origin=${profile.origin} --diff src > ${profile.origin}.patch`,
      `npx lyra-ui-migrate --origin=${profile.origin} --check --report=${profile.origin}-migration.json src`,
      '```',
      '',
      '`--diff` prints a patch and writes nothing. The profile rewrites a name only where the rewrite',
      'cannot change what the site reaches: attribute, property and slot bindings on the component in',
      'HTML, Lit, JSX, Vue, Svelte and Angular templates; `exportparts` and `::part()` or attribute',
      'selectors that name the component; and calls rooted at `querySelector(\'lr-…\')`, `closest()` or',
      '`createElement()`. Events bubble and custom properties inherit, so a listener moves only when no',
      'other component already dispatches the new name, and an unowned listener or any custom-property',
      'use only when, in addition, every component with the old name renamed it the same way and the',
      'scanned code never dispatches the old name itself. Everything else is reported with a location;',
      hasRetired ? 'review removed names before running the migrated application.' : 'the old name keeps working meanwhile.',
      '',
      '| Code | Reported when |',
      '|---|---|',
      '| `RENAME_REVIEW` | An old name at a site that does not prove its component, or where another component keeps the name. |',
      '| `RENAME_TARGET_SHARED_REVIEW` | The new name is already used by another component, so renaming would widen the site. |',
      '| `NAME_GAINED_OWNER_REVIEW` | A listener, `::part()` selector or declaration of a name that more components use after the upgrade. |',
      '| `POLARITY_REVIEW` | A boolean replaced by its inverse is bound, assigned or selected, or set statically where a framework assigns properties. |',
      '| `DETAIL_SHAPE_REVIEW` | A listener may receive an event whose detail changed; details cannot be aliased. |',
      '| `RETIRED_EVENT_REVIEW` | A listener or event-name string may use an alias already removed in the target release; review its replacement and listener reach. |',
      '| `PROPERTY_CHANGE_REVIEW` | A property keeps its name but changes its accepted values or behavior; review the assignment without rewriting an ambiguous runtime value. |',
      '| `DEPRECATED_MEMBER_REVIEW`, `DEPRECATED_CONTENT_REVIEW` | A deprecated member, tag or kind of slotted content without a mechanical replacement. |',
      '| `DEPRECATED_MODULE_REVIEW` | A deprecated module, stylesheet, named export, window event or root attribute. Its replacement needs a semantic review. |',
      '| `MODULE_NAMESPACE_REVIEW` | A namespace, dynamic import or CommonJS module access whose exported bindings need review. |',
      '| `RENAME_CONFLICT_REVIEW` | The element already binds the new name, or the same receiver already listens to it with the same handler. |',
      '| `UNUSED_ACKNOWLEDGEMENT` | An acknowledgement comment matches no report. |',
      '',
      'After reviewing a site, add a comment containing `lyra-migrate-reviewed: CODE:name` (for example',
      '`DETAIL_SHAPE_REVIEW:lr-close`) on the reported line, alone on the line above it, or directly before',
      'the element\'s opening tag. Acknowledged reports no longer fail `--check`. Re-running the profile',
      'is idempotent. Templates rendered on the server must be re-rendered after migrating, because Lit',
      'hydration compares template strings.',
      '',
    );
    const total = [profile.renames, profile.defaults, profile.detailChanges, profile.propertyChanges ?? [], profile.retiredEvents ?? [], profile.reviews, profile.slotContent, profile.moduleReviews]
      .reduce((sum, entries) => sum + entries.length, 0);
    if (total === 0) {
      lines.push(`No ${from} names are scheduled to change yet.`, '');
      continue;
    }
    if (profile.renames.length) {
      lines.push(
        '| Component | Kind | Deprecated name | New name | Handling |',
        '|---|---|---|---|---|',
        ...profile.renames.map((entry) => {
          const handling = entry.polarity === 'inverted'
            ? 'Inverted boolean: static HTML and Lit attributes rewritten, everything else reported'
            : entry.kind === 'css-property' || entry.kind === 'event'
              ? 'Rewritten where the reach is unchanged, otherwise reported'
              : entry.kind === 'attribute' && !entry.reflects
                ? 'Rewritten on the component; selectors reported (not reflected)'
                : 'Rewritten where the component is proven';
          return `| \`<${entry.tag}>\` | ${entry.kind} | \`${cell(entry.from)}\` | \`${cell(entry.to)}\` | ${handling} |`;
        }),
        '',
      );
    }
    if (profile.defaults.length) {
      lines.push(
        `| Component | Attribute | Inserted when absent to keep the ${from} default |`,
        '|---|---|---|',
        ...profile.defaults.map((entry) =>
          `| \`<${entry.tag}>\` | \`${entry.attribute}\` | ${entry.value === true ? `presence \`${entry.attribute}\`` : `\`${entry.attribute}="${cell(entry.value)}"\``} |`),
        '',
      );
    }
    if (profile.detailChanges.length) {
      lines.push(
        `| Component | Event | Detail change in ${to} (reported, never rewritten) |`,
        '|---|---|---|',
        ...profile.detailChanges.map((entry) => `| \`<${entry.tag}>\` | \`${entry.event}\` | ${cell(entry.summary)} |`),
        '',
      );
    }
    if (profile.retiredEvents?.length) {
      lines.push(
        `The following aliases were still published in ${from} and are removed in ${to}. They are`,
        'reported without rewriting: move listeners and matching removals together, preserve unrelated',
        'events with the same name, and check nested event targets and existing canonical handlers.',
        '',
        `| Component | Removed event | Replacement | Migration review |`,
        '|---|---|---|---|',
        ...profile.retiredEvents.map((entry) => `| \`<${entry.tag}>\` | \`${entry.event}\` | \`${entry.replacement}\` | ${cell(entry.summary)} |`),
        '',
      );
    }
    if (profile.propertyChanges?.length) {
      lines.push(
        `| Component | Property | Semantic change in ${to} (reported, never rewritten) |`,
        '|---|---|---|',
        ...profile.propertyChanges.map((entry) => `| \`<${entry.tag}>\` | \`${entry.property}\` | ${cell(entry.summary)} |`),
        '',
      );
    }
    if (profile.reviews.length) {
      lines.push(
        `| Component | Kind | Deprecated name | Replacement (manual) |`,
        '|---|---|---|---|',
        ...profile.reviews.map((entry) => {
          const replacement = entry.replacement;
          const name = entry.kind === 'slot' && entry.name === '' ? '(default slot)' : `\`${cell(entry.name)}\``;
          return `| \`<${entry.tag}>\` | ${entry.kind} | ${name} | \`${cell(replacement)}\` |`;
        }),
        '',
      );
    }
    if (profile.slotContent.length) {
      lines.push(
        '| Component | Slot | Reported content | Change |',
        '|---|---|---|---|',
        ...profile.slotContent.map((entry) =>
          `| \`<${entry.tag}>\` | ${entry.slot === '' ? 'default' : `\`${cell(entry.slot)}\``} | ` +
          `${entry.report ? entry.report.map((element) => `\`<${element}>\``).join(', ') : `anything but ${entry.allow.map((element) => `\`<${element}>\``).join(', ')}`} | ` +
          `${cell(entry.summary)} |`),
        '',
      );
    }
    if (profile.moduleReviews.length) {
      lines.push(
        'Module migrations are report-only. Named imports and re-exports establish export ownership;',
        'namespace, dynamic and CommonJS imports require a module-level review. Window event listeners,',
        'root attribute bindings and selectors are reported without requiring a local module import.',
        'Computed module paths, computed event/attribute names and application re-export chains still',
        'need manual inspection. Review event detail, saved preferences and selector scope before updating.',
        '',
        '| Kind | Deprecated module or name | Replacement (manual) | Removal no earlier than |',
        '|---|---|---|---|',
        ...profile.moduleReviews.map((entry) => {
          return `| ${entry.kind} | \`${cell(entry.module ? `${entry.module}#${entry.name}` : entry.name)}\` | ${cell(entry.replacement)} | ${entry.removedIn ? `Removed in ${entry.removedIn}` : entry.removalNotBefore} |`;
        }),
        '',
      );
    }
  }
  return lines;
}

export function buildMigration({ compatibilityContext = readCurrentCompatibilityContextSync(packageDir) } = {}) {
  const inventory = JSON.parse(read('scripts', 'fixtures', 'component-inventory.json'));
  const renameLedger = JSON.parse(read('scripts', 'fixtures', 'lyra-renames.json'));
  const exportDeprecations = assembleComponentMetadata(readComponentMetadataSources(packageDir)).exportDeprecations;
  const readmeNotes = parseReadmeMirrorNotes(read('README.md'));
  const classifications = [
    'exact',
    'rewritten',
    'warning-required',
    'conceptual-only',
    'unsupported',
  ];
  const ruleSections = [
    'attributes',
    'properties',
    'events',
    'slots',
    'parts',
    'cssProperties',
    'methods',
    'defaults',
  ];
  if (
    inventory.schemaVersion !== 1 ||
    !Array.isArray(inventory.components) ||
    !Array.isArray(inventory.mappings) ||
    !Array.isArray(inventory.localMigrations)
  ) {
    throw new Error('Cannot build migration reference: component-inventory.json must use schema version 1.');
  }
  const localMigrationFindings = validateLocalMigrations(inventory);
  if (localMigrationFindings.length > 0) {
    throw new Error(`Cannot build migration reference: ${localMigrationFindings.join('; ')}`);
  }

  const components = new Map(inventory.components.map((component) => [component.tag, component]));
  const componentTags = new Set(components.keys());
  const upstreams = new Map(
    Object.values(inventory.upstreams ?? {}).flatMap((upstream) =>
      (upstream.components ?? []).map((component) => [component.tag, component]),
    ),
  );
  const seen = new Set();
  for (const mapping of inventory.mappings) {
    if (
      !mapping ||
      typeof mapping.upstreamTag !== 'string' ||
      !mapping.upstreamTag ||
      seen.has(mapping.upstreamTag) ||
      !['webawesome', 'shoelace'].includes(mapping.upstream) ||
      !classifications.includes(mapping.classification) ||
      !mapping.rewrites ||
      Object.keys(mapping.rewrites).some((section) => !ruleSections.includes(section)) ||
      ruleSections.some((section) => !Array.isArray(mapping.rewrites[section]))
    ) {
      throw new Error(`Cannot build migration reference: invalid mapping ${mapping?.upstreamTag ?? '<unknown>'}.`);
    }
    if (
      mapping.normalizations !== undefined &&
      (!mapping.normalizations ||
        Object.keys(mapping.normalizations).some((section) => !NORMALIZATION_SECTIONS.includes(section)) ||
        NORMALIZATION_SECTIONS.some((section) => !Array.isArray(mapping.normalizations[section])))
    ) {
      throw new Error(`Cannot build migration reference: invalid normalizations for ${mapping.upstreamTag}.`);
    }
    const normalizationFindings = validateMappingNormalizations(mapping, {
      upstream: upstreams.get(mapping.upstreamTag)?.surface,
      target: components.get(mapping.targetTag)?.surface,
    });
    if (normalizationFindings.length > 0) {
      throw new Error(`Cannot build migration reference: ${normalizationFindings.join('; ')}`);
    }
    const methodEdgeFindings = validateMethodEdgeParity(mapping, {
      upstream: upstreams.get(mapping.upstreamTag)?.surface,
      target: components.get(mapping.targetTag)?.surface,
    });
    if (methodEdgeFindings.length > 0) {
      throw new Error(`Cannot build migration reference: ${methodEdgeFindings.join('; ')}`);
    }
    seen.add(mapping.upstreamTag);
  }

  const count = (classification, upstream = null) =>
    inventory.mappings.filter(
      (mapping) => mapping.classification === classification && (!upstream || mapping.upstream === upstream),
    ).length;
  // These legacy mirror aliases use the original placeholder floor (10.0.0); that floor is not
  // their removal schedule. Keep the consumer-facing list derived from the same authored
  // deprecation records rather than maintaining a second policy list in migration prose.
  const upstreamProtectedAliases = inventory.components.flatMap((component) =>
    (component.maturity?.deprecations ?? [])
      .filter((entry) => entry.removalNotBefore === '10.0.0')
      .map((entry) => ({ tag: component.tag, ...entry })),
  );
  const automatic = (upstream = null) => count('exact', upstream) + count('rewritten', upstream);
  const manual = (upstream = null) => inventory.mappings.filter(
    (mapping) =>
      (!upstream || mapping.upstream === upstream) &&
      !['exact', 'rewritten'].includes(mapping.classification),
  ).length;
  const escapeCell = (value) => String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
  const summarizeRules = (mapping) => {
    const rules = [];
    for (const section of ruleSections) {
      for (const rule of mapping.rewrites[section]) {
        if (section === 'defaults') {
          rules.push(
            rule.action === 'insert-if-absent'
              ? `insert ${rule.member}=${String(rule.value)}`
              : `${rule.member}: ${String(rule.from)} → ${String(rule.to)}`,
          );
        } else {
          rules.push(`${section}: ${rule.from} → ${rule.to}`);
        }
      }
    }
    return rules.join('; ');
  };
  const summarizeNormalizations = (mapping) => {
    const defaults = (mapping.normalizations?.defaultEquivalences ?? []).map(
      (rule) => `${rule.member} defaults ${String(rule.upstream)} ≡ ${String(rule.target)}`,
    );
    const inferred = (mapping.normalizations?.inferredAttributeSuppressions ?? []).map(
      (rule) => `${rule.attribute} is analyzer-inferred for property-only ${rule.property}`,
    );
    const entries = [...defaults, ...inferred];
    return entries.length > 0 ? ` Equivalent surface representation: ${entries.join('; ')}; no source rewrite.` : '';
  };
  const noteSuffix = (mapping) => {
    const note = mapping.notes || readmeNotes.get(mapping.upstreamTag);
    if (!note) return '';
    return ` ${note}${/[.!?]$/.test(note) ? '' : '.'}`;
  };
  const disposition = (mapping) => {
    if (mapping.classification === 'exact') {
      return `Automatic: tag and supported side-effect registration import.${summarizeNormalizations(mapping)}${noteSuffix(mapping)}`;
    }
    if (mapping.classification === 'rewritten') {
      return `Automatic: tag/import plus ${summarizeRules(mapping)}.${summarizeNormalizations(mapping)}`;
    }
    return `Manual: ${mapping.rationale || 'inspect the target contract before porting.'}`;
  };
  const section = (title, upstream, note) => {
    const rows = inventory.mappings
      .filter((mapping) => mapping.upstream === upstream)
      .sort((left, right) => left.upstreamTag.localeCompare(right.upstreamTag));
    return [
      `## ${title} (${rows.length})`,
      '',
      note,
      '',
      '| From | Lyra target or candidate | Classification | Disposition |',
      '|---|---|---|---|',
      ...rows.map((mapping) => {
        const target = mapping.targetTag
          ? componentTags.has(mapping.targetTag)
            ? `\`<${mapping.targetTag}>\``
            : `not shipped (\`<${mapping.targetTag}>\` candidate)`
          : '—';
        return `| \`<${mapping.upstreamTag}>\` | ${target} | \`${mapping.classification}\` | ${escapeCell(disposition(mapping))} |`;
      }),
      '',
    ];
  };
  return [
    GENERATED('scripts/fixtures/component-inventory.json + scripts/fixtures/lyra-renames.json'),
    '',
    '# Migrating to `lr-*`',
    '',
    'Migration decisions come from the pinned, schema-validated component inventory. A matching name',
    'does not by itself prove API compatibility. The codemod changes only `exact` and `rewritten`',
    'mappings; `warning-required`, `conceptual-only`, `unsupported`, and unknown tags stay unchanged',
    'and receive location-aware warnings.',
    '',
    'The version-matched CLI ships with the package and runs without a repository checkout.',
    'Replace `<version>` with the installed Lyra major/minor/patch you are targeting:',
    '',
    '```bash',
    'npx --package @aceshooting/lyra-ui@<version> lyra-ui-migrate --check --report=lyra-migration.json src',
    '```',
    '',
    '`--check` never writes source files and exits nonzero while rewrites or warnings remain, which',
    'makes it suitable for CI after an applied migration.',
    '',
    'The supported upstream identities are `@awesome.me/webawesome` and `@awesome.me/webawesome-pro`',
    'for Web Awesome, plus `@shoelace-style/shoelace`. The tool scans HTML, standalone CSS,',
    'JavaScript, TypeScript, JSX, Vue, Svelte, MDX, and Markdown. It rewrites inventory-declared',
    'tags, members, defaults, and supported side-effect registration imports.',
    'Imports with bindings remain manual because exported names cannot be inferred safely. An',
    'aliased component value that uses a rewritten member blocks that mapping across the scanned',
    'target set, preventing a registration import from changing while an old member remains. A root',
    'Web Awesome or Shoelace registration import changes only when that package identity and tier',
    'prove the registration closure and no manual component use exists anywhere in the scanned target',
    'set. Root-included targets use `@aceshooting/lyra-ui/all.js`; root-excluded targets receive granular registration imports.',
    'An automatic-looking tag with no matching side-effect registration in the scanned target set',
    'stays unchanged with `REGISTRATION_CLOSURE_REQUIRED`; include the registration-owning entry file',
    'in the scan instead of accepting an inert `lr-*` result.',
    'Targets with optional runtime peers also emit an `OPTIONAL_PEER_REQUIRED` report entry naming',
    'each package that must be installed.',
    'Migrated Web Awesome and Shoelace icon tags emit `BEHAVIOR_REVIEW_REQUIRED` because Lyra\'s',
    'dependency-free default library contains only `add`, `check`, `close`, `search`, `menu`,',
    '`chevron-left`, `chevron-right`, `chevron-down`, `calendar`, `command`, and `trash`.',
    'Replace other names explicitly or provide their vocabulary with',
    "`registerIconLibrary('default', { resolver })`.",
    'Re-running the tool is idempotent; comments, prose, partial strings, and unrelated packages are',
    'left alone.',
    '',
    'The JSON migration report records every rewrite and warning with its file, line, column,',
    'origin, tag/member, action, target, and warning code. Run without `--check` only after inspecting',
    'that report and the target component reference in `llms/components/<tag>.md`.',
    '',
    '`dir` and `lang` are platform-global HTML passthrough attributes, not component-member drift.',
    'Web Awesome\'s `did-ssr` is its runtime hydration marker, not an authored member to recreate or',
    'rename on a Lyra component. The inventory records these exclusions explicitly.',
    '',
    ...buildLyraRenameReference(renameLedger, inventory, { exportDeprecations, compatibilityContext }),
    '## Upstream-protected compatibility spellings',
    '',
    `These ${upstreamProtectedAliases.length} legacy spellings remain supported while their corresponding Web Awesome or Shoelace surface publishes them. Prefer the current Lyra spelling for new code. Their recorded \`removalNotBefore\` value is a minimum, not an automatic removal date or permission to remove a still-mirrored spelling.`,
    '',
    '| Lyra surface | Retained spelling | Preferred spelling for new code |',
    '|---|---|---|',
    ...upstreamProtectedAliases.map((entry) => {
      const retained = entry.kind === 'part'
        ? `::part(${entry.name})`
        : entry.kind === 'property'
          ? `${entry.name} / ${entry.attribute}`
          : entry.name;
      const preferred = entry.replacement?.usage ?? entry.replacement?.name ?? 'review the current API';
      return `| \`<${entry.tag}>\` | \`${escapeCell(retained)}\` | \`${escapeCell(preferred)}\` |`;
    }),
    '',
    'For `lr-icon`, `autoWidth` is a CSS-level alias for `canvas="auto"`; an explicit `canvas` value wins. Review selector reach before changing existing `[auto-width]` rules. The migration tool does not blanket-rewrite these protected spellings.',
    '',
    '## Classification summary',
    '',
    '| Ecosystem | Exact | Rewritten | Warning required | Conceptual only | Unsupported | Automatic | Manual |',
    '|---|---:|---:|---:|---:|---:|---:|---:|',
    ...[
      ['Web Awesome', 'webawesome'],
      ['Shoelace', 'shoelace'],
    ].map(
      ([label, upstream]) =>
        `| ${label} | ${count('exact', upstream)} | ${count('rewritten', upstream)} | ${count('warning-required', upstream)} | ${count('conceptual-only', upstream)} | ${count('unsupported', upstream)} | ${automatic(upstream)} | ${manual(upstream)} |`,
    ),
    `| **Total** | **${count('exact')}** | **${count('rewritten')}** | **${count('warning-required')}** | **${count('conceptual-only')}** | **${count('unsupported')}** | **${automatic()}** | **${manual()}** |`,
    '',
    ...section(
      'Web Awesome',
      'webawesome',
      'The pinned Web Awesome manifest is authoritative for this inventory; only rows marked automatic are codemod inputs.',
    ),
    ...section(
      'Shoelace',
      'shoelace',
      'Shoelace relationships are classified independently; a same-suffix tag is never treated as proof of compatibility.',
    ),
  ].join('\n');
}

/** A package export specifier (`./x.js`) as the full import specifier a consumer writes. */
function packageSpecifier(specifier) {
  return specifier === '.' ? '@aceshooting/lyra-ui' : `@aceshooting/lyra-ui/${specifier.replace(/^\.\//, '')}`;
}

/**
 * The generated `llms/index.md` section for `component-metadata.json#exportDeprecations`:
 * deprecated entry points, types and runtime exports have no component reference to live in. Empty when
 * nothing is deprecated, so the index carries no placeholder heading.
 */
export function buildExportDeprecationsSection(records) {
  if (!records?.length) return '';
  const lines = records.map((entry) => {
    const subject = entry.module
      ? `**Deprecated ${entry.kind}** \`${entry.name}\` from \`${packageSpecifier(entry.module)}\``
      : `**Deprecated ${entry.kind === 'stylesheet' ? 'stylesheet' : 'entry point'}** \`${packageSpecifier(entry.name)}\``;
    const replacementKind = entry.replacement?.kind === 'entry-point'
      ? 'entry point'
      : entry.replacement?.kind ?? 'API';
    const replacement = entry.replacement?.usage ?? entry.replacement?.name;
    return `- ${subject} since \`${entry.since}\`; use ${replacementKind} \`${replacement}\`; ` +
      `removal not before \`${entry.removalNotBefore}\` — ${entry.rationale}`;
  });
  return [
    '## Deprecated package exports',
    '',
    'These package exports, stylesheets and global DOM contracts still work but are deprecated. Each names its',
    'replacement and the earliest release that may remove it, under the deprecation policy in',
    '`llms/shared.md`.',
    '',
    ...lines,
    '',
  ].join('\n');
}

function buildIndex(sectionsByFamily, tagFacts, exportDeprecations = []) {
  const out = [
    GENERATED('custom-elements.json + llms/<family>.md'),
    '',
    '# Component index',
    '',
    `${tagFacts.size} custom elements, grouped by the source family they live in.`,
    '',
    '**Reading one component.** Its reference file path is derived from the tag — no search needed:',
    '`llms/components/<tag>.md` (e.g. `llms/components/lr-table.md`): import path, optional peers,',
    'properties, events, slots, CSS parts, themeable custom properties, a usage snippet, and known',
    'gotchas — a few hundred tokens instead of the whole catalog. A tag documented together with',
    'siblings (e.g. `lr-combobox` / `lr-option`) still gets its own generated facts (import path,',
    'class, status, deprecations, optional peers), but the properties, events, slots, usage snippet,',
    'and gotchas live once in the primary sibling\'s file; the secondary tag\'s file carries a one-line',
    'pointer to it instead of a duplicated copy.',
    '',
    '**Importing.** Registration paths are stable aliases derived from the tag:',
    "`import '@aceshooting/lyra-ui/components/lr-table.js';` registers `<lr-table>` and remains",
    'valid if its internal family folder moves. Class-only `.class.js` entries intentionally keep',
    'their owning family path and do not register the tag.',
    '',
    '**Library-wide topics.** Focused guides cover imports and registration (`llms/shared/imports-and-registration.md`),',
    'the v23-to-v24 upgrade path (`llms/shared/v23-to-v24-migration.md`),',
    'events and types (`llms/shared/events-and-types.md`), forms and accessibility',
    '(`llms/shared/forms-and-accessibility.md`), styles and tokens',
    '(`llms/shared/styles-and-tokens.md`), native styles and utilities',
    '(`llms/shared/native-styles-and-utilities.md`), localization and RTL',
    '(`llms/shared/localization-and-rtl.md`), frameworks and SSR',
    '(`llms/shared/frameworks-and-ssr.md`), AI and optional peers (`llms/shared/ai-and-peers.md`),',
    'and testing and utilities (`llms/shared/testing-and-utilities.md`). The combined',
    'compatibility guide remains at `llms/shared.md`. Design tokens: `llms/tokens.md`.',
    'Optional peers: `llms/peers.md`. Safe `wa-*`/`sl-*` migration: `llms/migration.md`.',
    '',
  ];
  for (const [family, title] of FAMILIES) {
    const sections = sectionsByFamily.get(family) ?? [];
    const tags = sections.flatMap((s) => s.tags);
    out.push(`## ${title} — \`components/${family}/\` (${tags.length})`, '');
    for (const section of sections) {
      const fallback = firstSentence(section);
      for (const tag of section.tags) {
        const facts = tagFacts.get(tag);
        if (!facts) continue;
        const shortPath = `${tag}.js`;
        out.push(
          `- \`${tag}\` · ${shortPath} · \`${facts.status}\` since \`${facts.since}\` — ` +
            `${facts.purpose || fallback}`,
        );
      }
    }
    out.push('');
  }
  const exportSection = buildExportDeprecationsSection(exportDeprecations);
  if (exportSection) out.push(exportSection);
  return out.join('\n');
}

/**
 * The tag whose generated `llms/components/<tag>.md` carries a multi-tag section's full body text.
 * `section.tags` is already ordered title-tags-first (see splitSections), so its first entry is
 * exactly "the first lr-* tag in the section's title line; if ambiguous, the first tag found".
 */
export function primaryTagOfSection(section) {
  return section.tags[0];
}

export function buildComponentFile(
  tag,
  section,
  tagFacts,
  peersByTag,
  { familyHasBreakingNotes = false } = {},
) {
  const facts = tagFacts.get(tag);
  const primaryTag = primaryTagOfSection(section);
  const isPrimary = tag === primaryTag;
  const shares = section.tags.filter((t) => t !== tag && tagFacts.has(t));
  const peers = peersByTag.get(tag) ?? [];
  const cssPartNames = facts.cssParts?.map((p) => p.name) ?? [];
  const cssPropNames = facts.cssProperties?.map((p) => p.name) ?? [];
  const compoundUsageRegistrations = COMPOUND_USAGE_REGISTRATIONS[tag] ?? [];
  const deprecationLines = facts.deprecations.map((entry) => {
    const subject = formatDeprecationSubject(entry, tag);
    const replacement = entry.replacement?.usage ?? entry.replacement?.name;
    return `- **Deprecated ${entry.kind}** ${subject} since \`${entry.since}\`; use ` +
      `${entry.replacement?.kind ?? 'API'} \`${replacement}\`; removal not before ` +
      `\`${entry.removalNotBefore}\` — ${entry.rationale}`;
  });
  // A section shared by several tags publishes its full body only once, in the primary tag's file
  // (the first tag named in the section's own title) -- every sibling gets its own generated facts
  // above plus this one-line pointer instead of a duplicated copy of the shared prose.
  const documentedWithLine = isPrimary
    ? shares.length
      ? `- **Documented with** ${shares.map((t) => `\`${t}\``).join(', ')} (same section below)`
      : null
    : `- **Documented with** \`${primaryTag}\`: see [${primaryTag}.md](./${primaryTag}.md).`;
  return [
    GENERATED(`llms/${facts.family}.md`),
    '',
    `# \`${tag}\``,
    '',
    `- **Import** \`import '@aceshooting/lyra-ui/components/${tag}.js';\` ` +
      '(stable tag alias; registers the tag)',
    compoundUsageRegistrations.length
      ? '- **Compound usage registrations** ' +
        compoundUsageRegistrations
          .map(
            (relatedTag) =>
              `\`import '@aceshooting/lyra-ui/components/${relatedTag}.js';\``,
          )
          .join(', ') +
        ` — required by the consumer-supplied child tags in this reference; usage-only, not ` +
        `registration dependencies of \`${tag}\``
      : null,
    `- **Class** \`${facts.className}\`, also available unregistered from` +
      ` \`${facts.importPath.replace(/\.js$/, '.class.js')}\``,
    `- **Family** \`components/${facts.family}/\` — see \`llms/index.md\` for its siblings`,
    `- **Status** \`${facts.status}\` since \`${facts.since}\` — see the maturity and deprecation` +
      ' policy in `llms/shared.md`',
    '- **Release history** [CHANGELOG.md](../../CHANGELOG.md)' +
      (familyHasBreakingNotes
        ? `; family-wide breaking-change summaries: [${facts.family}](https://github.com/aceshooting/lyra-ui/blob/main/packages/lyra-ui/llms/${facts.family}.md)`
        : ''),
    ...(deprecationLines.length ? deprecationLines : ['- **Deprecations** none']),
    peers.length
      ? `- **Optional peers** ${peers.map((p) => `\`${p}\``).join(', ') } — see \`llms/peers.md\``
      : '- **Optional peers** none',
    cssPartNames.length || cssPropNames.length
      ? `- **Themeable via** ${cssPartNames.length} part${cssPartNames.length === 1 ? '' : 's'}, ${cssPropNames.length} custom propert${cssPropNames.length === 1 ? 'y' : 'ies'} — see ${isPrimary ? "this component's own `@csspart`/`@cssprop` list below" : `\`${primaryTag}.md\``}`
      : '- **Themeable via** nothing component-specific — inherits only the shared surface',
    documentedWithLine,
    '- **Library-wide behavior** (events, form association, `locale`/`strings`, tokens, TS types):' +
      ' `llms/shared.md`',
    '',
    ...(isPrimary ? ['---', '', section.text, ''] : []),
  ]
    .filter((l) => l !== null)
    .join('\n');
}

const SHARED_CHANGELOG_LINK = '[CHANGELOG.md](../CHANGELOG.md)';
const ROOT_CHANGELOG_LINK = '[CHANGELOG.md](./CHANGELOG.md)';

const SHARED_STYLE_CONTINUATION = '### Composing looks, surfaces and density';
const SHARED_ACCESSIBILITY_CONTINUATION = '### Host accessible names and compatibility properties';
const FOCUSED_NATIVE_STYLES_START = '<!-- focused-native-styles:start -->';
const FOCUSED_NATIVE_STYLES_END = '<!-- focused-native-styles:end -->';

function stripFocusedNativeStylesPointer(source, sourcePath) {
  const start = source.indexOf(FOCUSED_NATIVE_STYLES_START);
  const end = source.indexOf(FOCUSED_NATIVE_STYLES_END);
  if (start < 0 || end < start || source.indexOf(FOCUSED_NATIVE_STYLES_START, start + 1) >= 0 ||
    source.indexOf(FOCUSED_NATIVE_STYLES_END, end + 1) >= 0) {
    throw new Error(`${sourcePath} must contain exactly one focused native-styles pointer block.`);
  }
  return source.slice(0, start) + source.slice(end + FOCUSED_NATIVE_STYLES_END.length);
}

function splitSharedSections(text, sourcePath) {
  const sections = new Map();
  let title = null;
  let section = '';
  const finish = () => {
    if (title === null) return;
    if (sections.has(title)) throw new Error(`${sourcePath} repeats shared section "${title}".`);
    sections.set(title, section.trimEnd() + '\n');
  };
  for (const line of text.split(/(?<=\n)/u)) {
    const match = line.match(/^## (.+?)\s*\n$/u);
    if (match) {
      finish();
      title = match[1];
      section = line;
    } else if (title !== null) {
      section += line;
    } else if (line.trim()) {
      throw new Error(`${sourcePath} has content before its first H2 section.`);
    }
  }
  finish();
  return sections;
}

function replaceExactlyOnce(text, source, replacement, label) {
  const count = text.split(source).length - 1;
  if (count !== 1) throw new Error(`Expected one ${label}, found ${count}.`);
  return text.replace(source, replacement);
}

/** Read focused shared sources and assemble the stable combined route and anchor order. */
export function buildSharedReferences() {
  const sections = new Map();
  for (const [name, title, routeMode] of SHARED_TOPICS) {
    if (routeMode === 'index-only') continue;
    const sourcePath = `llms/shared/${name}.md`;
    const authoredSource = read('llms', 'shared', `${name}.md`).trimEnd();
    const source = name === 'styles-and-tokens'
      ? stripFocusedNativeStylesPointer(authoredSource, sourcePath)
      : authoredSource;
    const heading = `# ${title}`;
    if (!source.startsWith(`${heading}\n`)) {
      throw new Error(`${sourcePath} must start with "${heading}".`);
    }
    for (const [sectionTitle, sectionText] of splitSharedSections(
      source.slice(heading.length).trimStart(),
      sourcePath,
    )) {
      if (sections.has(sectionTitle)) {
        throw new Error(`Shared section "${sectionTitle}" is authored more than once.`);
      }
      sections.set(sectionTitle, sectionText);
    }
  }

  const stylesPath = 'llms/shared/styles-and-tokens.md';
  const stylesSource = read('llms', 'shared', 'styles-and-tokens.md');
  const styleTail = `${SHARED_STYLE_CONTINUATION}${stylesSource.split(SHARED_STYLE_CONTINUATION)[1] ?? ''}`;
  if (stylesSource.split(SHARED_STYLE_CONTINUATION).length !== 2) {
    throw new Error(`${stylesPath} must contain exactly one ${SHARED_STYLE_CONTINUATION}.`);
  }
  const accessPath = 'llms/shared/forms-and-accessibility.md';
  const accessSource = read('llms', 'shared', 'forms-and-accessibility.md');
  const accessTail = `${SHARED_ACCESSIBILITY_CONTINUATION}${accessSource.split(SHARED_ACCESSIBILITY_CONTINUATION)[1] ?? ''}`;
  if (accessSource.split(SHARED_ACCESSIBILITY_CONTINUATION).length !== 2) {
    throw new Error(`${accessPath} must contain exactly one ${SHARED_ACCESSIBILITY_CONTINUATION}.`);
  }

  const themeStyles = sections.get('Theming and design tokens');
  const accessibility = sections.get('Accessibility contract');
  if (!themeStyles?.includes(SHARED_STYLE_CONTINUATION) || !accessibility?.includes(SHARED_ACCESSIBILITY_CONTINUATION)) {
    throw new Error('Shared topic continuation headings must remain after their source sections.');
  }
  sections.set(
    'Theming and design tokens',
    themeStyles.slice(0, themeStyles.indexOf(SHARED_STYLE_CONTINUATION)).trimEnd() + '\n',
  );
  sections.set(
    'Accessibility contract',
    accessibility.slice(0, accessibility.indexOf(SHARED_ACCESSIBILITY_CONTINUATION)).trimEnd() + '\n',
  );

  const missing = SHARED_COMPAT_ORDER.filter((title) => !sections.has(title));
  const extra = [...sections.keys()].filter((title) => !SHARED_COMPAT_ORDER.includes(title));
  if (missing.length || extra.length) {
    throw new Error(
      `Shared reference sections differ from the compatibility inventory; missing: ${missing.join(', ') || 'none'}; extra: ${extra.join(', ') || 'none'}.`,
    );
  }

  let assembled = [...SHARED_COMPAT_ORDER.map((title) => sections.get(title)), styleTail, accessTail]
    .join('\n')
    .replace(/\n{3,}/gu, '\n\n')
    .trimEnd();
  assembled = replaceExactlyOnce(
    assembled,
    '../../CHANGELOG.md',
    '../CHANGELOG.md',
    'shared topic changelog path',
  );
  assembled = replaceExactlyOnce(
    assembled,
    './styles-and-tokens.md#reading-the-resolved-tokens-from-your-own-components--tokens-rootcss',
    '#reading-the-resolved-tokens-from-your-own-components--tokens-rootcss',
    'native styles cross-topic anchor route',
  );
  assembled = replaceExactlyOnce(
    assembled,
    './styles-and-tokens.md#',
    '#',
    'shared topic style anchor route',
  );
  assembled = replaceExactlyOnce(
    assembled,
    './testing-and-utilities.md#',
    '#',
    'shared cross-topic anchor route',
  );
  const compatibility =
    `${GENERATED('llms/shared/*.md')}\n${assembled}\n`;
  const sourceChangelog = '[CHANGELOG.md](../CHANGELOG.md)';
  const occurrences = compatibility.split(sourceChangelog).length - 1;
  if (occurrences !== 1) {
    throw new Error(`Expected exactly one ${sourceChangelog} in assembled llms/shared.md, found ${occurrences}.`);
  }
  return { compatibility };
}

export function rewriteSharedLinksForRoot(text) {
  const occurrences = text.split(SHARED_CHANGELOG_LINK).length - 1;
  if (occurrences !== 1) {
    throw new Error(
      `Expected exactly one ${SHARED_CHANGELOG_LINK} in llms/shared.md, found ${occurrences}.`,
    );
  }
  return text.replace(SHARED_CHANGELOG_LINK, ROOT_CHANGELOG_LINK);
}

// ---------------------------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------------------------

export function build({ write = true } = {}) {
  const manifest = JSON.parse(read('custom-elements.json'));
  const tagFacts = readTagFacts(manifest);

  const preamble = read('llms', '00-preamble.md').trimEnd();
  const sharedReferences = buildSharedReferences();
  const shared = sharedReferences.compatibility.trimEnd();
  const rootShared = rewriteSharedLinksForRoot(shared);

  const sectionsByFamily = new Map();
  const sectionByTag = new Map();
  const problems = [];
  for (const [tag, facts] of tagFacts) {
    if (!['stable', 'experimental'].includes(facts.status) ||
        !/^(?:\d+\.\d+\.\d+|unreleased)$/.test(facts.since ?? '')) {
      problems.push(`\`${tag}\` has no valid CEM status/since metadata.`);
    }
  }
  for (const [family] of FAMILIES) {
    const file = path.join(llmsDir, `${family}.md`);
    if (!existsSync(file)) {
      problems.push(`llms/${family}.md is missing.`);
      continue;
    }
    const sections = splitSections(readFileSync(file, 'utf8'));
    sectionsByFamily.set(family, sections);
    for (const section of sections) problems.push(...findDanglingPositionalReferences(section));
    for (const section of sections) {
      for (const tag of section.tags) {
        const facts = tagFacts.get(tag);
        if (!facts) {
          problems.push(`llms/${family}.md documents \`${tag}\`, which no longer exists in custom-elements.json.`);
          continue;
        }
        if (facts.family !== family) {
          problems.push(
            `\`${tag}\` is documented in llms/${family}.md but declared in src/components/${facts.family}/ — move the section to llms/${facts.family}.md.`,
          );
        }
        if (sectionByTag.has(tag)) {
          problems.push(`\`${tag}\` is documented twice: "${sectionByTag.get(tag).title}" and "${section.title}".`);
          continue;
        }
        sectionByTag.set(tag, section);
      }
    }
  }
  for (const tag of tagFacts.keys()) {
    if (!sectionByTag.has(tag)) problems.push(`\`${tag}\` has no section in any llms/<family>.md.`);
  }
  problems.push(
    ...validateCompoundUsageRegistrations(
      COMPOUND_USAGE_REGISTRATIONS,
      tagFacts,
      sectionByTag,
    ),
  );
  if (problems.length) {
    throw new Error(`Cannot build llms artifacts:\n  - ${problems.join('\n  - ')}`);
  }

  // Peer map, reused by the per-component headers.
  const peersText = buildPeers(tagFacts);
  const peersByTag = new Map();
  for (const line of peersText.split('\n')) {
    const m = line.match(/^\| `([^`]+)` \| `[^`]*` \| (.*) \|$/);
    if (!m) continue;
    for (const tag of m[2].match(/lr-[a-z0-9-]+/g) ?? []) {
      (peersByTag.get(tag) ?? peersByTag.set(tag, []).get(tag)).push(m[1]);
    }
  }

  // llms-full.txt — the single-file reference, unchanged in role since v1.
  const contents = [
    '## Contents',
    '',
    'This file is the concatenation of the per-family sources in `llms/`. When only one component is',
    'in question, read `llms/components/<tag>.md` instead — for a tag documented on its own, that file',
    'holds the same text plus its import path; for a tag documented together with siblings, it holds',
    'the generated facts (import path, status, peers, and so on) plus a pointer to the primary',
    'sibling\'s file for the shared prose. Either way it costs a few hundred tokens instead of the',
    'whole catalog. `llms/index.md` maps every tag to its family and entry point.',
    '',
    '- **Foundation** — base class, form association, events, i18n, theming, TypeScript, frameworks,' +
      ' SSR, packaging (`llms/shared.md`)',
    ...FAMILIES.map(([family, title]) => {
      const tags = (sectionsByFamily.get(family) ?? []).flatMap((s) => s.tags).length;
      return `- **${title}** — ${tags} tags in \`components/${family}/\``;
    }),
    '- **Reference tables** — design tokens (`llms/tokens.md`), optional peers (`llms/peers.md`),' +
      ' `wa-*`/`sl-*` migration (`llms/migration.md`)',
  ].join('\n');

  const fullParts = [preamble, '', contents, '', '---', '', '# Foundation', '', rootShared, ''];
  for (const [family, title] of FAMILIES) {
    fullParts.push(`# ${title} (\`components/${family}/\`)`, '');
    for (const section of sectionsByFamily.get(family)) fullParts.push(section.text, '');
  }
  const full = fullParts.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';

  // llms.txt — the short index. Its catalog is generated from the same family sources, so its
  // taxonomy can never drift from llms-full.txt's (it used to carry its own hand-kept grouping).
  const shortIndex = [readFileSync(path.join(llmsDir, '00-llms-txt-intro.md'), 'utf8').trimEnd(), ''];
  for (const [family, title] of FAMILIES) {
    const tags = (sectionsByFamily.get(family) ?? []).flatMap((s) => s.tags);
    shortIndex.push(
      `- **${title}** (\`components/${family}/\`, ${tags.length}) — ${tags.map((t) => `\`${t}\``).join(', ')}`,
      '',
    );
  }

  const artifacts = new Map([
    [path.join(packageDir, 'llms-full.txt'), full],
    [path.join(packageDir, 'llms.txt'), `${shortIndex.join('\n').trimEnd()}\n`],
    [path.join(llmsDir, 'shared.md'), `${shared}\n`],
    [
      path.join(llmsDir, 'index.md'),
      buildIndex(
        sectionsByFamily,
        tagFacts,
        JSON.parse(read('scripts', 'fixtures', 'component-metadata.json')).exportDeprecations ?? [],
      ),
    ],
    [path.join(llmsDir, 'tokens.md'), buildTokens()],
    [path.join(llmsDir, 'peers.md'), peersText],
    [path.join(llmsDir, 'migration.md'), buildMigration()],
  ]);
  for (const [tag, section] of sectionByTag) {
    const facts = tagFacts.get(tag);
    const familyHasBreakingNotes = (sectionsByFamily.get(facts.family) ?? []).some((candidate) =>
      /^Breaking changes\b/iu.test(candidate.title),
    );
    artifacts.set(
      path.join(llmsDir, 'components', `${tag}.md`),
      buildComponentFile(tag, section, tagFacts, peersByTag, { familyHasBreakingNotes }),
    );
  }

  if (write) {
    rmSync(path.join(llmsDir, 'components'), { recursive: true, force: true });
    mkdirSync(path.join(llmsDir, 'components'), { recursive: true });
    for (const [file, text] of artifacts) writeFileSync(file, text);
  }
  return artifacts;
}

if (isMainModule(import.meta.url)) {
  const artifacts = build();
  console.log(
    `Built llms-full.txt + ${artifacts.size - 1} files under llms/ (${[...artifacts.values()].reduce((a, t) => a + t.length, 0)} bytes).`,
  );
}
