// Tooling tests for scripts/generate-theme-presets.mjs: the generator that turns each
// src/themes/<name>.css look into the runtime token preset src/theme/presets/<name>.ts. Synthetic
// packages live in tmp directories; the last test checks the real, committed output.
//
// Run: node --test scripts/generate-theme-presets.test.mjs

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after, test } from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  buildThemePresets,
  checkThemePresets,
  parsePresetStylesheet,
  writeThemePresets,
} from './generate-theme-presets.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageDir = dirname(scriptDir);
const roots = [];

after(() => {
  for (const root of roots) rmSync(root, { recursive: true, force: true });
});

const LAYER = '@layer lr-base, lr-theme, lr-theme-preset, lr-utilities, lr-overrides;';

function stylesheet(light, dark, { extra = '', layer = LAYER } = {}) {
  return `/* A synthetic look. */
${layer}

@layer lr-theme-preset {
  :root,
  [data-lr-theme='light'] {
    color-scheme: light;
${light.map((line) => `    ${line}`).join('\n')}
  }

  [data-lr-theme='dark'] {
    color-scheme: dark;
${dark.map((line) => `    ${line}`).join('\n')}
  }
${extra}}
`;
}

function makePackage(files) {
  const root = mkdtempSync(join(tmpdir(), 'lyra-theme-presets-'));
  roots.push(root);
  mkdirSync(join(root, 'src', 'themes'), { recursive: true });
  mkdirSync(join(root, 'src', 'theme', 'presets'), { recursive: true });
  for (const [name, text] of Object.entries(files)) writeFileSync(join(root, 'src', 'themes', name), text);
  return root;
}

function errorsFor(light, dark, options) {
  return parsePresetStylesheet(stylesheet(light, dark, options), 'src/themes/sample.css').errors;
}

function snapshotTree(root) {
  const entries = [];
  const walk = (directory) => {
    for (const name of readdirSync(directory).sort()) {
      const path = join(directory, name);
      const stats = statSync(path);
      if (stats.isDirectory()) walk(path);
      else entries.push([path, readFileSync(path, 'utf8')]);
    }
  };
  walk(root);
  return entries;
}

test('round trip: bare and per-mode values, light-block order, header, quoting, tokens only', () => {
  const root = makePackage({
    'sample-look.css': stylesheet(
      [
        "--lr-theme-font-family-body: 'Geist', sans-serif;",
        '--lr-theme-color-surface-default: #ffffff;',
        '--lr-theme-border-radius-m: 0.5rem;',
      ],
      [
        '--lr-theme-border-radius-m: 0.5rem;',
        '--lr-theme-color-surface-default: #0a0a0a;',
        "--lr-theme-font-family-body: 'Geist', sans-serif;",
      ],
    ),
  });
  const { outputs, errors } = buildThemePresets(root);
  assert.deepEqual(errors, []);
  assert.equal(outputs.length, 1);
  const { content } = outputs[0];
  assert.ok(content.startsWith('// GENERATED by scripts/generate-theme-presets.mjs from src/themes/sample-look.css -- do not edit\n'));
  assert.match(content, /export const LYRA_SAMPLE_LOOK_THEME_PRESET: Readonly<LyraThemePreset> = defineLyraThemePreset\(\{/);
  assert.match(content, /id: 'sample-look',/);
  const body = content.slice(content.indexOf('tokens: {'));
  const lines = body.split('\n').filter((line) => line.trim().startsWith("'--lr-theme-"));
  assert.deepEqual(lines.map((line) => line.trim()), [
    "'--lr-theme-font-family-body': '\\'Geist\\', sans-serif',",
    "'--lr-theme-color-surface-default': { light: '#ffffff', dark: '#0a0a0a' },",
    "'--lr-theme-border-radius-m': '0.5rem',",
  ]);
  const code = content.slice(content.indexOf('export const'));
  for (const field of ['mode:', 'accent:', 'surface:']) assert.equal(code.includes(field), false, field);
  assert.equal(code.includes('color-scheme'), false, 'color-scheme is ignored');
});

test('errors name the file, the line, the declaration and the reason', () => {
  const cases = [
    ['light/dark key mismatch', ['--lr-theme-x: 1px;'], [], /sample\.css:\d+: --lr-theme-x: declared in the light block but not in the dark block/],
    ['non --lr-theme-* declaration', ['color: red;'], ['color: red;'], /sample\.css:8: color: red: only --lr-theme-\* inputs/],
    ['reserved name', ['--lr-theme-accent: red;'], ['--lr-theme-accent: red;'], /sample\.css:8: --lr-theme-accent: red: --lr-theme-accent is reserved/],
    ['url()', ['--lr-theme-x: url(x);'], ['--lr-theme-x: red;'], /sample\.css:8: --lr-theme-x: url\(x\): the value uses the function url\(\)/],
    ['unclosed parenthesis', ['--lr-theme-x: rgb(0 0 0;'], ['--lr-theme-x: red;'], /sample\.css:8: --lr-theme-x: rgb\(0 0 0: the value has an unclosed or unmatched parenthesis or quote/],
    ['!important', ['--lr-theme-x: red !important;'], ['--lr-theme-x: red;'], /sample\.css:8: --lr-theme-x: red !important: the value contains "!"/],
    ['value split across lines', ['--lr-theme-x: 0 1px 2px red,', '  0 2px 4px blue;'], ['--lr-theme-x: red;'], /sample\.css:8: --lr-theme-x: 0 1px 2px red, 0 2px 4px blue: the value contains a control character or line break/],
    ['fill without on', ['--lr-theme-color-danger-fill-loud: red;'], ['--lr-theme-color-danger-fill-loud: red;'], /--lr-theme-color-danger-fill-loud: declared in the light block without its partner --lr-theme-color-danger-on-loud/],
    ['on without fill', ['--lr-theme-color-brand-on-quiet: red;'], ['--lr-theme-color-brand-on-quiet: red;'], /--lr-theme-color-brand-on-quiet: declared in the light block without its partner --lr-theme-color-brand-fill-quiet/],
    ['overlay-strong without on-strong-overlay', ['--lr-theme-color-overlay-strong: black;'], ['--lr-theme-color-overlay-strong: black;'], /--lr-theme-color-overlay-strong: declared in the light block without its partner --lr-theme-color-on-strong-overlay/],
    ['duplicate declaration', ['--lr-theme-x: 1px;', '--lr-theme-x: 2px;'], ['--lr-theme-x: 1px;'], /sample\.css:9: --lr-theme-x: 2px: duplicate declaration of --lr-theme-x/],
  ];
  for (const [label, light, dark, pattern] of cases) {
    const errors = errorsFor(light, dark);
    assert.ok(errors.some((error) => pattern.test(error)), `${label}: ${JSON.stringify(errors)}`);
  }

  const many = Array.from({ length: 513 }, (_, index) => `--lr-theme-x${index}: 1px;`);
  assert.ok(errorsFor(many, many).some((error) => /declares 513 inputs, more than the 512/.test(error)));

  const extraRule = errorsFor(['--lr-theme-x: 1px;'], ['--lr-theme-x: 1px;'], { extra: '  .other { --lr-theme-x: 2px; }\n' });
  assert.ok(extraRule.some((error) => /\.other: unexpected rule/.test(error)), JSON.stringify(extraRule));
  const extraAtRule = errorsFor(['--lr-theme-x: 1px;'], ['--lr-theme-x: 1px;'], { extra: '  @media print { .a { --lr-theme-x: 2px; } }\n' });
  assert.ok(extraAtRule.some((error) => /@media print/.test(error)), JSON.stringify(extraAtRule));
  const innerAtRule = errorsFor(['--lr-theme-x: 1px;'], ['--lr-theme-x: 1px;'], { extra: "  @font-face { font-family: 'x'; }\n" });
  assert.ok(innerAtRule.some((error) => /@font-face: unexpected at-rule inside the preset layer/.test(error)), JSON.stringify(innerAtRule));
  const secondLayer = parsePresetStylesheet(`${stylesheet(['--lr-theme-x: 1px;'], ['--lr-theme-x: 1px;'])}\n@layer lr-theme-preset {\n}\n`, 'src/themes/sample.css').errors;
  assert.ok(secondLayer.some((error) => /@layer lr-theme-preset: unexpected at-rule; only one @layer lr-theme-preset block/.test(error)), JSON.stringify(secondLayer));
  const outsideAtRule = parsePresetStylesheet(`${stylesheet(['--lr-theme-x: 1px;'], ['--lr-theme-x: 1px;'])}\n@media print { :root { --lr-theme-x: 2px; } }\n`, 'src/themes/sample.css').errors;
  assert.ok(outsideAtRule.some((error) => /unexpected at-rule/.test(error)), JSON.stringify(outsideAtRule));
  const missingBlock = parsePresetStylesheet(`${LAYER}\n`, 'src/themes/sample.css').errors;
  assert.ok(missingBlock.some((error) => /missing the @layer lr-theme-preset block/.test(error)), JSON.stringify(missingBlock));
  const missingDark = parsePresetStylesheet(`${LAYER}\n@layer lr-theme-preset {\n  [data-lr-theme='light'] { --lr-theme-x: 1px; }\n}\n`, 'src/themes/sample.css').errors;
  assert.ok(missingDark.some((error) => /missing the dark rule/.test(error)), JSON.stringify(missingDark));
  const wrongLayer = errorsFor(['--lr-theme-x: 1px;'], ['--lr-theme-x: 1px;'], { layer: '@layer lr-base, lr-theme;' });
  assert.ok(wrongLayer.some((error) => /missing the layer order statement/.test(error)), JSON.stringify(wrongLayer));

  assert.deepEqual(errorsFor(['--lr-theme-x: 1px;'], ['--lr-theme-x: 1px;']), [], 'color-scheme is ignored, not an error');
});

test('a stylesheet with errors produces no output and writes nothing', () => {
  const root = makePackage({ 'broken.css': stylesheet(['--lr-theme-x: url(x);'], ['--lr-theme-x: red;']) });
  const before = snapshotTree(root);
  const { errors, written } = writeThemePresets(root);
  assert.ok(errors.length > 0);
  assert.deepEqual(written, []);
  assert.deepEqual(snapshotTree(root), before);
});

test('--check passes when fresh, fails when stale or orphaned, and never mutates the tree', () => {
  const root = makePackage({ 'sample.css': stylesheet(['--lr-theme-x: 1px;'], ['--lr-theme-x: 2px;']) });
  assert.deepEqual(writeThemePresets(root).errors, []);
  assert.deepEqual(checkThemePresets(root).findings, []);

  const target = join(root, 'src', 'theme', 'presets', 'sample.ts');
  writeFileSync(target, `${readFileSync(target, 'utf8')}// hand edit\n`);
  let before = snapshotTree(root);
  assert.ok(checkThemePresets(root).findings.some((finding) => /sample\.ts is stale relative to src\/themes\/sample\.css/.test(finding)));
  assert.deepEqual(snapshotTree(root), before);

  assert.deepEqual(writeThemePresets(root).errors, []);
  writeFileSync(join(root, 'src', 'theme', 'presets', 'orphan.ts'), 'export {};\n');
  writeFileSync(join(root, 'src', 'theme', 'presets', 'sample.test.ts'), 'export {};\n');
  before = snapshotTree(root);
  const { findings } = checkThemePresets(root);
  assert.deepEqual(findings, ['src/theme/presets/orphan.ts has no source stylesheet src/themes/orphan.css']);
  assert.deepEqual(snapshotTree(root), before);

  rmSync(target);
  assert.ok(checkThemePresets(root).findings.some((finding) => /sample\.ts is missing/.test(finding)));
});

test('an unknown CLI argument exits 1', () => {
  let status = 0;
  try {
    execFileSync(process.execPath, [join(scriptDir, 'generate-theme-presets.mjs'), '--bogus'], { stdio: 'pipe' });
  } catch (error) {
    status = error.status;
  }
  assert.equal(status, 1);
});

test('the real src/themes/shadcn.css regenerates byte-identically to the committed module', () => {
  const { findings, outputs } = checkThemePresets(packageDir);
  assert.deepEqual(findings, []);
  assert.ok(outputs.some((output) => output.name === 'shadcn'));
  const status = (() => {
    try {
      execFileSync(process.execPath, [join(scriptDir, 'generate-theme-presets.mjs'), '--check'], { stdio: 'pipe' });
      return 0;
    } catch (error) {
      return error.status;
    }
  })();
  assert.equal(status, 0);
});
