/** Authored shared guides, in the order exposed through the narrow-reference indexes. */
export const SHARED_TOPICS = Object.freeze([
  ['imports-and-registration', 'Imports and registration'],
  ['events-and-types', 'Events and TypeScript'],
  ['forms-and-accessibility', 'Forms and accessibility'],
  ['styles-and-tokens', 'Styles and tokens'],
  ['localization-and-rtl', 'Localization and RTL'],
  ['frameworks-and-ssr', 'Frameworks and SSR'],
  ['ai-and-peers', 'AI types and optional peers'],
  ['testing-and-utilities', 'Testing and utilities'],
]);

/** Section order retained by the generated llms/shared.md compatibility assembly. */
export const SHARED_COMPAT_ORDER = Object.freeze([
  'Component status, versioning, and deprecation',
  'Importing and registering components',
  'Optional native scoped registries',
  'Collection identity',
  'Events',
  'TypeScript',
  'Form association',
  'CSS custom states',
  'The required-field marker',
  'Presenting hint text as a compact disclosure',
  'The shared styling vocabulary',
  'Theming and design tokens',
  'Preventing layout shift from lazy-upgrading elements (CLS)',
  'Scope: what this library does not provide',
  'Optional native styles and CSS utilities',
  'Localization: `locale`, `strings`, and the locale runtime',
  'RTL and direction',
  'Provider-neutral AI types: `@aceshooting/lyra-ui/ai`',
  'Optional peer dependencies',
  'Framework integration',
  'SSR and declarative shadow DOM',
  'Testing form-associated components: `@aceshooting/lyra-ui/testing`',
  'Constructing a validated test event: `createLyraEvent()`',
  "Driving a component's real activation path: interaction drivers",
  'Awaiting a lazily registered mount: `waitForLyraElement()` and `waitForToast()`',
  "happy-dom's custom-property resolver and host-to-part token forwarding",
  'Accessibility contract',
  'Editor and tooling integration',
  'Independence and migration',
  'Family barrels',
  'Shared helpers: `utilities/`',
  'Reference artifacts',
  'When no component fits, file it',
  'Exported TypeScript contracts',
]);
