import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { readStyleModel, renderRuntimeLook, renderLook, renderDensity, renderTheme, concreteThemeCss, referenceSurfaces, renderAccents, contrastSurfaces, validateLook, renderGlass, defaultStyleInputs, replaceStyleFallbacks, renderNativeChrome } from './style-axes-model.mjs';

const packageDir = dirname(dirname(fileURLToPath(import.meta.url)));

test('aggregate theme declares layer order once while standalone assets retain their preludes', () => {
  const model = readStyleModel(packageDir);
  const glass = JSON.parse(readFileSync(new URL('../tokens/surfaces/glass.json', import.meta.url), 'utf8'));
  const density = JSON.parse(readFileSync(new URL('../tokens/density.json', import.meta.url), 'utf8'));
  const order = '@layer lr-base, lr-theme, lr-theme-preset, lr-utilities, lr-overrides;';
  const suborder = '@layer lr-theme-preset.look, lr-theme-preset.density, lr-theme-preset.surface, lr-theme-preset.accent, lr-theme-preset.mode;';
  const standalone = [
    ...model.looks.map(look => renderLook(model, look)),
    renderAccents(model, { emerald: '#34d399' }),
    renderGlass(glass),
    renderDensity(density),
  ];
  for (const css of standalone) {
    assert.ok(css.startsWith(`${order}\n${suborder}\n`), 'standalone asset establishes its layer order before rules');
    assert.equal(css.split(order).length - 1, 1, 'standalone top-level prelude occurs once');
    assert.equal(css.split(suborder).length - 1, 1, 'standalone sublayer prelude occurs once');
  }
  const aggregate = renderTheme(model);
  assert.equal(aggregate.split(order).length - 1, 1, 'aggregate top-level prelude occurs once');
  assert.equal(aggregate.split(suborder).length - 1, 1, 'aggregate sublayer prelude occurs once');
  assert.ok(aggregate.indexOf(order) < aggregate.indexOf('@layer lr-theme {'), 'aggregate prelude precedes the first rule block');
});

test('concrete theme extraction retains both generated mode slots and shared inputs', () => {
  const model = readStyleModel(packageDir);
  const css = concreteThemeCss(renderTheme(model));
  const [light, dark] = css.split('  .lr-dark,');
  assert.ok(dark, 'a dark projection is present independently of resolver selector syntax');
  for (const [name, values] of Object.entries(defaultStyleInputs(model))) {
    assert.ok(light.includes(`${name}: ${values.light};`), `${name}: concrete light value`);
    if (values.dark !== undefined) {
      assert.ok(dark.includes(`${name}: ${values.dark};`), `${name}: concrete dark value`);
    } else {
      assert.equal(dark.includes(`${name}:`), false, `${name}: no invented dark override`);
    }
  }
  assert.equal(css.includes('--_lr-'), false);
  for (const name of model.names.filter(name => !model.base[name])) {
    assert.equal(light.includes(`${name}: initial;`), false, 'absent optional look inputs stay undeclared');
  }
});

test('concrete theme preserves explicitly authored optional initial inputs without inventing look defaults', () => {
  const model = readStyleModel(packageDir);
  model.base['--lr-theme-line-break'] = { light: 'initial' };
  const generated = renderTheme(model);
  const projected = concreteThemeCss(generated);
  assert.match(projected, /--lr-theme-line-break: initial;/);
  assert.doesNotMatch(projected, /--lr-theme-font-family-heading: initial;/);
  assert.throws(() => concreteThemeCss(generated.replace(
    '--lr-theme-line-break: initial; /* declared optional input */',
    '--lr-theme-line-break: normal; /* declared optional input */',
  )), /Invalid declared optional input/);
  model.slotted.push('--lr-theme-line-break');
  model.paired.push('--lr-theme-line-break');
  const [light, dark] = concreteThemeCss(renderTheme(model)).split('  .lr-dark,');
  assert.match(light, /--lr-theme-line-break: initial;/);
  assert.doesNotMatch(dark, /--lr-theme-line-break:/);
});

test('concrete theme extraction fails closed for missing generated rules and dark slots', () => {
  const header = '/* GENERATED by scripts/generate-style-axes.mjs; */\n';
  assert.throws(() => concreteThemeCss(header), /no base input rule/);
  assert.throws(() => concreteThemeCss(`${header}:root, [data-lr-look] { --lr-theme-color-focus: #123456; }`), /no dark input slots/);
  const legacy = ':root { --lr-theme-color-focus: #123456; }';
  assert.equal(concreteThemeCss(legacy), legacy);
  const generated = renderTheme(readStyleModel(packageDir));
  const wrongFallback = generated.replace(/(--_lr-ld-[a-z0-9-]+):[^;]+; \/\* mode-independent fallback \*\//, '$1: 999px; /* mode-independent fallback */');
  assert.notEqual(wrongFallback, generated);
  assert.throws(() => concreteThemeCss(wrongFallback), /fallback differs from light input/);
});

test('authored look validation rejects shapes the runtime cannot accept', () => {
  for (const tokens of [[], { '--lr-theme-color-focus': { light: null, dark: null } }, { '--lr-theme-shadow-color': { light: '0 0 0', dark: '255 255 255' } }]) {
    assert.throws(() => validateLook({ id: 'invalid', tokens }));
  }
});

test('default glass qualifies text, control edges and focus across all built-in looks and named accents', () => {
  const model = readStyleModel(packageDir);
  const glass = JSON.parse(readFileSync(new URL('../tokens/surfaces/glass.json', import.meta.url), 'utf8'));
  assert.equal(glass.opacity, 0.7, 'default glass uses the authored 70% opacity');
  assert.equal(glass.minimumOpacity, 0, 'explicit opacity can reach zero');
  const highlightAlpha = Number(glass.highlight.match(/\/ ([\d.]+)\)/)[1]);
  const rgb = value => {
    if (/^#[a-f0-9]{6}$/i.test(value)) return [1, 3, 5].map(index => parseInt(value.slice(index, index + 2), 16));
    const match = value.match(/^rgb\(([^)]+)\)$/);
    assert.ok(match, `opaque authored color: ${value}`);
    return match[1].split(' ').map(Number);
  };
  const mix = (a, b, weight) => a.map((channel, index) => channel * (1 - weight) + b[index] * weight);
  const luminance = color => color.map(channel => channel / 255).map(channel => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4).reduce((sum, channel, index) => sum + channel * [0.2126, 0.7152, 0.0722][index], 0);
  const contrast = (a, b) => (Math.max(luminance(a), luminance(b)) + 0.05) / (Math.min(luminance(a), luminance(b)) + 0.05);
  const gemstoneSource = readFileSync(new URL('../src/theme/gemstones-data.ts', import.meta.url), 'utf8');
  const gemstones = Object.fromEntries([...gemstoneSource.matchAll(/(\w+): \{ key: '\w+', fill: '([^']+)'/g)].map(match => [match[1], match[2]]));
  const accents = [{ id: 'none', css: '' }, ...Object.entries(gemstones).map(([id, value]) => ({ id, css: renderAccents(model, { [id]: value }) }))];
  for (const look of [{ id: 'lyra', tokens: {} }, ...model.looks]) for (const mode of ['light', 'dark']) for (const accent of accents) {
    const read = suffix => {
      const name = `--lr-theme-color-${suffix}`;
      const override = accent.css.match(new RegExp(`--_lr-a${mode === 'light' ? 'l' : 'd'}-color-${suffix}: ([^;]+);`))?.[1];
      const authored = look.tokens[name];
      const value = override ?? (typeof authored === 'string' ? authored : authored?.[mode]) ?? model.base[name]?.[mode] ?? model.base[name]?.light;
      if (value === 'initial' || value === undefined) return read('surface-overlay');
      if (value?.startsWith('var(')) return read(value.slice(4, -1).replace('--lr-theme-color-', ''));
      return rgb(value);
    };
    const normal = read('text-normal');
    const qualify = color => mix(color, normal, glass.foregroundWeight);
    for (const surface of ['surface-default', 'surface-raised', 'surface-overlay', 'surface-container-high', 'surface-container-highest']) {
      const backgrounds = [0, 255].map(backdrop => mix([backdrop, backdrop, backdrop], read(surface), glass.opacity));
      const roles = [['text-normal', normal, 4.5], ['text-quiet', qualify(read('text-quiet')), 4.5], ['action', qualify(read('brand-fill-loud')), 4.5], ['control', qualify(read('surface-border')), 3], ['focus', qualify(read('focus')), 3]];
      for (const [role, color, minimum] of roles) {
        const measured = backgrounds.map(background => role === 'control' || role === 'focus' ? mix(background, [255, 255, 255], highlightAlpha) : background);
        assert.ok(measured.every(background => contrast(color, background) >= minimum), `${look.id}/${mode}/${accent.id}/${surface}/${role}: ${measured.map(background => contrast(color, background)).join(', ')}`);
        const signs = measured.map(background => Math.sign(luminance(color) - luminance(background)));
        assert.equal(signs[0], signs[1], 'extreme backdrops stay on the same side of the foreground luminance');
      }
      assert.ok(contrast(read('brand-on-loud'), read('brand-fill-loud')) >= 4.5, `${look.id}/${mode}/${accent.id}: opaque accent pair remains qualified`);
    }
  }
});

test('glass compiler rejects an unqualified transparency or foreground bound', () => {
  const glass = JSON.parse(readFileSync(new URL('../tokens/surfaces/glass.json', import.meta.url), 'utf8'));
  assert.doesNotThrow(() => renderGlass(glass));
  for (const value of [-0.01, 1.01, NaN, Infinity, '0.7', null]) {
    assert.throws(() => renderGlass({ ...glass, minimumOpacity: value }), /Invalid glass bounds/);
    assert.throws(() => renderGlass({ ...glass, opacity: value }), /Invalid glass bounds/);
  }
  assert.throws(() => renderGlass({ ...glass, foregroundWeight: 0 }), /Invalid glass bounds/);
  assert.throws(() => renderGlass({ ...glass, maximumBlur: '100px' }), /blur radius bound/);
  assert.throws(() => renderGlass({ ...glass, highlight: 'rgb(255 255 255 / 0.5)' }), /highlight bound/);
  assert.throws(() => renderGlass({ ...glass, maximumBlur: '1px; color: red' }), /Invalid glass maximumBlur/);
});

test('emerald retains its seed while loud text is readable on light, dark and quiet surfaces', () => {
  const model = readStyleModel(packageDir);
  const css = renderAccents(model, { emerald: '#34d399' });
  assert.match(css, /--lr-theme-accent: #34d399;/);
  const luminance = channels => channels.map(channel => channel / 255).map(channel => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4).reduce((sum, channel, index) => sum + channel * [0.2126, 0.7152, 0.0722][index], 0);
  const contrast = (a, b) => (Math.max(luminance(a), luminance(b)) + 0.05) / (Math.min(luminance(a), luminance(b)) + 0.05);
  const input = (mode, channel) => {
    const match = css.match(new RegExp(`--_lr-a${mode === 'light' ? 'l' : 'd'}-color-brand-${channel}: rgb\\(([^)]+)\\)`));
    assert.ok(match, `${mode} ${channel} is present`);
    return match[1].split(' ').map(Number);
  };
  for (const mode of ['light', 'dark']) {
    const loud = input(mode, 'fill-loud');
    const backgrounds = contrastSurfaces(model)[mode].map(hex => [1, 3, 5].map(index => parseInt(hex.slice(index, index + 2), 16)));
    backgrounds.push(input(mode, 'fill-quiet'));
    for (const background of backgrounds) assert.ok(contrast(loud, background) >= 4.5, `${mode}: loud text on ${background}`);
    assert.ok(contrast(input(mode, 'on-loud'), loud) >= 4.5, `${mode}: foreground on corrected fill`);
  }
  assert.notDeepEqual(input('light', 'fill-loud'), [52, 211, 153]);
});

test('sparse runtime look branches retain null without fabricating string values', () => {
  const look = { id: 'sparse', tokens: {
    '--lr-theme-color-text-normal': { light: '#111111' },
    '--lr-theme-color-text-quiet': { light: null, dark: '#eeeeee' },
  } };
  const source = renderRuntimeLook(look);
  assert.match(source, /\{ light: '#111111' \}/);
  assert.match(source, /\{ light: null, dark: '#eeeeee' \}/);
  assert.equal(source.includes("'null'"), false);
  assert.equal(source.includes('undefined'), false);
});

test('reference surfaces accept one value or sparse mode pairs', () => {
  const model = readStyleModel(packageDir);
  model.looks = [
    { id: 'plain', tokens: { '--lr-theme-color-surface-default': '#eeeeee' } },
    { id: 'sparse', tokens: { '--lr-theme-color-surface-default': { dark: '#111111' } } },
  ];
  const references = referenceSurfaces(model);
  assert.deepEqual(references.plain, { light: '#eeeeee', dark: '#eeeeee' });
  assert.deepEqual(references.sparse, { light: model.base['--lr-theme-color-surface-default'].light, dark: '#111111' });
});

test('full look references preserve the canonical page, raised, text and scrim in both modes', () => {
  const model = readStyleModel(packageDir);
  const references = referenceSurfaces(model, true);
  assert.deepEqual(references.lyra.light, ['#ffffff', '#f6f8fa', '#1a1a1a', 'rgb(0 0 0 / 0.92)']);
  assert.deepEqual(references.shadcn.dark, ['#0a0a0a', '#171717', '#fafafa', 'rgb(0 0 0 / 0.95)']);
  for (const look of model.looks) for (const mode of ['light', 'dark']) {
    const names = ['color-surface-default', 'color-surface-raised', 'color-text-normal', 'color-overlay-strong'];
    for (const [index, suffix] of names.entries()) {
      const name = `--lr-theme-${suffix}`;
      const own = look.tokens[name];
      const expected = (typeof own === 'string' ? own : own?.[mode]) ?? model.base[name]?.[mode] ?? model.base[name]?.light;
      assert.equal(references[look.id][mode][index], expected, `${look.id} ${mode} ${suffix}`);
    }
  }
});

test('clear media scrim plus fill qualifies white controls over black and white', () => {
  const { clearMedia } = JSON.parse(readFileSync(new URL('../tokens/surfaces/glass.json', import.meta.url), 'utf8'));
  const luminance = channel => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4;
  for (const backdrop of [0, 1]) for (const scrim of [clearMedia.scrimStart, clearMedia.scrimEnd]) {
    const painted = (clearMedia.fillOpacity + backdrop * (1 - clearMedia.fillOpacity)) * (1 - scrim);
    for (const hover of [0, clearMedia.fillOpacity]) {
      const background = painted * (1 - hover) + hover;
      assert.ok(1.05 / (luminance(background) + 0.05) >= 4.5, 'white text and controls preserve their contrast through hover and press');
    }
  }
});


test('profile projection is idempotent and can restore a previous fallback without changing the Lyra source', () => {
  const model = readStyleModel(packageDir);
  const inputs = defaultStyleInputs(model);
  assert.deepEqual(model.defaults, { look: 'shadcn', surface: 'glass', density: 'comfortable', mode: 'system', accent: 'emerald' });
  assert.equal(inputs['--lr-theme-color-neutral-fill-loud'].dark, inputs['--lr-theme-color-brand-fill-loud'].dark);
  assert.equal(inputs['--lr-theme-color-neutral-on-loud'].dark, inputs['--lr-theme-color-brand-on-loud'].dark);
  const expression = 'var(--lr-theme-color-surface-default, var(--lr-color-surface, rgb(1 2 3)))';
  const projected = replaceStyleFallbacks(expression, inputs, 'light');
  assert.equal(replaceStyleFallbacks(projected, inputs, 'light'), projected);
  assert.equal(replaceStyleFallbacks(projected, model.base, 'light'), `var(--lr-theme-color-surface-default, ${model.base['--lr-theme-color-surface-default'].light})`);
  assert.equal(model.base['--lr-theme-color-surface-default'].dark, '#1a1a1a');
  assert.throws(() => replaceStyleFallbacks('var(--lr-theme-color-surface-default, broken(', inputs, 'light'), /Unclosed/);
});

test('theme alone contains only the built-in profile and explicit Lyra restoration, with named Emerald startup paint', () => {
  const model = readStyleModel(packageDir);
  const css = renderTheme(model);
  assert.match(css, /\[data-lr-look='shadcn'\]/);
  assert.match(css, /\[data-lr-look='lyra'\]/);
  assert.match(css, /\[data-lr-accent='emerald'\]/);
  assert.match(css, /:root:not\(\[data-lr-surface\]\)/);
  for (const look of ['material', 'data', 'terminal', 'high-contrast']) assert.equal(css.includes(`[data-lr-look='${look}']`), false);
});

test('optional subtle projection keeps the canonical local alias and is idempotent', () => {
  const model = readStyleModel(packageDir);
  const inputs = defaultStyleInputs(model);
  for (const mode of ['light', 'dark']) {
    const canonical = model.canonical.tokens['--lr-color-border-subtle'].values[mode];
    const projected = replaceStyleFallbacks(canonical, inputs, mode, model.canonical.tokens);
    assert.ok(projected.includes('var(--lr-color-border)'), 'the alias resolves at the consuming host');
    assert.ok(projected.includes('var(--_lr-subtle-mix,100%)'), 'sheetless startup retains its projected default');
    assert.equal(replaceStyleFallbacks(projected, inputs, mode, model.canonical.tokens), projected);
    assert.equal(replaceStyleFallbacks(projected, model.base, mode, model.canonical.tokens), canonical);
  }
  assert.match(renderTheme(model), /--_lr-subtle-mix: 0%;/);
});

test('startup look projects a delta over one canonical scope base without changing cascade priority', () => {
  const model = readStyleModel(packageDir);
  const css = renderTheme(model);
  const base = css.match(/:root, \[data-lr-look\] \{([^}]+)\}/)?.[1];
  assert.ok(base);
  assert.match(base, /--_lr-ld-color-surface-default: #1a1a1a;/);
  assert.equal(css.includes('  [data-lr-look] {'), false, 'an explicit look uses the shared canonical base once');
  const defaults = css.match(/:root:where\(:not\(\[data-lr-look\]\)\) \{([^}]+)\}/)?.[1];
  assert.ok(defaults);
  assert.match(defaults, /--_lr-ld-color-surface-default: #0a0a0a;/);
  assert.equal(defaults.includes('--lr-theme-line-height-normal:'), false, 'unchanged inputs inherit the shared base');
  assert.ok(css.indexOf(':root:where(:not([data-lr-look]))') < css.indexOf('@layer lr-theme-preset.mode {'), 'startup overrides remain in the base theme layer');
});

test('concrete startup projection retains an explicit dark branch equal to the canonical light fallback', () => {
  const model = readStyleModel(packageDir);
  model.base['--lr-theme-color-text-quiet'] = { light: '#111111' };
  model.looks.find(look => look.id === model.defaults.look).tokens['--lr-theme-color-text-quiet'] = { light: '#222222', dark: '#111111' };
  const [light, dark] = concreteThemeCss(renderTheme(model)).split('  .lr-dark,');
  assert.match(light, /--lr-theme-color-text-quiet: #222222;/);
  assert.match(dark, /--lr-theme-color-text-quiet: #111111;/);
});

test('native chrome compiles the shared protected surface without unresolved template expressions', () => {
  const css = renderNativeChrome();
  assert.match(css, /:where\(\.lr-surface-chrome\)::before/);
  assert.match(css, /--lr-surface-background/);
  assert.match(css, /--_lr-surface-default-blur: 12px;/);
  assert.match(css, /--_lr-surface-default-maximum-blur: 16px;/);
  assert.match(css, /--_lr-surface-default-highlight: rgb\(255 255 255 \/ 0\.12\);/);
  assert.match(css, /prefers-reduced-transparency/);
  assert.match(css, /forced-colors/);
  assert.equal(css.includes('$' + '{'), false);
  assert.equal(css.includes(':host'), false);
});
