import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { readStyleModel, renderFixedLook, renderRuntimeLook, renderTheme, concreteThemeCss, referenceSurfaces, renderAccents, contrastSurfaces, validateLook, renderGlass } from './style-axes-model.mjs';

const packageDir = dirname(dirname(fileURLToPath(import.meta.url)));

test('concrete theme extraction retains both generated mode slots and shared inputs', () => {
  const model = readStyleModel(packageDir);
  const css = concreteThemeCss(renderTheme(model));
  const [light, dark] = css.split('  .lr-dark,');
  assert.ok(dark, 'a dark projection is present independently of resolver selector syntax');
  for (const [name, values] of Object.entries(model.base)) {
    assert.ok(light.includes(`${name}: ${values.light};`), `${name}: concrete light value`);
    if (values.dark !== undefined) {
      assert.ok(dark.includes(`${name}: ${values.dark};`), `${name}: concrete dark value`);
    } else {
      assert.equal(dark.includes(`${name}:`), false, `${name}: no invented dark override`);
    }
  }
  assert.equal(css.includes('--_lr-'), false);
  for (const name of model.names.filter(name => !model.base[name])) {
    assert.equal(light.includes(`${name}: initial;`), false, 'absent optional look inputs stay undeclared');
  }
});

test('concrete theme preserves explicitly authored optional initial inputs without inventing look defaults', () => {
  const model = readStyleModel(packageDir);
  model.base['--lr-theme-line-break'] = { light: 'initial' };
  const generated = renderTheme(model);
  const projected = concreteThemeCss(generated);
  assert.match(projected, /--lr-theme-line-break: initial;/);
  assert.doesNotMatch(projected, /--lr-theme-font-family-heading: initial;/);
  assert.throws(() => concreteThemeCss(generated.replace(
    '--lr-theme-line-break: initial; /* declared optional input */',
    '--lr-theme-line-break: normal; /* declared optional input */',
  )), /Invalid declared optional input/);
  model.slotted.push('--lr-theme-line-break');
  model.paired.push('--lr-theme-line-break');
  const [light, dark] = concreteThemeCss(renderTheme(model)).split('  .lr-dark,');
  assert.match(light, /--lr-theme-line-break: initial;/);
  assert.doesNotMatch(dark, /--lr-theme-line-break:/);
});

test('concrete theme extraction fails closed for missing generated rules and dark slots', () => {
  const header = '/* GENERATED by scripts/generate-style-axes.mjs; */\n';
  assert.throws(() => concreteThemeCss(header), /no base input rule/);
  assert.throws(() => concreteThemeCss(`${header}:root, [data-lr-look] { --lr-theme-color-focus: #123456; }`), /no dark input slots/);
  const legacy = ':root { --lr-theme-color-focus: #123456; }';
  assert.equal(concreteThemeCss(legacy), legacy);
  const generated = renderTheme(readStyleModel(packageDir));
  const wrongFallback = generated.replace(/(--_lr-ld-[a-z0-9-]+):[^;]+; \/\* mode-independent fallback \*\//, '$1: 999px; /* mode-independent fallback */');
  assert.notEqual(wrongFallback, generated);
  assert.throws(() => concreteThemeCss(wrongFallback), /fallback differs from light input/);
});

test('fixed compatibility looks retain new authored inputs alongside their frozen legacy inventory', () => {
  const model = readStyleModel(packageDir);
  const look = model.looks.find(look => look.id === 'shadcn');
  const fixed = renderFixedLook(model, look);
  for (const [name, values] of Object.entries(look.tokens)) {
    for (const mode of ['light', 'dark']) assert.ok(fixed.includes(`${name}: ${typeof values === 'string' ? values : values[mode]};`), name);
  }
});

test('authored look validation rejects shapes the runtime cannot accept', () => {
  for (const tokens of [[], { '--lr-theme-color-focus': { light: null, dark: null } }, { '--lr-theme-shadow-color': { light: '0 0 0', dark: '255 255 255' } }]) {
    assert.throws(() => validateLook({ id: 'invalid', tokens }));
  }
});

test('glass qualifies text, control edges and focus across all built-in looks and named accents', () => {
  const model = readStyleModel(packageDir);
  const glass = JSON.parse(readFileSync(new URL('../tokens/surfaces/glass.json', import.meta.url), 'utf8'));
  assert.ok(glass.minimumOpacity <= 0.92, 'regular glass remains visibly translucent');
  const highlightAlpha = Number(glass.highlight.match(/\/ ([\d.]+)\)/)[1]);
  const rgb = value => {
    if (/^#[a-f0-9]{6}$/i.test(value)) return [1, 3, 5].map(index => parseInt(value.slice(index, index + 2), 16));
    const match = value.match(/^rgb\(([^)]+)\)$/);
    assert.ok(match, `opaque authored color: ${value}`);
    return match[1].split(' ').map(Number);
  };
  const mix = (a, b, weight) => a.map((channel, index) => channel * (1 - weight) + b[index] * weight);
  const luminance = color => color.map(channel => channel / 255).map(channel => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4).reduce((sum, channel, index) => sum + channel * [0.2126, 0.7152, 0.0722][index], 0);
  const contrast = (a, b) => (Math.max(luminance(a), luminance(b)) + 0.05) / (Math.min(luminance(a), luminance(b)) + 0.05);
  const gemstoneSource = readFileSync(new URL('../src/theme/gemstones-data.ts', import.meta.url), 'utf8');
  const gemstones = Object.fromEntries([...gemstoneSource.matchAll(/(\w+): \{ key: '\w+', fill: '([^']+)'/g)].map(match => [match[1], match[2]]));
  const accents = [{ id: 'none', css: '' }, ...Object.entries(gemstones).map(([id, value]) => ({ id, css: renderAccents(model, { [id]: value }) }))];
  for (const look of [{ id: 'lyra', tokens: {} }, ...model.looks]) for (const mode of ['light', 'dark']) for (const accent of accents) {
    const read = suffix => {
      const name = `--lr-theme-color-${suffix}`;
      const override = accent.css.match(new RegExp(`--_lr-a${mode === 'light' ? 'l' : 'd'}-color-${suffix}: ([^;]+);`))?.[1];
      const authored = look.tokens[name];
      const value = override ?? (typeof authored === 'string' ? authored : authored?.[mode]) ?? model.base[name]?.[mode] ?? model.base[name]?.light;
      if (value?.startsWith('var(')) return read(value.slice(4, -1).replace('--lr-theme-color-', ''));
      return rgb(value);
    };
    const normal = read('text-normal');
    const qualify = color => mix(color, normal, glass.foregroundWeight);
    for (const surface of ['surface-default', 'surface-raised', 'surface-overlay']) {
      const backgrounds = [0, 255].map(backdrop => mix([backdrop, backdrop, backdrop], read(surface), glass.minimumOpacity));
      const roles = [['text-normal', normal, 4.5], ['text-quiet', qualify(read('text-quiet')), 4.5], ['action', qualify(read('brand-fill-loud')), 4.5], ['control', qualify(read('surface-border')), 3], ['focus', qualify(read('focus')), 3]];
      for (const [role, color, minimum] of roles) {
        const measured = backgrounds.map(background => role === 'control' || role === 'focus' ? mix(background, [255, 255, 255], highlightAlpha) : background);
        assert.ok(measured.every(background => contrast(color, background) >= minimum), `${look.id}/${mode}/${accent.id}/${surface}/${role}: ${measured.map(background => contrast(color, background)).join(', ')}`);
        const signs = measured.map(background => Math.sign(luminance(color) - luminance(background)));
        assert.equal(signs[0], signs[1], 'extreme backdrops stay on the same side of the foreground luminance');
      }
      assert.ok(contrast(read('brand-on-loud'), read('brand-fill-loud')) >= 4.5, `${look.id}/${mode}/${accent.id}: opaque accent pair remains qualified`);
    }
  }
});

test('glass compiler rejects an unqualified transparency or foreground bound', () => {
  const glass = JSON.parse(readFileSync(new URL('../tokens/surfaces/glass.json', import.meta.url), 'utf8'));
  assert.throws(() => renderGlass({ ...glass, minimumOpacity: 0.5 }), /Invalid glass bounds/);
  assert.throws(() => renderGlass({ ...glass, foregroundWeight: 0 }), /Invalid glass bounds/);
  assert.throws(() => renderGlass({ ...glass, maximumBlur: '100px' }), /blur radius bound/);
  assert.throws(() => renderGlass({ ...glass, highlight: 'rgb(255 255 255 / 0.5)' }), /highlight bound/);
  assert.throws(() => renderGlass({ ...glass, maximumBlur: '1px; color: red' }), /Invalid glass maximumBlur/);
});

test('legacy shadcn preserves its owned inputs without claiming spacing or motion', () => {
  const model = readStyleModel(packageDir);
  const look = model.looks.find(candidate => candidate.id === 'shadcn');
  const css = renderFixedLook(model, look);
  const inputs = new Set([...css.matchAll(/(--lr-theme-[a-z0-9-]+):/g)].map(match => match[1]));
  assert.deepEqual([...inputs].sort(), [...new Set([...look.legacyInputs, ...Object.keys(look.tokens)])].sort());
  assert.equal(look.legacyInputs.length, 124, 'the original fixed-input inventory remains intact');
  for (const name of ['space-m', 'transition-fast', 'border-width-medium']) {
    assert.equal(css.includes(`--lr-theme-${name}:`), false, name);
  }
  assert.match(css, /BEGIN REPEATED BASE THEME VALUES/);
  assert.match(css, /--lr-theme-color-neutral-fill-loud: var\(--lr-theme-color-brand-fill-loud\)/);
});

test('emerald retains its seed while loud text is readable on light, dark and quiet surfaces', () => {
  const model = readStyleModel(packageDir);
  const css = renderAccents(model, { emerald: '#34d399' });
  assert.match(css, /--lr-theme-accent: #34d399;/);
  const luminance = channels => channels.map(channel => channel / 255).map(channel => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4).reduce((sum, channel, index) => sum + channel * [0.2126, 0.7152, 0.0722][index], 0);
  const contrast = (a, b) => (Math.max(luminance(a), luminance(b)) + 0.05) / (Math.min(luminance(a), luminance(b)) + 0.05);
  const input = (mode, channel) => {
    const match = css.match(new RegExp(`--_lr-a${mode === 'light' ? 'l' : 'd'}-color-brand-${channel}: rgb\\(([^)]+)\\)`));
    assert.ok(match, `${mode} ${channel} is present`);
    return match[1].split(' ').map(Number);
  };
  for (const mode of ['light', 'dark']) {
    const loud = input(mode, 'fill-loud');
    const backgrounds = contrastSurfaces(model)[mode].map(hex => [1, 3, 5].map(index => parseInt(hex.slice(index, index + 2), 16)));
    backgrounds.push(input(mode, 'fill-quiet'));
    for (const background of backgrounds) assert.ok(contrast(loud, background) >= 4.5, `${mode}: loud text on ${background}`);
    assert.ok(contrast(input(mode, 'on-loud'), loud) >= 4.5, `${mode}: foreground on corrected fill`);
  }
  assert.notDeepEqual(input('light', 'fill-loud'), [52, 211, 153]);
});

test('sparse runtime look branches retain null without fabricating string values', () => {
  const look = { id: 'sparse', tokens: {
    '--lr-theme-color-text-normal': { light: '#111111' },
    '--lr-theme-color-text-quiet': { light: null, dark: '#eeeeee' },
  } };
  const source = renderRuntimeLook(look);
  assert.match(source, /\{ light: '#111111' \}/);
  assert.match(source, /\{ light: null, dark: '#eeeeee' \}/);
  assert.equal(source.includes("'null'"), false);
  assert.equal(source.includes('undefined'), false);
});

test('fixed projections resolve sparse branches against the canonical mode', () => {
  const model = readStyleModel(packageDir);
  const name = '--lr-theme-color-text-normal';
  const css = renderFixedLook(model, { id: 'sparse', legacyInputs: [name], tokens: { [name]: { light: null, dark: '#eeeeee' } } });
  assert.match(css, new RegExp(`${name}: ${model.base[name].light};`));
  assert.match(css, new RegExp(`${name}: #eeeeee;`));
  assert.equal(css.includes(': null;'), false);
});

test('reference surfaces accept one value or sparse mode pairs', () => {
  const model = readStyleModel(packageDir);
  model.looks = [
    { id: 'plain', tokens: { '--lr-theme-color-surface-default': '#eeeeee' } },
    { id: 'sparse', tokens: { '--lr-theme-color-surface-default': { dark: '#111111' } } },
  ];
  const references = referenceSurfaces(model);
  assert.deepEqual(references.plain, { light: '#eeeeee', dark: '#eeeeee' });
  assert.deepEqual(references.sparse, { light: model.base['--lr-theme-color-surface-default'].light, dark: '#111111' });
});

test('clear media scrim plus fill qualifies white controls over black and white', () => {
  const { clearMedia } = JSON.parse(readFileSync(new URL('../tokens/surfaces/glass.json', import.meta.url), 'utf8'));
  const luminance = channel => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4;
  for (const backdrop of [0, 1]) for (const scrim of [clearMedia.scrimStart, clearMedia.scrimEnd]) {
    const painted = (clearMedia.fillOpacity + backdrop * (1 - clearMedia.fillOpacity)) * (1 - scrim);
    for (const hover of [0, clearMedia.fillOpacity]) {
      const background = painted * (1 - hover) + hover;
      assert.ok(1.05 / (luminance(background) + 0.05) >= 4.5, 'white text and controls preserve their contrast through hover and press');
    }
  }
});
