// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  rating: 'ರೇಟಿಂಗ್',
  calloutAnnouncementWithContext: '{context}: {content}',
  closeWithContext: 'ಮುಚ್ಚಿ: {snippet}',
  closeWithTruncatedContext: 'ಮುಚ್ಚಿ: {snippet}…',
  toastContentIncomplete: 'ಅಪೂರ್ಣ ವಿಷಯದ ಅಧಿಸೂಚನೆ',
  toastOverflow: '{count} ಅಧಿಸೂಚನೆಗಳನ್ನು ತೋರಿಸಲಾಗಿಲ್ಲ.',
  kbdEscapeVisual: 'Esc',
  kbdEscapeWord: 'Escape ಕೀ',
  kbdTabWord: 'Tab ಕೀ',
  kbdSpaceWord: 'Space ಕೀ',
  kbdDeleteVisual: 'Del',
  kbdDeleteWord: 'Delete ಕೀ',
  kbdHomeWord: 'Home ಕೀ',
  kbdEndWord: 'End ಕೀ',
  kbdPageUpVisual: 'PgUp',
  kbdPageUpWord: 'Page Up ಕೀ',
  kbdPageDownVisual: 'PgDn',
  kbdPageDownWord: 'Page Down ಕೀ',
  kbdEnterWord: 'Enter ಕೀ',
  kbdBackspaceWord: 'Backspace ಕೀ',
  kbdArrowUpWord: 'ಮೇಲಿನ ಬಾಣದ ಕೀ',
  kbdArrowDownWord: 'ಕೆಳಗಿನ ಬಾಣದ ಕೀ',
  kbdArrowLeftWord: 'ಎಡ ಬಾಣದ ಕೀ',
  kbdArrowRightWord: 'ಬಲ ಬಾಣದ ಕೀ',
  kbdPlusWord: 'ಪ್ಲಸ್ ಕೀ',
  kbdMinusWord: 'ಮೈನಸ್ ಕೀ',
  kbdCommandWord: 'Command ಕೀ',
  kbdControlVisual: 'Ctrl',
  kbdControlWord: 'Control ಕೀ',
  kbdOptionWord: 'Option ಕೀ',
  kbdAltWord: 'Alt ಕೀ',
  kbdShiftWord: 'Shift ಕೀ',
};

registerLyraLocale('kn', strings);
