// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON ಅನ್ನು ಕ್ಲಿಪ್‌ಬೋರ್ಡ್‌ಗೆ ನಕಲಿಸಿ',
  circularReference: 'ವೃತ್ತಾಕಾರದ ಉಲ್ಲೇಖ',
  copyDiff: 'ವ್ಯತ್ಯಾಸ ನಕಲಿಸಿ',
  diffViewOldLabel: 'ಮೂಲ',
  diffViewNewLabel: 'ಮಾರ್ಪಡಿಸಿದ',
  diffViewHiddenLines: {
    one: '{count} ಬದಲಾಗದ ಸಾಲು',
    other: '{count} ಬದಲಾಗದ ಸಾಲುಗಳು',
  },
  diffViewTooLarge: 'ತೋರಿಸಲು ವ್ಯತ್ಯಾಸ ತುಂಬಾ ದೊಡ್ಡದಾಗಿದೆ.',
  jsonArray: 'ಅರೇ',
  jsonObject: 'ಆಬ್ಜೆಕ್ಟ್',
  jsonValue: 'ಮೌಲ್ಯ',
  jsonCopyLabel: '{label} ನಕಲಿಸಿ',
  jsonExpandLabel: '{label} ವಿಸ್ತರಿಸಿ',
  jsonCollapseLabel: '{label} ಕುಗ್ಗಿಸಿ',
  jsonItemCount: {
    one: '{count} ಐಟಂ',
    other: '{count} ಐಟಂಗಳು',
  },
  jsonKeyCount: {
    one: '{count} ಕೀ',
    other: '{count} ಕೀಗಳು',
  },
  jsonViewerLimit: 'ಮೊದಲ {count} JSON ನೋಡ್‌ಗಳು ಮತ್ತು {depth} ನೆಸ್ಟಿಂಗ್ ಹಂತಗಳನ್ನು ಮಾತ್ರ ತೋರಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಹುಡುಕಲಾಗುತ್ತದೆ.',
  pollPause: 'ವಿರಾಮಗೊಳಿಸಿ',
  pollResume: 'ಮತ್ತೆ ಆರಂಭಿಸಿ',
  pollRefresh: 'ಈಗ ರಿಫ್ರೆಶ್ ಮಾಡಿ',
  pollInactive: 'ನಿಷ್ಕ್ರಿಯ',
  pollRefreshing: 'ರಿಫ್ರೆಶ್ ಆಗುತ್ತಿದೆ…',
  pollPaused: 'ವಿರಾಮದಲ್ಲಿದೆ',
  pollPausedAnnounce: 'ವಿರಾಮಗೊಳಿಸಲಾಗಿದೆ.',
  pollResumedAnnounce: 'ಮತ್ತೆ ಆರಂಭಿಸಲಾಗಿದೆ.',
  pollRefreshingAnnounce: 'ಈಗ ರಿಫ್ರೆಶ್ ಆಗುತ್ತಿದೆ.',
  randomContentPause: 'ತಿರುಗುವಿಕೆಯನ್ನು ನಿಲ್ಲಿಸಿ',
  randomContentResume: 'ತಿರುಗುವಿಕೆಯನ್ನು ಮುಂದುವರಿಸಿ',
  randomContentNext: 'ಇನ್ನೊಂದನ್ನು ತೋರಿಸಿ',
  exportButtonLabel: 'ರಫ್ತು ಮಾಡಿ',
  knownDateDay: 'ದಿನ',
  knownDateMonth: 'ತಿಂಗಳು',
  knownDateYear: 'ವರ್ಷ',
  exportFormatMenuLabel: '{label} ಸ್ವರೂಪ',
  mentionSuggestions: 'ಸಲಹೆಗಳು',
  mentionResultCount: {
    one: '{count} ಸಲಹೆ',
    other: '{count} ಸಲಹೆಗಳು',
  },
  mentionResultPosition: 'ಒಟ್ಟು {total}ರಲ್ಲಿ {current}ನೇ ಸಲಹೆ',
  iconLoadError: 'ಐಕಾನ್ ಲೋಡ್ ಆಗಲಿಲ್ಲ.',
  iconTooLarge: 'ಐಕಾನ್ ಫೈಲ್ ತೋರಿಸಲು ತುಂಬಾ ದೊಡ್ಡದಾಗಿದೆ.',
  iconSanitizerMissing: 'ಸುರಕ್ಷಿತವಾಗಿ ರೆಂಡರ್ ಮಾಡಲು ಈ ಐಕಾನ್‌ಗೆ ಐಚ್ಛಿಕ "dompurify" ಪ್ಯಾಕೇಜ್ ಬೇಕು.',
  tourSkip: 'ಬಿಟ್ಟುಹೋಗಿ',
  tourDone: 'ಮುಗಿದಿದೆ',
  tourStepOf: 'ಒಟ್ಟು {total}ರಲ್ಲಿ {current}ನೇ ಹಂತ',
  mentionMoreResults: {
    one: '{count} ಹೆಚ್ಚಿನ ಸಲಹೆ',
    other: '{count} ಹೆಚ್ಚಿನ ಸಲಹೆಗಳು',
  },
};

registerLyraLocale('kn', strings);
