export * from './document-library.class.js';
import { LyraDocumentLibrary } from './document-library.class.js';
import { defineElement } from '../../internal/prefix.js';
import '../table/table.js';
import '../checkbox/checkbox.js';
import '../chip/chip.js';
import '../chip/chip-group.js';
import '../file-icon/file-icon.js';
import '../input/input.js';
import '../combobox/combobox.js';
defineElement('document-library', LyraDocumentLibrary);
