// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'سلائیڈ شو',
  carouselLabel: 'سلائیڈ شو',
  carouselSlide: 'سلائیڈ',
  carouselSlidePosition: '{total} وچوں سلائیڈ {index}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'سلائیڈ شو دیاں سلائیڈاں',
  carouselGoTo: 'سلائیڈ {index} تے جاؤ',
  scrollerLabel: 'سکرول ہو سکّن والا مواد',
  scrollPrevious: 'پچھے سکرول کرو',
  scrollNext: 'اگے سکرول کرو',
  closeNavigation: 'راہنمائی بند کرو',
  openNavigation: 'راہنمائی کھولو',
  resizeNavigation: 'راہنمائی دا سائز بدلو',
  appRailCollapse: 'راہنمائی سمیٹو',
  appRailExpand: 'راہنمائی پھیلاؤ',
  appRailItemCollapse: '{label} سمیٹو',
  appRailItemExpand: '{label} پھیلاؤ',
  resizeValuePercent: '{value} فیصد',
  commandPaletteLabel: 'کمانڈ پیلیٹ',
  commandPalettePlaceholder: 'کمانڈ لبھو…',
  commandPaletteEmpty: 'کوئی میل کھاندی کمانڈ نئیں۔',
  commandPaletteResults: 'کمانڈاں',
  dockPanelCollapse: 'پینل سمیٹو',
  dockPanelExpand: 'پینل پھیلاؤ',
  dockPanelResize: 'پینل دا سائز بدلو',
  responsivePanel: 'پینل',
  breadcrumb: 'بریڈ کرمب',
  resizeDivider: 'پینل {a} تے پینل {b} دے وچکار دی وکھری پٹی دا سائز بدلو',
  widgetFullscreenPanel: 'پوری سکرین پینل',
  widgetViewGroup: 'پینل دا منظر',
  widgetExitFullscreen: 'پوری سکرین توں باہر آؤ',
  widgetExpandToFullscreen: 'پوری سکرین تے پھیلاؤ',
  widgetCollapse: 'پینل سمیٹو',
  widgetExpand: 'پینل پھیلاؤ',
  skipToContent: 'مواد تے جاؤ',
  dashboardGridLabel: 'ڈیش بورڈ گرڈ',
  dashboardCellCollisionRejected: '{label} اتھے نئیں رکھیا جا سکدا، کیوں جو ایہہ دوجے خانے تے چڑھدا اے۔',
  dashboardCellMoved: '{label} کالم {x}، قطار {y} تے چلا گیا۔',
  dashboardCellResized: '{label} دا سائز چوڑائی {w}، اُچائی {h} کیتا گیا۔',
  filterBarReset: 'فلٹر مڑ بحال کرو',
  filterBarActiveFilters: 'چالو فلٹر',
  drilldownDocuments: 'دستاویزاں',
  drilldownRuns: 'ایجنٹ دے رن',
  drilldownEmpty: 'کوئی شے نئیں چنی',
  drilldownUntitledNode: 'بے ناں قدم',
  reorderMovePending: 'ترتیب بدلنے دی اُڈیک اے۔',
  reorderMoveCancelled: 'ترتیب بدلنا منسوخ ہویا۔',
  commandPaletteResultCount: {
    one: '{count} کمانڈ',
    other: '{count} کمانڈاں',
  },
};

registerLyraLocale('pnb', strings, { dir: 'rtl', name: 'پنجابی' });
