// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
//
// The `forms` slice of the ko translation catalog for @aceshooting/lyra-ui: strings owned exclusively by `src/components/forms/**`.
// A side-effect-only module -- a consumer writes a bare
// `import '@aceshooting/lyra-ui/translations/ko/forms';` and reads nothing from it.
// `../ko.ts` re-exports every slice for this locale and remains the safe, back-compat
// default; import this file directly only once the application knows it needs exactly this
// family's strings. Keep the keys in DEFAULT_STRINGS order -- `scripts/check-translations.mjs`
// enforces coverage, order, placeholder names and the plural-category set per slice now, not just
// per locale.
//
// Regenerate with: node scripts/generate-translation-slices.mjs --write
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  openCalendar: '달력 열기',
  comboboxLoadError: '옵션을 로드할 수 없습니다.',
  comboboxSelectedOverflow: '+ {n} 더 보기',
  checkboxRequired: '계속하려면 이 확인란을 선택하세요.',
  checkboxGroupRequired: '하나 이상의 옵션을 선택하십시오.',
  tokenInputRequired: '하나 이상의 값을 입력하십시오.',
  tokenInputEditWithContext: '{label} 편집',
  iconButtonLabel: '버튼',
  codeEditorLabel: '코드 편집기',
  switchRequired: '이 기능을 켜주세요.',
  textareaLabel: '텍스트',
  comboboxOverflow: '+ {n}개 더 보기 — 검색을 구체화하세요',
  comboboxRequired: '옵션을 선택하십시오.',
  comboboxCreate: '{value} 생성',
  comboboxLabel: '콤보 상자',
  previousMonth: '지난 달',
  nextMonth: '다음 달',
  chooseDate: '날짜 선택',
  dateInputPastDisabled: '과거 날짜는 선택할 수 없습니다.',
  dateInputFutureDisabled: '미래 날짜는 선택할 수 없습니다.',
  timeInputLabel: '시간',
  timeInputHour: '시간',
  timeInputMinute: '분',
  timeInputSecond: '초',
  timeInputDayPeriod: '오전/오후',
  timeInputEmptySegment: '비어 있음',
  timeInputOpen: '시간 선택 도구',
  timeInputPopup: '시간 선택',
  timeInputNow: '현재',
  timeInputInvalid: '전체 시간을 입력하세요.',
  timeInputMinMessage: '시간은 {min} 이후여야 합니다.',
  timeInputMaxMessage: '시간은 {max} 이전이어야 합니다.',
  timeInputRangeMessage: '시간은 자정을 넘어도 {min}부터 {max} 사이여야 합니다.',
  timeInputStepMessage: '필요한 간격과 일치하는 시간을 입력하십시오.',
  inputLabel: '텍스트',
  showPassword: '비밀번호 표시',
  hidePassword: '비밀번호 숨기기',
  radioRequired: '옵션을 선택하십시오.',
  sliderLabel: '슬라이더',
  colorPicker: '색 선택',
  selectValueMissing: '옵션을 선택하십시오.',
  rangeStart: '범위 시작',
  rangeEnd: '범위 끝',
  matchMismatch: '값이 일치하지 않습니다.',
  phoneInputLabel: '전화번호',
  phoneInputIncomplete: '전화번호가 완성되지 않았습니다.',
  otpInputIncomplete: '모든 {total} 문자를 입력하십시오.',
  otpInputLabel: '인증 코드',
  numberInputIncrease: '값 증가',
  numberInputDecrease: '값 감소',
  textareaCharacterCount: {
    other: '{count}자',
  },
  textareaCharactersRemaining: {
    other: '남은 문자 수: {count}',
  },
  colorPickerSaturationBrightness: '채도 및 밝기',
  colorPickerSaturationBrightnessValue: '채도 {saturation} %, 밝기 {brightness} %',
  colorPickerHue: '색상',
  colorPickerHueValue: '{hue}도',
  colorPickerOpacity: '불투명도',
  colorPickerOpacityValue: '불투명도 {opacity}%',
  colorPickerValueField: '색상 값',
  colorPickerToggleFormat: '색상 형식 전환',
  colorPickerEyeDropper: '화면에서 색상을 선택하세요.',
  colorPickerSwatches: '색상 견본',
  colorPickerSwatch: '{color} 선택',
  colorPickerCurrentValue: '현재 색상: {color}',
  selectSelectedOverflow: '+ {n} 더 보기',
  emojiPickerSearchLabel: '이모티콘 검색',
  emojiPickerSearchPlaceholder: '이모티콘 검색…',
  emojiPickerGridLabel: '이모지',
  emojiPickerEmpty: '이모티콘이 없습니다',
  emojiPickerLoadError: '이모티콘을 로드할 수 없습니다.',
  emojiPickerGroupSmileysEmotion: '미소와 감정',
  emojiPickerGroupPeopleBody: '사람 및 신체',
  emojiPickerGroupComponent: '요소',
  emojiPickerGroupAnimalsNature: '동물과 자연',
  emojiPickerGroupFoodDrink: '음식 및 음료',
  emojiPickerGroupTravelPlaces: '여행 및 장소',
  emojiPickerGroupActivities: '활동',
  emojiPickerGroupObjects: '사물',
  emojiPickerGroupSymbols: '기호',
  emojiPickerGroupFlags: '플래그',
  emojiPickerGroupUnknown: '그룹 {group}',
  rubricSubmit: '제출',
  rubricSubmitAndNext: '제출 및 다음',
  rubricSkip: '넘기기',
  localePickerLabel: '언어',
  localePickerRequired: '언어 선택',
};

registerLyraLocale('ko', strings, { dir: 'ltr', name: '한국어' });
