// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: '캐러셀',
  carouselLabel: '캐러셀',
  carouselSlide: '슬라이드',
  carouselSlidePosition: '전체 {total}개 중 {index}번째 슬라이드',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: '캐러셀 슬라이드',
  carouselGoTo: '{index} 슬라이드로 이동',
  scrollerLabel: '스크롤 가능한 콘텐츠',
  scrollPrevious: '뒤로 스크롤',
  scrollNext: '앞으로 스크롤',
  closeNavigation: '탐색 메뉴 닫기',
  openNavigation: '내비게이션 열기',
  resizeNavigation: '내비게이션 크기 조정',
  appRailCollapse: '내비게이션 접기',
  appRailExpand: '내비게이션 펼치기',
  appRailItemCollapse: '{label} 접기',
  appRailItemExpand: '{label} 확장',
  resizeValuePercent: '{value}퍼센트',
  commandPaletteLabel: '명령 팔레트',
  commandPalettePlaceholder: '명령 검색...',
  commandPaletteEmpty: '일치하는 명령이 없습니다.',
  commandPaletteResults: '명령어',
  dockPanelCollapse: '패널 접기',
  dockPanelExpand: '패널 펼치기',
  dockPanelResize: '패널 크기 조정',
  responsivePanel: '패널',
  breadcrumb: '이동경로',
  resizeDivider: '패널 {a}와 패널 {b} 사이의 크기 조정 구분자',
  widgetFullscreenPanel: '전체 화면 패널',
  widgetViewGroup: '패널 보기',
  widgetExitFullscreen: '전체 화면 종료',
  widgetExpandToFullscreen: '전체 화면으로 확장',
  widgetCollapse: '패널 접기',
  widgetExpand: '패널 펼치기',
  skipToContent: '본문으로 건너뛰기',
  dashboardGridLabel: '대시보드 그리드',
  dashboardCellCollisionRejected: '{label}은(는) 다른 셀과 겹치므로 여기에 배치할 수 없습니다.',
  dashboardCellMoved: '{label}이(가) 열 {x}, 행 {y}(으)로 이동됨.',
  dashboardCellResized: '{label} 크기가 너비 {w}, 높이 {h}(으)로 조정됨.',
  filterBarReset: '필터 재설정',
  filterBarActiveFilters: '적용된 필터',
  drilldownDocuments: '문서',
  drilldownRuns: '에이전트 실행',
  drilldownEmpty: '선택한 항목이 없습니다',
  drilldownUntitledNode: '제목 없는 단계',
  reorderMovePending: '순서 변경 대기 중.',
  reorderMoveCancelled: '순서 변경이 취소되었습니다.',
  commandPaletteResultCount: {
    other: '{count} 명령',
  },
};

registerLyraLocale('ko', strings);
