import { expect, fixture, html, waitUntil } from '@open-wc/testing';
import './calendar-viewer.js';
import type { LyraCalendarViewer } from './calendar-viewer.js';

const SAMPLE_ICS = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//lyra-ui//test//EN', 'BEGIN:VEVENT', 'UID:event-1@example.test', 'DTSTAMP:20260701T090000Z', 'DTSTART:20260714T140000Z', 'DTEND:20260714T150000Z', 'SUMMARY:Quarterly planning', 'LOCATION:Room 204', 'DESCRIPTION:Review roadmap and budget.', 'END:VEVENT', 'END:VCALENDAR', ''].join('\r\n');
const TWO_EVENTS = SAMPLE_ICS.replace('END:VCALENDAR', ['BEGIN:VEVENT', 'UID:event-2@example.test', 'DTSTAMP:20260701T090000Z', 'DTSTART:20260715T100000Z', 'DTEND:20260715T110000Z', 'SUMMARY:Design review', 'END:VEVENT', 'END:VCALENDAR'].join('\r\n'));
const EMPTY_ICS = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//lyra-ui//test//EN', 'END:VCALENDAR', ''].join('\r\n');

function response(body: string, ok = true): Response { return { ok, status: ok ? 200 : 404, statusText: ok ? 'OK' : 'Not Found', text: () => Promise.resolve(body) } as Response; }
function stubFetch(body: string): () => void { const original = window.fetch; window.fetch = (() => Promise.resolve(response(body))) as typeof window.fetch; return () => { window.fetch = original; }; }
async function loaded(body: string): Promise<{ el: LyraCalendarViewer; restore: () => void }> { const restore = stubFetch(body); const el = await fixture<LyraCalendarViewer>(html`<lyra-calendar-viewer src="https://example.test/calendar.ics"></lyra-calendar-viewer>`); await waitUntil(() => el.shadowRoot!.querySelector('[part="event"]') !== null || el.shadowRoot!.querySelector('[part="error"]') !== null); return { el, restore }; }

describe('lyra-calendar-viewer', () => {
  it('renders a localized empty state by default', async () => { const el = await fixture<LyraCalendarViewer>(html`<lyra-calendar-viewer></lyra-calendar-viewer>`); expect(el.shadowRoot!.querySelector('.empty-note')!.textContent).to.equal('No calendar to display.'); });
  it('parses and renders events with plain text fields', async () => { const { el, restore } = await loaded(SAMPLE_ICS); try { expect(el.shadowRoot!.querySelectorAll('[part="event"]')).to.have.lengthOf(1); expect(el.shadowRoot!.querySelector('[part="event-summary"]')!.textContent).to.contain('Quarterly planning'); expect(el.shadowRoot!.querySelector('[part="event-location"]')!.textContent).to.contain('Room 204'); expect(el.shadowRoot!.querySelector('[part="event-description"]')!.textContent).to.contain('Review roadmap'); expect(el.shadowRoot!.querySelector('[part="event-time"]')!.textContent).to.not.equal(''); } finally { restore(); } });
  it('renders multiple events in source order', async () => { const { el, restore } = await loaded(TWO_EVENTS); try { expect(Array.from(el.shadowRoot!.querySelectorAll('[part="event-summary"]')).map((node) => node.textContent)).to.deep.equal(['Quarterly planning', 'Design review']); } finally { restore(); } });
  it('renders an error for an empty calendar', async () => { const { el, restore } = await loaded(EMPTY_ICS); try { expect(el.shadowRoot!.querySelector('[part="error"]')!.textContent).to.equal('This calendar has no events.'); } finally { restore(); } });
  it('rejects unsafe URLs and applies max-height', async () => { const el = await fixture<LyraCalendarViewer>(html`<lyra-calendar-viewer max-height="20rem" .src=${'java\tscript:alert(1)'}></lyra-calendar-viewer>`); await el.updateComplete; expect(el.shadowRoot!.querySelector('[part="error"]')).to.exist; expect((el.shadowRoot!.querySelector('[part="base"]') as HTMLElement).style.getPropertyValue('--lyra-calendar-viewer-max-height')).to.equal('20rem'); });
  it('supports localized empty-state strings', async () => { const el = await fixture<LyraCalendarViewer>(html`<lyra-calendar-viewer .strings=${{ documentPreviewEmpty: 'Aucun {type} à afficher.', documentPreviewTypeCalendar: 'calendrier' }}></lyra-calendar-viewer>`); expect(el.shadowRoot!.querySelector('.empty-note')!.textContent).to.equal('Aucun calendrier à afficher.'); });
  it('is accessible', async () => { const el = await fixture<LyraCalendarViewer>(html`<lyra-calendar-viewer></lyra-calendar-viewer>`); await expect(el).to.be.accessible(); });
  it('uses the name property as the accessible name of the base region', async () => { const el = await fixture<LyraCalendarViewer>(html`<lyra-calendar-viewer name="Team offsite.ics"></lyra-calendar-viewer>`); expect(el.shadowRoot!.querySelector('[part="base"]')!.getAttribute('aria-label')).to.equal('Team offsite.ics'); });
  it('falls back to a host aria-label when name is unset', async () => { const el = await fixture<LyraCalendarViewer>(html`<lyra-calendar-viewer aria-label="Holiday schedule"></lyra-calendar-viewer>`); expect(el.shadowRoot!.querySelector('[part="base"]')!.getAttribute('aria-label')).to.equal('Holiday schedule'); });
  it('lets name take precedence over a host aria-label', async () => { const el = await fixture<LyraCalendarViewer>(html`<lyra-calendar-viewer name="Team offsite.ics" aria-label="Host label"></lyra-calendar-viewer>`); expect(el.shadowRoot!.querySelector('[part="base"]')!.getAttribute('aria-label')).to.equal('Team offsite.ics'); });
  it('falls back to the localized calendarViewerLabel default when neither name nor a host aria-label is set', async () => { const el = await fixture<LyraCalendarViewer>(html`<lyra-calendar-viewer></lyra-calendar-viewer>`); expect(el.shadowRoot!.querySelector('[part="base"]')!.getAttribute('aria-label')).to.equal('Calendar viewer'); });
  it('supports a .strings override for the calendarViewerLabel fallback', async () => { const el = await fixture<LyraCalendarViewer>(html`<lyra-calendar-viewer .strings=${{ calendarViewerLabel: 'Visionneuse de calendrier' }}></lyra-calendar-viewer>`); expect(el.shadowRoot!.querySelector('[part="base"]')!.getAttribute('aria-label')).to.equal('Visionneuse de calendrier'); });
});
