// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.
import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  copyJson: 'JSON ڪلپ بورڊ تي ڪاپي ڪريو',
  circularReference: 'چڪرائتو حوالو',
  copyDiff: 'فرق ڪاپي ڪريو',
  diffViewOldLabel: 'اصل',
  diffViewNewLabel: 'ترميم ٿيل',
  diffViewHiddenLines: {
    one: '{count} اڻبدليل ليڪ',
    other: '{count} اڻبدليل ليڪون',
  },
  diffViewTooLarge: 'فرق ڏيکارڻ لاءِ تمام وڏو آهي.',
  jsonArray: 'ايري',
  jsonObject: 'آبجيڪٽ',
  jsonValue: 'قدر',
  jsonCopyLabel: '{label} ڪاپي ڪريو',
  jsonExpandLabel: '{label} وڌايو',
  jsonCollapseLabel: '{label} سميٽيو',
  jsonItemCount: {
    one: '{count} شيءِ',
    other: '{count} شيون',
  },
  jsonKeyCount: {
    one: '{count} ڪنجي',
    other: '{count} ڪنجيون',
  },
  jsonViewerLimit: 'صرف پهريان {count} JSON نوڊ ۽ {depth} اندروني سطحون ڏيکاري ۽ ڳولهي سگهجن ٿيون.',
  pollPause: 'روڪيو',
  pollResume: 'ٻيهر شروع ڪريو',
  pollRefresh: 'هاڻي تازو ڪريو',
  pollInactive: 'غيرفعال',
  pollRefreshing: 'تازو ٿي رهيو آهي…',
  pollPaused: 'روڪيل',
  pollPausedAnnounce: 'روڪيو ويو.',
  pollResumedAnnounce: 'ٻيهر شروع ٿيو.',
  pollRefreshingAnnounce: 'هاڻي تازو ٿي رهيو آهي.',
  randomContentPause: 'گهمڻ روڪيو',
  randomContentResume: 'گهمڻ ٻيهر شروع ڪريو',
  exportButtonLabel: 'برآمد ڪريو',
  knownDateDay: 'ڏينهن',
  knownDateMonth: 'مهينو',
  knownDateYear: 'سال',
  exportFormatMenuLabel: '{label} فارميٽ',
  mentionSuggestions: 'تجويزون',
  mentionResultCount: {
    one: '{count} تجويز',
    other: '{count} تجويزون',
  },
  mentionResultPosition: '{total} مان تجويز {current}',
  iconLoadError: 'آئڪن لوڊ نه ٿي سگهيو.',
  iconTooLarge: 'آئڪن فائل ڏيکارڻ لاءِ تمام وڏي آهي.',
  iconSanitizerMissing: 'هن آئڪن کي محفوظ نموني ڏيکارڻ لاءِ اختياري "dompurify" پيڪيج گهربل آهي.',
  tourSkip: 'ڇڏي ڏيو',
  tourDone: 'مڪمل',
  tourStepOf: '{total} مان قدم {current}',
};

registerLyraLocale('sd', strings, { dir: 'rtl', name: 'سنڌي' });
