// Generated from scripts/fixtures/component-inventory.json by generate-autoloader-manifest.mjs.
// Do not edit by hand.

import type { AutoloadableTagName } from './autoloader-tags.js';

/** Optional-peer packages each autoloadable tag needs; a tag absent from this table needs none. */
export const AUTOLOADER_OPTIONAL_PEERS: Readonly<Partial<Record<AutoloadableTagName, readonly string[]>>> = {
  'lr-agent-workspace': ['dompurify', 'katex', 'marked', 'shiki'],
  'lr-bar-chart': ['chart.js', 'chartjs-plugin-annotation', 'chartjs-plugin-datalabels', 'chartjs-plugin-zoom'],
  'lr-box-plot': ['@sgratzl/chartjs-chart-boxplot', 'chart.js'],
  'lr-bubble-chart': ['chart.js', 'chartjs-plugin-annotation', 'chartjs-plugin-datalabels', 'chartjs-plugin-zoom'],
  'lr-calendar-viewer': ['ical.js'],
  'lr-change-review': ['shiki'],
  'lr-chart': ['chart.js', 'chartjs-plugin-annotation', 'chartjs-plugin-datalabels', 'chartjs-plugin-zoom'],
  'lr-code-block': ['shiki'],
  'lr-code-block-core': ['shiki'],
  'lr-csv-viewer': ['papaparse'],
  'lr-dashboard-grid': ['dompurify', 'katex', 'marked', 'shiki'],
  'lr-dataset-viewer': ['papaparse'],
  'lr-diff-view': ['shiki'],
  'lr-document-compare': ['shiki'],
  'lr-docx-viewer': ['dompurify', 'mammoth'],
  'lr-doughnut-chart': ['chart.js', 'chartjs-plugin-annotation', 'chartjs-plugin-datalabels', 'chartjs-plugin-zoom'],
  'lr-ebook-viewer': ['epubjs'],
  'lr-email-viewer': ['dompurify', 'postal-mime'],
  'lr-emoji-picker': ['emoji-picker-element-data'],
  'lr-eval-result': ['shiki'],
  'lr-eval-run': ['dompurify', 'katex', 'marked', 'shiki'],
  'lr-geojson-viewer': ['maplibre-gl'],
  'lr-graph': ['d3-drag', 'd3-force', 'd3-selection', 'd3-zoom'],
  'lr-histogram': ['chart.js', 'chartjs-plugin-annotation', 'chartjs-plugin-datalabels', 'chartjs-plugin-zoom'],
  'lr-html-viewer': ['dompurify'],
  'lr-icon': ['dompurify'],
  'lr-icon-button': ['dompurify'],
  'lr-include': ['dompurify'],
  'lr-knowledge-graph-explorer': ['d3-drag', 'd3-force', 'd3-selection', 'd3-zoom'],
  'lr-line-chart': ['chart.js', 'chartjs-plugin-annotation', 'chartjs-plugin-datalabels', 'chartjs-plugin-zoom'],
  'lr-map': ['maplibre-gl'],
  'lr-markdown': ['dompurify', 'katex', 'marked', 'shiki'],
  'lr-markdown-core': ['dompurify', 'katex', 'marked', 'shiki'],
  'lr-message-parts': ['dompurify', 'katex', 'marked', 'shiki'],
  'lr-notebook-viewer': ['dompurify', 'katex', 'marked', 'shiki'],
  'lr-pdf-viewer': ['pdfjs-dist'],
  'lr-pie-chart': ['chart.js', 'chartjs-plugin-annotation', 'chartjs-plugin-datalabels', 'chartjs-plugin-zoom'],
  'lr-polar-area-chart': ['chart.js', 'chartjs-plugin-annotation', 'chartjs-plugin-datalabels', 'chartjs-plugin-zoom'],
  'lr-pptx-viewer': ['@aiden0z/pptx-renderer'],
  'lr-qr-code': ['qrcode'],
  'lr-radar-chart': ['chart.js', 'chartjs-plugin-annotation', 'chartjs-plugin-datalabels', 'chartjs-plugin-zoom'],
  'lr-rag-answer': ['dompurify', 'katex', 'marked', 'shiki'],
  'lr-scatter-chart': ['chart.js', 'chartjs-plugin-annotation', 'chartjs-plugin-datalabels', 'chartjs-plugin-zoom'],
  'lr-spreadsheet-viewer': ['xlsx'],
  'lr-streaming-text': ['dompurify', 'katex', 'marked', 'shiki'],
  'lr-streaming-text-core': ['dompurify', 'katex', 'marked', 'shiki'],
  'lr-svg-viewer': ['dompurify'],
  'lr-video': ['dompurify'],
  'lr-video-playlist': ['dompurify'],
  'lr-widget-renderer': ['dompurify', 'katex', 'marked', 'shiki'],
};
