// GENERATED FILE — do not edit. Regenerate with pnpm run scoped-definitions.
import type { LyraScopedElementConstructor } from '../utilities/scoped-registry.js';

export const scopedDefinitionLoaders: Readonly<Record<string, () => Promise<LyraScopedElementConstructor>>> = Object.freeze({
  'lr-accordion': () => import('../components/layout/details/accordion.class.js').then((module) => module.LyraAccordion),
  'lr-accordion-item': () => import('../components/layout/details/accordion-item.class.js').then((module) => module.LyraAccordionItem),
  'lr-activity-feed': () => import('../components/agent-tools/activity-feed/activity-feed.class.js').then((module) => module.LyraActivityFeed),
  'lr-agent-eval-dashboard': () => import('../components/agent-tools/agent-eval-dashboard/agent-eval-dashboard.class.js').then((module) => module.LyraAgentEvalDashboard),
  'lr-agent-question': () => import('../components/agent-tools/agent-question/agent-question.class.js').then((module) => module.LyraAgentQuestion),
  'lr-agent-run': () => import('../components/agent-tools/agent-run/agent-run.class.js').then((module) => module.LyraAgentRun),
  'lr-agent-trace': () => import('../components/agent-tools/agent-trace/agent-trace.class.js').then((module) => module.LyraAgentTrace),
  'lr-agent-workspace': () => import('../components/conversation/agent-workspace/agent-workspace.class.js').then((module) => module.LyraAgentWorkspace),
  'lr-alert': () => import('../components/overlays/alert/alert.class.js').then((module) => module.LyraAlert),
  'lr-animated-image': () => import('../components/media/animated-image/animated-image.class.js').then((module) => module.LyraAnimatedImage),
  'lr-animation': () => import('../components/media/animation/animation.class.js').then((module) => module.LyraAnimation),
  'lr-app-rail': () => import('../components/layout/app-rail/app-rail.class.js').then((module) => module.LyraAppRail),
  'lr-app-rail-group': () => import('../components/layout/app-rail-group/app-rail-group.class.js').then((module) => module.LyraAppRailGroup),
  'lr-app-rail-item': () => import('../components/layout/app-rail/app-rail-item.class.js').then((module) => module.LyraAppRailItem),
  'lr-approval-queue': () => import('../components/agent-tools/approval-queue/approval-queue.class.js').then((module) => module.LyraApprovalQueue),
  'lr-archive-viewer': () => import('../components/viewers/archive-viewer/archive-viewer.class.js').then((module) => module.LyraArchiveViewer),
  'lr-artifact-panel': () => import('../components/agent-tools/artifact-panel/artifact-panel.class.js').then((module) => module.LyraArtifactPanel),
  'lr-attachment-chip': () => import('../components/media/attachment-chip/attachment-chip.class.js').then((module) => module.LyraAttachmentChip),
  'lr-attachment-trigger': () => import('../components/media/attachment-trigger/attachment-trigger.class.js').then((module) => module.LyraAttachmentTrigger),
  'lr-audio-visualizer': () => import('../components/conversation/audio-visualizer/audio-visualizer.class.js').then((module) => module.LyraAudioVisualizer),
  'lr-av-player': () => import('../components/media/av-player/av-player.class.js').then((module) => module.LyraAvPlayer),
  'lr-avatar': () => import('../components/media/avatar/avatar.class.js').then((module) => module.LyraAvatar),
  'lr-avatar-group': () => import('../components/media/avatar-group/avatar-group.class.js').then((module) => module.LyraAvatarGroup),
  'lr-background-runs': () => import('../components/agent-tools/background-runs/background-runs.class.js').then((module) => module.LyraBackgroundRuns),
  'lr-badge': () => import('../components/overlays/badge/badge.class.js').then((module) => module.LyraBadge),
  'lr-bar-chart': () => import('../components/charts/chart/bar-chart.class.js').then((module) => module.LyraBarChart),
  'lr-box-plot': () => import('../components/charts/chart/box-plot.class.js').then((module) => module.LyraBoxPlot),
  'lr-branch-picker': () => import('../components/conversation/branch-picker/branch-picker.class.js').then((module) => module.LyraBranchPicker),
  'lr-breadcrumb': () => import('../components/layout/breadcrumb/breadcrumb.class.js').then((module) => module.LyraBreadcrumb),
  'lr-breadcrumb-item': () => import('../components/layout/breadcrumb/breadcrumb-item.class.js').then((module) => module.LyraBreadcrumbItem),
  'lr-browser-frame': () => import('../components/agent-tools/browser-frame/browser-frame.class.js').then((module) => module.LyraBrowserFrame),
  'lr-bubble-chart': () => import('../components/charts/chart/bubble-chart.class.js').then((module) => module.LyraBubbleChart),
  'lr-budget-meter': () => import('../components/agent-tools/budget-meter/budget-meter.class.js').then((module) => module.LyraBudgetMeter),
  'lr-button': () => import('../components/forms/button/button.class.js').then((module) => module.LyraButton),
  'lr-button-group': () => import('../components/layout/button-group/button-group.class.js').then((module) => module.LyraButtonGroup),
  'lr-calendar': () => import('../components/data/calendar/calendar.class.js').then((module) => module.LyraCalendar),
  'lr-calendar-viewer': () => import('../components/viewers/calendar-viewer/calendar-viewer.class.js').then((module) => module.LyraCalendarViewer),
  'lr-callout': () => import('../components/overlays/callout/callout.class.js').then((module) => module.LyraCallout),
  'lr-card': () => import('../components/layout/card/card.class.js').then((module) => module.LyraCard),
  'lr-carousel': () => import('../components/layout/carousel/carousel.class.js').then((module) => module.LyraCarousel),
  'lr-carousel-item': () => import('../components/layout/carousel/carousel-item.class.js').then((module) => module.LyraCarouselItem),
  'lr-change-review': () => import('../components/agent-tools/change-review/change-review.class.js').then((module) => module.LyraChangeReview),
  'lr-chart': () => import('../components/charts/chart/chart.class.js').then((module) => module.LyraChart),
  'lr-chat-composer': () => import('../components/conversation/chat-composer/chat-composer.class.js').then((module) => module.LyraChatComposer),
  'lr-chat-message': () => import('../components/conversation/chat-message/chat-message.class.js').then((module) => module.LyraChatMessage),
  'lr-chat-viewport': () => import('../components/conversation/chat-viewport/chat-viewport.class.js').then((module) => module.LyraChatViewport),
  'lr-checkbox': () => import('../components/forms/checkbox/checkbox.class.js').then((module) => module.LyraCheckbox),
  'lr-checkbox-group': () => import('../components/forms/checkbox-group/checkbox-group.class.js').then((module) => module.LyraCheckboxGroup),
  'lr-checkpoint': () => import('../components/conversation/checkpoint/checkpoint.class.js').then((module) => module.LyraCheckpoint),
  'lr-chip': () => import('../components/overlays/chip/chip.class.js').then((module) => module.LyraChip),
  'lr-chip-group': () => import('../components/overlays/chip/chip-group.class.js').then((module) => module.LyraChipGroup),
  'lr-chunk-inspector': () => import('../components/retrieval/chunk-inspector/chunk-inspector.class.js').then((module) => module.LyraChunkInspector),
  'lr-citation-badge': () => import('../components/retrieval/citation-badge/citation-badge.class.js').then((module) => module.LyraCitationBadge),
  'lr-claim-evidence': () => import('../components/retrieval/claim-evidence/claim-evidence.class.js').then((module) => module.LyraClaimEvidence),
  'lr-code-block': () => import('../components/conversation/code-block/code-block.class.js').then((module) => module.LyraCodeBlock),
  'lr-code-block-core': () => import('../components/conversation/code-block/code-block-core.class.js').then((module) => module.LyraCodeBlockCore),
  'lr-code-editor': () => import('../components/forms/code-editor/code-editor.class.js').then((module) => module.LyraCodeEditor),
  'lr-color-picker': () => import('../components/forms/color-picker/color-picker.class.js').then((module) => module.LyraColorPicker),
  'lr-combobox': () => import('../components/forms/combobox/combobox.class.js').then((module) => module.LyraCombobox),
  'lr-command-palette': () => import('../components/layout/command-palette/command-palette.class.js').then((module) => module.LyraCommandPalette),
  'lr-commit-card': () => import('../components/agent-tools/commit-card/commit-card.class.js').then((module) => module.LyraCommitCard),
  'lr-community-card': () => import('../components/retrieval/community-card/community-card.class.js').then((module) => module.LyraCommunityCard),
  'lr-compare-panel': () => import('../components/agent-tools/compare-panel/compare-panel.class.js').then((module) => module.LyraComparePanel),
  'lr-condition-builder': () => import('../components/data/condition-builder/condition-builder.class.js').then((module) => module.LyraConditionBuilder),
  'lr-confirm-bar': () => import('../components/agent-tools/confirm-bar/confirm-bar.class.js').then((module) => module.LyraConfirmBar),
  'lr-connector-manager': () => import('../components/agent-tools/connector-manager/connector-manager.class.js').then((module) => module.LyraConnectorManager),
  'lr-contact-viewer': () => import('../components/viewers/contact-viewer/contact-viewer.class.js').then((module) => module.LyraContactViewer),
  'lr-context-inspector': () => import('../components/agent-tools/context-inspector/context-inspector.class.js').then((module) => module.LyraContextInspector),
  'lr-context-menu': () => import('../components/overlays/context-menu/context-menu.class.js').then((module) => module.LyraContextMenu),
  'lr-context-meter': () => import('../components/data/context-meter/context-meter.class.js').then((module) => module.LyraContextMeter),
  'lr-control-group': () => import('../components/layout/control-group/control-group.class.js').then((module) => module.LyraControlGroup),
  'lr-conversation-item': () => import('../components/conversation/conversation-item/conversation-item.class.js').then((module) => module.LyraConversationItem),
  'lr-copy-button': () => import('../components/utility/copy-button/copy-button.class.js').then((module) => module.LyraCopyButton),
  'lr-csv-viewer': () => import('../components/viewers/csv-viewer/csv-viewer.class.js').then((module) => module.LyraCsvViewer),
  'lr-dashboard-grid': () => import('../components/layout/dashboard-grid/dashboard-grid.class.js').then((module) => module.LyraDashboardGrid),
  'lr-data-grid': () => import('../components/data/data-grid/data-grid.class.js').then((module) => module.LyraDataGrid),
  'lr-dataset-viewer': () => import('../components/viewers/dataset-viewer/dataset-viewer.class.js').then((module) => module.LyraDatasetViewer),
  'lr-date-input': () => import('../components/forms/date-picker/date-input.class.js').then((module) => module.LyraDateInput),
  'lr-date-picker': () => import('../components/forms/date-picker/date-picker.class.js').then((module) => module.LyraDatePicker),
  'lr-details': () => import('../components/layout/details/details.class.js').then((module) => module.LyraDetails),
  'lr-dialog': () => import('../components/overlays/dialog/dialog.class.js').then((module) => module.LyraDialog),
  'lr-diff-view': () => import('../components/utility/diff-view/diff-view.class.js').then((module) => module.LyraDiffView),
  'lr-divider': () => import('../components/utility/divider/divider.class.js').then((module) => module.LyraDivider),
  'lr-dock-panel': () => import('../components/layout/dock-panel/dock-panel.class.js').then((module) => module.LyraDockPanel),
  'lr-document-compare': () => import('../components/viewers/document-compare/document-compare.class.js').then((module) => module.LyraDocumentCompare),
  'lr-document-library': () => import('../components/data/document-library/document-library.class.js').then((module) => module.LyraDocumentLibrary),
  'lr-document-preview': () => import('../components/viewers/document-preview/document-preview.class.js').then((module) => module.LyraDocumentPreview),
  'lr-document-viewer': () => import('../components/viewers/document-viewer/document-viewer.class.js').then((module) => module.LyraDocumentViewer),
  'lr-docx-viewer': () => import('../components/viewers/docx-viewer/docx-viewer.class.js').then((module) => module.LyraDocxViewer),
  'lr-doughnut-chart': () => import('../components/charts/chart/doughnut-chart.class.js').then((module) => module.LyraDoughnutChart),
  'lr-drawer': () => import('../components/overlays/drawer/drawer.class.js').then((module) => module.LyraDrawer),
  'lr-drilldown-panel': () => import('../components/layout/drilldown-panel/drilldown-panel.class.js').then((module) => module.LyraDrilldownPanel),
  'lr-drop-zone': () => import('../components/media/drop-zone/drop-zone.class.js').then((module) => module.LyraDropZone),
  'lr-dropdown': () => import('../components/overlays/overlay/dropdown.class.js').then((module) => module.LyraDropdown),
  'lr-dropdown-item': () => import('../components/layout/menu/dropdown-item.class.js').then((module) => module.LyraDropdownItem),
  'lr-ebook-viewer': () => import('../components/viewers/ebook-viewer/ebook-viewer.class.js').then((module) => module.LyraEbookViewer),
  'lr-email-viewer': () => import('../components/viewers/email-viewer/email-viewer.class.js').then((module) => module.LyraEmailViewer),
  'lr-embedding-explorer': () => import('../components/retrieval/embedding-explorer/embedding-explorer.class.js').then((module) => module.LyraEmbeddingExplorer),
  'lr-emoji-picker': () => import('../components/forms/emoji-picker/emoji-picker.class.js').then((module) => module.LyraEmojiPicker),
  'lr-empty': () => import('../components/overlays/empty/empty.class.js').then((module) => module.LyraEmpty),
  'lr-entity-card': () => import('../components/retrieval/entity-card/entity-card.class.js').then((module) => module.LyraEntityCard),
  'lr-entity-chip': () => import('../components/retrieval/entity-chip/entity-chip.class.js').then((module) => module.LyraEntityChip),
  'lr-entity-dossier': () => import('../components/retrieval/entity-dossier/entity-dossier.class.js').then((module) => module.LyraEntityDossier),
  'lr-env-list': () => import('../components/data/env-list/env-list.class.js').then((module) => module.LyraEnvList),
  'lr-eval-dataset': () => import('../components/agent-tools/eval-dataset/eval-dataset.class.js').then((module) => module.LyraEvalDataset),
  'lr-eval-result': () => import('../components/agent-tools/eval-result/eval-result.class.js').then((module) => module.LyraEvalResult),
  'lr-eval-run': () => import('../components/agent-tools/evaluation-run/evaluation-run.class.js').then((module) => module.LyraEvalRun),
  'lr-export-button': () => import('../components/utility/export-button/export-button.class.js').then((module) => module.LyraExportButton),
  'lr-file-icon': () => import('../components/media/file-icon/file-icon.class.js').then((module) => module.LyraFileIcon),
  'lr-file-input': () => import('../components/media/file-input/file-input.class.js').then((module) => module.LyraFileInput),
  'lr-file-tree': () => import('../components/data/file-tree/file-tree.class.js').then((module) => module.LyraFileTree),
  'lr-filter-bar': () => import('../components/layout/filter-bar/filter-bar.class.js').then((module) => module.LyraFilterBar),
  'lr-flag': () => import('../components/media/flag/flag.class.js').then((module) => module.LyraFlag),
  'lr-flow-canvas': () => import('../components/data/flow-canvas/flow-canvas.class.js').then((module) => module.LyraFlowCanvas),
  'lr-flow-controls': () => import('../components/data/flow-controls/flow-controls.class.js').then((module) => module.LyraFlowControls),
  'lr-flow-minimap': () => import('../components/data/flow-minimap/flow-minimap.class.js').then((module) => module.LyraFlowMinimap),
  'lr-flow-node': () => import('../components/data/flow-node/flow-node.class.js').then((module) => module.LyraFlowNode),
  'lr-flow-run-status': () => import('../components/data/flow-run-status/flow-run-status.class.js').then((module) => module.LyraFlowRunStatus),
  'lr-format-bytes': () => import('../components/utility/format/format-bytes.class.js').then((module) => module.LyraFormatBytes),
  'lr-format-date': () => import('../components/utility/format/format-date.class.js').then((module) => module.LyraFormatDate),
  'lr-format-number': () => import('../components/utility/format/format-number.class.js').then((module) => module.LyraFormatNumber),
  'lr-funnel': () => import('../components/data/funnel/funnel.class.js').then((module) => module.LyraFunnel),
  'lr-gauge': () => import('../components/data/gauge/gauge.class.js').then((module) => module.LyraGauge),
  'lr-generation-metrics': () => import('../components/conversation/generation-metrics/generation-metrics.class.js').then((module) => module.LyraGenerationMetrics),
  'lr-geojson-view': () => import('../components/viewers/geojson-view/geojson-view.class.js').then((module) => module.LyraGeojsonView),
  'lr-geojson-viewer': () => import('../components/viewers/geojson-view/geojson-viewer.class.js').then((module) => module.LyraGeoJsonViewer),
  'lr-graph': () => import('../components/retrieval/graph/graph.class.js').then((module) => module.LyraGraph),
  'lr-graph-legend': () => import('../components/retrieval/graph-legend/graph-legend.class.js').then((module) => module.LyraGraphLegend),
  'lr-graph-query-builder': () => import('../components/data/graph-query-builder/graph-query-builder.class.js').then((module) => module.LyraGraphQueryBuilder),
  'lr-grounding-summary': () => import('../components/retrieval/grounding-summary/grounding-summary.class.js').then((module) => module.LyraGroundingSummary),
  'lr-handoff-divider': () => import('../components/conversation/handoff-divider/handoff-divider.class.js').then((module) => module.LyraHandoffDivider),
  'lr-heatmap': () => import('../components/data/heatmap/heatmap.class.js').then((module) => module.LyraHeatmap),
  'lr-highlight-layer': () => import('../components/viewers/highlight-layer/highlight-layer.class.js').then((module) => module.LyraHighlightLayer),
  'lr-histogram': () => import('../components/charts/chart/histogram.class.js').then((module) => module.LyraHistogram),
  'lr-html-viewer': () => import('../components/viewers/html-viewer/html-viewer.class.js').then((module) => module.LyraHtmlViewer),
  'lr-icon': () => import('../components/utility/icon/icon.class.js').then((module) => module.LyraIcon),
  'lr-icon-button': () => import('../components/forms/icon-button/icon-button.class.js').then((module) => module.LyraIconButton),
  'lr-image-comparer': () => import('../components/media/image-comparer/image-comparer.class.js').then((module) => module.LyraImageComparer),
  'lr-image-viewer': () => import('../components/media/image-viewer/image-viewer.class.js').then((module) => module.LyraImageViewer),
  'lr-include': () => import('../components/viewers/include/include.class.js').then((module) => module.LyraInclude),
  'lr-ingestion-queue': () => import('../components/retrieval/ingestion-queue/ingestion-queue.class.js').then((module) => module.LyraIngestionQueue),
  'lr-input': () => import('../components/forms/input/input.class.js').then((module) => module.LyraInput),
  'lr-intersection-observer': () => import('../components/utility/intersection-observer/intersection-observer.class.js').then((module) => module.LyraIntersectionObserver),
  'lr-json-schema-viewer': () => import('../components/agent-tools/schema-viewer/schema-viewer.class.js').then((module) => module.LyraJsonSchemaViewer),
  'lr-json-viewer': () => import('../components/utility/json-viewer/json-viewer.class.js').then((module) => module.LyraJsonViewer),
  'lr-kbd': () => import('../components/overlays/kbd/kbd.class.js').then((module) => module.LyraKbd),
  'lr-knowledge-base': () => import('../components/retrieval/knowledge-base/knowledge-base.class.js').then((module) => module.LyraKnowledgeBase),
  'lr-knowledge-base-admin': () => import('../components/retrieval/knowledge-base-admin/knowledge-base-admin.class.js').then((module) => module.LyraKnowledgeBaseAdmin),
  'lr-knowledge-graph-explorer': () => import('../components/retrieval/knowledge-graph-explorer/knowledge-graph-explorer.class.js').then((module) => module.LyraKnowledgeGraphExplorer),
  'lr-known-date': () => import('../components/utility/known-date/known-date.class.js').then((module) => module.LyraKnownDate),
  'lr-lightbox': () => import('../components/media/lightbox/lightbox.class.js').then((module) => module.LyraLightbox),
  'lr-line-chart': () => import('../components/charts/chart/line-chart.class.js').then((module) => module.LyraLineChart),
  'lr-lite-chart': () => import('../components/charts/chart/lite-chart.class.js').then((module) => module.LyraLiteChart),
  'lr-live-region': () => import('../components/utility/live-region/live-region.class.js').then((module) => module.LyraLiveRegion),
  'lr-locale-picker': () => import('../components/forms/locale-picker/locale-picker.class.js').then((module) => module.LyraLocalePicker),
  'lr-map': () => import('../components/media/map/map.class.js').then((module) => module.LyraMap),
  'lr-markdown': () => import('../components/conversation/markdown/markdown.class.js').then((module) => module.LyraMarkdown),
  'lr-markdown-core': () => import('../components/conversation/markdown/markdown-core.class.js').then((module) => module.LyraMarkdownCore),
  'lr-mcp-app': () => import('../components/agent-tools/mcp-app/mcp-app.class.js').then((module) => module.LyraMcpApp),
  'lr-media-card': () => import('../components/media/media-card/media-card.class.js').then((module) => module.LyraMediaCard),
  'lr-memory-panel': () => import('../components/retrieval/memory-panel/memory-panel.class.js').then((module) => module.LyraMemoryPanel),
  'lr-mention-popover': () => import('../components/utility/mention-popover/mention-popover.class.js').then((module) => module.LyraMentionPopover),
  'lr-menu': () => import('../components/layout/menu/menu.class.js').then((module) => module.LyraMenu),
  'lr-menu-item': () => import('../components/layout/menu/menu-item.class.js').then((module) => module.LyraMenuItem),
  'lr-menu-label': () => import('../components/layout/menu/menu-label.class.js').then((module) => module.LyraMenuLabel),
  'lr-menubar': () => import('../components/layout/menubar/menubar.class.js').then((module) => module.LyraMenubar),
  'lr-menubar-item': () => import('../components/layout/menubar/menubar-item.class.js').then((module) => module.LyraMenubarItem),
  'lr-message-actions': () => import('../components/conversation/message-actions/message-actions.class.js').then((module) => module.LyraMessageActions),
  'lr-message-feedback': () => import('../components/conversation/message-feedback/message-feedback.class.js').then((module) => module.LyraMessageFeedback),
  'lr-message-parts': () => import('../components/conversation/message-parts/message-parts.class.js').then((module) => module.LyraMessageParts),
  'lr-mind-map': () => import('../components/retrieval/mind-map/mind-map.class.js').then((module) => module.LyraMindMap),
  'lr-model-select': () => import('../components/conversation/model-select/model-select.class.js').then((module) => module.LyraModelSelect),
  'lr-model-settings-panel': () => import('../components/conversation/model-settings-panel/model-settings-panel.class.js').then((module) => module.LyraModelSettingsPanel),
  'lr-multi-split': () => import('../components/layout/multi-split/multi-split.class.js').then((module) => module.LyraMultiSplit),
  'lr-mutation-observer': () => import('../components/utility/mutation-observer/mutation-observer.class.js').then((module) => module.LyraMutationObserver),
  'lr-native-time-input': () => import('../components/forms/input/native-time-input.class.js').then((module) => module.LyraNativeTimeInput),
  'lr-navigation-menu': () => import('../components/layout/navigation-menu/navigation-menu.class.js').then((module) => module.LyraNavigationMenu),
  'lr-navigation-menu-item': () => import('../components/layout/navigation-menu-item/navigation-menu-item.class.js').then((module) => module.LyraNavigationMenuItem),
  'lr-neighbor-list': () => import('../components/retrieval/neighbor-list/neighbor-list.class.js').then((module) => module.LyraNeighborList),
  'lr-node-palette': () => import('../components/retrieval/node-palette/node-palette.class.js').then((module) => module.LyraNodePalette),
  'lr-notebook-viewer': () => import('../components/viewers/notebook-viewer/notebook-viewer.class.js').then((module) => module.LyraNotebookViewer),
  'lr-number-input': () => import('../components/forms/input/number-input.class.js').then((module) => module.LyraNumberInput),
  'lr-option': () => import('../components/forms/combobox/option.class.js').then((module) => module.LyraOption),
  'lr-otp-input': () => import('../components/forms/otp-input/otp-input.class.js').then((module) => module.LyraOtpInput),
  'lr-page': () => import('../components/layout/page/page.class.js').then((module) => module.LyraPage),
  'lr-page-rail': () => import('../components/viewers/page-rail/page-rail.class.js').then((module) => module.LyraPageRail),
  'lr-pagination': () => import('../components/data/pagination/pagination.class.js').then((module) => module.LyraPagination),
  'lr-pan-zoom': () => import('../components/media/pan-zoom/pan-zoom.class.js').then((module) => module.LyraPanZoom),
  'lr-path-strip': () => import('../components/retrieval/path-strip/path-strip.class.js').then((module) => module.LyraPathStrip),
  'lr-pdf-viewer': () => import('../components/viewers/pdf-viewer/pdf-viewer.class.js').then((module) => module.LyraPdfViewer),
  'lr-permission-grant': () => import('../components/agent-tools/permission-grant/permission-grant.class.js').then((module) => module.LyraPermissionGrant),
  'lr-permission-rules': () => import('../components/agent-tools/permission-rules/permission-rules.class.js').then((module) => module.LyraPermissionRules),
  'lr-phone-input': () => import('../components/forms/phone-input/phone-input.class.js').then((module) => module.LyraPhoneInput),
  'lr-pie-chart': () => import('../components/charts/chart/pie-chart.class.js').then((module) => module.LyraPieChart),
  'lr-polar-area-chart': () => import('../components/charts/chart/polar-area-chart.class.js').then((module) => module.LyraPolarAreaChart),
  'lr-policy-summary': () => import('../components/agent-tools/policy-summary/policy-summary.class.js').then((module) => module.LyraPolicySummary),
  'lr-poll-status': () => import('../components/utility/poll-status/poll-status.class.js').then((module) => module.LyraPollStatus),
  'lr-popover': () => import('../components/overlays/overlay/popover.class.js').then((module) => module.LyraPopover),
  'lr-popup': () => import('../components/overlays/popup/popup.class.js').then((module) => module.LyraPopup),
  'lr-pptx-viewer': () => import('../components/viewers/pptx-viewer/pptx-viewer.class.js').then((module) => module.LyraPptxViewer),
  'lr-progress-bar': () => import('../components/overlays/progress/progress-bar.class.js').then((module) => module.LyraProgressBar),
  'lr-progress-ring': () => import('../components/overlays/progress/progress-ring.class.js').then((module) => module.LyraProgressRing),
  'lr-prompt-input': () => import('../components/conversation/prompt-input/prompt-input.class.js').then((module) => module.LyraPromptInput),
  'lr-prompt-queue': () => import('../components/conversation/prompt-queue/prompt-queue.class.js').then((module) => module.LyraPromptQueue),
  'lr-prompt-studio': () => import('../components/agent-tools/prompt-studio/prompt-studio.class.js').then((module) => module.LyraPromptStudio),
  'lr-provenance-panel': () => import('../components/retrieval/provenance-panel/provenance-panel.class.js').then((module) => module.LyraProvenancePanel),
  'lr-push-to-talk': () => import('../components/conversation/push-to-talk/push-to-talk.class.js').then((module) => module.LyraPushToTalk),
  'lr-qr-code': () => import('../components/media/qr-code/qr-code.class.js').then((module) => module.LyraQrCode),
  'lr-radar-chart': () => import('../components/charts/chart/radar-chart.class.js').then((module) => module.LyraRadarChart),
  'lr-radio': () => import('../components/forms/radio/radio.class.js').then((module) => module.LyraRadio),
  'lr-radio-button': () => import('../components/forms/radio/radio-button.class.js').then((module) => module.LyraRadioButton),
  'lr-radio-group': () => import('../components/forms/radio/radio-group.class.js').then((module) => module.LyraRadioGroup),
  'lr-rag-answer': () => import('../components/retrieval/rag-answer/rag-answer.class.js').then((module) => module.LyraRagAnswer),
  'lr-rag-eval-dashboard': () => import('../components/retrieval/rag-eval-dashboard/rag-eval-dashboard.class.js').then((module) => module.LyraRagEvalDashboard),
  'lr-random-content': () => import('../components/utility/random-content/random-content.class.js').then((module) => module.LyraRandomContent),
  'lr-rating': () => import('../components/overlays/rating/rating.class.js').then((module) => module.LyraRating),
  'lr-realtime-session': () => import('../components/conversation/realtime-session/realtime-session.class.js').then((module) => module.LyraRealtimeSession),
  'lr-relative-time': () => import('../components/utility/format/relative-time.class.js').then((module) => module.LyraRelativeTime),
  'lr-reorder-item': () => import('../components/layout/reorder-list/reorder-item.class.js').then((module) => module.LyraReorderItem),
  'lr-reorder-list': () => import('../components/layout/reorder-list/reorder-list.class.js').then((module) => module.LyraReorderList),
  'lr-research-progress': () => import('../components/retrieval/research-progress/research-progress.class.js').then((module) => module.LyraResearchProgress),
  'lr-resize-observer': () => import('../components/utility/resize-observer/resize-observer.class.js').then((module) => module.LyraResizeObserver),
  'lr-responsive-panel': () => import('../components/layout/responsive-panel/responsive-panel.class.js').then((module) => module.LyraResponsivePanel),
  'lr-result-card': () => import('../components/agent-tools/result-card/result-card.class.js').then((module) => module.LyraResultCard),
  'lr-result-field': () => import('../components/agent-tools/result-card/result-field.class.js').then((module) => module.LyraResultField),
  'lr-retrieval-compare': () => import('../components/retrieval/retrieval-compare/retrieval-compare.class.js').then((module) => module.LyraRetrievalCompare),
  'lr-retrieval-results': () => import('../components/retrieval/retrieval-results/retrieval-results.class.js').then((module) => module.LyraRetrievalResults),
  'lr-retrieval-search': () => import('../components/retrieval/retrieval-search/retrieval-search.class.js').then((module) => module.LyraRetrievalSearch),
  'lr-retrieval-trace': () => import('../components/retrieval/retrieval-trace/retrieval-trace.class.js').then((module) => module.LyraRetrievalTrace),
  'lr-rubric-form': () => import('../components/forms/rubric-form/rubric-form.class.js').then((module) => module.LyraRubricForm),
  'lr-scatter-chart': () => import('../components/charts/chart/scatter-chart.class.js').then((module) => module.LyraScatterChart),
  'lr-scroller': () => import('../components/layout/scroller/scroller.class.js').then((module) => module.LyraScroller),
  'lr-segmented': () => import('../components/layout/segmented/segmented.class.js').then((module) => module.LyraSegmented),
  'lr-select': () => import('../components/forms/select/select.class.js').then((module) => module.LyraSelect),
  'lr-selection-toolbar': () => import('../components/conversation/selection-toolbar/selection-toolbar.class.js').then((module) => module.LyraSelectionToolbar),
  'lr-sequence-playback': () => import('../components/media/sequence-playback/sequence-playback.class.js').then((module) => module.LyraSequencePlayback),
  'lr-sequence-strip': () => import('../components/data/sequence-strip/sequence-strip.class.js').then((module) => module.LyraSequenceStrip),
  'lr-skeleton': () => import('../components/overlays/skeleton/skeleton.class.js').then((module) => module.LyraSkeleton),
  'lr-slider': () => import('../components/forms/slider/slider.class.js').then((module) => module.LyraSlider),
  'lr-source-card': () => import('../components/retrieval/source-card/source-card.class.js').then((module) => module.LyraSourceCard),
  'lr-source-list': () => import('../components/retrieval/source-list/source-list.class.js').then((module) => module.LyraSourceList),
  'lr-source-picker': () => import('../components/retrieval/source-picker/source-picker.class.js').then((module) => module.LyraSourcePicker),
  'lr-span-waterfall': () => import('../components/agent-tools/span-waterfall/span-waterfall.class.js').then((module) => module.LyraSpanWaterfall),
  'lr-sparkline': () => import('../components/data/sparkline/sparkline.class.js').then((module) => module.LyraSparkline),
  'lr-spinner': () => import('../components/overlays/spinner/spinner.class.js').then((module) => module.LyraSpinner),
  'lr-split-panel': () => import('../components/layout/split-panel/split-panel.class.js').then((module) => module.LyraSplitPanel),
  'lr-spreadsheet-viewer': () => import('../components/viewers/spreadsheet-viewer/spreadsheet-viewer.class.js').then((module) => module.LyraSpreadsheetViewer),
  'lr-stack-trace': () => import('../components/agent-tools/stack-trace/stack-trace.class.js').then((module) => module.LyraStackTrace),
  'lr-stat': () => import('../components/data/stat/stat.class.js').then((module) => module.LyraStat),
  'lr-stepper': () => import('../components/layout/stepper/stepper.class.js').then((module) => module.LyraStepper),
  'lr-stream-status': () => import('../components/conversation/stream-status/stream-status.class.js').then((module) => module.LyraStreamStatus),
  'lr-streaming-text': () => import('../components/conversation/streaming-text/streaming-text.class.js').then((module) => module.LyraStreamingText),
  'lr-streaming-text-core': () => import('../components/conversation/streaming-text/streaming-text-core.class.js').then((module) => module.LyraStreamingTextCore),
  'lr-subagent-panel': () => import('../components/agent-tools/subagent-panel/subagent-panel.class.js').then((module) => module.LyraSubagentPanel),
  'lr-suggestion-chips': () => import('../components/conversation/suggestion-chips/suggestion-chips.class.js').then((module) => module.LyraSuggestionChips),
  'lr-svg-viewer': () => import('../components/viewers/svg-viewer/svg-viewer.class.js').then((module) => module.LyraSvgViewer),
  'lr-swatch-picker': () => import('../components/forms/swatch-picker/swatch-picker.class.js').then((module) => module.LyraSwatchPicker),
  'lr-switch': () => import('../components/forms/switch/switch.class.js').then((module) => module.LyraSwitch),
  'lr-tab': () => import('../components/layout/tab-group/tab.class.js').then((module) => module.LyraTab),
  'lr-tab-group': () => import('../components/layout/tab-group/tab-group.class.js').then((module) => module.LyraTabGroup),
  'lr-tab-panel': () => import('../components/layout/tab-group/tab-panel.class.js').then((module) => module.LyraTabPanel),
  'lr-table': () => import('../components/data/table/table.class.js').then((module) => module.LyraTable),
  'lr-tag': () => import('../components/overlays/badge/tag.class.js').then((module) => module.LyraTag),
  'lr-task-list': () => import('../components/agent-tools/task-list/task-list.class.js').then((module) => module.LyraTaskList),
  'lr-terminal': () => import('../components/agent-tools/terminal/terminal.class.js').then((module) => module.LyraTerminal),
  'lr-test-results': () => import('../components/agent-tools/test-results/test-results.class.js').then((module) => module.LyraTestResults),
  'lr-textarea': () => import('../components/forms/textarea/textarea.class.js').then((module) => module.LyraTextarea),
  'lr-thinking-panel': () => import('../components/agent-tools/thinking-panel/thinking-panel.class.js').then((module) => module.LyraThinkingPanel),
  'lr-thread-list': () => import('../components/conversation/thread-list/thread-list.class.js').then((module) => module.LyraThreadList),
  'lr-time-input': () => import('../components/forms/input/time-input.class.js').then((module) => module.LyraTimeInput),
  'lr-time-range': () => import('../components/forms/time-range/time-range.class.js').then((module) => module.LyraTimeRange),
  'lr-timeline': () => import('../components/data/timeline/timeline.class.js').then((module) => module.LyraTimeline),
  'lr-timeline-item': () => import('../components/data/timeline/timeline-item.class.js').then((module) => module.LyraTimelineItem),
  'lr-toast': () => import('../components/overlays/toast/toast.class.js').then((module) => module.LyraToast),
  'lr-toast-item': () => import('../components/overlays/toast/toast-item.class.js').then((module) => module.LyraToastItem),
  'lr-toggle': () => import('../components/forms/toggle/toggle.class.js').then((module) => module.LyraToggle),
  'lr-toggle-group': () => import('../components/forms/toggle-group/toggle-group.class.js').then((module) => module.LyraToggleGroup),
  'lr-token-input': () => import('../components/forms/token-input/token-input.class.js').then((module) => module.LyraTokenInput),
  'lr-tool-approval-dialog': () => import('../components/agent-tools/tool-approval-dialog/tool-approval-dialog.class.js').then((module) => module.LyraToolApprovalDialog),
  'lr-tool-call-block': () => import('../components/agent-tools/tool-call-block/tool-call-block.class.js').then((module) => module.LyraToolCallBlock),
  'lr-tool-call-chip': () => import('../components/agent-tools/tool-call-chip/tool-call-chip.class.js').then((module) => module.LyraToolCallChip),
  'lr-tool-param-form': () => import('../components/agent-tools/tool-param-form/tool-param-form.class.js').then((module) => module.LyraToolParamForm),
  'lr-tool-result-dialog': () => import('../components/agent-tools/tool-result-dialog/tool-result-dialog.class.js').then((module) => module.LyraToolResultDialog),
  'lr-tool-result-view': () => import('../components/agent-tools/tool-result-view/tool-result-view.class.js').then((module) => module.LyraToolResultView),
  'lr-tool-select-dialog': () => import('../components/agent-tools/tool-select-dialog/tool-select-dialog.class.js').then((module) => module.LyraToolSelectDialog),
  'lr-tool-timeline': () => import('../components/agent-tools/tool-timeline/tool-timeline.class.js').then((module) => module.LyraToolTimeline),
  'lr-tooltip': () => import('../components/overlays/overlay/tooltip.class.js').then((module) => module.LyraTooltip),
  'lr-tour': () => import('../components/utility/tour/tour.class.js').then((module) => module.LyraTour),
  'lr-trace-tree': () => import('../components/agent-tools/trace-tree/trace-tree.class.js').then((module) => module.LyraTraceTree),
  'lr-transcript-feed': () => import('../components/conversation/transcript-feed/transcript-feed.class.js').then((module) => module.LyraTranscriptFeed),
  'lr-tree': () => import('../components/data/tree/tree.class.js').then((module) => module.LyraTree),
  'lr-tree-item': () => import('../components/data/tree/tree-item.class.js').then((module) => module.LyraTreeItem),
  'lr-typing-indicator': () => import('../components/conversation/typing-indicator/typing-indicator.class.js').then((module) => module.LyraTypingIndicator),
  'lr-usage-badge': () => import('../components/conversation/usage-badge/usage-badge.class.js').then((module) => module.LyraUsageBadge),
  'lr-video': () => import('../components/media/video/video.class.js').then((module) => module.LyraVideo),
  'lr-video-playlist': () => import('../components/media/video-playlist/video-playlist.class.js').then((module) => module.LyraVideoPlaylist),
  'lr-virtual-list': () => import('../components/layout/virtual-list/virtual-list.class.js').then((module) => module.LyraVirtualList),
  'lr-visually-hidden': () => import('../components/utility/visually-hidden/visually-hidden.class.js').then((module) => module.LyraVisuallyHidden),
  'lr-voice-picker': () => import('../components/conversation/voice-picker/voice-picker.class.js').then((module) => module.LyraVoicePicker),
  'lr-widget': () => import('../components/layout/widget/widget.class.js').then((module) => module.LyraWidget),
  'lr-widget-renderer': () => import('../components/conversation/widget-renderer/widget-renderer.class.js').then((module) => module.LyraWidgetRenderer),
  'lr-word-cloud': () => import('../components/data/word-cloud/word-cloud.class.js').then((module) => module.LyraWordCloud),
  'lr-xml-viewer': () => import('../components/viewers/xml-viewer/xml-viewer.class.js').then((module) => module.LyraXmlViewer),
  'lr-zoomable-frame': () => import('../components/media/zoomable-frame/zoomable-frame.class.js').then((module) => module.LyraZoomableFrame),
});

export const scopedDefinitionClosures: Readonly<Record<string, readonly string[]>> = Object.freeze({
  'lr-accordion': ['lr-accordion'],
  'lr-accordion-item': ['lr-accordion-item'],
  'lr-activity-feed': ['lr-activity-feed', 'lr-live-region', 'lr-virtual-list'],
  'lr-agent-eval-dashboard': ['lr-agent-eval-dashboard', 'lr-badge', 'lr-lite-chart', 'lr-live-region', 'lr-stat'],
  'lr-agent-question': ['lr-agent-question', 'lr-number-input', 'lr-option', 'lr-select', 'lr-tool-param-form'],
  'lr-agent-run': ['lr-agent-run', 'lr-badge', 'lr-empty', 'lr-generation-metrics', 'lr-live-region', 'lr-task-list', 'lr-usage-badge'],
  'lr-agent-trace': ['lr-agent-trace', 'lr-empty', 'lr-graph-legend', 'lr-handoff-divider', 'lr-live-region', 'lr-trace-tree'],
  'lr-agent-workspace': ['lr-agent-run', 'lr-agent-workspace', 'lr-attachment-chip', 'lr-badge', 'lr-button', 'lr-card', 'lr-chat-composer', 'lr-chat-message', 'lr-chat-viewport', 'lr-checkbox', 'lr-chunk-inspector', 'lr-citation-badge', 'lr-claim-evidence', 'lr-context-inspector', 'lr-context-meter', 'lr-copy-button', 'lr-details', 'lr-empty', 'lr-export-button', 'lr-generation-metrics', 'lr-grounding-summary', 'lr-icon-button', 'lr-json-viewer', 'lr-live-region', 'lr-markdown', 'lr-media-card', 'lr-message-parts', 'lr-result-card', 'lr-result-field', 'lr-retrieval-results', 'lr-skeleton', 'lr-spinner', 'lr-stat', 'lr-task-list', 'lr-thinking-panel', 'lr-tool-approval-dialog', 'lr-tool-call-block', 'lr-tool-call-chip', 'lr-tool-result-view', 'lr-tool-timeline', 'lr-tooltip', 'lr-usage-badge', 'lr-virtual-list', 'lr-widget-renderer'],
  'lr-alert': ['lr-alert', 'lr-toast', 'lr-toast-item'],
  'lr-animated-image': ['lr-animated-image'],
  'lr-animation': ['lr-animation'],
  'lr-app-rail': ['lr-app-rail', 'lr-app-rail-item'],
  'lr-app-rail-group': ['lr-app-rail-group'],
  'lr-app-rail-item': ['lr-app-rail-item'],
  'lr-approval-queue': ['lr-approval-queue', 'lr-badge', 'lr-button', 'lr-json-viewer', 'lr-tool-approval-dialog'],
  'lr-archive-viewer': ['lr-archive-viewer', 'lr-virtual-list'],
  'lr-artifact-panel': ['lr-artifact-panel', 'lr-live-region'],
  'lr-attachment-chip': ['lr-attachment-chip'],
  'lr-attachment-trigger': ['lr-attachment-trigger', 'lr-dropdown', 'lr-icon-button', 'lr-menu', 'lr-menu-item'],
  'lr-audio-visualizer': ['lr-audio-visualizer'],
  'lr-av-player': ['lr-av-player', 'lr-virtual-list'],
  'lr-avatar': ['lr-avatar'],
  'lr-avatar-group': ['lr-avatar-group'],
  'lr-background-runs': ['lr-background-runs'],
  'lr-badge': ['lr-badge'],
  'lr-bar-chart': ['lr-bar-chart', 'lr-chart', 'lr-skeleton'],
  'lr-box-plot': ['lr-box-plot', 'lr-skeleton'],
  'lr-branch-picker': ['lr-branch-picker', 'lr-live-region'],
  'lr-breadcrumb': ['lr-breadcrumb'],
  'lr-breadcrumb-item': ['lr-breadcrumb-item'],
  'lr-browser-frame': ['lr-browser-frame'],
  'lr-bubble-chart': ['lr-bubble-chart', 'lr-chart', 'lr-skeleton'],
  'lr-budget-meter': ['lr-budget-meter'],
  'lr-button': ['lr-button'],
  'lr-button-group': ['lr-button-group'],
  'lr-calendar': ['lr-calendar'],
  'lr-calendar-viewer': ['lr-calendar-viewer'],
  'lr-callout': ['lr-callout', 'lr-icon-button'],
  'lr-card': ['lr-card'],
  'lr-carousel': ['lr-carousel'],
  'lr-carousel-item': ['lr-carousel-item'],
  'lr-change-review': ['lr-change-review', 'lr-diff-view'],
  'lr-chart': ['lr-chart', 'lr-skeleton'],
  'lr-chat-composer': ['lr-chat-composer'],
  'lr-chat-message': ['lr-chat-message', 'lr-live-region'],
  'lr-chat-viewport': ['lr-chat-viewport'],
  'lr-checkbox': ['lr-checkbox'],
  'lr-checkbox-group': ['lr-checkbox-group'],
  'lr-checkpoint': ['lr-checkpoint'],
  'lr-chip': ['lr-chip'],
  'lr-chip-group': ['lr-chip-group'],
  'lr-chunk-inspector': ['lr-chunk-inspector', 'lr-empty', 'lr-virtual-list'],
  'lr-citation-badge': ['lr-citation-badge'],
  'lr-claim-evidence': ['lr-badge', 'lr-citation-badge', 'lr-claim-evidence', 'lr-empty'],
  'lr-code-block': ['lr-code-block', 'lr-icon-button', 'lr-skeleton'],
  'lr-code-block-core': ['lr-code-block-core', 'lr-icon-button', 'lr-skeleton'],
  'lr-code-editor': ['lr-code-editor'],
  'lr-color-picker': ['lr-color-picker'],
  'lr-combobox': ['lr-combobox', 'lr-empty', 'lr-option'],
  'lr-command-palette': ['lr-command-palette', 'lr-icon'],
  'lr-commit-card': ['lr-commit-card'],
  'lr-community-card': ['lr-button', 'lr-chip', 'lr-community-card', 'lr-empty'],
  'lr-compare-panel': ['lr-compare-panel', 'lr-live-region'],
  'lr-condition-builder': ['lr-button', 'lr-combobox', 'lr-condition-builder', 'lr-date-input', 'lr-date-picker', 'lr-empty', 'lr-icon', 'lr-icon-button', 'lr-input', 'lr-option', 'lr-select'],
  'lr-confirm-bar': ['lr-button', 'lr-confirm-bar', 'lr-details', 'lr-json-viewer', 'lr-live-region'],
  'lr-connector-manager': ['lr-connector-manager'],
  'lr-contact-viewer': ['lr-contact-viewer'],
  'lr-context-inspector': ['lr-citation-badge', 'lr-context-inspector', 'lr-context-meter', 'lr-copy-button', 'lr-empty', 'lr-export-button', 'lr-icon-button', 'lr-tooltip'],
  'lr-context-menu': ['lr-context-menu', 'lr-dropdown', 'lr-menu', 'lr-menu-item'],
  'lr-context-meter': ['lr-context-meter'],
  'lr-control-group': ['lr-control-group'],
  'lr-conversation-item': ['lr-conversation-item'],
  'lr-copy-button': ['lr-copy-button', 'lr-icon-button', 'lr-tooltip'],
  'lr-csv-viewer': ['lr-csv-viewer', 'lr-virtual-list'],
  'lr-dashboard-grid': ['lr-badge', 'lr-button', 'lr-card', 'lr-dashboard-grid', 'lr-empty', 'lr-markdown', 'lr-media-card', 'lr-result-card', 'lr-result-field', 'lr-stat', 'lr-widget', 'lr-widget-renderer'],
  'lr-data-grid': ['lr-button', 'lr-data-grid', 'lr-dropdown', 'lr-dropdown-item', 'lr-empty', 'lr-menu', 'lr-menu-item'],
  'lr-dataset-viewer': ['lr-dataset-viewer', 'lr-virtual-list'],
  'lr-date-input': ['lr-date-input', 'lr-date-picker'],
  'lr-date-picker': ['lr-date-picker'],
  'lr-details': ['lr-details'],
  'lr-dialog': ['lr-dialog', 'lr-icon-button'],
  'lr-diff-view': ['lr-diff-view'],
  'lr-divider': ['lr-divider'],
  'lr-dock-panel': ['lr-dock-panel'],
  'lr-document-compare': ['lr-diff-view', 'lr-document-compare', 'lr-document-preview', 'lr-pan-zoom'],
  'lr-document-library': ['lr-checkbox', 'lr-chip', 'lr-chip-group', 'lr-combobox', 'lr-document-library', 'lr-empty', 'lr-file-icon', 'lr-input', 'lr-option', 'lr-pagination', 'lr-skeleton', 'lr-spinner', 'lr-table'],
  'lr-document-preview': ['lr-document-preview', 'lr-pan-zoom'],
  'lr-document-viewer': ['lr-dialog', 'lr-document-preview', 'lr-document-viewer', 'lr-icon-button', 'lr-pan-zoom'],
  'lr-docx-viewer': ['lr-docx-viewer'],
  'lr-doughnut-chart': ['lr-chart', 'lr-doughnut-chart', 'lr-skeleton'],
  'lr-drawer': ['lr-drawer', 'lr-icon-button'],
  'lr-drilldown-panel': ['lr-badge', 'lr-breadcrumb', 'lr-breadcrumb-item', 'lr-button', 'lr-chip', 'lr-document-preview', 'lr-drilldown-panel', 'lr-empty', 'lr-entity-card', 'lr-pan-zoom', 'lr-result-field', 'lr-source-card', 'lr-tab', 'lr-tab-group', 'lr-tab-panel'],
  'lr-drop-zone': ['lr-drop-zone'],
  'lr-dropdown': ['lr-dropdown', 'lr-menu', 'lr-menu-item'],
  'lr-dropdown-item': ['lr-dropdown-item', 'lr-menu', 'lr-menu-item'],
  'lr-ebook-viewer': ['lr-ebook-viewer'],
  'lr-email-viewer': ['lr-email-viewer'],
  'lr-embedding-explorer': ['lr-embedding-explorer'],
  'lr-emoji-picker': ['lr-emoji-picker'],
  'lr-empty': ['lr-empty'],
  'lr-entity-card': ['lr-badge', 'lr-button', 'lr-chip', 'lr-empty', 'lr-entity-card', 'lr-result-field'],
  'lr-entity-chip': ['lr-entity-chip'],
  'lr-entity-dossier': ['lr-badge', 'lr-button', 'lr-chip', 'lr-chunk-inspector', 'lr-community-card', 'lr-empty', 'lr-entity-card', 'lr-entity-chip', 'lr-entity-dossier', 'lr-neighbor-list', 'lr-path-strip', 'lr-provenance-panel', 'lr-result-field', 'lr-scroller', 'lr-stat', 'lr-tab', 'lr-tab-group', 'lr-tab-panel', 'lr-virtual-list'],
  'lr-env-list': ['lr-empty', 'lr-env-list'],
  'lr-eval-dataset': ['lr-chip', 'lr-chip-group', 'lr-empty', 'lr-eval-dataset', 'lr-export-button', 'lr-file-input', 'lr-pagination', 'lr-skeleton', 'lr-spinner', 'lr-table'],
  'lr-eval-result': ['lr-checkbox', 'lr-checkbox-group', 'lr-diff-view', 'lr-empty', 'lr-eval-result', 'lr-option', 'lr-pagination', 'lr-rubric-form', 'lr-segmented', 'lr-select', 'lr-skeleton', 'lr-slider', 'lr-spinner', 'lr-table', 'lr-textarea'],
  'lr-eval-run': ['lr-badge', 'lr-button', 'lr-citation-badge', 'lr-claim-evidence', 'lr-code-block', 'lr-copy-button', 'lr-details', 'lr-empty', 'lr-eval-run', 'lr-grounding-summary', 'lr-icon-button', 'lr-json-viewer', 'lr-live-region', 'lr-markdown', 'lr-progress-bar', 'lr-skeleton', 'lr-stat', 'lr-tool-approval-dialog', 'lr-tool-call-chip', 'lr-tool-result-view', 'lr-tool-timeline', 'lr-tooltip'],
  'lr-export-button': ['lr-export-button'],
  'lr-file-icon': ['lr-file-icon'],
  'lr-file-input': ['lr-file-input'],
  'lr-file-tree': ['lr-empty', 'lr-file-icon', 'lr-file-tree', 'lr-live-region', 'lr-tree', 'lr-tree-item'],
  'lr-filter-bar': ['lr-button', 'lr-chip', 'lr-chip-group', 'lr-combobox', 'lr-date-input', 'lr-date-picker', 'lr-dropdown', 'lr-dropdown-item', 'lr-empty', 'lr-filter-bar', 'lr-input', 'lr-menu', 'lr-menu-item', 'lr-option', 'lr-select', 'lr-spinner'],
  'lr-flag': ['lr-flag', 'lr-skeleton'],
  'lr-flow-canvas': ['lr-empty', 'lr-flow-canvas', 'lr-flow-node'],
  'lr-flow-controls': ['lr-flow-controls'],
  'lr-flow-minimap': ['lr-flow-minimap'],
  'lr-flow-node': ['lr-flow-node'],
  'lr-flow-run-status': ['lr-flow-run-status'],
  'lr-format-bytes': ['lr-format-bytes'],
  'lr-format-date': ['lr-format-date'],
  'lr-format-number': ['lr-format-number'],
  'lr-funnel': ['lr-funnel'],
  'lr-gauge': ['lr-gauge'],
  'lr-generation-metrics': ['lr-generation-metrics'],
  'lr-geojson-view': ['lr-geojson-view', 'lr-geojson-viewer', 'lr-json-viewer', 'lr-map', 'lr-skeleton'],
  'lr-geojson-viewer': ['lr-geojson-viewer', 'lr-json-viewer', 'lr-map', 'lr-skeleton'],
  'lr-graph': ['lr-graph', 'lr-skeleton'],
  'lr-graph-legend': ['lr-graph-legend'],
  'lr-graph-query-builder': ['lr-chip', 'lr-chip-group', 'lr-graph-query-builder', 'lr-input', 'lr-option', 'lr-select'],
  'lr-grounding-summary': ['lr-badge', 'lr-citation-badge', 'lr-claim-evidence', 'lr-empty', 'lr-grounding-summary', 'lr-stat'],
  'lr-handoff-divider': ['lr-handoff-divider', 'lr-live-region'],
  'lr-heatmap': ['lr-heatmap'],
  'lr-highlight-layer': ['lr-highlight-layer'],
  'lr-histogram': ['lr-chart', 'lr-histogram', 'lr-skeleton'],
  'lr-html-viewer': ['lr-html-viewer'],
  'lr-icon': ['lr-icon'],
  'lr-icon-button': ['lr-icon', 'lr-icon-button'],
  'lr-image-comparer': ['lr-image-comparer'],
  'lr-image-viewer': ['lr-image-viewer', 'lr-live-region', 'lr-pan-zoom'],
  'lr-include': ['lr-include'],
  'lr-ingestion-queue': ['lr-badge', 'lr-empty', 'lr-ingestion-queue', 'lr-progress-bar', 'lr-virtual-list'],
  'lr-input': ['lr-input'],
  'lr-intersection-observer': ['lr-intersection-observer'],
  'lr-json-schema-viewer': ['lr-badge', 'lr-empty', 'lr-json-schema-viewer'],
  'lr-json-viewer': ['lr-json-viewer'],
  'lr-kbd': ['lr-kbd'],
  'lr-knowledge-base': ['lr-badge', 'lr-button', 'lr-dropdown', 'lr-empty', 'lr-knowledge-base', 'lr-menu', 'lr-menu-item', 'lr-pagination', 'lr-skeleton', 'lr-spinner', 'lr-stat', 'lr-table'],
  'lr-knowledge-base-admin': ['lr-badge', 'lr-button', 'lr-dropdown', 'lr-empty', 'lr-ingestion-queue', 'lr-knowledge-base', 'lr-knowledge-base-admin', 'lr-menu', 'lr-menu-item', 'lr-pagination', 'lr-progress-bar', 'lr-skeleton', 'lr-spinner', 'lr-stat', 'lr-table', 'lr-virtual-list'],
  'lr-knowledge-graph-explorer': ['lr-badge', 'lr-button', 'lr-chip', 'lr-empty', 'lr-entity-card', 'lr-graph', 'lr-graph-legend', 'lr-input', 'lr-knowledge-graph-explorer', 'lr-neighbor-list', 'lr-path-strip', 'lr-popover', 'lr-result-field', 'lr-scroller', 'lr-skeleton', 'lr-virtual-list'],
  'lr-known-date': ['lr-known-date'],
  'lr-lightbox': ['lr-lightbox', 'lr-pan-zoom'],
  'lr-line-chart': ['lr-chart', 'lr-line-chart', 'lr-skeleton'],
  'lr-lite-chart': ['lr-lite-chart', 'lr-live-region'],
  'lr-live-region': ['lr-live-region'],
  'lr-locale-picker': ['lr-flag', 'lr-locale-picker', 'lr-skeleton'],
  'lr-map': ['lr-map', 'lr-skeleton'],
  'lr-markdown': ['lr-markdown'],
  'lr-markdown-core': ['lr-markdown-core'],
  'lr-mcp-app': ['lr-mcp-app'],
  'lr-media-card': ['lr-media-card'],
  'lr-memory-panel': ['lr-button', 'lr-chip', 'lr-chunk-inspector', 'lr-community-card', 'lr-confirm-bar', 'lr-details', 'lr-empty', 'lr-entity-chip', 'lr-json-viewer', 'lr-live-region', 'lr-memory-panel', 'lr-path-strip', 'lr-provenance-panel', 'lr-scroller', 'lr-virtual-list'],
  'lr-mention-popover': ['lr-mention-popover'],
  'lr-menu': ['lr-menu', 'lr-menu-item'],
  'lr-menu-item': ['lr-menu', 'lr-menu-item'],
  'lr-menu-label': ['lr-menu-label'],
  'lr-menubar': ['lr-menu', 'lr-menu-item', 'lr-menubar', 'lr-menubar-item'],
  'lr-menubar-item': ['lr-menu', 'lr-menu-item', 'lr-menubar-item'],
  'lr-message-actions': ['lr-chip', 'lr-copy-button', 'lr-icon-button', 'lr-live-region', 'lr-message-actions', 'lr-message-feedback', 'lr-tooltip'],
  'lr-message-feedback': ['lr-chip', 'lr-live-region', 'lr-message-feedback'],
  'lr-message-parts': ['lr-attachment-chip', 'lr-badge', 'lr-button', 'lr-card', 'lr-citation-badge', 'lr-copy-button', 'lr-details', 'lr-icon-button', 'lr-json-viewer', 'lr-markdown', 'lr-media-card', 'lr-message-parts', 'lr-result-card', 'lr-result-field', 'lr-skeleton', 'lr-stat', 'lr-thinking-panel', 'lr-tool-call-block', 'lr-tool-call-chip', 'lr-tool-result-view', 'lr-tooltip', 'lr-widget-renderer'],
  'lr-mind-map': ['lr-mind-map'],
  'lr-model-select': ['lr-model-select'],
  'lr-model-settings-panel': ['lr-model-select', 'lr-model-settings-panel', 'lr-slider'],
  'lr-multi-split': ['lr-multi-split'],
  'lr-mutation-observer': ['lr-mutation-observer'],
  'lr-native-time-input': ['lr-native-time-input'],
  'lr-navigation-menu': ['lr-navigation-menu', 'lr-navigation-menu-item'],
  'lr-navigation-menu-item': ['lr-navigation-menu-item'],
  'lr-neighbor-list': ['lr-empty', 'lr-neighbor-list', 'lr-virtual-list'],
  'lr-node-palette': ['lr-node-palette'],
  'lr-notebook-viewer': ['lr-code-block', 'lr-icon-button', 'lr-json-viewer', 'lr-markdown', 'lr-notebook-viewer', 'lr-skeleton', 'lr-virtual-list'],
  'lr-number-input': ['lr-number-input'],
  'lr-option': ['lr-option'],
  'lr-otp-input': ['lr-otp-input'],
  'lr-page': ['lr-page'],
  'lr-page-rail': ['lr-file-icon', 'lr-page-rail', 'lr-skeleton', 'lr-virtual-list'],
  'lr-pagination': ['lr-pagination'],
  'lr-pan-zoom': ['lr-pan-zoom'],
  'lr-path-strip': ['lr-path-strip', 'lr-scroller'],
  'lr-pdf-viewer': ['lr-highlight-layer', 'lr-pdf-viewer', 'lr-skeleton', 'lr-virtual-list'],
  'lr-permission-grant': ['lr-permission-grant'],
  'lr-permission-rules': ['lr-permission-rules'],
  'lr-phone-input': ['lr-flag', 'lr-phone-input', 'lr-skeleton'],
  'lr-pie-chart': ['lr-chart', 'lr-pie-chart', 'lr-skeleton'],
  'lr-polar-area-chart': ['lr-chart', 'lr-polar-area-chart', 'lr-skeleton'],
  'lr-policy-summary': ['lr-badge', 'lr-details', 'lr-empty', 'lr-policy-summary'],
  'lr-poll-status': ['lr-live-region', 'lr-poll-status'],
  'lr-popover': ['lr-popover'],
  'lr-popup': ['lr-popup'],
  'lr-pptx-viewer': ['lr-pptx-viewer', 'lr-skeleton'],
  'lr-progress-bar': ['lr-progress-bar'],
  'lr-progress-ring': ['lr-progress-ring'],
  'lr-prompt-input': ['lr-attachment-chip', 'lr-attachment-trigger', 'lr-button', 'lr-chat-composer', 'lr-checkbox', 'lr-dropdown', 'lr-empty', 'lr-file-icon', 'lr-icon-button', 'lr-input', 'lr-mention-popover', 'lr-menu', 'lr-menu-item', 'lr-model-select', 'lr-prompt-input', 'lr-prompt-queue', 'lr-source-picker', 'lr-textarea', 'lr-voice-picker'],
  'lr-prompt-queue': ['lr-button', 'lr-prompt-queue', 'lr-textarea'],
  'lr-prompt-studio': ['lr-prompt-studio'],
  'lr-provenance-panel': ['lr-button', 'lr-chip', 'lr-chunk-inspector', 'lr-community-card', 'lr-empty', 'lr-entity-chip', 'lr-path-strip', 'lr-provenance-panel', 'lr-scroller', 'lr-virtual-list'],
  'lr-push-to-talk': ['lr-live-region', 'lr-push-to-talk'],
  'lr-qr-code': ['lr-qr-code'],
  'lr-radar-chart': ['lr-chart', 'lr-radar-chart', 'lr-skeleton'],
  'lr-radio': ['lr-radio'],
  'lr-radio-button': ['lr-radio-button'],
  'lr-radio-group': ['lr-radio-group'],
  'lr-rag-answer': ['lr-badge', 'lr-button', 'lr-citation-badge', 'lr-claim-evidence', 'lr-empty', 'lr-grounding-summary', 'lr-markdown', 'lr-rag-answer', 'lr-source-card', 'lr-source-list', 'lr-spinner', 'lr-stat'],
  'lr-rag-eval-dashboard': ['lr-empty', 'lr-lite-chart', 'lr-live-region', 'lr-rag-eval-dashboard', 'lr-stat'],
  'lr-random-content': ['lr-random-content'],
  'lr-rating': ['lr-rating'],
  'lr-realtime-session': ['lr-audio-visualizer', 'lr-badge', 'lr-live-region', 'lr-push-to-talk', 'lr-realtime-session', 'lr-transcript-feed'],
  'lr-relative-time': ['lr-relative-time'],
  'lr-reorder-item': ['lr-icon-button', 'lr-reorder-item'],
  'lr-reorder-list': ['lr-icon-button', 'lr-live-region', 'lr-reorder-item', 'lr-reorder-list'],
  'lr-research-progress': ['lr-research-progress'],
  'lr-resize-observer': ['lr-resize-observer'],
  'lr-responsive-panel': ['lr-responsive-panel'],
  'lr-result-card': ['lr-result-card'],
  'lr-result-field': ['lr-result-field'],
  'lr-retrieval-compare': ['lr-empty', 'lr-retrieval-compare'],
  'lr-retrieval-results': ['lr-checkbox', 'lr-chunk-inspector', 'lr-empty', 'lr-retrieval-results', 'lr-spinner', 'lr-virtual-list'],
  'lr-retrieval-search': ['lr-chip', 'lr-chip-group', 'lr-empty', 'lr-input', 'lr-retrieval-search', 'lr-segmented', 'lr-spinner'],
  'lr-retrieval-trace': ['lr-chunk-inspector', 'lr-empty', 'lr-live-region', 'lr-retrieval-trace', 'lr-span-waterfall', 'lr-virtual-list'],
  'lr-rubric-form': ['lr-checkbox', 'lr-checkbox-group', 'lr-option', 'lr-rubric-form', 'lr-segmented', 'lr-select', 'lr-slider', 'lr-textarea'],
  'lr-scatter-chart': ['lr-chart', 'lr-scatter-chart', 'lr-skeleton'],
  'lr-scroller': ['lr-scroller'],
  'lr-segmented': ['lr-segmented'],
  'lr-select': ['lr-option', 'lr-select'],
  'lr-selection-toolbar': ['lr-button', 'lr-selection-toolbar'],
  'lr-sequence-playback': ['lr-sequence-playback'],
  'lr-sequence-strip': ['lr-sequence-strip'],
  'lr-skeleton': ['lr-skeleton'],
  'lr-slider': ['lr-slider'],
  'lr-source-card': ['lr-source-card'],
  'lr-source-list': ['lr-source-list'],
  'lr-source-picker': ['lr-checkbox', 'lr-empty', 'lr-file-icon', 'lr-input', 'lr-source-picker'],
  'lr-span-waterfall': ['lr-empty', 'lr-live-region', 'lr-span-waterfall'],
  'lr-sparkline': ['lr-sparkline'],
  'lr-spinner': ['lr-spinner'],
  'lr-split-panel': ['lr-split-panel'],
  'lr-spreadsheet-viewer': ['lr-spreadsheet-viewer', 'lr-tab', 'lr-tab-group', 'lr-tab-panel', 'lr-virtual-list'],
  'lr-stack-trace': ['lr-stack-trace'],
  'lr-stat': ['lr-stat'],
  'lr-stepper': ['lr-stepper'],
  'lr-stream-status': ['lr-live-region', 'lr-stream-status'],
  'lr-streaming-text': ['lr-markdown', 'lr-streaming-text'],
  'lr-streaming-text-core': ['lr-markdown-core', 'lr-streaming-text-core'],
  'lr-subagent-panel': ['lr-badge', 'lr-empty', 'lr-subagent-panel'],
  'lr-suggestion-chips': ['lr-scroller', 'lr-suggestion-chips'],
  'lr-svg-viewer': ['lr-pan-zoom', 'lr-svg-viewer'],
  'lr-swatch-picker': ['lr-swatch-picker'],
  'lr-switch': ['lr-switch'],
  'lr-tab': ['lr-tab'],
  'lr-tab-group': ['lr-tab-group'],
  'lr-tab-panel': ['lr-tab-panel'],
  'lr-table': ['lr-empty', 'lr-pagination', 'lr-skeleton', 'lr-spinner', 'lr-table'],
  'lr-tag': ['lr-tag'],
  'lr-task-list': ['lr-live-region', 'lr-task-list'],
  'lr-terminal': ['lr-terminal', 'lr-virtual-list'],
  'lr-test-results': ['lr-empty', 'lr-live-region', 'lr-spinner', 'lr-test-results'],
  'lr-textarea': ['lr-textarea'],
  'lr-thinking-panel': ['lr-thinking-panel'],
  'lr-thread-list': ['lr-conversation-item', 'lr-empty', 'lr-live-region', 'lr-thread-list', 'lr-virtual-list'],
  'lr-time-input': ['lr-time-input'],
  'lr-time-range': ['lr-time-range'],
  'lr-timeline': ['lr-relative-time', 'lr-timeline', 'lr-timeline-item'],
  'lr-timeline-item': ['lr-relative-time', 'lr-timeline-item'],
  'lr-toast': ['lr-toast', 'lr-toast-item'],
  'lr-toast-item': ['lr-toast-item'],
  'lr-toggle': ['lr-toggle'],
  'lr-toggle-group': ['lr-toggle-group'],
  'lr-token-input': ['lr-token-input'],
  'lr-tool-approval-dialog': ['lr-button', 'lr-json-viewer', 'lr-tool-approval-dialog'],
  'lr-tool-call-block': ['lr-copy-button', 'lr-icon-button', 'lr-json-viewer', 'lr-skeleton', 'lr-tool-call-block', 'lr-tool-result-view', 'lr-tooltip'],
  'lr-tool-call-chip': ['lr-tool-call-chip'],
  'lr-tool-param-form': ['lr-number-input', 'lr-option', 'lr-select', 'lr-tool-param-form'],
  'lr-tool-result-dialog': ['lr-tool-result-dialog'],
  'lr-tool-result-view': ['lr-copy-button', 'lr-icon-button', 'lr-json-viewer', 'lr-skeleton', 'lr-tool-result-view', 'lr-tooltip'],
  'lr-tool-select-dialog': ['lr-checkbox', 'lr-switch', 'lr-tool-select-dialog'],
  'lr-tool-timeline': ['lr-button', 'lr-copy-button', 'lr-details', 'lr-empty', 'lr-icon-button', 'lr-json-viewer', 'lr-skeleton', 'lr-tool-approval-dialog', 'lr-tool-call-chip', 'lr-tool-result-view', 'lr-tool-timeline', 'lr-tooltip'],
  'lr-tooltip': ['lr-tooltip'],
  'lr-tour': ['lr-tour'],
  'lr-trace-tree': ['lr-empty', 'lr-live-region', 'lr-trace-tree'],
  'lr-transcript-feed': ['lr-transcript-feed'],
  'lr-tree': ['lr-empty', 'lr-live-region', 'lr-tree', 'lr-tree-item'],
  'lr-tree-item': ['lr-tree-item'],
  'lr-typing-indicator': ['lr-typing-indicator'],
  'lr-usage-badge': ['lr-usage-badge'],
  'lr-video': ['lr-icon', 'lr-video'],
  'lr-video-playlist': ['lr-icon', 'lr-video', 'lr-video-playlist'],
  'lr-virtual-list': ['lr-virtual-list'],
  'lr-visually-hidden': ['lr-visually-hidden'],
  'lr-voice-picker': ['lr-voice-picker'],
  'lr-widget': ['lr-widget'],
  'lr-widget-renderer': ['lr-badge', 'lr-button', 'lr-card', 'lr-markdown', 'lr-media-card', 'lr-result-card', 'lr-result-field', 'lr-stat', 'lr-widget-renderer'],
  'lr-word-cloud': ['lr-word-cloud'],
  'lr-xml-viewer': ['lr-xml-viewer'],
  'lr-zoomable-frame': ['lr-zoomable-frame'],
});
