// GENERATED FILE — do not edit. Regenerate with pnpm run scoped-definitions.

export const scopedDefinitionClosures: Readonly<Record<string, readonly string[]>> = Object.freeze({
  'lr-accordion': ['lr-accordion'],
  'lr-accordion-item': ['lr-accordion-item'],
  'lr-activity-feed': ['lr-activity-feed', 'lr-live-region', 'lr-virtual-list'],
  'lr-agent-eval-dashboard': ['lr-agent-eval-dashboard', 'lr-badge', 'lr-lite-chart', 'lr-live-region', 'lr-stat'],
  'lr-agent-question': ['lr-agent-question', 'lr-number-input', 'lr-option', 'lr-select', 'lr-tool-param-form'],
  'lr-agent-run': ['lr-agent-run', 'lr-badge', 'lr-empty', 'lr-generation-metrics', 'lr-live-region', 'lr-task-list', 'lr-usage-badge'],
  'lr-agent-trace': ['lr-agent-trace', 'lr-empty', 'lr-graph-legend', 'lr-handoff-divider', 'lr-live-region', 'lr-trace-tree'],
  'lr-agent-workspace': ['lr-agent-run', 'lr-agent-workspace', 'lr-attachment-chip', 'lr-badge', 'lr-button', 'lr-card', 'lr-chat-composer', 'lr-chat-message', 'lr-chat-viewport', 'lr-checkbox', 'lr-chunk-inspector', 'lr-citation-badge', 'lr-claim-evidence', 'lr-context-inspector', 'lr-context-meter', 'lr-copy-button', 'lr-details', 'lr-empty', 'lr-export-button', 'lr-generation-metrics', 'lr-grounding-summary', 'lr-icon-button', 'lr-json-viewer', 'lr-live-region', 'lr-markdown', 'lr-media-card', 'lr-message-parts', 'lr-result-card', 'lr-result-field', 'lr-retrieval-results', 'lr-skeleton', 'lr-spinner', 'lr-stat', 'lr-task-list', 'lr-thinking-panel', 'lr-tool-approval-dialog', 'lr-tool-call-block', 'lr-tool-call-chip', 'lr-tool-result-view', 'lr-tool-timeline', 'lr-tooltip', 'lr-usage-badge', 'lr-virtual-list', 'lr-widget-renderer'],
  'lr-alert': ['lr-alert', 'lr-toast', 'lr-toast-item'],
  'lr-animated-image': ['lr-animated-image'],
  'lr-animation': ['lr-animation'],
  'lr-app-rail': ['lr-app-rail', 'lr-app-rail-item'],
  'lr-app-rail-group': ['lr-app-rail-group'],
  'lr-app-rail-item': ['lr-app-rail-item'],
  'lr-approval-queue': ['lr-approval-queue', 'lr-badge', 'lr-button', 'lr-json-viewer', 'lr-tool-approval-dialog'],
  'lr-archive-viewer': ['lr-archive-viewer', 'lr-virtual-list'],
  'lr-artifact-panel': ['lr-artifact-panel', 'lr-live-region'],
  'lr-attachment-chip': ['lr-attachment-chip'],
  'lr-attachment-trigger': ['lr-attachment-trigger', 'lr-dropdown', 'lr-icon-button', 'lr-menu', 'lr-menu-item'],
  'lr-audio-visualizer': ['lr-audio-visualizer'],
  'lr-av-player': ['lr-av-player', 'lr-virtual-list'],
  'lr-avatar': ['lr-avatar'],
  'lr-avatar-group': ['lr-avatar-group'],
  'lr-background-runs': ['lr-background-runs'],
  'lr-badge': ['lr-badge'],
  'lr-bar-chart': ['lr-bar-chart', 'lr-chart', 'lr-skeleton'],
  'lr-box-plot': ['lr-box-plot', 'lr-skeleton'],
  'lr-branch-picker': ['lr-branch-picker', 'lr-live-region'],
  'lr-breadcrumb': ['lr-breadcrumb'],
  'lr-breadcrumb-item': ['lr-breadcrumb-item'],
  'lr-browser-frame': ['lr-browser-frame'],
  'lr-bubble-chart': ['lr-bubble-chart', 'lr-chart', 'lr-skeleton'],
  'lr-budget-meter': ['lr-budget-meter'],
  'lr-button': ['lr-button'],
  'lr-button-group': ['lr-button-group'],
  'lr-calendar': ['lr-calendar'],
  'lr-calendar-viewer': ['lr-calendar-viewer'],
  'lr-callout': ['lr-callout', 'lr-icon-button'],
  'lr-card': ['lr-card'],
  'lr-carousel': ['lr-carousel'],
  'lr-carousel-item': ['lr-carousel-item'],
  'lr-change-review': ['lr-change-review', 'lr-diff-view'],
  'lr-chart': ['lr-chart', 'lr-skeleton'],
  'lr-chat-composer': ['lr-chat-composer'],
  'lr-chat-message': ['lr-chat-message'],
  'lr-chat-viewport': ['lr-chat-viewport'],
  'lr-checkbox': ['lr-checkbox'],
  'lr-checkbox-group': ['lr-checkbox-group'],
  'lr-checkpoint': ['lr-checkpoint'],
  'lr-chip': ['lr-chip'],
  'lr-chip-group': ['lr-chip-group'],
  'lr-chunk-inspector': ['lr-chunk-inspector', 'lr-empty', 'lr-virtual-list'],
  'lr-citation-badge': ['lr-citation-badge'],
  'lr-claim-evidence': ['lr-badge', 'lr-citation-badge', 'lr-claim-evidence', 'lr-empty'],
  'lr-code-block': ['lr-code-block', 'lr-icon-button', 'lr-skeleton'],
  'lr-code-block-core': ['lr-code-block-core', 'lr-icon-button', 'lr-skeleton'],
  'lr-code-editor': ['lr-code-editor'],
  'lr-color-picker': ['lr-color-picker'],
  'lr-combobox': ['lr-combobox', 'lr-empty', 'lr-option'],
  'lr-command-palette': ['lr-command-palette'],
  'lr-commit-card': ['lr-commit-card'],
  'lr-community-card': ['lr-button', 'lr-chip', 'lr-community-card', 'lr-empty'],
  'lr-compare-panel': ['lr-compare-panel', 'lr-live-region'],
  'lr-condition-builder': ['lr-button', 'lr-combobox', 'lr-condition-builder', 'lr-date-input', 'lr-date-picker', 'lr-empty', 'lr-icon', 'lr-icon-button', 'lr-input', 'lr-option', 'lr-select'],
  'lr-confirm-bar': ['lr-button', 'lr-confirm-bar', 'lr-details', 'lr-json-viewer', 'lr-live-region'],
  'lr-connector-manager': ['lr-connector-manager'],
  'lr-contact-viewer': ['lr-contact-viewer'],
  'lr-context-inspector': ['lr-citation-badge', 'lr-context-inspector', 'lr-context-meter', 'lr-copy-button', 'lr-empty', 'lr-export-button', 'lr-icon-button', 'lr-tooltip'],
  'lr-context-menu': ['lr-context-menu', 'lr-dropdown', 'lr-menu', 'lr-menu-item'],
  'lr-context-meter': ['lr-context-meter'],
  'lr-control-group': ['lr-control-group'],
  'lr-conversation-item': ['lr-conversation-item'],
  'lr-copy-button': ['lr-copy-button', 'lr-icon-button', 'lr-tooltip'],
  'lr-country-picker': ['lr-combobox', 'lr-country-picker', 'lr-empty', 'lr-option', 'lr-select'],
  'lr-csv-viewer': ['lr-csv-viewer', 'lr-virtual-list'],
  'lr-currency-picker': ['lr-combobox', 'lr-currency-picker', 'lr-empty', 'lr-option', 'lr-select'],
  'lr-dashboard-grid': ['lr-badge', 'lr-button', 'lr-card', 'lr-dashboard-grid', 'lr-empty', 'lr-markdown', 'lr-media-card', 'lr-result-card', 'lr-result-field', 'lr-stat', 'lr-widget', 'lr-widget-renderer'],
  'lr-data-grid': ['lr-button', 'lr-data-grid', 'lr-dropdown', 'lr-dropdown-item', 'lr-empty', 'lr-menu', 'lr-menu-item'],
  'lr-dataset-viewer': ['lr-dataset-viewer', 'lr-virtual-list'],
  'lr-date-input': ['lr-date-input', 'lr-date-picker'],
  'lr-date-picker': ['lr-date-picker'],
  'lr-details': ['lr-details'],
  'lr-dialog': ['lr-dialog', 'lr-icon-button'],
  'lr-diff-view': ['lr-diff-view'],
  'lr-divider': ['lr-divider'],
  'lr-dock-panel': ['lr-dock-panel'],
  'lr-document-compare': ['lr-diff-view', 'lr-document-compare', 'lr-document-preview', 'lr-pan-zoom'],
  'lr-document-library': ['lr-checkbox', 'lr-chip', 'lr-chip-group', 'lr-combobox', 'lr-document-library', 'lr-empty', 'lr-file-icon', 'lr-input', 'lr-option', 'lr-pagination', 'lr-skeleton', 'lr-spinner', 'lr-table'],
  'lr-document-preview': ['lr-document-preview', 'lr-pan-zoom'],
  'lr-document-viewer': ['lr-dialog', 'lr-document-preview', 'lr-document-viewer', 'lr-icon-button', 'lr-pan-zoom'],
  'lr-docx-viewer': ['lr-docx-viewer'],
  'lr-doughnut-chart': ['lr-chart', 'lr-doughnut-chart', 'lr-skeleton'],
  'lr-drawer': ['lr-drawer', 'lr-icon-button'],
  'lr-drilldown-panel': ['lr-badge', 'lr-breadcrumb', 'lr-breadcrumb-item', 'lr-button', 'lr-chip', 'lr-document-preview', 'lr-drilldown-panel', 'lr-empty', 'lr-entity-card', 'lr-pan-zoom', 'lr-result-field', 'lr-source-card', 'lr-tab', 'lr-tab-group', 'lr-tab-panel'],
  'lr-drop-zone': ['lr-drop-zone'],
  'lr-dropdown': ['lr-dropdown', 'lr-menu', 'lr-menu-item'],
  'lr-dropdown-item': ['lr-dropdown-item', 'lr-menu', 'lr-menu-item'],
  'lr-ebook-viewer': ['lr-ebook-viewer'],
  'lr-email-viewer': ['lr-email-viewer'],
  'lr-embedding-explorer': ['lr-embedding-explorer'],
  'lr-emoji-picker': ['lr-emoji-picker'],
  'lr-empty': ['lr-empty'],
  'lr-entity-card': ['lr-badge', 'lr-button', 'lr-chip', 'lr-empty', 'lr-entity-card', 'lr-result-field'],
  'lr-entity-chip': ['lr-entity-chip'],
  'lr-entity-dossier': ['lr-badge', 'lr-button', 'lr-chip', 'lr-chunk-inspector', 'lr-community-card', 'lr-empty', 'lr-entity-card', 'lr-entity-chip', 'lr-entity-dossier', 'lr-neighbor-list', 'lr-path-strip', 'lr-provenance-panel', 'lr-result-field', 'lr-scroller', 'lr-stat', 'lr-tab', 'lr-tab-group', 'lr-tab-panel', 'lr-virtual-list'],
  'lr-env-list': ['lr-empty', 'lr-env-list'],
  'lr-eval-dataset': ['lr-chip', 'lr-chip-group', 'lr-empty', 'lr-eval-dataset', 'lr-export-button', 'lr-file-input', 'lr-pagination', 'lr-skeleton', 'lr-spinner', 'lr-table'],
  'lr-eval-result': ['lr-checkbox', 'lr-checkbox-group', 'lr-diff-view', 'lr-empty', 'lr-eval-result', 'lr-option', 'lr-pagination', 'lr-rubric-form', 'lr-segmented', 'lr-select', 'lr-skeleton', 'lr-slider', 'lr-spinner', 'lr-table', 'lr-textarea'],
  'lr-eval-run': ['lr-badge', 'lr-button', 'lr-citation-badge', 'lr-claim-evidence', 'lr-code-block', 'lr-copy-button', 'lr-details', 'lr-empty', 'lr-eval-run', 'lr-grounding-summary', 'lr-icon-button', 'lr-json-viewer', 'lr-live-region', 'lr-markdown', 'lr-progress-bar', 'lr-skeleton', 'lr-stat', 'lr-tool-approval-dialog', 'lr-tool-call-chip', 'lr-tool-result-view', 'lr-tool-timeline', 'lr-tooltip'],
  'lr-export-button': ['lr-export-button'],
  'lr-file-icon': ['lr-file-icon'],
  'lr-file-input': ['lr-file-input'],
  'lr-file-tree': ['lr-empty', 'lr-file-icon', 'lr-file-tree', 'lr-live-region', 'lr-tree', 'lr-tree-item'],
  'lr-filter-bar': ['lr-button', 'lr-chip', 'lr-chip-group', 'lr-combobox', 'lr-date-input', 'lr-date-picker', 'lr-dropdown', 'lr-dropdown-item', 'lr-empty', 'lr-filter-bar', 'lr-input', 'lr-menu', 'lr-menu-item', 'lr-option', 'lr-select', 'lr-spinner'],
  'lr-flag': ['lr-flag', 'lr-skeleton'],
  'lr-flow-canvas': ['lr-empty', 'lr-flow-canvas', 'lr-flow-node'],
  'lr-flow-controls': ['lr-flow-controls'],
  'lr-flow-minimap': ['lr-flow-minimap'],
  'lr-flow-node': ['lr-flow-node'],
  'lr-flow-run-status': ['lr-flow-run-status'],
  'lr-format-bytes': ['lr-format-bytes'],
  'lr-format-date': ['lr-format-date'],
  'lr-format-number': ['lr-format-number'],
  'lr-funnel': ['lr-funnel'],
  'lr-gauge': ['lr-gauge'],
  'lr-generation-metrics': ['lr-generation-metrics'],
  'lr-geojson-viewer': ['lr-geojson-viewer', 'lr-json-viewer', 'lr-map', 'lr-skeleton'],
  'lr-graph': ['lr-graph', 'lr-skeleton'],
  'lr-graph-legend': ['lr-graph-legend'],
  'lr-graph-query-builder': ['lr-chip', 'lr-chip-group', 'lr-graph-query-builder', 'lr-input', 'lr-option', 'lr-select'],
  'lr-grounding-summary': ['lr-badge', 'lr-citation-badge', 'lr-claim-evidence', 'lr-empty', 'lr-grounding-summary', 'lr-stat'],
  'lr-handoff-divider': ['lr-handoff-divider'],
  'lr-heatmap': ['lr-heatmap'],
  'lr-highlight-layer': ['lr-highlight-layer'],
  'lr-histogram': ['lr-chart', 'lr-histogram', 'lr-skeleton'],
  'lr-html-viewer': ['lr-html-viewer'],
  'lr-icon': ['lr-icon'],
  'lr-icon-button': ['lr-icon', 'lr-icon-button'],
  'lr-image-comparer': ['lr-image-comparer'],
  'lr-image-viewer': ['lr-image-viewer', 'lr-live-region', 'lr-pan-zoom'],
  'lr-include': ['lr-include'],
  'lr-ingestion-queue': ['lr-badge', 'lr-empty', 'lr-ingestion-queue', 'lr-progress-bar', 'lr-virtual-list'],
  'lr-input': ['lr-input'],
  'lr-intersection-observer': ['lr-intersection-observer'],
  'lr-json-schema-viewer': ['lr-badge', 'lr-empty', 'lr-json-schema-viewer'],
  'lr-json-viewer': ['lr-json-viewer'],
  'lr-kbd': ['lr-kbd'],
  'lr-knowledge-base': ['lr-badge', 'lr-button', 'lr-dropdown', 'lr-empty', 'lr-knowledge-base', 'lr-menu', 'lr-menu-item', 'lr-pagination', 'lr-skeleton', 'lr-spinner', 'lr-stat', 'lr-table'],
  'lr-knowledge-base-admin': ['lr-badge', 'lr-button', 'lr-dropdown', 'lr-empty', 'lr-ingestion-queue', 'lr-knowledge-base', 'lr-knowledge-base-admin', 'lr-menu', 'lr-menu-item', 'lr-pagination', 'lr-progress-bar', 'lr-skeleton', 'lr-spinner', 'lr-stat', 'lr-table', 'lr-virtual-list'],
  'lr-knowledge-graph-explorer': ['lr-badge', 'lr-button', 'lr-chip', 'lr-empty', 'lr-entity-card', 'lr-graph', 'lr-graph-legend', 'lr-input', 'lr-knowledge-graph-explorer', 'lr-neighbor-list', 'lr-path-strip', 'lr-popover', 'lr-result-field', 'lr-scroller', 'lr-skeleton', 'lr-virtual-list'],
  'lr-known-date': ['lr-known-date'],
  'lr-lightbox': ['lr-lightbox', 'lr-pan-zoom'],
  'lr-line-chart': ['lr-chart', 'lr-line-chart', 'lr-skeleton'],
  'lr-lite-chart': ['lr-lite-chart', 'lr-live-region'],
  'lr-live-region': ['lr-live-region'],
  'lr-locale-picker': ['lr-flag', 'lr-locale-picker', 'lr-skeleton'],
  'lr-map': ['lr-map', 'lr-skeleton'],
  'lr-markdown': ['lr-markdown'],
  'lr-markdown-core': ['lr-markdown-core'],
  'lr-mcp-app': ['lr-mcp-app'],
  'lr-media-card': ['lr-media-card'],
  'lr-memory-panel': ['lr-button', 'lr-chip', 'lr-chunk-inspector', 'lr-community-card', 'lr-confirm-bar', 'lr-details', 'lr-empty', 'lr-entity-chip', 'lr-json-viewer', 'lr-live-region', 'lr-memory-panel', 'lr-path-strip', 'lr-provenance-panel', 'lr-scroller', 'lr-virtual-list'],
  'lr-mention-popover': ['lr-mention-popover'],
  'lr-menu': ['lr-menu', 'lr-menu-item'],
  'lr-menu-item': ['lr-menu', 'lr-menu-item'],
  'lr-menu-label': ['lr-menu-label'],
  'lr-menubar': ['lr-menu', 'lr-menu-item', 'lr-menubar', 'lr-menubar-item'],
  'lr-menubar-item': ['lr-menu', 'lr-menu-item', 'lr-menubar-item'],
  'lr-message-actions': ['lr-chip', 'lr-copy-button', 'lr-icon-button', 'lr-message-actions', 'lr-message-feedback', 'lr-tooltip'],
  'lr-message-feedback': ['lr-chip', 'lr-message-feedback'],
  'lr-message-parts': ['lr-attachment-chip', 'lr-badge', 'lr-button', 'lr-card', 'lr-citation-badge', 'lr-copy-button', 'lr-details', 'lr-icon-button', 'lr-json-viewer', 'lr-markdown', 'lr-media-card', 'lr-message-parts', 'lr-result-card', 'lr-result-field', 'lr-skeleton', 'lr-stat', 'lr-thinking-panel', 'lr-tool-call-block', 'lr-tool-call-chip', 'lr-tool-result-view', 'lr-tooltip', 'lr-widget-renderer'],
  'lr-mind-map': ['lr-mind-map'],
  'lr-model-select': ['lr-model-select'],
  'lr-model-settings-panel': ['lr-model-select', 'lr-model-settings-panel', 'lr-slider'],
  'lr-multi-split': ['lr-multi-split'],
  'lr-mutation-observer': ['lr-mutation-observer'],
  'lr-native-time-input': ['lr-native-time-input'],
  'lr-navigation-menu': ['lr-navigation-menu', 'lr-navigation-menu-item'],
  'lr-navigation-menu-item': ['lr-navigation-menu-item'],
  'lr-neighbor-list': ['lr-empty', 'lr-neighbor-list', 'lr-virtual-list'],
  'lr-node-palette': ['lr-node-palette'],
  'lr-notebook-viewer': ['lr-code-block', 'lr-icon-button', 'lr-json-viewer', 'lr-markdown', 'lr-notebook-viewer', 'lr-skeleton', 'lr-virtual-list'],
  'lr-number-input': ['lr-number-input'],
  'lr-option': ['lr-option'],
  'lr-otp-input': ['lr-otp-input'],
  'lr-page': ['lr-page'],
  'lr-page-rail': ['lr-file-icon', 'lr-page-rail', 'lr-skeleton', 'lr-virtual-list'],
  'lr-pagination': ['lr-pagination'],
  'lr-pan-zoom': ['lr-pan-zoom'],
  'lr-path-strip': ['lr-path-strip', 'lr-scroller'],
  'lr-pdf-viewer': ['lr-highlight-layer', 'lr-pdf-viewer', 'lr-virtual-list'],
  'lr-permission-grant': ['lr-permission-grant'],
  'lr-permission-rules': ['lr-permission-rules'],
  'lr-phone-input': ['lr-flag', 'lr-phone-input', 'lr-skeleton'],
  'lr-pie-chart': ['lr-chart', 'lr-pie-chart', 'lr-skeleton'],
  'lr-polar-area-chart': ['lr-chart', 'lr-polar-area-chart', 'lr-skeleton'],
  'lr-policy-summary': ['lr-badge', 'lr-details', 'lr-empty', 'lr-policy-summary'],
  'lr-poll-status': ['lr-live-region', 'lr-poll-status'],
  'lr-popover': ['lr-popover'],
  'lr-popup': ['lr-popup'],
  'lr-pptx-viewer': ['lr-pptx-viewer'],
  'lr-progress-bar': ['lr-progress-bar'],
  'lr-progress-ring': ['lr-progress-ring'],
  'lr-prompt-input': ['lr-attachment-chip', 'lr-attachment-trigger', 'lr-button', 'lr-chat-composer', 'lr-checkbox', 'lr-dropdown', 'lr-empty', 'lr-file-icon', 'lr-icon-button', 'lr-input', 'lr-mention-popover', 'lr-menu', 'lr-menu-item', 'lr-model-select', 'lr-prompt-input', 'lr-prompt-queue', 'lr-source-picker', 'lr-textarea', 'lr-voice-picker'],
  'lr-prompt-queue': ['lr-button', 'lr-prompt-queue', 'lr-textarea'],
  'lr-prompt-studio': ['lr-prompt-studio'],
  'lr-provenance-panel': ['lr-button', 'lr-chip', 'lr-chunk-inspector', 'lr-community-card', 'lr-empty', 'lr-entity-chip', 'lr-path-strip', 'lr-provenance-panel', 'lr-scroller', 'lr-virtual-list'],
  'lr-push-to-talk': ['lr-live-region', 'lr-push-to-talk'],
  'lr-qr-code': ['lr-qr-code'],
  'lr-radar-chart': ['lr-chart', 'lr-radar-chart', 'lr-skeleton'],
  'lr-radio': ['lr-radio'],
  'lr-radio-button': ['lr-radio-button'],
  'lr-radio-group': ['lr-radio-group'],
  'lr-rag-answer': ['lr-badge', 'lr-button', 'lr-citation-badge', 'lr-claim-evidence', 'lr-empty', 'lr-grounding-summary', 'lr-markdown', 'lr-rag-answer', 'lr-source-card', 'lr-source-list', 'lr-spinner', 'lr-stat'],
  'lr-rag-eval-dashboard': ['lr-empty', 'lr-lite-chart', 'lr-live-region', 'lr-rag-eval-dashboard', 'lr-stat'],
  'lr-random-content': ['lr-random-content'],
  'lr-rating': ['lr-rating'],
  'lr-realtime-session': ['lr-audio-visualizer', 'lr-badge', 'lr-live-region', 'lr-push-to-talk', 'lr-realtime-session', 'lr-transcript-feed'],
  'lr-relative-time': ['lr-relative-time'],
  'lr-reorder-item': ['lr-icon-button', 'lr-reorder-item'],
  'lr-reorder-list': ['lr-icon-button', 'lr-live-region', 'lr-reorder-item', 'lr-reorder-list'],
  'lr-research-progress': ['lr-research-progress'],
  'lr-resize-observer': ['lr-resize-observer'],
  'lr-responsive-panel': ['lr-responsive-panel'],
  'lr-result-card': ['lr-result-card'],
  'lr-result-field': ['lr-result-field'],
  'lr-retrieval-compare': ['lr-empty', 'lr-retrieval-compare'],
  'lr-retrieval-results': ['lr-checkbox', 'lr-chunk-inspector', 'lr-empty', 'lr-retrieval-results', 'lr-spinner', 'lr-virtual-list'],
  'lr-retrieval-search': ['lr-chip', 'lr-chip-group', 'lr-empty', 'lr-input', 'lr-retrieval-search', 'lr-segmented', 'lr-spinner'],
  'lr-retrieval-trace': ['lr-chunk-inspector', 'lr-empty', 'lr-retrieval-trace', 'lr-span-waterfall', 'lr-virtual-list'],
  'lr-rubric-form': ['lr-checkbox', 'lr-checkbox-group', 'lr-option', 'lr-rubric-form', 'lr-segmented', 'lr-select', 'lr-slider', 'lr-textarea'],
  'lr-scatter-chart': ['lr-chart', 'lr-scatter-chart', 'lr-skeleton'],
  'lr-scroller': ['lr-scroller'],
  'lr-segmented': ['lr-segmented'],
  'lr-select': ['lr-option', 'lr-select'],
  'lr-selection-toolbar': ['lr-button', 'lr-selection-toolbar'],
  'lr-sequence-playback': ['lr-sequence-playback'],
  'lr-sequence-strip': ['lr-sequence-strip'],
  'lr-signature-pad': ['lr-signature-pad'],
  'lr-skeleton': ['lr-skeleton'],
  'lr-slider': ['lr-slider'],
  'lr-source-card': ['lr-source-card'],
  'lr-source-list': ['lr-source-list'],
  'lr-source-picker': ['lr-checkbox', 'lr-empty', 'lr-file-icon', 'lr-input', 'lr-source-picker'],
  'lr-span-waterfall': ['lr-empty', 'lr-span-waterfall'],
  'lr-sparkline': ['lr-sparkline'],
  'lr-spinner': ['lr-spinner'],
  'lr-split-panel': ['lr-split-panel'],
  'lr-spreadsheet-viewer': ['lr-spreadsheet-viewer', 'lr-tab', 'lr-tab-group', 'lr-tab-panel', 'lr-virtual-list'],
  'lr-stack-trace': ['lr-stack-trace'],
  'lr-stat': ['lr-stat'],
  'lr-stepper': ['lr-stepper'],
  'lr-stream-status': ['lr-live-region', 'lr-stream-status'],
  'lr-streaming-text': ['lr-markdown', 'lr-streaming-text'],
  'lr-streaming-text-core': ['lr-markdown-core', 'lr-streaming-text-core'],
  'lr-subagent-panel': ['lr-badge', 'lr-empty', 'lr-subagent-panel'],
  'lr-suggestion-chips': ['lr-scroller', 'lr-suggestion-chips'],
  'lr-svg-viewer': ['lr-pan-zoom', 'lr-svg-viewer'],
  'lr-swatch-picker': ['lr-swatch-picker'],
  'lr-switch': ['lr-switch'],
  'lr-tab': ['lr-tab'],
  'lr-tab-group': ['lr-tab-group'],
  'lr-tab-panel': ['lr-tab-panel'],
  'lr-table': ['lr-empty', 'lr-pagination', 'lr-skeleton', 'lr-spinner', 'lr-table'],
  'lr-tag': ['lr-tag'],
  'lr-task-list': ['lr-live-region', 'lr-task-list'],
  'lr-terminal': ['lr-terminal', 'lr-virtual-list'],
  'lr-test-results': ['lr-empty', 'lr-live-region', 'lr-spinner', 'lr-test-results'],
  'lr-textarea': ['lr-textarea'],
  'lr-thinking-panel': ['lr-thinking-panel'],
  'lr-thread-list': ['lr-conversation-item', 'lr-empty', 'lr-live-region', 'lr-thread-list', 'lr-virtual-list'],
  'lr-time-input': ['lr-time-input'],
  'lr-time-range': ['lr-time-range'],
  'lr-time-zone-picker': ['lr-combobox', 'lr-empty', 'lr-option', 'lr-select', 'lr-time-zone-picker'],
  'lr-timeline': ['lr-relative-time', 'lr-timeline', 'lr-timeline-item'],
  'lr-timeline-item': ['lr-relative-time', 'lr-timeline-item'],
  'lr-toast': ['lr-toast', 'lr-toast-item'],
  'lr-toast-item': ['lr-toast-item'],
  'lr-toggle': ['lr-toggle'],
  'lr-toggle-group': ['lr-toggle-group'],
  'lr-token-input': ['lr-token-input'],
  'lr-tool-approval-dialog': ['lr-button', 'lr-json-viewer', 'lr-tool-approval-dialog'],
  'lr-tool-call-block': ['lr-copy-button', 'lr-icon-button', 'lr-json-viewer', 'lr-skeleton', 'lr-tool-call-block', 'lr-tool-result-view', 'lr-tooltip'],
  'lr-tool-call-chip': ['lr-tool-call-chip'],
  'lr-tool-param-form': ['lr-number-input', 'lr-option', 'lr-select', 'lr-tool-param-form'],
  'lr-tool-result-dialog': ['lr-tool-result-dialog'],
  'lr-tool-result-view': ['lr-copy-button', 'lr-icon-button', 'lr-json-viewer', 'lr-skeleton', 'lr-tool-result-view', 'lr-tooltip'],
  'lr-tool-select-dialog': ['lr-checkbox', 'lr-switch', 'lr-tool-select-dialog'],
  'lr-tool-timeline': ['lr-button', 'lr-copy-button', 'lr-details', 'lr-empty', 'lr-icon-button', 'lr-json-viewer', 'lr-skeleton', 'lr-tool-approval-dialog', 'lr-tool-call-chip', 'lr-tool-result-view', 'lr-tool-timeline', 'lr-tooltip'],
  'lr-tooltip': ['lr-tooltip'],
  'lr-tour': ['lr-tour'],
  'lr-trace-tree': ['lr-empty', 'lr-live-region', 'lr-trace-tree'],
  'lr-transcript-feed': ['lr-transcript-feed'],
  'lr-tree': ['lr-empty', 'lr-live-region', 'lr-tree', 'lr-tree-item'],
  'lr-tree-item': ['lr-tree-item'],
  'lr-typing-indicator': ['lr-typing-indicator'],
  'lr-unit-picker': ['lr-combobox', 'lr-empty', 'lr-option', 'lr-select', 'lr-unit-picker'],
  'lr-usage-badge': ['lr-usage-badge'],
  'lr-video': ['lr-icon', 'lr-video'],
  'lr-video-playlist': ['lr-icon', 'lr-video', 'lr-video-playlist'],
  'lr-virtual-list': ['lr-virtual-list'],
  'lr-visually-hidden': ['lr-visually-hidden'],
  'lr-voice-picker': ['lr-voice-picker'],
  'lr-widget': ['lr-widget'],
  'lr-widget-renderer': ['lr-badge', 'lr-button', 'lr-card', 'lr-markdown', 'lr-media-card', 'lr-result-card', 'lr-result-field', 'lr-stat', 'lr-widget-renderer'],
  'lr-word-cloud': ['lr-word-cloud'],
  'lr-xml-viewer': ['lr-xml-viewer'],
  'lr-zoomable-frame': ['lr-zoomable-frame'],
});
