import { css } from 'lit';

// Specialist visualization and terminal palettes are opt-in so primitive controls do not parse
// token families they can never consume. Token names, values and mode selectors remain identical
// to the shared catalog; components that reference one of these families adopt this sheet after
// LyraElement.styles and before their own component stylesheet.
// The graph ramp is independently themeable from the chart ramp. The ANSI foreground/background
// values remain generated by scripts/generate-terminal-palette.mjs and intentionally use separate
// sets solved against opposite references.
const lightSpecialistTokens = css`
    /* chart fallback ramp: generated (light) -- see scripts/generate-chart-palette.mjs */
    --lr-color-chart-1: var(--lr-theme-color-chart-1, #0e006e);
    --lr-color-chart-2: var(--lr-theme-color-chart-2, #4d011a);
    --lr-color-chart-3: var(--lr-theme-color-chart-3, #862002);
    --lr-color-chart-4: var(--lr-theme-color-chart-4, #503983);
    --lr-color-chart-5: var(--lr-theme-color-chart-5, #315fdd);
    --lr-color-chart-6: var(--lr-theme-color-chart-6, #935e7c);
    --lr-color-chart-7: var(--lr-theme-color-chart-7, #de6906);
    --lr-color-chart-8: var(--lr-theme-color-chart-8, #8f81d3);
    /* chart fallback ramp: end */
    --lr-graph-cat-1: var(--lr-theme-graph-cat-1, #8250df);
    --lr-graph-cat-2: var(--lr-theme-graph-cat-2, #bf3989);
    --lr-graph-cat-3: var(--lr-theme-graph-cat-3, #0a7d91);
    --lr-graph-cat-4: var(--lr-theme-graph-cat-4, #57606a);
    --lr-graph-cat-5: var(--lr-theme-graph-cat-5, #b083f5);
    --lr-graph-cat-6: var(--lr-theme-graph-cat-6, #f470b8);
    --lr-graph-cat-7: var(--lr-theme-graph-cat-7, #52d6e8);
    --lr-graph-cat-8: var(--lr-theme-graph-cat-8, #c9d1d9);
    /* terminal ramp: generated (light) -- see scripts/generate-terminal-palette.mjs */
    --lr-terminal-color-black: var(--lr-theme-terminal-color-black, #2b2b2b);
    --lr-terminal-color-red: var(--lr-theme-terminal-color-red, #901114);
    --lr-terminal-color-green: var(--lr-theme-terminal-color-green, #015e15);
    --lr-terminal-color-yellow: var(--lr-theme-terminal-color-yellow, #5f4a03);
    --lr-terminal-color-blue: var(--lr-theme-terminal-color-blue, #06489c);
    --lr-terminal-color-magenta: var(--lr-theme-terminal-color-magenta, #67298c);
    --lr-terminal-color-cyan: var(--lr-theme-terminal-color-cyan, #02585f);
    --lr-terminal-color-white: var(--lr-theme-terminal-color-white, #555555);
    --lr-terminal-color-bright-black: var(--lr-theme-terminal-color-bright-black, #404040);
    --lr-terminal-color-bright-red: var(--lr-theme-terminal-color-bright-red, #b32322);
    --lr-terminal-color-bright-green: var(--lr-theme-terminal-color-bright-green, #01791e);
    --lr-terminal-color-bright-yellow: var(--lr-theme-terminal-color-bright-yellow, #796005);
    --lr-terminal-color-bright-blue: var(--lr-theme-terminal-color-bright-blue, #145ec1);
    --lr-terminal-color-bright-magenta: var(--lr-theme-terminal-color-bright-magenta, #823bae);
    --lr-terminal-color-bright-cyan: var(--lr-theme-terminal-color-bright-cyan, #04717a);
    --lr-terminal-color-bright-white: var(--lr-theme-terminal-color-bright-white, #6c6c6c);
    --lr-terminal-bg-black: var(--lr-theme-terminal-bg-black, #868686);
    --lr-terminal-bg-red: var(--lr-theme-terminal-bg-red, #d2918a);
    --lr-terminal-bg-green: var(--lr-theme-terminal-bg-green, #89b18a);
    --lr-terminal-bg-yellow: var(--lr-theme-terminal-bg-yellow, #b6a372);
    --lr-terminal-bg-blue: var(--lr-theme-terminal-bg-blue, #88a6d4);
    --lr-terminal-bg-magenta: var(--lr-theme-terminal-bg-magenta, #b497cb);
    --lr-terminal-bg-cyan: var(--lr-theme-terminal-bg-cyan, #77b0b6);
    --lr-terminal-bg-white: var(--lr-theme-terminal-bg-white, #b7b7b7);
    --lr-terminal-bg-bright-black: var(--lr-theme-terminal-bg-bright-black, #9e9e9e);
    --lr-terminal-bg-bright-red: var(--lr-theme-terminal-bg-bright-red, #f9aea5);
    --lr-terminal-bg-bright-green: var(--lr-theme-terminal-bg-bright-green, #a4d2a4);
    --lr-terminal-bg-bright-yellow: var(--lr-theme-terminal-bg-bright-yellow, #d8c288);
    --lr-terminal-bg-bright-blue: var(--lr-theme-terminal-bg-bright-blue, #a2c6fb);
    --lr-terminal-bg-bright-magenta: var(--lr-theme-terminal-bg-bright-magenta, #d6b4f0);
    --lr-terminal-bg-bright-cyan: var(--lr-theme-terminal-bg-bright-cyan, #8dd2da);
    --lr-terminal-bg-bright-white: var(--lr-theme-terminal-bg-bright-white, #d1d1d1);
    /* terminal ramp: end */
`;

const darkSpecialistTokens = css`
    /* chart fallback ramp: generated (dark) -- see scripts/generate-chart-palette.mjs */
    --lr-color-chart-1: var(--lr-theme-color-chart-1, #bbff94);
    --lr-color-chart-2: var(--lr-theme-color-chart-2, #ffbce8);
    --lr-color-chart-3: var(--lr-theme-color-chart-3, #2bd66a);
    --lr-color-chart-4: var(--lr-theme-color-chart-4, #bb99cb);
    --lr-color-chart-5: var(--lr-theme-color-chart-5, #7888fe);
    --lr-color-chart-6: var(--lr-theme-color-chart-6, #9b6b90);
    --lr-color-chart-7: var(--lr-theme-color-chart-7, #db3a29);
    --lr-color-chart-8: var(--lr-theme-color-chart-8, #555de3);
    /* chart fallback ramp: end */
    --lr-graph-cat-1: var(--lr-theme-graph-cat-1, #b58cff);
    --lr-graph-cat-2: var(--lr-theme-graph-cat-2, #ff7ab2);
    --lr-graph-cat-3: var(--lr-theme-graph-cat-3, #4fd1c5);
    --lr-graph-cat-4: var(--lr-theme-graph-cat-4, #aab4c4);
    --lr-graph-cat-5: var(--lr-theme-graph-cat-5, #d4a7ff);
    --lr-graph-cat-6: var(--lr-theme-graph-cat-6, #ff91c8);
    --lr-graph-cat-7: var(--lr-theme-graph-cat-7, #79e2ef);
    --lr-graph-cat-8: var(--lr-theme-graph-cat-8, #e4e7eb);
    /* terminal ramp: generated (dark) -- see scripts/generate-terminal-palette.mjs */
    --lr-terminal-color-black: var(--lr-theme-terminal-color-black, #929292);
    --lr-terminal-color-red: var(--lr-theme-terminal-color-red, #f9786c);
    --lr-terminal-color-green: var(--lr-theme-terminal-color-green, #67bb6b);
    --lr-terminal-color-yellow: var(--lr-theme-terminal-color-yellow, #c7a01e);
    --lr-terminal-color-blue: var(--lr-theme-terminal-color-blue, #69a5fe);
    --lr-terminal-color-magenta: var(--lr-theme-terminal-color-magenta, #c385ef);
    --lr-terminal-color-cyan: var(--lr-theme-terminal-color-cyan, #17bac8);
    --lr-terminal-color-white: var(--lr-theme-terminal-color-white, #c4c4c4);
    --lr-terminal-color-bright-black: var(--lr-theme-terminal-color-bright-black, #ababab);
    --lr-terminal-color-bright-red: var(--lr-theme-terminal-color-bright-red, #ffaba1);
    --lr-terminal-color-bright-green: var(--lr-theme-terminal-color-bright-green, #7cdf81);
    --lr-terminal-color-bright-yellow: var(--lr-theme-terminal-color-bright-yellow, #ecbe24);
    --lr-terminal-color-bright-blue: var(--lr-theme-terminal-color-bright-blue, #a0c6fe);
    --lr-terminal-color-bright-magenta: var(--lr-theme-terminal-color-bright-magenta, #dcaefe);
    --lr-terminal-color-bright-cyan: var(--lr-theme-terminal-color-bright-cyan, #00ddef);
    --lr-terminal-color-bright-white: var(--lr-theme-terminal-color-bright-white, #dedede);
    --lr-terminal-bg-black: var(--lr-theme-terminal-bg-black, #292929);
    --lr-terminal-bg-red: var(--lr-theme-terminal-bg-red, #733a35);
    --lr-terminal-bg-green: var(--lr-theme-terminal-bg-green, #335735);
    --lr-terminal-bg-yellow: var(--lr-theme-terminal-bg-yellow, #5c4b1a);
    --lr-terminal-bg-blue: var(--lr-theme-terminal-bg-blue, #324e76);
    --lr-terminal-bg-magenta: var(--lr-theme-terminal-bg-magenta, #5a406e);
    --lr-terminal-bg-cyan: var(--lr-theme-terminal-bg-cyan, #1c565d);
    --lr-terminal-bg-white: var(--lr-theme-terminal-bg-white, #525252);
    --lr-terminal-bg-bright-black: var(--lr-theme-terminal-bg-bright-black, #3d3d3d);
    --lr-terminal-bg-bright-red: var(--lr-theme-terminal-bg-bright-red, #904e47);
    --lr-terminal-bg-bright-green: var(--lr-theme-terminal-bg-bright-green, #456f46);
    --lr-terminal-bg-bright-yellow: var(--lr-theme-terminal-bg-bright-yellow, #756127);
    --lr-terminal-bg-bright-blue: var(--lr-theme-terminal-bg-bright-blue, #446493);
    --lr-terminal-bg-bright-magenta: var(--lr-theme-terminal-bg-bright-magenta, #73548a);
    --lr-terminal-bg-bright-cyan: var(--lr-theme-terminal-bg-bright-cyan, #286f76);
    --lr-terminal-bg-bright-white: var(--lr-theme-terminal-bg-bright-white, #696969);
    /* terminal ramp: end */
`;

/**
 * Composed into selectors mirroring every dark route below, not a bare :host. A Windows High
 * Contrast *dark* theme also reports prefers-color-scheme: dark, so the ordinary HCM case is
 * forced colors AND dark at once; at 0-1-0 this block loses to every dark selector here and the
 * whole system-colour ramp goes dead exactly where it is needed. Charts and graphs feel it worst:
 * they resolve these tokens through getComputedStyle and paint into canvas/SVG, which the user
 * agent's own forced-colour substitution never reaches.
 */
const forcedColorSpecialistTokens = css`
    --lr-color-chart-1: Highlight;
    --lr-color-chart-2: LinkText;
    --lr-color-chart-3: CanvasText;
    --lr-color-chart-4: Highlight;
    --lr-color-chart-5: LinkText;
    --lr-color-chart-6: CanvasText;
    --lr-color-chart-7: Highlight;
    --lr-color-chart-8: LinkText;
    --lr-graph-cat-1: Highlight;
    --lr-graph-cat-2: LinkText;
    --lr-graph-cat-3: CanvasText;
    --lr-graph-cat-4: Highlight;
    --lr-graph-cat-5: LinkText;
    --lr-graph-cat-6: CanvasText;
    --lr-graph-cat-7: Highlight;
    --lr-graph-cat-8: LinkText;
`;

export const specialistTokens = css`
  :host {${lightSpecialistTokens}
  }

  /* @media (prefers-color-scheme: dark) */
  @media (prefers-color-scheme: dark) {
    :host(:not([data-lr-theme='light'])) {${darkSpecialistTokens}
    }
  }
  :host([data-lr-theme='dark']) {${darkSpecialistTokens}
  }
  :host(:not([data-lr-theme='light'])):host-context(.lr-dark),
  :host(:not([data-lr-theme='light'])):host-context([data-lr-theme='dark']) {${darkSpecialistTokens}
  }

  /* Last, and selector-for-selector against each dark rule above: at equal specificity the later
     declaration wins, so system colours hold in every theme state. The :host-context() pair stays
     a separate rule because Firefox and Safari ship no :host-context() and one unsupported
     selector invalidates a whole list -- which would take the supported branches down with it. */
  /* @media (forced-colors: active) */
  @media (forced-colors: active) {
    :host,
    :host(:not([data-lr-theme='light'])),
    :host([data-lr-theme='dark']) {${forcedColorSpecialistTokens}
    }
    :host(:not([data-lr-theme='light'])):host-context(.lr-dark),
    :host(:not([data-lr-theme='light'])):host-context([data-lr-theme='dark']) {${forcedColorSpecialistTokens}
    }
  }
`;
