// GENERATED by scripts/generate-translation-slices.mjs -- do not edit by hand.
// String values ARE hand-edited here and survive regeneration verbatim; regenerate structure with
// node scripts/generate-translation-slices.mjs --write.

import { registerLyraLocale } from '../../internal/localization-runtime.js';
import type { LyraLocaleStrings } from '../../internal/localization.js';

const strings: LyraLocaleStrings = {
  carousel: 'കറങ്ങുന്ന സ്ലൈഡുകൾ',
  carouselLabel: 'കറങ്ങുന്ന സ്ലൈഡുകൾ',
  carouselSlide: 'സ്ലൈഡ്',
  carouselSlidePosition: '{total}ൽ സ്ലൈഡ് {index}',
  carouselSlideAnnouncement: '{position}: {content}',
  carouselSlideAnnouncementSeparator: '. ',
  carouselIndicators: 'കറങ്ങുന്ന സ്ലൈഡുകളുടെ സൂചകങ്ങൾ',
  carouselGoTo: 'സ്ലൈഡ് {index}ലേക്ക് പോകുക',
  scrollerLabel: 'സ്ക്രോൾ ചെയ്യാവുന്ന ഉള്ളടക്കം',
  scrollPrevious: 'പിന്നോട്ട് സ്ക്രോൾ ചെയ്യുക',
  scrollNext: 'മുന്നോട്ട് സ്ക്രോൾ ചെയ്യുക',
  closeNavigation: 'നാവിഗേഷൻ അടയ്ക്കുക',
  openNavigation: 'നാവിഗേഷൻ തുറക്കുക',
  resizeNavigation: 'നാവിഗേഷന്റെ വലുപ്പം മാറ്റുക',
  appRailCollapse: 'നാവിഗേഷൻ ചുരുക്കുക',
  appRailExpand: 'നാവിഗേഷൻ വികസിപ്പിക്കുക',
  appRailItemCollapse: '{label} ചുരുക്കുക',
  appRailItemExpand: '{label} വികസിപ്പിക്കുക',
  resizeValuePercent: '{value} ശതമാനം',
  commandPaletteLabel: 'കമാൻഡ് പാലറ്റ്',
  commandPalettePlaceholder: 'കമാൻഡുകൾ തിരയുക…',
  commandPaletteEmpty: 'പൊരുത്തപ്പെടുന്ന കമാൻഡുകളില്ല.',
  commandPaletteResults: 'കമാൻഡുകൾ',
  dockPanelCollapse: 'പാനൽ ചുരുക്കുക',
  dockPanelExpand: 'പാനൽ വികസിപ്പിക്കുക',
  dockPanelResize: 'പാനലിന്റെ വലുപ്പം മാറ്റുക',
  responsivePanel: 'പാനൽ',
  breadcrumb: 'ബ്രെഡ്ക്രംബ്',
  resizeDivider: 'പാനൽ {a}നും {b}നും ഇടയിലെ വിഭാജിയുടെ വലുപ്പം മാറ്റുക',
  widgetFullscreenPanel: 'പൂർണ്ണസ്ക്രീൻ പാനൽ',
  widgetViewGroup: 'പാനൽ കാഴ്ച',
  widgetExitFullscreen: 'പൂർണ്ണസ്ക്രീനിൽ നിന്ന് പുറത്തുകടക്കുക',
  widgetExpandToFullscreen: 'പൂർണ്ണസ്ക്രീനിലേക്ക് വികസിപ്പിക്കുക',
  widgetCollapse: 'പാനൽ ചുരുക്കുക',
  widgetExpand: 'പാനൽ വികസിപ്പിക്കുക',
  skipToContent: 'ഉള്ളടക്കത്തിലേക്ക് പോകുക',
  dashboardGridLabel: 'ഡാഷ്ബോർഡ് ഗ്രിഡ്',
  dashboardCellCollisionRejected: 'മറ്റൊരു സെല്ലിനുമേൽ വരുന്നതിനാൽ {label} അവിടെ വയ്ക്കാനാവില്ല.',
  dashboardCellMoved: '{label} നിര {x}, വരി {y}ലേക്ക് മാറ്റി.',
  dashboardCellResized: '{label}ന്റെ വീതി {w}യും ഉയരം {h}യും ആക്കി.',
  filterBarReset: 'ഫിൽട്ടറുകൾ പുനഃസജ്ജമാക്കുക',
  filterBarActiveFilters: 'സജീവ ഫിൽട്ടറുകൾ',
  drilldownDocuments: 'രേഖകൾ',
  drilldownRuns: 'ഏജന്റ് റണ്ണുകൾ',
  drilldownEmpty: 'ഇനമൊന്നും തിരഞ്ഞെടുത്തിട്ടില്ല',
  drilldownUntitledNode: 'പേരില്ലാത്ത ഘട്ടം',
  reorderMovePending: 'ക്രമമാറ്റം കാത്തിരിക്കുന്നു.',
  reorderMoveCancelled: 'ക്രമമാറ്റം റദ്ദാക്കി.',
  commandPaletteResultCount: {
    one: '{count} കമാൻഡ്',
    other: '{count} കമാൻഡുകൾ',
  },
};

registerLyraLocale('ml', strings);
